### ISSUE TITLE
openingHours uses datetime in a non-confirming way

### ISSUE THREAD

**Issue by halindrome** [schemaorg/schemaorg#1012]
The HTML5 datetime attribute (in [1]) has very specific supported syntax.  Unfortunately, the schema.org syntax for it expands on this in a way that will cause validation errors.  I am not sure how important validation is to everyone, but there is a community out there that attempts it as a matter of course.  

I propose that the schema.org syntax be limited to that defined in HTML5.

[1] https://www.w3.org/TR/html-markup/time.html#time

**Comment by mfhepp** [comment]
A quick fix is to simply use <meta> instead of <time> as the element holding respective Microdata markup. But the underlying problem is that http://schema.org/openingHours tries to cover recurring weekly opening hour patterns, which is beyond the initial use of datetime in HTML 5. The other, more advanced mechanism for opening hours in schema.org with https://schema.org/openingHoursSpecification and https://schema.org/OpeningHoursSpecification avoids these problems.

Martin

**Comment by unor** [comment]
https://github.com/schemaorg/schemaorg/issues/143

**Comment by danbri** [comment]
Thanks @halindrome - let's follow up in #143
