### ISSUE TITLE
add (or remove!) 'logo' property from Organization

### ISSUE THREAD

**Issue by a7madgamal** [schemaorg/schemaorg#1016]
according to https://schema.org/Organization 'logo' is a valid Property
but according to https://schema.org/logo and google validation, its not!

**Comment by dbs** [comment]
https://schema.org/logo says:

> Used on these types
> * Brand
> * Organization
> * Place
> * Product 

So it seems there is no inconsistency between the view of schema:Organization and schema:logo.

Google validation is separate from schema.org, which is a joint effort by many different organizations, so I would recommend following up with Google on that front, perhaps by posting on the Google Webmasters forum in the "structured data" category at https://productforums.google.com/d/categories/webmasters/structured-data

**Comment by danbri** [comment]
This does indeed sound like a Google issue - http://schema.org/logo is fine for Organization. I am going to go ahead and close this issue since this is the wider schema.org project issue tracker. 

@a7madgamal if you do raise this in the Google forum, please share a link to your post here so others can keep track. On the Google side, I note https://developers.google.com/structured-data/customize/logos does show logo used on Organization, and the [Google structured data testing tool](https://developers.google.com/structured-data/testing-tool/) has a 'logos' example which seems to work:

    <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Organization",
      "url": "http://www.example.com",
      "logo": "http://www.example.com/images/logo.png"
    }
    </script>
