### ISSUE TITLE
broaden warranty to Service ?

### ISSUE THREAD

**Issue by radusi** [schemaorg/schemaorg#1023]
[ title is self-explanatory ]

**Comment by unor** [comment]
For reference: Currently the `warranty` property has `Demand` and `Offer` as domain.

In https://github.com/schemaorg/schemaorg/issues/316 @mfhepp said:

> I would only potentially object attaching warrantyPromise [note: was later renamed to `warranty`] to Product or Service directly, because the warranty promise is bound to the context of a commercial transaction.

**Comment by danbri** [comment]
Where http://schema.org/warranty is the new name for http://schema.org/warrantyPromise, btw.

This makes sense to me. @mfhepp @scor @chaals @shankarnat @pmika @vholland @rvguha ?

**Comment by vholland** [comment]
+1

**Comment by danbri** [comment]
ping @mfhepp et al. - any view?

**Comment by danbri** [comment]
@radusi - can you give some example of a Service or Product) where there is a warranty / WarrantyPromise that applies universally, without being contextualised to a transaction (i.e. Offer/Demand).

**Comment by mfhepp** [comment]
I strongly recommend to keep the current, contextualized approach, because even manufacturer warranties are typically dependent on the country of purchase. With the route via Offer, we can constrain the region of the offer and thus keep such detail.

We might want to extend the modeling of warranties by a property for indicating whether it is provided by the dealer or the manufacturer, like warrantyProvider with a domain of WarrantyPromise and a range of Text or Organization.

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp
