### ISSUE TITLE
The website's server does not accept HEAD requests

### ISSUE THREAD

**Issue by raindev** [schemaorg/schemaorg#1024]
```
$ curl -i -XHEAD http://schema.org/breadcrumb
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Type: text/html; charset=UTF-8
Content-Length: 188
Date: Thu, 10 Mar 2016 08:52:25 GMT
Server: Google Frontend
```

Accordingly to RFC 2616 section 9.4:

> The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request.

**Comment by danbri** [comment]
Thanks for the nudge. We already track this as #256 so I will close this as a duplicate issue, but I want you to know we do feel guilty about this! The reason it is taking a while was the need for some code cleanup so that the Content-Length header could be accurately computed; details in the other bug. /cc @RichardWallis
