### ISSUE TITLE
reverse property of targetProduct

### ISSUE THREAD

**Issue by sballesteros** [schemaorg/schemaorg#1032]
`SoftwareSourceCode` has `targetProduct` taking `SoftwareApplication` for range.
However, unless I am missing something, there is no way for a `SoftwareApplication` to point to its source code. Maybe `targetProductOf` could be introduced (reverse property of `targetProduct`)

**Comment by dgarijo** [comment]
Hello, I see this issue is still unresolved.
We just had a meeting at the Scientific Software Registry Collaboration Workshop (https://asclnet.github.io/SWRegistryWorkshop/ActivitiesLinks.html), where we are revisiting codemeta and schema.org to help describe Scientific Software. 

From the point of view of a software metadata registry, we describe software entries (SoftwareApplications) which then point to the SourceCode. Having the inverseProperty of targetProduct would be very helpful. Something like "hasSourceCode" or "targetOfSourceCode" (target product was a little confusing for the participants).

This issue is related to https://github.com/codemeta/codemeta/issues/198. @danbri could you please let us know if we should instead extend Codemeta? 
Thanks in advance!
