### ISSUE TITLE
Expand domain of schema:inLanguage to all schema:Thing-s

### ISSUE THREAD

**Issue by betehess** [schemaorg/schemaorg#1064]
`schema:inLanguage` is currently limited to just a few types.

In [Question on expressing translations of terms](https://lists.w3.org/Archives/Public/public-schemaorg/2016Mar/thread.html#msg47), we touched upon the need to expand the use of `schema:inLanguage` to products and `schema:Website`. We also have a use-case internally to apply that to `schema:Country`. Finally, https://github.com/schemaorg/schemaorg/issues/561 wants to apply it to `schema:EntryPoint`.

I believe it should just be extended to all `schema:Thing`s.

**Comment by danbri** [comment]
How does this direction relate to the multi-property situation I mentioned in #1079, ie. that we have already

http://schema.org/availableLanguage (of a ServiceChannel, ContactPoint)
http://schema.org/inLanguage (of a CreativeWork, Event, etc.)
http://schema.org/programmingLanguage (on SoftwareSourceCode)
http://schema.org/subtitleLanguage (Movie, ScreeningEvent, TVEpisode)

... and a fairly plausible proposal for a preferredLanguage Person property in #1084. Would you prefer each of these to be covered by inLanguage instead? Or would inLanguage perhaps be a superproperty? (that wouldn't work on at least subtitleLanguage since that kind of media content would typically have a subtitle language and a main language). 

An event like a short meeting being 'in a language' is relatively straightforward. An event like a major historical event e.g. war being 'in a language' seems relatively meaningless. A country being "inLanguage" feels somewhere on a spectrum between those two. Many countries have dozens or hundreds of heavily used languages, as well as a smaller list of official languages. If we extend inLanguage to all scenarios then people will be left guessing which sense is intended for inLanguage applied to that type. Instead we might consider adding 'officialLanguage' and 'widelySpoken' properties associating countries with languages.

**Comment by danbri** [comment]
/cc @vholland for  #561 

Counter proposal (since we are conservative about adding properties to Thing, especially when similar but different properties are available on more specific types):

*  "we touched upon the need to expand the use of schema:inLanguage to products and schema:Website. "; -> let's add it to Product. Please note that http://schema.org/WebSite already supports inLanguage with no change needed.
* "We also have a use-case internally to apply that to schema:Country."  -> let's investigate that. I've filed a dedicated issue as there are some subtleties. #1108
* "Finally, #561 wants to apply it to schema:EntryPoint." -> I'd suggest just adding it, unless the LinkRole mechanism wins everyone's favour.

**Comment by betehess** [comment]
> let's add it to Product.

That would work for me.

I had a very loose definition for `inLanguage` in my mind: "The language attached to the item. Please use one of the language codes from the IETF BCP 47 standard."

Maybe it's weird to say that any `Thing` can be localized? I agree it is scary to add something on `Thing` but I cannot come up with a good counter example where it wouldn't work. We actually have several proposals about adding `inLanguage` to new types, without even trying to find a more appropriate term.

> Please note that http://schema.org/WebSite already supports inLanguage with no change needed.

By the way, my example at https://github.com/schemaorg/schemaorg/issues/1065#issuecomment-204024172 wrongly used `WebSite`. I meant `WebPage` but it works there as well :-)

> "Finally, #561 wants to apply it to schema:EntryPoint." -> I'd suggest just adding it, unless the LinkRole mechanism wins everyone's favour.

👍 I still think that LinkRole solves a different problem.

**Comment by betehess** [comment]
Back working on this issue. I believe there is a need to have a way to localize things, which is different from having a translation on some property.

For example, some products may not exist in all countries (and therefore are not defined), or sometimes they exist but have different properties.

Other things have the same properties: country borders are not the same depending on which country you ask.

**Comment by vholland** [comment]
I don't have a clear understanding of how this property would be understood across the spectrum of Thing. For example, what does it mean for an Organization to have inLanguage? or a country? Does the USA have an inLanguage even if there is no official language?

I can see applying inLanguage to EntryPoint and Product, but would like to hear use cases for how inLanguage would be used outside of those domains.

**Comment by RichardWallis** [comment]
I agree that _inLanguage_ doesn't make sense for many _Thing_ types.   The definition "_The language of the content or performance or used in an action..._"  makes it clear how it should be used for things that use or contain written or spoken language.

> For example, some products may not exist in all countries (and therefore are not defined), or sometimes they exist but have different properties.

A product with "different properties" should be defined as a _Product_ instance in its own right, possibly defined as being _isSimilarTo_ or _isRelatedTo_ others supplied in other regions.


We cover similar but not directly applicable concepts to what is being looked for by @betehess :

- _regionsAllowed_ used with _MediaObject_
- _areaServed_ used with _Service_ & _ContactPoint_

I think, at least in the Product related areas, we are looking for a property such as _applicableToRegion_ with a range of _AdministrativeArea_, _GeoShape_, _Place_ .
