### ISSUE TITLE
Language type lacks guidance on properties 

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1079]
Language - which property encodes the language and when to use formal vs informal names for languages. "Spanish" vs "ES", EN-uk etc.

**Comment by mfhepp** [comment]
To be frank, I think the handling of language information was much better in the strict RDF worlds where any plain literal could have a language tag, so it was straighforward to represent alternative texts for the same property depending on the language.

Of all relevant syntaxes for schema.org, only Microdata lacks this feature AFAIK. Why don't we simply recommend RDFa or JSON-LD for use-cases that require language meta-data? That seems much better to me that introducing a mechanism at the level of the vocabulary.

Best

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
I agree there are issues with Microdata (or Microdata-as-RDF at least). 

However you're missing the leading use case for the Language type: the many other contexts in which it is useful to mention and name languages, beyond annotation of sections of textual markup. 

For examples see the incoming properties section at bottom of http://schema.org/Language 

* http://schema.org/availableLanguage (of a ServiceChannel, ContactPoint)
* http://schema.org/inLanguage (of a CreativeWork, Event, etc.)
* http://schema.org/programmingLanguage (on SoftwareSourceCode)
* http://schema.org/subtitleLanguage (Movie, ScreeningEvent, TVEpisode)

In all  these cases we might have an informal name for a language, or (for human languages) a code from https://tools.ietf.org/html/bcp47 or perhaps a Wikipedia link.

**Comment by Aaranged** [comment]
Preliminary thoughts on this is that a new data type for Language be constructed, along the lines of the data type Date, with reference to a standard.

Which standard?

- For the [one class](https://developers.google.com/structured-data/videogames#markup_specification) where Google specifies a standard it is [IETF BCP 47](https://tools.ietf.org/html/bcp47)
- In [Yandex documentation](https://yandex.com/support/video/partners/schema-org.xml) the language code specified is [ISO-639](https://en.wikipedia.org/wiki/ISO_639) (while it's not stated explicitly in the documentation, the code type employed in their examples is [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1))
- Bing [still recommends](http://blogs.bing.com/webmaster/2011/03/01/how-to-tell-bing-your-websites-country-and-language/) use of `<meta http-equiv="content-language">` for language declarations, where the value for `content` is "comprised of a 2-letter ISO 639 language code, followed by a dash and the appropriate ISO 3166 geography code"
- [JSON-LD](https://www.w3.org/TR/json-ld/#string-internationalization) specifies BCP 47 for `@language` values
- In their specifications for implementing the `hreflang` tag both Google and Yandex stipulate ISO 639-1 for the language, and [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) for the optional region declaration (appended to the language code with a dash as separator)
- W3C's [HTML5 recommendation on language](https://www.w3.org/TR/html5/dom.html#the-lang-and-xml:lang-attributes) calls for a valid BCP 47 language tag
- W3C's internationalization documentation on "[Choosing a Language Tag](https://www.w3.org/International/questions/qa-choosing-language-tags.en.php)" and "[Language tags in HTML and XML](https://www.w3.org/International/articles/language-tags/)" both cite BCP 47
- [schema.org/inLanguage](https://schema.org/inLanguage), of course, expects the value to be Language or Text, with the directive "Please use one of the language codes from the IETF BCP 47 standard"

All things being equal it seems to me that BCP 47 should be the standard for schema.org language declarations.

All of this glosses over the data model issue that Language is already constituted as [a class in schema.org](Please use one of the language codes from the IETF BCP 47 standard), rather than a data type - and perhaps there's reason why the data model would want to support Text as an expected value rather than only pointing to BCP 47 (although this isn't done for Date, although dates, like languages, can also be represented in content as a string).

Regarding the comment by @mfhepp, aside from the response from @danbri I'd point to the potential limitations of language declarations in RDFa and JSON-LD in the context of possibly extending the classes on which inLanguage (or a similar property) can be used, as per #1065 started by @betehess.  I.e. JSON-LD permits `@language` only to be declared for a string, not a URI.

**Comment by danbri** [comment]
Another use case: #1084 - proposal to add 'preferred language' for describing persons.

**Comment by Aaranged** [comment]
Regarding programmingLanguage, which has as its expected type Language, I believe this is an awkward conflation of "language" in the conventional sense of "conventional human languages" with computer programming "language", "a system of signs for encoding and decoding information" (all this from the [Wikipedia article on language](https://en.wikipedia.org/wiki/Language)).

They're clearly quite different things, which is why one won't find C++ in BCP 47. :)  IMO the expected type for programmingLanguage should _not_ be Language, but Text.  (Absent, say, a enumerated value or code for programmingLanguage - but the former is unwieldy and has extensibility issues, and for the latter no standard, AFAIK, exists.  This is not the case for human languages, which are unlikely to be extended and _are_ supported by standards like BCP 47).

**Comment by betehess** [comment]
> Why don't we simply recommend RDFa or JSON-LD for use-cases that require language meta-data?

:+1: We can do such a thing? :+1:

> All things being equal it seems to me that BCP 47 should be the standard for schema.org language declarations.

![5135700](https://cloud.githubusercontent.com/assets/196849/14336128/f02ea3f8-fc15-11e5-97c5-8a2c658e922f.jpg)

**Comment by mfhepp** [comment]
As far as I understand, BCP 47 includes ISO 639 language tags, which are the basis for tagging the language of RDF plain literals. So maybe we have to update the RDF spec to broaden the set of language tags to the full BCP 47 set.

Except for thar, there is no conflict.

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by mfhepp** [comment]
RDF (at least 1.1) already allows all BCP 47 tags:
https://www.w3.org/TR/rdf-plain-literal/


---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by iBootstrap** [comment]
I came across this post while googling to find how to use 'programmingLanguage' ... let's say I have a div containing C++ code ... I'm still unsure of the best way ...

<div itemprop="programmingLanguage" content="c++">
  // some c++ code here
</div>

**Comment by danbri** [comment]
Looking at this again, I suggest:

* Creating a parallel ComputerLanguage type plus migrate programmingLanguage to point to it
* Clarify in definition of Language type that it is now (primarily) for representing human language, but that it can be used for other language-like systems. Partially this is to ease the migration of computer languages over to ComputerLanguage, but also to avoid nitpicking about any borderline cases.
* Endorse BCP 47 explicitly in the definition
* Decide and document which property links from an instance of the Language type to a BCP 47 code; alternateName? generalize 'code'?

**Comment by Dataliberate** [comment]
+1 on all of above, including generalizing 'code'

**Comment by danbri** [comment]
I looked into generalizing 'code' but it is a big job and tied up with our desire to engage with SKOS and external enumerations productively. I have done something simpler for now.

* Created a new ComputerLanguage type (rather than ProgrammingLanguage, to avoid nitpicking on whether SQL, datalog, RIF etc are programming or not; also we don't want types and properties to have the same name when case is omitted, and 'programmingLanguage is already taken).
* Updated ComputerLanguage and Language with cross-references. Language in particular notes its former use for computer languages.
* Updated programmingLanguage to have both Text (as @Aaranged suggests) and ComputerLanguage as values. 
* Added mention of BCP 47 to Language, as suggested by @betehess and others. Endorsed the alternateName property as a place to put these values (this seems better than saying nothing at all).

**Comment by danbri** [comment]
PTAL:

* http://webschemas.org/ComputerLanguage
* http://webschemas.org/Language

**Comment by chaals** [comment]
Include e.g. HTML (or some not-really-a-programming-language form of computer representation of stuff) in the example?

**Comment by danbri** [comment]
I'd avoid HTML at this stage as it could easily confuse people via too many meta layers. Plus the only property we have right now designed for ComputerLanguage is programming language. I'll work up something...

**Comment by danbri** [comment]
Investigated... It seems we have *no* example containing programmingLanguage currently. We should fix that.

For this release I'd like to focus on reflecting the BCP 47 consensus back into the human-language oriented definitions, unless someone here has time to put together a quick programmingLanguage / ComputerLanguage example. Looking more carefully at our definitions I have made some modest changes to clarify that both http://schema.org/inLanguage and http://schema.org/availableLanguage can directly take BCP 47 codes as Text values, in addition to referencing an item of type Language. That makes sense because the vast majority of uses there is nothing more to say about the language except that it is the value of some property. I have also updated one example to add alternateName="es" alongside the existing name="Spanish" property of a Language. This update also cross-references inLanguage and availableLanguage. We would do well to clarify their relationship further in future - there are subtle differences (content/performance vs ability to use) but this could be better explained.

**Comment by danbri** [comment]
Updated: 

* http://webschemas.org/inLanguage
* http://webschemas.org/availableLanguage

**Comment by danbri** [comment]
Closing per http://webschemas.org/docs/releases.html#g1079 

There are other language-related conversations rolling along nearby, but I think we've addressed #1079 as originally raised.

**Comment by 88kbbq** [comment]
Every property item should support the language property. Period.

**Comment by orynider** [comment]
Then you have en-GB for English Gibraltar and en-UK for English United-Kingdom etc.
