### ISSUE TITLE
StructuredValue description is confusing

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#109]
"If you are messing around near StructuredValue, it would probably be worthwhile to fix up the comment on StructuredValue, which says that structured values are strings, but all the subclasses of StructuredValue are not strings." -- http://lists.w3.org/Archives/Public/public-vocabs/2014Aug/0205.html

http://schema.org/StructuredValue "Structured values are strings—for example, addresses—that have certain constraints on their structure."

Subtypes: 

More specific Types
ContactPoint
GeoCoordinates
GeoShape
NutritionInformation
OpeningHoursSpecification
OwnershipInfo
PriceSpecification
QuantitativeValue
TypeAndQuantityNode
WarrantyPromise

**Comment by danbri** [comment]
See also https://github.com/schemaorg/schemaorg/issues/394

**Comment by mfhepp** [comment]
There is a pull request for this at https://github.com/schemaorg/schemaorg/pull/395

**Comment by danbri** [comment]
Moving my comment in here from #395 pull request. It was:

""""Structured values are values that consist of sub-elements and thus have some kind of internal structure."

Thanks for making an exact suggestion. We haven't so far used the term "element" heavily; it sounds rather XML-oriented. 

Maybe something like "Structured values are used when the value of a property has more complex structure than simply being a textual value or a reference to another thing."?"""

/cc @vholland @rvguha

**Comment by chaals** [comment]
WfM

**Comment by reavels** [comment]
I'm still confused by this to be honest. 
I can understand the difference between simple and complex (structured) types, such that a simple type is string, datetime, number, etc which don't have properties and a structured type has properties. 
Obviously, this definition doesn't work in Schema.org because everything is inherited from Thing which has properties...but then how is a StructuredValue different to say Person as the value type of the owner property, or Event as the value type of the event property? 
...hopefully someone can clear up my cloudy view here...

**Comment by thadguidry** [comment]
Its a Parent Type for holding ANY structured value.

16R22L12R

Like my old high school locker combination.
Instead of simply saying its a Text value.
I could instead say its a StructuredValue

Then proceed to describe the structure.

Name=LockCombination
Type = StructuredValue
Property=firstRotation
Value=16R
Property=secondRotation
Value=22L
Property=thirdRotation
Value=12R

This is a quick hack and not very applicable, but should help you
understand that StructuredValue lets you build structure for values...where
Schema.org might not have a Type for your Structure yet... Like my
LockCombination subtype above.

In Schema.org we use StructuredValue as a parent Type for all those
subtypes that you see on the page, like OpeningHoursSpecification,
GeoShape, etc.

Just don't expect the Search Enginges to fully understand your
StructuredValue, but they will understand that IT IS A StructuredValue that
your describing and not some arbitrary text like 16R22L12R.

Use it when you can breakdown a value itself into ...into parts, etc. like
my high school locker combination... or even an automobile's VIN
number...if you wanted to...or an ISO Code... any value that consists of
parts and you want to describe further those parts so that others might
understand more about it.

Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>
