### ISSUE TITLE
Schema.org workflow needs syntax-checkers integrated for all examples

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1104]
Related:
- unit tests in tests/ 
- Gregg's earlier work with his Ruby library
- the rdflib framework is now integrated via lib/

**Comment by gkellogg** [comment]
* [ ] Syntactic validation of markup
* [ ] Semantic validation of examples as using appropriate properties, classes, domains, and ranges and that literal values are both in range and valid.

The Linter does this using the Ruby [rdf-reasoner](https://rubygems.org/gems/rdf-reasoner) gem, which can be run from the command line using `rdf lint`, if installed properly. For extra credit, port to rdflib.

**Comment by gkellogg** [comment]
Also,

* [ ] Verify that graphs generated using different syntaxes for the same example produce isomorphic graphs, or perhaps all pass some SPARQL query.

**Comment by danbri** [comment]
does the microdata parser report missing 'itemscope'?

**Comment by gkellogg** [comment]
Looking at the [algorithm](http://www.w3.org/TR/microdata-rdf/#rdf-conversion-algorithm), it identifies top-level items because they have an `@itemscope` and not `@itemprop`. Later on, it uses `@itemprop` on sub-elements to find properties of that item, and if it also has `@itemscope` to link it to the newly located item.

To find items without `@itemscope` is sort of an oxymoron, as that's what defines an item. However, a parser might find elements having `@itemid` and/or `@itemtype` without `@itemscope` and treat these as errors or warnings, but that's not called for in the algorithm.

The fact that, for historical reasons, the algorithm is written using DOM functions rather than element attributes, as RDFa is, makes it harder to include such language in the algorithm.

I could implement something in my parser to check for this, which the Linter/Reasoner would take advantage of. Best is to record test cases that you encounter which the algorithm may want to flag at https://github.com/w3c/microdata-rdf/issues.

**Comment by danbri** [comment]
I guess we can close this out now?  Thanks so much @gkellogg!

Nearby- I saved a copy of a run, so we archive the bugs we've published for posterity (and for Microdata spec work, /cc @chaals ).
