### ISSUE TITLE
Generalization / specialization candidates (medical terms in health-lifesci)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1114]
The following terms are (to be) defined in the health-lifesci extension (see #492). However their naming, meaning and/or definitions suggest that we should review them as candidates for generalization or specialization.
# Properties
- http://webschemas.org/supplyTo
- http://webschemas.org/status
- http://webschemas.org/source
- http://webschemas.org/sourcedFrom
- http://webschemas.org/frequency
- http://webschemas.org/branch
- http://webschemas.org/origin
- http://webschemas.org/warning
- http://webschemas.org/guideline
- http://webschemas.org/cost
- http://webschemas.org/connectedTo
- http://webschemas.org/manufacturer
- http://webschemas.org/population
- http://webschemas.org/overview
- http://webschemas.org/endorsers
- http://webschemas.org/foodWarning
- http://webschemas.org/codeValue
- http://webschemas.org/code
- http://webschemas.org/diagram
- http://webschemas.org/costPerUnit

TODO: are there also any types, enumerated values?

**Comment by danbri** [comment]
Also deferred for now, for reasons above:


      <div typeof="rdf:Property" resource="http://schema.org/profession">
        <span class="h" property="rdfs:label">profession</span>
        <span property="rdfs:comment">A profession exercised by a person or other entity.</span>
        <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Person">Person</a></span>
    	  <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Organization">Organization</a></span>
        <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Specialty">Specialty</a></span>
      </div>

/cc @philbarker

**Comment by danbri** [comment]
I suggest these can all be addressed after the sdo-deimos release (#911) currently [under review](https://lists.w3.org/Archives/Public/public-schemaorg/2016Apr/0053.html).  /cc @twamarc

**Comment by twamarc** [comment]
I agree, let's first focus on the release of sdo-deimos

**Comment by twamarc** [comment]
Meanwhile my early thoughts:
Except otherwise suggested below, I would declare them 'obsolete' here and to add specific properties in extension with fine-tuned definitions.
Keeping them in core and create others in extension may be confusing webmasters who are using them. But deprecating them it will be ok--I guess. If they are needed in core afterwards we may create them (not exactly using the same term, but the same semantic)

Here are my suggestions (if we agree on I will make a pull request):


``http://webschemas.org/supplyTo`` supersededBy ``http://webschemas.org/arteryBloodSupplyTo``

``http://webschemas.org/status`` supersededBy ``http://webschemas.org/studyStatus``

``http://webschemas.org/source`` supersededBy ``http://webschemas.org/arteryOrigin``

``http://webschemas.org/sourcedFrom`` supersededBy ``http://webschemas.org/nerveOrigin``

``http://webschemas.org/frequency`` supersededBy ``http://webschemas.org/doseScheduleFrequency``

``http://webschemas.org/branch`` supersededBy ``http://webschemas.org/arterialBranch`` [Already done!] & ``http://webschemas.org/veinBranch``

``http://webschemas.org/origin`` supersededBy ``http://webschemas.org/muscleProximalInsertion`` & ``http://webschemas.org/muscleDistalInsertion``

``http://webschemas.org/warning`` supersededBy ``http://webschemas.org/medicationFDAWarning``

``http://webschemas.org/guideline`` supersededBy ``http://webschemas.org/medicalGuideline``

``http://webschemas.org/cost`` supersededBy ``http://webschemas.org/medicationCost`` & ``http://webschemas.org/drugPrice``

We have here opportunity to disambiguated this types at the same time: the *drug cost* include *drug price = the price of the molecule itself* and dispensation prices as well as others indirect costs

``http://webschemas.org/connectedTo`` Keep it in core but extend its definition like `` Specifying an entity  to which this entity is connected. Eg. anatomical structure connected to another anatomical structure; A road connected to another road, etc.  ``

``http://webschemas.org/manufacturer`` supersededBy ``http://webschemas.org/productManufacturer``and stay in core. Note: to map to ``http://purl.org/goodrelations/v1#hasManufacturer``

``http://webschemas.org/population`` supersededBy ``http://webschemas.org/studyPopulation`` 
At the same level of scope:
``http://webschemas.org/sponsor`` supersededBy ``http://webschemas.org/studySponsor`` 
``http://webschemas.org/outcome`` supersededBy ``http://webschemas.org/studyOutcome`` 

``http://webschemas.org/overview`` supersededBy ``http://webschemas.org/dietaryPlanOverview`` 

``http://webschemas.org/endorsers`` supersededBy ``http://webschemas.org/dietaryPlanEndorsers``

``http://webschemas.org/foodWarning`` supersededBy ``http://webschemas.org/medicationFoodWarning``

``http://webschemas.org/codeValue`` supersededBy ``http://webschemas.org/medicalCodeValue``

``http://webschemas.org/code`` supersededBy ``http://webschemas.org/medicalCode``

``http://webschemas.org/diagram`` supersededBy ``http://webschemas.org/anatomicalImageDiagram``

``http://webschemas.org/costPerUnit`` supersededBy ``http://webschemas.org/drugPricePerUnit``

**Comment by danbri** [comment]
Hmm, I like these names - thanks. To be clear, each of these terms that I listed have already been included in the move from core to health-lifesci. I will double-check that our supersededBy machinery functions correctly within extensions but it ought to be fine. /cc @RichardWallis ... 

medicalCode is not a great name as it is very close to http://health-lifesci.webschemas.org/MedicalCode - I suggest we leave that as 'code' and consider for a broader meaning. Most of the others look like sensible improvements, from a quick review.

**Comment by twamarc** [comment]
@danbri Thanks. Yes `` medicalCode`` sounds like ``MedicalCode``. I agree to keep it as it is and extend its definition. In case supersededBy doesn't work (or is expensive) within extension we can make a small pull-request for the listed item and ship them now. 
If it works we will do this in next cycle. Am ok with both.

**Comment by danbri** [comment]
Thinking about schedule, let's do this change in the next release. I hope we can get current sdo-deimos agreed next week, and continuing to change it could discourage reviewers. Can you begin preparing a pull request though, based on today's sdo-deimos?

**Comment by twamarc** [comment]
It's a wise decision. Yes I start preparing the pull request--let me get a fresh current fork.

**Comment by danbri** [comment]
Re generalizing 'code' (and the basic structure of MedicalCode), one idea (related to SKOS, external extensions etc.) would be to have a type named StructuredCode as supertype of MedicalCode, and roughly meaning what SKOS calls "Concept". I tried ConceptCode previously but it didn't sound good. This might be the same as what @RichardWallis in https://github.com/schemaorg/schemaorg/issues/894 calls EnumerationValue ... I'm not sure yet.

**Comment by twamarc** [comment]
Hmmm! seems interesting.

re-phrasing @nichtich in #894 we should have:

From something like this:
```
<http://snomed.info/id/103693007>
        a skos:Concept;
        skos:inScheme <http://snomed.info/sct> ;
        skos:notation "103693007" ;
        skos:prefLabel "Diagnostic procedure".
```
We should have (conservative, re-using existing types with minimum adds):
```
<http://snomed.info/id/103693007>
a health-lifesci:MedicalCode;	 # ≈ skos:Concept   	==> MedicalCode
health-lifesci:codingSystem <http://snomed.info/sct> ;  # ≈ skos:ConceptScheme	=>MedicalCodingSystem?
health-lifesci:codeValue "103693007" ;	# ≈ skos:notation	==> MedicalCodeValue ?
health-lifesci:codeLabel "Diagnostic procedure".	# ≈ skos:prefLabel	==> MedicalDescription ?
```

StructuredCode as supertype of MedicalCode sounds good, but we need to fine-tune it and see how it may fit in such use case.
Finally we need to converge or at least to align with #582 and #251.
Let's further investigate, we will have a clear view before finalising the pull request
