### ISSUE TITLE
Should we add Enums for actionPlatform?

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#1121]
I was going through [Google's developers documentation](https://developers.google.com/structured-data/local-businesses/place-actions-standard#markup_for_actions) with @ddeering today when to my surprise I discovered that Google provides schema.org enumerations for 'actionPlatform' - enumerations that lead to 404 pages on schema.org:

> - http://schema.org/DesktopWebPlatform: Works on desktop web browsers.
> - http://schema.org/MobileWebPlatform: Works on mobile web browsers.
> - http://schema.org/AndroidPlatform: Works on Android native app.
> - http://schema.org/IOSPlatform: Works on iOS native app.

Now in issue #778 @danbri mentions _"How about we add actionPlatform (Text, URL) initially, and work out the enum later?"_

Something that never happened yet somehow Google ended up providing these nevertheless.

Should we add the enumerations Google suggest or should this be posted in Google's product forum?

Personally I'd prefer we add these to schema.org as this markup is already getting published at the moment.

**Comment by danbri** [comment]
It may have been me that discouraged my colleagues for asking for this. There is enough subtlety, nuance and change around (e.g. different flavours of Android, grey status of small/medium/huge tablets which may come with keyboard, etc etc...) as to make any small discreet set of values rather tricky to create and maintain. Ah yes, that was around #778. 

Schema.org's "external extensions" mechanism does provide a technical mechanism now where such extras over the top of the core can be layered on elsewhere. I'm not sure whether that is being used for actionPlatform by Google yet, but at least the machinery is maturing whereby this kind of experimental extension to schema.org can be documented further. /cc @vholland

**Comment by jvandriel** [comment]
_"... as to make any small discreet set of values rather tricky to create and maintain."_

I get what you're saying with this but isn't it a bit strange that one of schema.org's sponsors has to host an enumerated list/extension themselves? Especially if there's a serious chance this markup will have a good adoption rate since it's mentioned in their guidelines. 

I for one can perfectly imagine (and live with the fact) that one of the perks of being a schema.org sponsors is that we (the community) are a bit more flexible in regards to what we accept being added to the vocabulary.

Now if it were the case that Google only mentions a list of text values (like with [contactType](https://developers.google.com/structured-data/customize/contact-points#adding_structured_markup_to_your_site)) I feel it would be a different situation, but since they're mentioning schema.org url's already this means there's now markup (and guidelines) out there that needs to be changed only because we didn't add the enumeration list - which to me seems the lowest effort to resolve this.

Anyways, these are just my 2 cents.

**Comment by danbri** [comment]
Being a schema.org sponsor doesn't necessarily mean that every idea we have is a good one - and we know that. In this particular case we genuinely are not sure what is the best thing to ask to add to schema.org's core in the longer term, even while there is also a compelling use case and requirement to make platform-oriented categories like these in data today. This is an entirely natural and predictable situation, which is why we (google 'we' and schema.org 'we') have emphasized the extensions mechanism so much in the last year or so. In particular the 'pending' extension being introduced in this release is designed for cases like this, where there is the basis of a good idea but more experience/thought/deployment is also useful (see pending.webschemas.org). The external extension mechanism also provides another way for the founding search engines and others to explore new vocabulary that may not be quite ready or consensual or ripe for full standardization. TimBL's notes on "partial understanding" (https://www.w3.org/DesignIssues/Evolution.html) are somewhat relevant here btw. 

Whether Google should have used strings instead of (tentative) URLs in this case is a reasonable question. There are some subtleties around string values in JSON-LD data (see also #1094) which mean that it isn't entirely ideal to have strings either. At the moment the feature whose documentation you mention is flagged explicitly as "We are currently piloting this feature with a small set of initial providers. We hope to soon open up the feature to more providers", rather than for general availability. I'll look into adding a note that the markup is also non-standard too.

**Comment by jvandriel** [comment]
Thanks for your feedback @danbri. Seems I have a lot of catching up to do and I understand the reluctance to add the enumerations (for the time being).

**Comment by danbri** [comment]
Note also http://schema.org/SoftwareApplication has MobileApplication and WebApplication subtypes. /cc @vholland
