### ISSUE TITLE
Bad GS1 links for gtin documentation

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1130]
We have several GTIN-related documentation links which are now inaccessible (requiring passwords). What should they be replaced with? e.g. http://apps.gs1.org/GDD/glossary/Pages/GTIN-12.asp

    <div typeof="rdf:Property" resource="http://schema.org/gtin12">
      <span class="h" property="rdfs:label">gtin12</span>
      <span property="rdfs:comment">The &lt;a href="http://apps.gs1.org/GDD/glossary/Pages/GTIN-12.aspx"&gt;GTIN-12&lt;/a&gt; code of the product, or the product to which the offer refers. The GTIN-12 is the 12-digit GS1 Identification Key composed of a U.P.C. Company Prefix, Item Reference, and Check Digit used to identify trade items. See &lt;a href="http://www.gs1.org/barcodes/technical/idkeys/gtin"&gt;GS1 GTIN Summary&lt;/a&gt; for more details.</span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Offer">Offer</a></span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Product">Product</a></span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Demand">Demand</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Text">Text</a></span>
    </div>
    <div typeof="rdf:Property" resource="http://schema.org/gtin13">
      <span class="h" property="rdfs:label">gtin13</span>
      <span property="rdfs:comment">The &lt;a href="http://apps.gs1.org/GDD/glossary/Pages/GTIN-13.aspx"&gt;GTIN-13&lt;/a&gt; code of the product, or the product to which the offer refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13. Former 12-digit UPC codes can be converted into a GTIN-13 code by simply adding a preceeding zero. See &lt;a href="http://www.gs1.org/barcodes/technical/idkeys/gtin"&gt;GS1 GTIN Summary&lt;/a&gt; for more details.</span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Offer">Offer</a></span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Product">Product</a></span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Demand">Demand</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Text">Text</a></span>
    </div>
    <div typeof="rdf:Property" resource="http://schema.org/gtin14">
      <span class="h" property="rdfs:label">gtin14</span>
      <span property="rdfs:comment">The &lt;a href="http://apps.gs1.org/GDD/glossary/Pages/GTIN-14.aspx"&gt;GTIN-14&lt;/a&gt; code of the product, or the product to which the offer refers. See &lt;a href="http://www.gs1.org/barcodes/technical/idkeys/gtin"&gt;GS1 GTIN Summary&lt;/a&gt; for more details.</span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Offer">Offer</a></span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Product">Product</a></span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Demand">Demand</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Text">Text</a></span>
    </div>
    <div typeof="rdf:Property" resource="http://schema.org/gtin8">
      <span class="h" property="rdfs:label">gtin8</span>
      <span property="rdfs:comment">The &lt;a href="http://apps.gs1.org/GDD/glossary/Pages/GTIN-8.aspx"&gt;GTIN-8&lt;/a&gt; code of the product, or the product to which the offer refers. This code is also known as EAN/UCC-8 or 8-digit EAN. See &lt;a href="http://www.gs1.org/barcodes/technical/idkeys/gtin"&gt;GS1 GTIN Summary&lt;/a&gt; for more details.</span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Offer">Offer</a></span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Product">Product</a></span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Demand">Demand</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Text">Text</a></span>
    </div>

**Comment by danbri** [comment]
I've mailed Mark/Eric/Steve at GS1. Will just fix this when we get an updated URL

**Comment by jaygray0919** [comment]
IME there have been IP issues WRT GS1 codes. Seeing this (http://gs1.org/voc/DietTypeCodeDetails) was a pleasant surprise. It might be useful to ask GS1 about licensing terms related to their vocabulary, and licensing terms related to GTIN. GTIN values may not be in the public domain.

**Comment by danbri** [comment]
From @ekgs1 (I'll update the schema.org files accordingly):

* http://ocp.gs1.org/sites/glossary/en-gb/Pages/GTIN-12.aspx
* http://ocp.gs1.org/sites/glossary/en-gb/Pages/GTIN-13.aspx
* http://ocp.gs1.org/sites/glossary/en-gb/Pages/GTIN-14.aspx
* http://ocp.gs1.org/sites/glossary/en-gb/Pages/GTIN-8.aspx

**Comment by ekgs1** [comment]
In response to jaygray0919's question on IP issues with GS1 Standards, there are no licensing restrictions on using the GS1 vocabulary and the GS1 identifiers included in the GS1 Vocabulary and schema.org (e.g. gtin). 

The GS1 system of standards includes the specifications for all GS1 "keys"...which are unique identifiers that are used to identify things. For example, the Global Trade Item Number (GTIN) is a GS1 key that is used to identify products or trade items. The allocation of blocks of GTINs is managed by GS1 around the world to ensure, to the best of our ability, that no two different products or trade items will be identified by the same GTIN, i.e. each GTIN corresponds to only one product. The GTIN (and its predecessors UPC-12, EAN-13, EAN-8) have been in use since 1973 and this approach has been used over the decades to enable efficient operations in open supply chains around the world, through the use of GS1 open standards developed by the GS1 community for data exchange in areas including master data, transaction data / EDI messaging and event data / traceability.
Additionally, the GS1 system of standards includes the GS1 Vocabulary, which has been made openly available for use. The use of the vocabulary is not constrained by any IP restrictions. On the contrary, GS1 is encouraging the broad use of the GS1 vocabulary as an extension to the schema.org core vocabulary, to enable semantic descriptions of products and trade items more precisely and in greater detail, through the additional properties and classes available using the GS1 Vocabulary.
Regarding IP constraints around any particular GTIN value, any constraints on the use of any individual number in a web page would be similar to any constraints that may exist around any other product identifier (such as a product name, sku etc.).  GS1 is not aware of any IP restrictions that should prevent the referencing of a GTIN within a web page for a product.

**Comment by danbri** [comment]
All fixed, thanks @ekgs1 :)
