### ISSUE TITLE
PublicHolidays as a "DayOfWeek" needs better definition, an example, if it is to be usable

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1139]
We have had this in the OpeningHoursSpecification construction since 2012.

DayOfWeek in schema.org v2.2 gives http://purl.org/goodrelations/v1#PublicHolidays 
 as a possible instance.  In the proposed sdo-deimos release aka v3.0 this (like URLs for Monday-Friday) is given a schema.org URL, preserving the previous expressivity. However currently we have no examples of its use. 

The current plan is for a simple mapping, i.e. 
- http://purl.org/goodrelations/v1#Monday -> http://schema.org/Monday
- http://purl.org/goodrelations/v1#Tuesday -> http://schema.org/Tuesday
- http://purl.org/goodrelations/v1#Wednesday -> http://schema.org/Wednesday
- http://purl.org/goodrelations/v1#Thursday -> http://schema.org/Thursday
- http://purl.org/goodrelations/v1#Friday  -> http://schema.org/Friday
- http://purl.org/goodrelations/v1#Saturday -> http://schema.org/Saturday 
- http://purl.org/goodrelations/v1#Sunday -> http://schema.org/Sunday
- http://purl.org/goodrelations/v1#PublicHolidays -> http://schema.org/PublicHolidays

However the latter has no examples. 

> grep PublicHolidays data/*.txt

The GoodRelations documentation does however say "A placeholder for all official public holidays at the gr:Location. This allows specifying the opening hours on public holidays. If a given day is a public holiday, this specification supersedes the opening hours for the respective day of the week.". Perhaps this should be incorporated? /cc @betehess @mfhepp 

Current definition proposed for v3 is http://webschemas.org/PublicHolidays "This stands for any day that is a public holiday. While not technically a "day of the week", it can be used to with OpeningHoursSpecification."

**Comment by danbri** [comment]
How about: "A placeholder for all official public holidays in some particular locale. In the context of an OpeningHours specification it can be used to indicate opening hours on public holidays, overriding general opening hours for the day of the week on which a public holiday occurs."

**Comment by betehess** [comment]
That is a better definition.

The problem as I understand it is in the interaction of PublicHolidays and
OpeningHoursSpecification.

I think that PublicHolidays alone will never be useful: with no further
constraint, the OpeningHours would match all local holidays, whatever they
are. It's almost impossible to know which actual days will be matched,
almost making it an anti-pattern in the context of an
OpeningHoursSpecification?

But it might be useful for a data publisher to say that a store will
be closed on a Monday because it's a holiday, as some kind of reminder. The
problem is that the semantics of dayOfWeek is additive: we only add days to
a OpeningHoursSpecification.

>

**Comment by danbri** [comment]
There is an implicit need for context. The original GR definition did this via the word "the" in " all official public holidays at *the* gr:Location". But since in a schema.org setting there could be lots of different things with locations related by different relationships to any given PublicHolidays instance, I suggest we make the model a little more explicit. I guess what we want to say is "when this is used as a day of the week in describing the opening hours of some local business, then the location of the place determines the applicable holidays". Which is a longwinded version of commonsense really. An example would help for sure.

**Comment by betehess** [comment]
I agree, that approach might be enough for now.

**Comment by mfhepp** [comment]
+1
Martin

**Comment by danbri** [comment]
I've updated http://webschemas.org/PublicHolidays in the light of this thread.

> This stands for any day that is a public holiday; it is a placeholder for all official public holidays in some particular location. While not technically a "day of the week", it can be used with OpeningHoursSpecification. In the context of an opening hours specification it can be used to indicate opening hours on public holidays, overriding general opening hours for the day of the week on which a public holiday occurs.

**Comment by betehess** [comment]
> I've updated http://webschemas.org/PublicHolidays in the light of this thread.

👍

**Comment by lexbi** [comment]
Is there an example of how to use @danbri 's  suggestion? Or, is it still currently a work in progress?

**Comment by unor** [comment]
@lexbi The enumeration value [`PublicHolidays`](http://schema.org/PublicHolidays) is part of Schema.org (since the last version, [3.0](http://schema.org/docs/releases.html#v3.0)), so it can be used.

I included [an example in my answer to a Stack Overflow question](http://stackoverflow.com/a/38015145/1591669). It uses the (also new) `specialOpeningHoursSpecification` property, which overrules the opening hours provided with `openingHours`/`openingHoursSpecification`.
