### ISSUE TITLE
Why don't previous MedicalEntity url's work?

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#1164]
Hi all,

I have the impression something went seriously wrong with schema.org's latest release in regards to schema.org/MedicalEntity.

If you currently visit http://schema.org/MedicalEntity you get the mesage:
_"The term 'MedicalEntity' is not in the schema.org core vocabulary, but is described by the following extension(s): health-lifesci"_ - as opposed to getting the proper page served.

Does this mean that all markup out there is now broken and should be reworked to comply with the new url's part of http://health-lifesci.schema.org? (same thing happens with other extensions as well)

If not, how fast can this be fixed cause there's now already a publication out there warning folks to rework their markup (http://www.searchinfluence.com/2016/05/oh-no-where-did-medical-schema-go/).

cc: @danbri / @RichardWallis / @twamarc

**Comment by RichardWallis** [comment]
Now that these terms have been moved in to an extension this is the normal mode of operation if you try to view the documentation when not in the extension in which the term has been defined.  All extensions work in this way.

__No previous markup is broken or will need to be reworked because of this change__ - the canonical URI of the term, as displayed at the top of the term page, is still http://schema.org/MedicalEntity

Hosted extensions, and the domain allocated for them [in this case http://health-lifesci.schema.org/] bring the terms together in a domain focused way for discussion and documentation.  However the term identifiers are all allocated in the schema.org namespace.

See http://health-lifesci.schema.org/docs/extension.html and http://health-lifesci.schema.org/docs/howwework.html for more information.

I will comment to this effect on the post you referenced.

~Richard

**Comment by jvandriel** [comment]
_"the canonical URI of the term, as displayed at the top of the term page"_

Now that's something I've overlooked because I haven't dealt with any referrals to extensions so far, until today that is. And I have to say as a developer/consultant I find it absolutely confusing and something that completely disrupts workflows - How so?

First off, many I know copy Type url's by right clicking the link and copy it's url via the menu that pops up.
When you do that now you end up copying the url of the extension as opposed the the schema.org url.

Secondly, it isn't obvious enough that one should use the canonical url as opposed to extensions url and my first impression is that this will likely end up in many folks doing it wrong.

Now before I turn this into a rant about how I think this doesn't work and should be modified ASAP, let me ask a question first.

Why doesn't schema.org use a form of 'url aliassing' [like Drupal does](https://www.drupal.org/node/120631)?

This way folks that visit URLs simply get to see and use the schema.org (canonical) url, thus completely avoiding any confusement.

**Comment by Aaranged** [comment]
@RichardWallis Pretty confusing use of "canonical" IMO. :)

Looking at http://bib.schema.org/docs/extension.html I can't quite get my head around this.  Is it possible that, now that schema.org _has_ external extensions, that the example on that page could be updated so that it uses an actual use case, rather than fictitious "Microform" type?  TL;DR in regard to my reserved comment is that, if the _canonical_ URL for an extension type or property is schema.org rather than extension.schema.org, why is it necessary to declare (in the case of JSON-LD) the extension subdomain at all?  Thanks!

**Comment by RichardWallis** [comment]
I can understand how this is initially confusing in this case where terms [that were previously in the core vocabulary] have been collected together in an extension.

Whereas the normal introduction to extension terms has been for terms that make their first appearance in an extension.  In such cases, where examples reference the canonical URI, no significant issues have been reported.

**Comment by danbri** [comment]
Queueing this for a proper reply (but not tonight).

**Comment by jvandriel** [comment]
_"if the canonical URL for an extension type or property is schema.org rather than extension.schema.org, why is it necessary to declare (in the case of JSON-LD) the extension subdomain at all?"_

+1

**Comment by mfhepp** [comment]
because of

1. schema.org source code management (it is getting very hard to review contributions to the cord of schemaorg)

2. term stability, term authority and differences in the organization of the subcommunity.

martin

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by danbri** [comment]
We've made some fast track tweaks (see #1165) to the wording of pages like http://schema.org/Drug which should ease some concerns. Also the medical situation is unusual. It was an exceptionally large chunk of the schema.org core (about 20%). I do not anticipate such large changes (especially moving things out of core) to happen often (or ever). 

The doc at http://schema.org/docs/extension.html also has too much of the flavour of an (evolving) discussion draft, and could also do with a refresh. In our earlier thinking we expected to see the subdomains more widely used in markup. They are still needed because each extension actually does amount to a kind of "sandbox" with its own slightly different view of the core, mainly by adding new type/property associations.

I expect the best practice consensus around use of extensions will continue to evolve as we figure out how best to integrate multiple independently hosted extensions (e.g. schema.org + GS1) within common markup. The work in #990 was an important step in that direction.

**Comment by jvandriel** [comment]
Thanks @danbri, that helps. What I still am wondering though is what happens if somebody copies and pastes an extension url (eg, http://health-lifesci.schema.org/Drug) into their markup as opposed to the canonical url, is that an issue or is that seen as valid markup?

**Comment by jvandriel** [comment]
And might it be an idea to include the output of each extension page on the canonical url page as well (as opposed to only the wording) so that one doesn't have to switch back and forth between core and extension pages?

As a frequent user of the site I expect to find the information I'm looking for on for example http://schema.org/Drug and find it a strange experience I to have to visit http://health-lifesci.schema.org/Drug to find out which types and properties I can use.

**Comment by danbri** [comment]
I think we've largely addressed this (esp. #1165), although @jvandriel 's UI suggestions for the main page are worth bearing in mind. I'll close for now, chasing the naive dream of < 400 open issues ;)
