### ISSUE TITLE
Why is there an 'itemOffered' property in Demand? Shouldn't it be called 'itemDemanded'?

### ISSUE THREAD

**Issue by vercotux** [schemaorg/schemaorg#1181]
It is rather confusing. A demand is being requested/demanded, not offered. The same goes for 'seller'. Nobody is selling a demand, the demand is being requested/demanded by a person or an organization that could be called a 'demander'.

**Comment by mfhepp** [comment]
The idea is that Demand is the indication to look for a matching offer, and it is fully symmetric to Offer in terms of structure and properties.

Read it that way: Peter seeks and Offer that includes, as itemOffered, a VW Golf Car  (or the repair of his ancient wristwatch).

I strongly advocate not to break this symmetry.

Historically, we used "Offer" for both supply and demand in the original GoodRelations model, and only the type of the link from the Agent (offers vs. seeks) would indicate whether this is an actual offer or the interest in such an offer. But this was suboptimal, because the meaning of the offer would critically depend on the type of a link *to* it, which is bad (if you miss that statement, you do not know whether this is an actual offer or the indication of a fellow human who likes the same products as you do).

Martin

**Comment by jaygray0919** [comment]
TY for your explanations. We keep a catalog of these entries. IOHO, these 'rich snippets' eventually need to appear in a book or dictionary-of-lessons-learned as 'reasons why ...'.

**Comment by mfhepp** [comment]
@jaygray0919 Thanks! In general, this "book" for all commercial patterns will be  at http://wiki.goodrelations-vocabulary.org/Documentation and http://wiki.goodrelations-vocabulary.org/Cookbook. But all the examples need to be completed and updated so that they reflect the schema.org naming of GoodRelations elements (see http://wiki.goodrelations-vocabulary.org/Cookbook/Schema.org) and of course be kept in sync with the evolution of schema.org.

Not sure I will ever find the time for this; after all, it is a volunteer effort that has already taken a decade of my life ;-)
