### ISSUE TITLE
deliveryLeadTime description update

### ISSUE THREAD

**Issue by gmackenz** [schemaorg/schemaorg#1201]
On site pickup is a delivery option. To make deliveryLeadTime clearer, modify the description to read:

"The typical delay between the receipt of the order and the goods either leaving the warehouse or being prepared for pickup, in case the delivery method is on site pickup."

#1200

**Comment by danbri** [comment]
That seems a sensible improvement to "The typical delay between the receipt of the order and the goods leaving the warehouse."

**Comment by mfhepp** [comment]
Yes, makes sense.
+1

**Comment by danbri** [comment]
@gmackenz since the PR got a bit tangled, could you simply copy/paste the essence of your proposal, or is it simple:

* ... that we change deliveryLeadTime to say "The typical delay between the receipt of the order and the goods either leaving the warehouse or being prepared for pickup, in case the delivery method is on site pickup." instead of "The typical delay between the receipt of the order and the goods leaving the warehouse." ?

**Comment by gmackenz** [comment]
@danbri - That's the proposed change, would be great to add it to sdo-makemake

**Comment by danbri** [comment]
@gmackenz thanks. It seems entirely innocuous, I'm going to just do it. [...] I just did it.

**Comment by gmackenz** [comment]
I saw what you did there :)


Gordon Mackenzie |  Schema Wrangler (Ontologist) |  gmackenz@google.com |
