### ISSUE TITLE
Schema.org and Google AMP

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#1207]
@danbri 
I know you are focused on several clean-up issues, Dan, but would like to briefly interrupt and ask for advice.

The Google AMP team has HTML elements to read external JSON files.

For example, publishers use `amp-list` and `amp-mustache` to access JSON data served via CORS using HTTPS.

By default, the AMP HTML elements expect a root JSON key and array as follows: `"items": [{}]`.

We have asked the Google AMP team to provide a more flexible approach where a publisher could process a JSON-LD structure.

The Github thread on this topic is here:

https://github.com/ampproject/amphtml/issues/3554#issuecomment-226045064

@dvoytenko has proposed a Javascript-like structure navigation method where `items` is either an explicit or implicit root, and one walks the tree to reach the "value-of-interest".

Consider the following use case: a publisher needs to document terms in an HTTPS/CORS/@context file. Rather than repeating the @context structure in-line in HTML, publisher uses `amp-list` and `amp-mustache` to "get" the target data.

The next level of effort would enable a publisher to format content of an in-line schema.org JSON-LD file (of which a mirror copy is served from an HTTPS/CORS server). This approach enables a publisher to expose the JSON-LD data in HTML, rather than duplicating the information using HTML microformats syntax.

My purpose for interrupting is to open a dialog with you, @dvoytenko and other interested parties to make sure we do this the right way.

Separately I've asked my teammates to analyze the @dvoytenko approach. For example, we do substitutions when initializing @context so we don't have to escape the `@` symbol when processing a graph. While this works for us, it's a non-standard technique. But it makes it easier to follow the proposed method.

Please let me know if you can help craft a solution here.

/jay

**Comment by gkellogg** [comment]
A couple of things here, if the JSON is provided using application/json (rather than application/ld+json), a JSON-LD processor will look at a link header to find a context (see [Interpreting JSON as JSON-LD](http://www.w3.org/TR/json-ld/#interpreting-json-as-json-ld)).

Also, you may continue to use `items` at the top-level if you alias it from `@graph`, which if it has an object value would work as JSON-LD. Of course, if you can specify the root, you might use something else, but then you would be ignoring the other properties of a top-level object, which may also be JSON-LD.

This mechanism doesn't work as will with in-line JSON, as there's no way o specify a Link header; in this case, you would want to use `type="application/ld+json"` and include the `@context` inline.

**Comment by jaygray0919** [comment]
Tks @gkellogg The focus here is exclusively JSON-LD, and helping Google AMP update their JSON processor (using elements `amp-list` and `amp-mustache`) to handle a JSON-LD structure.

In order to make the initial point, I shared an example of a JSON file that uses a root term different than `"items": [ { } ]`. The second stage of the example used a JSON-LD structure. 

In the thread above, (ampproject/amphtml#3554), Google proposes a modification to their processor that will "walk a tree" using a specification technique like this: `<amp-list ... items="PropertyTable.Properties">`. This proposal was in reply to my initial JSON example.

As I understand their proposal, a publisher would process (extract) values from a JSON file by specifying the path of the hierarchy. To generalize, it would look like this:

       `items=level-A-term.level-A-1-term.level-A-1-1-term`

Now let's consider a JSON-LD file. If the `@context` declaration is at the bottom of the structures (as used by some publishers), that approach might work. But I don't think it will work if the JSON-LD file opens with the `@context` declaration (as all of our JSON-LD documents do). The reason it won't work is that Google AMP is looking for an array in the form of {"term-0": [{"term-1"},{"term-2"} ...]}

Lemme get back to @dvoytenko and present him with a more complicated JSON-LD structure and ask for his advice. Will copy you on the thread.

**Comment by gkellogg** [comment]
> Now let's consider a JSON-LD file. If the @context declaration is at the bottom of the structures (as used by some publishers), that approach might work. But I don't think it will work if the JSON-LD file opens with the @context declaration (as all of our JSON-LD documents do). The reason it won't work is that Google AMP is looking for an array in the form of {"term-0": [{"term-1"},{"term-2"} ...]}

Setting aside the fact that JSON objects are not ordered, the specific location in a (top-level) JSON object for the `@context` is not important to a JSON-LD processor. Doesn't seem a particularly good practice for a Google AMP processor to depend on this either.

My earlier point is that a JSON-LD processor will look in a specific Link header for a reference to a context if the content is returned using `application/json` rather than `application/ld+json`. This allows you to not include the `@context` definition at all, but does place a requirement on the service providing the JSON file to add the Link header.

Given your example:

```
<p>
<amp-list
    width=auto
    height=80
    layout=fixed-height
    template="amp-template-1"
    src="https://dl.dropboxusercontent.com/u/3094317/pubchem_data.json"
>
</amp-list>
</p>
```

If, when retrieving `https://dl.dropboxusercontent.com/u/3094317/pubchem_data.json` you get something like the following:

```
HTTP/1.1 200 OK
...
Content-Type: application/json
Link: <https://dl.dropboxusercontent.com/u/3094317/pubchem_data_context.jsonld>; type="application/ld+json"

{
    "items": [
      {
        "CID": 2244,
        "MolecularFormula": "C9H8O4"
      }
    ]
}
```

Then you could retrieve `https://dl.dropboxusercontent.com/u/3094317/pubchem_data_context.jsonld`, you can have a context, such as the following:

```jsonld
{
  "@context": {
    "items": "@graph",
    "@vocab": "http://schema.org/"
  }
}
```

This would allow the result to be interpreted as JSON-LD, and give meaning to the properties contained within the returned JSON. Note that you can't do this for the embedded JSON case, but it might be enough to get you started.

**Comment by jaygray0919** [comment]
I need to do more research about if/how AMP processes `Content-Type`. BBTY.

**Comment by jaygray0919** [comment]
Sometimes the detail of these problems obscures the purpose of the question. The bigger picture here is: can AMP services (`amp-list` and `amp-mustache`) process a JSON-LD file that also is in-line on a AMP-valid web page? We know the harvesters will processes the in-line JSON-LD structure (as does GSDTT and your SDL). But if the AMP services will processes the companion to the in-line JSON-LD structure served as a file via HTTPS/CORS, then a publisher can format the JSON-LD contents on a web page. No need to re-type the keys and values, and no need to re-code the semantics in microformat syntax.

**Comment by jaygray0919** [comment]
Also, we never considered remapping `"@graph"` to `"items":` . That technique solves another set of problems. We typically use `@graph` to set an array (of schema.org structures and "W3C" structures). But your technique enables use of `"items"` We use many JSON and JSON-LD files from other authors who use `"items"` to set the array. Now our authored files can have the same structure as those files. "Dawn breaks on marble head" (self deprecation understood by folks from Massachusetts).

**Comment by danbri** [comment]
This seems well worth exploring, but I'm not up on the details. Glad to see @gkellogg here...

**Comment by jaygray0919** [comment]
Have tried to incorporate @gkellogg advice here:
 https://github.com/ampproject/amphtml/issues/3554#issuecomment-226045064

We'll learn Dima's reaction shortly.
