### ISSUE TITLE
subOrganization, department, branchOf

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1216]
- http://schema.org/subOrganization says "A relationship between two organizations where the first includes the second, e.g., as a subsidiary. See also: the more specific 'department' property."
- http://schema.org/department says "A relationship between an organization and a department of that organization, also described as an organization (allowing different urls, logos, opening hours). For example: a store with a pharmacy, or a bakery with a cafe."
  - Should these not be inverses?
  - We also have http://schema.org/branchOf "The larger organization that this local business is a branch of, if any. Not to be confused with (anatomical)branch." (which is superseded by http://webschemas.org/parentOrganization)
  - If these mean the same thing, we should converge the descriptions.

**Comment by marijane** [comment]
I landed here after searching for guidance on using department vs subOrganization/parentOrganization, and I just wanted to say that I'm leaning toward using the latter because I prefer to use properties that have inverses.  It's not clear to me what the specificity of department provides, and having both in the vocabulary is confusing.

**Comment by dbs** [comment]
I would like some clarity as well.

One functional difference is that http://schema.org/subOrganization has the inverse http://schema.org/parentOrganization, while http://schema.org/department has no inverse.

**Comment by akuckartz** [comment]
See also: https://www.w3.org/TR/vocab-org/
