### ISSUE TITLE
Missing "Price" on "Residence"

### ISSUE THREAD

**Issue by Rombecchi** [schemaorg/schemaorg#1233]
Please let Residence have a "Price" and "CurrencyPrice"!
For real estate selling
Thanks

**Comment by mfhepp** [comment]
no, include Residence or Place in tha range of itemOffered and use Offer for the commercial properties.

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by jvandriel** [comment]
Now I'm not saying we shouldn't expand the range of ```itemOffered``` but wouldn't a multi-type entity suffice, eg ```"@type":["Product","Residence"]```?

**Comment by mfhepp** [comment]
yes, an MTE pattern will also work, depending on search engine support for MTEs.

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by thadguidry** [comment]
@jvandriel Does Google already parse that particular MTE type ?  Have you tried ?

**Comment by jvandriel** [comment]
It works according to the Google's Search Console but the Structured Data Tool still fails on any type of MTE.

And as for the ```["Service","MedicalTherapy"]``` MTE, we're about to rollback to a ```["Product","MedicalTherapy"]``` to get those pretty search results again. 

Besides acknowledging the issue Google's Structured Data Team unfortunately didn't give any feedback as to whether they intend to support it or not. And I don't think it's correct to let @LeezaRodriguez be the victim of that situation. Especially since the ```["Product","MedicalTherapy"]``` is technically 'correct' as well. So alas, no ```["Service","MedicalTherapy"]``` until more about Google's* intentions is known.

**Comment by jaygray0919** [comment]
GSDTT does not accept compound Types, as are accepted in RDFa. There are schema.org examples that also fail. @danbri indicates this is a known problem at Google but have not heard of a planned fix.

**Comment by LeezaRodriguez** [comment]
I want the MTE and associated properties that best describe the content.  But like other webmasters, I can't help but gravitate (back) to where the snippets are. :)

**Comment by DDeering** [comment]
On one hand, I think there's a good argument to make things such as Residence, Book, Photograph, SoftwareApplication and so on subtypes of Product since they are sold as products.  On the other hand, if Google wasn't so tight with its display of rich snippets, showing them only for a handful of types, people like @jvandriel and @LeezaRodriguez wouldn't have to have this constant struggle deciding between using the most specific schema type and the one most likely to get rich snippets that in turn would likely lead to more clicks, visits, new clients, etc.

**Comment by vholland** [comment]
+1 to @mfhepp's suggestion. Otherwise, we cannot really scale to all the Things which may be sold.

This seems to have morphed into a discussion of Google's testing tool, so I am closing for now.

**Comment by jvandriel** [comment]
IMHO this hasn't morphed into a discussion about the SDTT. It's more a matter of schema.org's sponsors not indicating whether or not they support MTEs.

The SDTT and GSC are the only tools that can be referred to for illustration purposes as the other sponsors give us no data to work with, which makes discussing about whether or not MTEs are supported seem to be about Google's tooling.

So the bigger issue at hand is whether or not MTEs are the way to go with this (and confirmation by the sponsors would help out a lot with this discussion).

**Comment by danbri** [comment]
It is reasonable to ask us at schema.org whether we are serious about continuing to advocate for multi-typed descriptions given the apparently underwhelming implementation on this front from the project's founders. This is not the best place for that existing conversation, though I forget if there is an actual issue open for it. IMHO MTEs aren't going away and implementations will catch up eventually. I will propose a clarification to docs/datamodel.html relating to this soon.

**Comment by gigster99** [comment]
I agree with @jvandriel .To express the idea in the vernacular, schema.org vocabulary and grammar (S-O) is "potential energy." S-O doesn't  become "kenetic energy" until it is put to use. The best ways to verify the energy is correct are to use Google SDTT or Gregg Kellogg's Structured Data Linter. For me, JSON-LD Playground sometimes produces unexpected results.

Said another way, only GSDTT and SDL show reality. Up to that point, anything described by S-O is theory.

@danbri Dan has previously expressed the desire to keep the S-O project separate from Google. His reasons are sound; one often see the suspicion expressed on messaged boards that S-O is Google lock-in. We know it's not, but Dan needs to be like Caesar's wife here.

Having said that, we know examples of S-O grammar that are not accepted by Google SDTT. Is the S-O grammar wrong? In reality, the answer is **yes** because the "theory" cannot be translated to "reality."

IMHO, the proof that S-O statements are correct is verified by Google SDTT and Kellogg's SDL.

**Comment by mfhepp** [comment]
@gigster99 It is really important to understand that schema.org is a broad activity run by many stakeholders, and not a Google-only thing. I understand that for many adopters of schema.org, the effects in Google search engine products is the main motivation. The big search engines are major consumers of schema.org data, and they might impose additional requirements (like certain properties being mandatory) or relax some (e.g. accepting strings instead of URIs), but so will any other consumer of such data depending on domain, business requirements, and computational resources.

To my knowledge, schema.org is consumed by Google, Bing, Yahoo, Yandex, Apple, Pinterest, and likely hundreds of startups and app developers. It would be a real pity to reduce schema.org to Google Search products.

Also note that even in the case of a single search engine, there is no simply causal relationship between adding markup and easily monitorable effects like Rich Snippets. Search engines use markup in a myriad of ways, e.g. for augmenting their back-end knowledge bases (e.g. Google Knowledge Graph), for training data extraction, for spotting geographical relevance etc.

Hope that helps.

Martin

**Comment by gigster99** [comment]
@mfhepp "Uncle" (https://en.wikipedia.org/wiki/Say_Uncle). My wimping retort is: we really need @gkellogg Gregg Kellogg to make SDL correctly validate S-O grammar; otherwise "we won't know for sure." As an aside on your point about "restricting and relaxing", SDL is strict on datatypes (like integers on image dimensions) while GSDDT is relaxed. We can chose to overlook the error reported by SDL, knowing that GSDTT is relaxed; or, we can be precise. But at lease we can clearly see the results of a design.
