### ISSUE TITLE
Add Event & CreativeWork to range of itemOffered

### ISSUE THREAD

**Issue by RichardWallis** [schemaorg/schemaorg#1269]
`Event` & `CreativeWork` have `offers`, yet unlike `Product` and `Service` they are not in the range of `itemOffered`.   

Matching the changes associated with `Accommodation` see (#1264)

**Comment by vholland** [comment]
I am strongly opposed to this for reasons outlined in the discussion around Accommodation. We should be using MTEs for this.

**Comment by danbri** [comment]
@vholland I talked with @RichardWallis today and also encouraged MTEs. His point remains fair even in that context, which is that there is a larger ad-hoc list of types attached to "offers", but not to "itemOffered", and this is counter to their natural reading as a pair of mutually inverse properties.

My preference would be for MTE approach to come to dominate and we could make the two explicit inverses and use the same list of types for both.

**Comment by RichardWallis** [comment]
In principle I agree we should be using MTEs for this.

We have established practice however, for using 'offers' to relate CreaiveWork & Event to an Offer, in the same way as for Product and Service. Implicitly (for Product & Service) itemOffered is inverseOf offers.   That symmetry is not there for Event & CreativeWork.

**Comment by danbri** [comment]
So the counter proposal is to remove Event & CreativeWork from range of itemOffered. If someone uses itemOffered to point to an Event or to a CreativeWork, the assumption would be that the entity is also a Service and/or Product.

**Comment by jaygray0919** [comment]
FWIW we use this chain:

     EducationalEvent/makesOffer/Offer/itemOffered/Service

We would like to use this chain:

     EducationalEvent/makesOffer/Offer/itemOffered/CreativeWork

where the `CreativeWork` is a Syllabus with `hasPart`.

**Comment by RichardWallis** [comment]
@danbri Event and CreativeWork are _not_ in the range of [itemOffered](http://webschemas.org/itemOffered) (adding them was the subject of this proposal).

The counter proposal as you put it, would be to remove CreativeWork and Event from the domain of [offers](http://webschemas.org/offers).  

Assuming that a CreativeWork has also been defined as Product or Service, as its CreativeWork-ness cannot be 'offered' or traded is a bit of a leap, especially in the cultural heritage world.   

Firstly the concept that all the items on the physical and virtual shelves of a library, or artefacts in an archive or museum are 'products' or worse still 'tradable items' would go beyond the comprehension of most curators, archivists and librarians.

Secondly, apart from upsetting the sensibilities of cultural heritage professionals the model, adopted from previous standard practice with Offer, has been that such items have _offers_, to loan, download, gain information about, and/or view, made by the holding organisation.  [This model](https://www.w3.org/community/schemabibex/wiki/Holdings_via_Offer#Library_holdings) was evolved through much discussion in the Schema Bib Extend community group as a pragmatic solution to the problem of describing what a library 'holds'.

I understand, and have a great deal of sympathy with, the desire voiced by @vholland to use MTEs to drive this pattern, but I am also strongly of the opinion that you cannot divide the world into Products/Services and everything else.   

I would however say that we _do_ have things that are offer-able and those that are not. [We should avoid using terms such as tradable because of the commercial overtones which immediately exclude a whole area of activities]

So I am tempted to suggest that we create a new Intangible Type 'OfferableItem' with a single 'offer' property (that supersedes the currently awkwardly named 'offers').  Product, Service, Event, & CreateiveWork are removed from the range of 'offer' (_offers_) and replaced by OfferableItem.  Product & Service are then made subtypes of OfferableItem.

This would have little impact for the core commercial world, except encouraging the use of _offer_ instead of _offers_, as offer would be still be available without the need for extra MTEs.  In the cultural heritage world, the pattern of making things offerable by adding the _OfferableItem_ MTE (instead of Product) will make far more sense.  Plus we will introduce the flexibility to describe things for sale that are definitely not products or services, [such as this attractive proposition](http://www.dailymail.co.uk/news/article-3716933/The-ultimate-hideaway-Snap-190-000-home-private-river-island-River-Avon-view-booking-boat-crossing.html).

Whatever the solution, my original proposal, something like I describe here, both, or neither, the documentation and guidance needs to improve in this area, beyond tweaking of term descriptions and examples.  This is one area where I consistently I hit the _I can't quite get my head around it_ syndrome when introducing Schema to new people.

**Comment by danbri** [comment]
Sorry - bug in my hasty weekend comment. I think we all share the goal of having "offers" and "itemOffered" not arbitrarily differ, since they appear on natural reading to be intended as mutually inverse. 

There is a view (cue @rvguha ) that terms named like "OfferableItem" go against the general thrust of schema.org's design which has been to *avoid* interposing artificial classes purely for the sake of expressing domain/range patterns. But I think I understand where you're coming from, which is that there is a general meaning to the "offers" property that is deeper/wider/bigger than what we get from the commercially-minded product+service types.

> "I am also strongly of the opinion that you cannot divide the world into Products/Services and everything else."

That captures the motivation for better support of multiple typing: it allows you to mix together situation-appropriate types without them being rigidly organized into a single hierarchy. If a thing that is e.g. a Book also makes sense to describe using Product properties, then you just directly add in the relevant properties to your description. Some things are books, some are products, some are both, ... no big deal.

Product is already "Any offered product or service". There is a case that a Service is a kind of Product and that product+service captures the "offerable" aspect of creative works. However I take your point that this may look to a crass / commercial dumbing down of cultural artifacts to the level of mass produced consumer goods. Also cue @mfhepp (except he's on vacation) to point out that in GoodRelations he had ProductOrService rather than breaking out the two into distinct types.

Can we all agree that if "x offers y" doesn't always imply "y itemOffered x" we ought to have a decent story as to why?

Thanks @jaygray0919 for bringing up "makesOffer", which *is* marked as an inverseOf of offeredBy (a pair of inverse properties whose corresponding expected types match exactly). The main question here is why "offers" and "itemOffered" do not have a similar matching structure.

**Comment by danbri** [comment]
Closing in favour of #637 but noting that we should support non-commercial offers more clearly in our language.
