### ISSUE TITLE
health-lifesci missing `treatment` and `preventiveProcedure` property definitions

### ISSUE THREAD

**Issue by gkellogg** [schemaorg/schemaorg#1295]
Note that `possibleTreatment` has a super-property `treatment` which is not defined and that `primaryPrevention` has a super-property `preventiveProcedure` which is also not defined.

Is there a process to be sure that all referenced terms are defined prior to release?

**Comment by gkellogg** [comment]
Presumably `preventativeProcedure` and `treatment` should be a sub-properties of `availableService`.

**Comment by danbri** [comment]
Thanks! We have SPARQL-based unit tests in tests/* but obviously not enough...

**Comment by danbri** [comment]
@twamarc what list?

**Comment by twamarc** [comment]
@danbri It was just a way of saying, It's my desktop sticker list. Not an official one. However am making a backlog of raised issues so I can plan future suggested improvements: https://github.com/twamarc/ScheMed/issues/38

**Comment by danbri** [comment]
I am most concerned here that we published data that is not (in some sense) well-formed. Whether we want to add more properties later is a secondary matter,  although we have quite a lot of terminology already. Schema.org's definitions should not reference non-existent schema.org terms.

My suggestion is that we remove the broken schema references to "treatment" and "preventiveProcedure" immediately as a quick fix, rather than wait for our next release. 

Any objections?

**Comment by danbri** [comment]
There's a role for desktop lists (here's [mine](https://twitter.com/danbri/status/763391811603861505) :) but let's get everything in Github too!

**Comment by gkellogg** [comment]
My own internal tests do reasoning over every term to be sure all referenced terms are if within a know vocabulary are actually defined in that vocabulary; that would be hard to do in SPARQL, but a python script might look at all URIs the vocabulary and do a similar filter.

**Comment by danbri** [comment]
Yeah. We could check that all values of rdfs:subPropertyOf mention something described as an rdf:Property, and so on.

**Comment by RichardWallis** [comment]
Commit (a0a3b53) added 2 new tests to identify:
1. Catches Types declared as rdfs:subClassOf a nonexistent Type
2. Catches Properties declared as rdfs:subPropertyOf a nonexistent Property
