### ISSUE TITLE
Course-related administrivia tracking, breakout from #195

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1315]
@philbarker @westurner ... I'm opening a separate issue to track course-related admin issues separately from main #195 conversation.

On the question of keeping Github history trails and minimizing reworking of files - I've just broken out the courses file into a boilerplate-195.rdfa and an issues-195.rdfa. I'd encourage the Community Group to work from a fresh copy of latest branch of schema.org and make PRs against the latter; I'll take on the duty of updating boilerplate-195.rdfa. This does however mean (because our implementation uses special file paths for extensions) that when we do finally merge these definitions into data/schema.rdfa it won't be possible to understand the complete trail purely via Git, but that's why we have have also a releases page, blog posts, acknowledgements mechanism etc.  It is good to have Git but we don't want to get overly entangled with it. So for example releases are explicitly materialized in data/releases/\* too...

**Comment by philbarker** [comment]
happy to do what makes managing schema development easiest, and that seems easier all round.

**Comment by danbri** [comment]
Likewise. I think the change I made yesterday makes it easier for something to temporarily be in pending even while destined for core, in terms of the RDFa+RDFS document's *contents* but not its *filename*. But it is far from perfect.

Maybe I should have shared more explicitly one of my concerns regarding risk of Community Group git repos drifting too far from the latest commits in the project's working branch. We had quite a painful experience with the 3.0 release - which I take full responsibility for, and [fixed](http://schema.org/docs/releases.html#g1203) after several days work. See #1203 for details but basically I merged in a pull request from the Schemed CG that was based on their work in a schema.org fork which had not kept up to date. The commit was too large for visual review within Github's Web based UI, and I rather optimistically hit "merge" based on the false belief that the had been tracking recent changes. The result was that version 3.0 at release contained accidental rollbacks to 12+ previously fixed issues, and repairing this involved careful double-checking of a triple-by-triple, issue-by-issue crosschecking between 3.0 and 2.2's schema definitions. 

There are certainly other things we can also do to avoid those kinds of mistake - having more folk review drafts (by making sure things get onto webschemas.org faster), better unit tests, etc. But a lot of it comes back to keeping the CG schema drafting releases closer to the project's main branch...

**Comment by philbarker** [comment]
OK, I have tidied up my git repository for schema.org. It was a bit of mess before and cognitive overload of managing a repo with different branches forked different upstream repositories on github was likely lead to me making errors & causing work for others.

@danbri you referenced  https://github.com/philbarker/schemaorg-1/ in https://github.com/schemaorg/schemaorg/issues/195#issuecomment-240729669  My 'clean' repository is now at https://github.com/philbarker/schemaorg/

@westurner you may have seen that I dropped the fork from your schema.org repository in order to have a repository forked directly from the latest development branch of schema.org . That was purely to make my life simple, to match my level of mastery of git. What would be the simple way to keep the files in our repos synched?
