### ISSUE TITLE
Clearer (GS1-based?) guidelines for gender+age product codes would be useful

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1316]
Schema.org defines the [Audience](http://schema.org/Audience) type which is used to express target audience in a general way.  In particular [PeopleAudience](http://schema.org/PeopleAudience) has gender and age related fields. This property is present in the Product type, but it is fairly complex to specify two important notions in shopping: age-group and gender.  It would also be easy to present an overly simplistic view of these issues, particularly when considered in broader terms (i.e. beyond shopping product codes). http://schema.org/GenderType and http://schema.org/gender are also available, but are not integrated with the audience terminology. 

This is a difficult and sensitive area, but also one in which much Web content has a lot of structured content. Can we improve our markup examples in the Product area?

Proposal: document examples of schema.org Product markup that exploit GS1's terminology from http://gs1.org/voc/ConsumerLifestageCode and http://gs1.org/voc/TargetConsumerGenderCode

Nearby: https://github.com/schemaorg/schemaorg/issues/1278 on updating GS1 example(s), including MixedVocabExample.txt from @ekgs1 /cc @mgh128

**Comment by mfhepp** [comment]
If we model age-ranges for Audience, I recommend using schema:QuantitativeValue, because it allows modeling point values as well as open and closed intervals ("you need to 18 years or up"), and both year and months as units of measure, which can be useful for child-related products ("for babies 3 - 6 month of age").

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by danbri** [comment]
@mfhepp could you sketch an example? is the idea that we go straight to specific numbers rather than try to pre-bake anticipated categories?

It would also be good to work through a multiple-JSON-LD-contexts example with GS1, to see how that looks and make sure the approach works. (ping @ekgs1 @mgh128).

**Comment by danbri** [comment]
Passing along a couple of example records that were suggested as illustrative:

> Title: Princess Unicorn Onesie
Brand: Cute ribbon
MPN: CRB341/PNK
Color: pink
Gender: Female
Age Group: Newborn
>
> Title: Maxi leather boots
Brand: Labottine
MPN: LBT/4566
Size: 39
Color: Black
Gender: female
Age Group: Adult

**Comment by pmh3005** [comment]
As a property of Product > audience you can use suggestedAudience which is probably a more suitable solution, since it is a suggestion.

`
 "audience":{
      "@type":"PeopleAudience",
      "suggestedGender":"https://schema.org/Male"
    },
`

Technically the type is Text but the url does pass, perhaps 'Male' or 'Female' might be better.

`
 "audience":{
      "@type":"PeopleAudience",
      "suggestedGender":"Female"
    },
`

This is for a product worn on the body, what do others think?
