### ISSUE TITLE
Need award/championship entity

### ISSUE THREAD

**Issue by martinbean** [schemaorg/schemaorg#1324]
I work a lot with professional wrestling and MMA (mixed martial arts) websites. Both activities see competitors contend for _championships_. Other activities see participants compete for _awards_.

It would be good if an _Award_ type could be added to the schema.org specification to mark up such entities:

```html
<article itemscope itemtype="http://schema.org/Award">
  <h1 itemprop="name">WWE World Championship</h1>
  <p>
    <strong>Current champion:</strong>
    <span itemprop="currentHolder" itemscope itemtype="http://schema.org/Person">
      <span itemprop="name">Dean Ambrose</span>
    </span>
  </p>
</article>
```

**Comment by RichardWallis** [comment]
This is an overlap with the discussions around Educational Courses and Credentials awarded see (#195)  and [mailing list thread](https://lists.w3.org/Archives/Public/public-schema-course-extend/2016Aug/0015.html).

Also see close issue (#989).

Agree we need something in this area but it should be part of a broad solution.

**Comment by martinbean** [comment]
> but it should be part of a broad solution.

What do you mean by this?

**Comment by danbri** [comment]
/cc @vholland was was involved at the time.

I'd suggest the nearest large cluster of topics would be those around sports, and that our neighbouring [Sports Schema community group](https://www.w3.org/community/sport-schema/) at W3C is a good place to take these discussions.

Background - 

A couple years ago Jason Johnson (then of Microsoft/Bing) was leading our Sports effort. Since he moved on things have gone a bit quiet. You can see how far we got at the time here: http://blog.schema.org/2014/02/schemaorg-sports-vocabulary.html

Working notes from that period are in W3C's Wiki, https://www.w3.org/wiki/WebSchemas/Sports 

See https://www.w3.org/wiki/File:2014SportsVocabularyProposalv2.pdf ([PDF](https://www.w3.org/wiki/images/6/60/2014SportsVocabularyProposalv2.pdf)) for a draft that addressed the competitions use case. The design was never finalized. You can find previous discussions in the W3C public-vocabs list e.g. searching on "[sports proposal](https://www.w3.org/Search/Mail/Public/search?keywords=sports+proposal&hdr-1-name=subject&hdr-1-query=&index-grp=Public_FULL&index-type=t&type-index=public-vocabs)".

**Comment by danbri** [comment]
I should also mention that we do have a simple textual property, http://schema.org/awards which can capture something of this, in a limited way.

**Comment by martinbean** [comment]
@danbri Thanks, but I need something that describes a championship as a standalone entity, as per my example above. (I have a page that lists championships that I wanted to mark up.)

**Comment by danbri** [comment]
@martinbean for now then I think our answer is, "thanks for the suggestion! we don't currently have such vocabulary". 

Since we have over 400 open issues I'll close this issue as I've noted your suggestion in #2 which is where we track and cross-reference such proposals. Sorry we don't have anything for you right now, and do feel to stick around and discuss further if you like. Thanks again!

(and to be clear, a closed issue shouldn't stop further discussion...)

**Comment by martinbean** [comment]
@danbri Cheers, Dan.

How would one get involved in the ongoing Schema.org development? I’d rather be a bit more proactive than just going, “It should have this.”

**Comment by danbri** [comment]
You're doing it, pretty much. We ask serious contributors to join the W3C group, https://www.w3.org/community/schemaorg/ but much of the discussion and implementation takes place here. Ultimately we'll need to settle on a set a specific design and its detailed specification in files that look like https://github.com/schemaorg/schemaorg/blob/sdo-callisto/data/ext/pending/issue-195.rdfa 

For now it would be great just to capture usecases and exemplar websites. We can't handle every scenario in detail within our vocabulary so some evidence indicating that lots of sites have this kind of content, sample URLs etc, helps...

**Comment by martinbean** [comment]
@danbri Hi, Dan. I’m really interesting in helping to craft definitions for Schema.org, starting with a Championship entity. I’ve joined the W3C community. How do I become a more involved member? Is there a new lead on Sports schemas that I could liaise with?

To offer a suggestion, I see a `Championship` entity having these properties:

* `name`
* `dateEstablished`
* `dateRetired`
* `awardingBody` (`Organization`)
* `currentHolder` (`Person` or `Organization`)
* `lastHolder` (i.e. if the `Championship` is retired)

I’d love to start a discussion around this particular entity and help progress it to becoming an official schema.

**Comment by martinbean** [comment]
Ping @danbri
