### ISSUE TITLE
Example contains 'author' property with text value (which is not expected)

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#1327]
[Example 1 for `Article`](http://schema.org/Article#example-1) contains an `author` property with a string value. But the [`author` property](http://schema.org/author) expects `Organization` or `Person`, not `Text`.

While the documentation makes clear that [providing a text value is fine (for every property)](http://schema.org/docs/gs.html#schemaorg_expected), in my opinion the examples should always use expected values (they represent good/best practices).

Thoughts? Keeping it like it is? Changing this and possibly other examples so that only expected values are used? Or listing `Text` as expected value for `author`?

**Comment by danbri** [comment]
I was thinking about this today, and suggest we add an authorName property to keep the markup simplicity of this (very common) usecase. I agree that the original "expect strings where there should be strings" shouldn't really extend to our best-practice examples, particularly with the rise of JSON-LD which is somewhat more compact than Microdata/RDFa.

**Comment by danbri** [comment]
authorName 
domainIncludes: CreativeWork, Rating (to match author exactly)

"The authorName property represents a name of an author of something."

**Comment by vholland** [comment]
authorName is potentially useful for authors using pseudonyms. For example, saying Richard Bachman is an alias for Stephen King is not nearly as useful as saying the authorName is "Richard Bachman" while the author is a schema.org/Person named Stephen King.

**Comment by danbri** [comment]
Interesting @vholland, I guess it literally bypasses the troublesome Person entity...

**Comment by RichardWallis** [comment]
On the surface the simple proposal for authorName looks attractive.

However in practice I can see it causing some issues.  All fine for a single author that you do not have a URL for.  

I can already hear the questions incubating for situations that are not so simple:

- I have a URL, should I use authorName as well?

  - .. and if I do, what about more than one, how do I associate each authorName with its relevant author?

- If I add two authorNames does that mean two names for the same author (Richard Bachman  & Stephen King), or two different authors?

- If you have authorName, what about publisherName, characterName, providerName, sponsorName, translatorName?  Or itemOfferedName on Offer, or eventName on Organization & Place, or deathPlaceName on Person.

I know I have gone a bit extreme on that last one, but I see this as  potential slippery slope towards string based degradation in the ability to describe relationships between Things.

Is this a necessary introduction of a duplicate way of identifying the same information [when](http://schema.org/docs/datamodel.html#conformance) "some types such as Role and URL can be used with all properties" anyway.

I agree there needs to be more guidance/examples encouraging the use of URLs when available but showing strings when not, but a text based authorName gets a -1 from me.

**Comment by danbri** [comment]
@RichardWallis think blog post rather than a 3rd volume of a scholarly compendium...

**Comment by danbri** [comment]
Historically this little situation has caused no end of debate in e.g. Dublin Core circles, eg. see https://web.archive.org/web/20070909033748/http://ahds.ac.uk/public/metadata/disc_09.html "dc.creator.personalName.2" and so on.

Revised proposal: """The [[authorName]] property represents a name of an author of something. To fully describe multiple authors or other contributors, e.g. to associate them with URLs and other information, it is better to explicitly use [[author]] with [[Person]] or [[Organization]]. """

BTW the analogy between a CreativeWork's authorName and an Organization's (or Place's) supposed eventName doesn't really hold, since creative works most typically have only one author, whereas an Organization or Place can be associated with a vast and growing range of events. It is very common to have only a name string for an author field, which is exactly why in Dublin Core and other metadata communities there were endless discussions about how a name-value for creator/author could be "dumbed down" to a person/agent value or vice-versa. 

See also http://dublincore.org/documents/info-factoring/

**Comment by RichardWallis** [comment]
> think blog post rather than a 3rd volume of a scholarly compendium...

CreativeWork is a super-type for far more than blog posts, think Book & Article.  If you cannot constrain the discussion of the ramifications of this to only one area of sub-types .

I am far from convinced that the edge-case benefits (_for people who cannot get their head around using a Person and/or a string for the author property_) of this proposal overcome the potential anomalies and confused practice it could introduce.

From the info-factoring document @danbri  references "_The only problem with this method is that it requires a lot of intelligence in the reader or user of the metadata to interpret the meaning of fields which occur more than once._ "  Multiple occurrences of authorName have no way to distinguish if they are different individuals or  pseudonyms of a single person, or a combination thereof.  

You underplay the prevalence of multiple author creative works.  For blog posts and works of fiction I agree it is unusual; in non-fiction it is more common; technical/academic non-fiction yet more common; for scientific/academic articles it is very common.

In referencing names of other types I was not implying that they often have multiple names.  
The point I was trying to make was that this [authorName] case, if adopted, would establish a new vocabulary pattern whereby at text property is introduced that duplicates the core capability within Schema.org for all properties to to accept a Text value.  Having introduced it, it would be difficult to reject similar proposals in other areas.  

I am still -1 on this

My [counter]proposal would be to explicitly add [Text](http://schema.org/Text) to the range of [author](http://schema.org/author).  Plus ensure that we show a mixture of examples with Text and Person references.

**Comment by vholland** [comment]
Schema.org already states it accepts Text for any property, so rather than add Text explicitly, I would rather put the burden on data consumers to understand how to convert a string into some sort of Agent type in their internal representation. They would need to do that anyway for a Text field.

**Comment by thadguidry** [comment]
problem is that @unor just lacked a bit of extra documentation and knowledge.  Most of all of us developers have been expecting Text.  The examples for me are fine as-is.

-1 for introducing an authorName property and duplicating a known vocabulary pattern we already know and are used to.... expect for @unor ... :) but now he knows also.

**Comment by danbri** [comment]
I don't believe @unor is lacking knowledge.

> The point I was trying to make was that this [authorName] case, if adopted, would establish a new vocabulary pattern whereby at text property is introduced that duplicates the core capability within Schema.org for all properties to to accept a Text value

Yes, I would like to gently move us away from that expectation, at least for common cases. I have seen no evidence that it is dealt with gracefully by the search engines. The flagship example by far is that it allows compact markup for the names of authors, so if we address that usecase (and eventually perhaps a handful of others) we could nudge the "strings instead of things" hack/heuristic back into being an exotic cornercase instead of a core claim for how schema.org should be consumed.

**Comment by RichardWallis** [comment]
I think you balancing on the tip of a significant iceberg here.  We are discussing a potential individual property but there are further ramifications as to a) The future general development direction, and b) how it would be used.

Are you saying that you want to move towards a point where the following statement would _not_ be true? 

> We also expect that often, where we expect a property value of type Person, Place, Organization or some other subClassOf Thing, we will get a text string, even if our schemas don't formally document that expectation.

If you are that is a really significant shift.

As to the use of the proposed authorName property, as I said earlier, it raises many questions about its application beyond the the simplistic author of a blogpost case, that I can see causing confusion.

**Comment by danbri** [comment]
I'm suggesting that we keep that statement but it shouldn't be the centre-piece of our data consumption story, not least because it doesn't say what graph structure such strings map into. It is a matter of degree and tone rather than absolutes. Back when the schema.org steering group was debating whether to support JSON-LD there were some of us (including Microsoft folk) who were of the view that schema.org in the JSON data exchange world could usefully shed some of the scruffyness that was somewhat endorsed for HTML+Microdata.

**Comment by renevoorburg** [comment]
If we have a book and an author and we want to know the name of the author as used in the context of the book at hand an approach might be to use a blank node (used for entities that only have meaning in the context of an other entity) and a sameAs-relation. In turtle this might look like:

@prefix schema: <http://schema.org/> .

<uri_of_a_book>
 a schema:Book ;
 schema:author [
    a schema:Person ;
    schema:name "Stephen King" ;
    schema:sameAs <uri_of_Richard_Bachman>
 ] .
