### ISSUE TITLE
Addiction Enumeration

### ISSUE THREAD

**Issue by kevinawilson** [schemaorg/schemaorg#1334]
I would like to suggest adding Addiction as an enumeration member of MedicalSpeciality in the health-lifesci extension. Addiction treatment centers often employ both medical and psychiatric providers, so it wouldn't make sense to use just Psychiatric alone. I have been unable to find an ontology for addiction treatment online, so I cannot reference an external vocabulary.

**Comment by LeezaRodriguez** [comment]
The concern I have is that "Addiction"  treatment online may or may not have a _properly trained and certified physician overseeing the treatment._ I could be wrong, but that is my first concern.  While these entities can certainly provide valuable services to those addicted to drugs, it may not be correct to allow these entities to assert a formal 'Medical Specialty'.  A 'Medical Specialty' is quite a formal thing which implies a medical residency  and certification by a Medical Board.

In the USA, 'Addiction Psychiatry' is a formal **Medical Subspecialty** of the ABMS approved Medical Specialty of 'Psychiatry'.  http://www.abms.org/member-boards/contact-an-abms-member-board/american-board-of-psychiatry/

 I do not know the criteria for owning an operating an 'addiction' clinic or online portal, but we should be very careful when creating **Medical Specialty** enumerations.  IMO, Medical Specialty enumerations should have a recognized Medical Board who grants the Medical Specialty or Subspecialty Certification.  Even so, there are lots of bogus Medical Boards floating around with no oversight organization.

Knowing that a **Medical Specialty enumeration**  may eventually show up in G Knowledge Panels alongside a entity name, we have a responsibility to not mislead the consumer  . A clinic that specializes in a certain disease should have a physician with residency training and certification in that Medical Specialty or Subspecialty. IF no such medical specialist exist in the entity organization, it should not be able to assert itself as having that Medical Specialty.   Otherwise, it can be misleading to the consumer. 

In the US, "pain clinics" got totally out of control for many decades.  They marketed themselves on the web and TV as being 'Pain Specialist', although they were being run by anybody with a Medical School diploma, even though these physicians had _no formal certification in the formal 'Pain Medicine' Medical Subspecialty._    This created a hugely abusive infrastructure, as any clinic could market themselves as a 'pain clinic' .  To combat this many states now have statues which mandate that pain clinics must be owned and operated by a physician trained in the Medical Subspecialty = 'Pain Medicine'. Physicians can achieve this Subspecialty pathway via  ~7 different Medical Specialties.

So, let's please give this more thought. For 'Medical Specialty', let's stick to the ABMS Medical Specialty and Subspecialty lists or the lists at Wikipedia. 

ABMS: http://www.abms.org/member-boards/specialty-subspecialty-certificates/
Wikipedia Worldwide: https://en.wikipedia.org/wiki/Specialty_(medicine)

cc: @twamarc

**Comment by kevinawilson** [comment]
I have no problem with using AddictionMedicine and AddictionPsychiatry. The differentiation is a solid one. Many addiction treatment centers offer only psychiatric treatment without medical specialists on staff, so it would help to make that distinction. And the fact that it conforms to an existing vocabulary already used in the medical field is a plus.

I'm not sure this will prevent the problem you outline above, however, although I certainly agree it is a problem. Given that markup is usually done by the organizations themselves, I'm not sure there is any mechanism to keep them from using enumerations inappropriately. A center that does not have formal certification can still describe themselves using these terms. The law may proscribe such use, but in that case it is an issue for law enforcement. The people who authored the schema would not be the ones misleading the public. 

As I understand ontologies, they are meant to provide a framework for marking data, and so we should ensure that they fulfill that role well. If people choose to use this markup inappropriately, I don't think there is much schema.org can do about it. Search engines may weed out those marked inappropriately, but I don't think there is a way to prevent inappropriate markup on our end.

**Comment by LeezaRodriguez** [comment]
In addition to tightly controlling the enumerated list, the only concrete thing to do is **better define the term MedicalSpecialty** so webmasters don't use the term so loosely.  Perhaps, something along these lines:

Current: 
Any specific branch of medical science or practice. Medical specialities include clinical specialties that pertain to particular organ systems and their respective disease states, as well as allied health specialties. Enumerated type.

**Proposed:** 
_A medical specialty is a branch of medical science or practice. Enumerated members of this data type are aligned with formal Residency training programs.  After completing medical school, physicians complete a formal multiple year residency in a Medical Specialty or Subspecialty.  Organizations who represent a Medical Specialty employ person(s) with formal training in this Medical Specialty._

**Comment by LeezaRodriguez** [comment]
ICYMI: A few months ago I started a Medical Specialty spreadsheet.  Marc and others gave it a thumbs up.  **It's a work in progress** as I am trying to utilize the ABMS Medical Specialty/Subspecialties lists  **and** the Medical Specialty members listed at Wikipedia. 

https://docs.google.com/spreadsheets/d/1y7KIP0icoqowZ1uX4H33rVJKfj5WAjIeqkEpnuN6A9U/edit#gid=575069605

**Comment by kevinawilson** [comment]
Thanks. I hadn't seen that. Is there corresponding work being done for Medical Conditions? I've been using DSM-V for thinking about how to mark psychological disorders.
