### ISSUE TITLE
Add new Type 'PersonalBlog' or 'PersonalBlogPosting'

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1343]
There are numerous publishing platforms that all seem to use Article instead of BlogPosting as their default content frame.  Usage statistics seem to indicate that they are using Article for both personal blogs and news-y articles.  This may stem from the confusing examples on BlogPosting and where we already have issue #883 to address that.

**I suggest that we narrow the BlogPosting definition** to use the phrase

    'A personal blog post.  For non-personal publishing such as news, magazines, use Article instead.'

 to help further clarify its intended usage and to help filter out true personal opinions on topics from other news agencies, media houses, publishers, etc that primarily use Article in their templates.

@scor @ErisDS Further the Publishing Software frameworks could help matters also by giving an install option to choose the primary usecase, one of either a 'personal' blog or for a 'news agency, media entity, or publisher' and informing the user that template setup consequence between 'BlogPosting' or 'Article' as the default content frame.  Alternatively, Software developers might want to give the user a quick flip option upon content creation or publication to promote as 'a personal Blog Posting' or 'an Article'.

**Comment by danbri** [comment]
This feels too narrow to me. The distinction is a subtle and cultural one, and one that has been evolving over time. Groups and organizations also have blogs and make blog posts; some in a relatively personal voice, some in an informal but communal or collaborative voice, while others are more in a thinly veiled corporate communications mode, or (e.g. celebrities) ghost-written by interns or PR teams. I don't think we're in a position to make such subtle markup distinctions effectively in a way that will be picked up and used. Does a blog post stop being a "BlogPosting" if two people sign it, for example?

**Comment by thadguidry** [comment]
@danbri  I'm all ears on suggestions of improving my searchability with Google and Bing.  How do you suggest to filter out the noise of searches returning Articles on "GoPro" and instead BlogPosts on "GoPro" ?

**Comment by dkutcher** [comment]
What is "personal"? If I'm the owner of a small business (like I am), and I blog for business purposes in the first-person narrative, is that an article or a blog post? Are business-focused submissions on Medium (for example) articles or blog posts? Is the demarcation a level of professionalism, voice, opinion...?

I think it's an interesting semantic discussions, but not sure where the line is.

**Comment by thadguidry** [comment]
@dkutcher @danbri I'm looking to isolate and find only 'non-business' blogs.  That's what I mean when I say 'personal'.  If we need to design a new type for that, then fine, lets do that.

**Comment by WeaverStever** [comment]
I disagree with the creation of yet another narrowing of the blog category, blogs by nature are not "personal" they are published for a reason.  Further, the scope is already convoluted:

Thing > CreativeWork > Blog 
Thing > CreativeWork > Article > SocialMediaPosting > BlogPosting

Properties:
Thing > Property > blogPost
Thing > Property > blogPosts

By default, the Blogger platform (#5 on Alexa) placed the editor within Blog>Blogposting by default.  I suggest adding subtopics that are common to both Articles and Blogs (as mentioned above, news organizations also publish blogs).  Other traditional topic sections such as, news, opinion, research, sports, lifestyle, calendar, pressRelease could be added for search granularity. Again, these topics are commonly found in both Blogs and Articles.

Since the Blogger editor is starting by default within blogposting,, a single wrapper, like pressRelease, would be much more user friendly. And the Blogger templates are already woefully out of date, I don't foresee Google fixing them anytime soon. 

WordPress (to my knowledge) relies on plugins -- I doubt if they would allow themselves to be painted into the "Blog" box though for flexibility reasons and the fact that WP is a platform that is suitable for news organizations. There is absolutely no benefit to tagging your writing with the scope of "Blog," so enforcing a standard would be quite impossible, and likely just lead to the adoption of another standard (rdf/JSON).

**Comment by thadguidry** [comment]
I'm giving this up... the world doesn't see a problem like I do.  I'll just use anti-patterns on Article data with surrounding semantic do-dads to figure out if it might be an Article from a news/media agency or not.

And probably just compare domains to Wikidata's instance of Website (Q35127) because Wikidata doesn't have many or any personal blog sites against that identifier.  Cats are skinnable in my world.

CLOSING.  Thanks all.
