### ISSUE TITLE
The property offers is not recognized by Google for an object of type HotelRoom.

### ISSUE THREAD

**Issue by rccprince** [schemaorg/schemaorg#1356]
The https://schema.org/HotelRoom shema is not valid in google Structured Data test.

Please try to change and notify.

**Comment by eliaskaerle** [comment]
This is probably because there is no property 'offers' in HotelRoom. To offer a HotelRoom it should be offered by a Hotel.
`Hotel --> makesOffer --> Offer --> itemOffered --> HotelRoom'
I wrote a post about how to use HotelRoom as an offer (https://elias.kaerle.com/annotating-a-hotel-offering-rooms-with-the-new-schema-org-version-3-1/ ), but the Google   structured data test tool doesn't like that either because it uses multi-typed entities, which is not recogniced by the tool. This is not a schema.org issue but a Google Structured Data Test Tool Issue.

**Comment by danbri** [comment]
This is a google issue, we will address it at Google. You could raise it at https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Astructured-data%7Csort:relevance%7Cspell:false but the issue is already appreciated within Google. Thanks for raising it here, but I'll close the schema.org issue tracker as this is beyond the direct scope of schema.org as a project.
