### ISSUE TITLE
Question: How to create new vocab extension

### ISSUE THREAD

**Issue by reidyoder** [schemaorg/schemaorg#1383]
[https://www.w3.org/community/smartmfg/]

Me and a few others would like to make some new schema vocabulary for manufacturing companies (likely a subclass of Organization). While I know how to markup schema data in HTML files with JSON-LD, I do not know how to make a new vocabulary to be used. I've read just about everything on schema.org but I don't see any specific descriptions or literal steps on how to do this. If someone could send me in the right direction, I would appreciate it. Also, once the vocabulary has been made, how do I get it to properly merge with the core?

And just to clarify -- is the heirarchy on schema.org the actual schema data itself or just a documentation?

**Comment by RichardWallis** [comment]
The basic approach is to propose, via issues such as this, enhancements, additions and/or extensions to the existing vocabulary.  

Supporting these with marked up examples, use cases, and real world situations where they are likely to be used.

For simple proposals, just documentation may suffice.  For more complex proposals a fork to the github repository, and possibly an appspot.com example working site might be needed to fully explain things to the community.

For background to these steps I can suggest my _Schema.org in Practice_ articles: [part 1](http://dataliberate.com/2016/02/10/evolving-schema-org-in-practice-pt1-the-bits-and-pieces/), [2](http://dataliberate.com/2016/02/25/evolving-schema-org-in-practice-pt2-working-within-the-vocabulary/), and [3](http://dataliberate.com/2016/03/01/evolving-schema-org-in-practice-pt3-choosing-where-to-extend/).

However you intend to pursue this, I would always recommend starting with your use cases and the entities you want to describe, attempting to describe them as fully as possible with Schema.org terms as they are today.  That way you can identify if you really need any new sub types, or for example is [LocalBusiness](http://schem.org/LocalBussiness) sufficient to describe a manufacturing organisation.  Also you can identify what properties might need to have their domain broadened or need be created to fulfill your needs.

If you can also engage with some people who have been through similar steps before as early as possible, that can also be helpful.

I would be interested to hear what your thinking is after reading the above.

~Richard.

**Comment by reidyoder** [comment]
Richard -- I have read through you 3 articles and they have been very helpful. I will definitely be referencing them when I get to coding this. One quick question though -- what exactly is the difference between extending the core and a hosted extension? If an extension is going to be hosted by schema.org, why not just extend the core?

**Comment by RichardWallis** [comment]
@reidyoder Good question.  Especially as the canonical URI for a term does not include the extension subdomain.  So for example [Thesis](http://bib.schema.org/Thesis), defined in the bib.schema.org extension has the canonical URI of http://schema.org/Thesis

The purpose of hosted extensions is to group together terms specifically referencing a particular domain for organisational and human consumption reasons.  In total Schema.org consists of some 15 hundred terms.

The idea is that terms applicable to many domains should reside in the core with domain specific terms should be grouped together in an extension.  This approach helps the analysis, evolution, and acceptance of individual proposals by the Schema.org community.  If a proposal is targeted  extension of the core, one would expect a broad analysis of the the impact of the terms for all.  

For an extension proposal, the syntax, naming convention impacts, and vocabulary style would obviously be analysed as per a core proposal.  However because of the domain specific nature of some terms, it would not necessarily be for the broad community to comment on if those terms would make sense for that domain.

Once a hosted extension has been released, this pattern is also useful to help navigation through the documentation with, for instance, all the medically focussed terms being listed together on the home page for the [health-lifesci](http://health-lifesci.schema.org/) extension.

Not a perfect system but in practice better than putting things all together in one pot.

**Comment by reidyoder** [comment]
"The idea is that terms applicable to many domains should reside in the core with domain specific terms should be grouped together in an extension." - That makes perfect sense, thanks. I will close down this issue and create a new thread in the near future to discuss the details of the manufacturing extension.
