### ISSUE TITLE
For IOT support, discussion for a Sensor Type (see other issues for other levels of IOT)

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1391]
A Sensor can hold or report a measurement or a bag of measurements.

This issue brings forth the realistic need for aligning with something like  [SSN](https://www.w3.org/TR/vocab-ssn/) and its Sensor type http://www.w3.org/ns/ssn/Sensor that defines the capabilities as well as the Sensor's outputs (observed values / bag of measurements).

**Comment by kevinSuttle** [comment]
Andy Stanford-Clarke mentioned http://www.hypercat.io/

**Comment by joshsh** [comment]
Another thought is to create not only a Sensor type, but rather adapt an existing sensor ontology such as [SSN](https://www.w3.org/TR/vocab-ssn/).  SSN models sensors and observations, as well as supporting entities such as features of interest, sampling time, units of measure, etc.  A small subset of classes could be included in schema.org, with the possibility of importing others as needed, while integrating them with related classes including PropertyValue, QuantitativeValue, and Dataset.

**Comment by vholland** [comment]
+1 to @joshsh's suggestion. Other folks have spent time thinking through a number of issues we have yet to conceive of. It would be better to take a moment to survey their work before creating a bunch of schema.

**Comment by kevinSuttle** [comment]
Right, the MQTT org has done quite a bit as well, which is why I asked Andy.

**Comment by kevinSuttle** [comment]
See also: https://github.com/w3c/wot

**Comment by danbri** [comment]
See also #1272 for top level IoT/WoT issue tracking.

We're not going to rush this one.

I was at W3C's annual TPAC event recently, where there were detailed discussions (see [minutes](https://www.w3.org/2016/09/20-sdw-minutes#item01)) in the Spatial Web WG session about coordinating between SSN and pre-existing OGC sensor-related standards, around the issue of distinguishing 'records of observations' vs 'activity of observing'. 

After some discussion that WG resolved (as the group working on SSN at W3C):
> RESOLUTION: The ssn:Observation will be redefined as an activity, in line with O&M Observation

See http://www.opengeospatial.org/standards/om "Observations and Measurements" and nearby.  For example in their 10-004r3_Topic_20_Observations_and_Measurements.pdf

> OGC and ISO 19156:2011(E)
> Introduction
This International Standard arises from work originally undertaken through the Open Geospatial Consortium’s Sensor Web Enablement (SWE) activity. SWE is concerned with establishing interfaces and protocols that will enable a “Sensor Web” through which applications and services will be able to access sensors of all types, and observations generated by them, over the Web. SWE has defined, prototyped and tested several components needed for a Sensor Web, namely:
— Sensor Model Language (SensorML).
— Observations & Measurements (O&M).
— Sensor Observation Service (SOS).
— Sensor Planning Service (SPS).
— Sensor Alert Service (SAS).
This International Standard specifies the Observations and Measurements schema, including a schema for sampling features.

There are a good number of initiatives in this area. This is a great time to experiment, explore and look into interoperability. We may we add vocabulary around sensors, devices, observations/measurments, and we could well end up adding detail to our /Action design to deal with initiating device-based actions, but it will take some investigation first.

It is also critical to clarify our approach to units of measure (we have two systems already, those types under http://schema.org/Quantity which were the original pragmatic schema.org design, and another around ecommerce that was added from Good Relations, see http://schema.org/QuantitativeValue). I've started investigating the potential integration of the (huge body of work at) http://qudt.org/ ("Quantities, Units, Dimensions and Data Types") in #1390 and had a very positive call with Ralph Hodgson yesterday.

Also - oddly enough - we got close to this territory of 'observations' previously in the work that Jason Johnson was doing around Sports to record sports score statistics. See https://www.w3.org/wiki/WebSchemas/Sports https://www.w3.org/wiki/images/6/60/2014SportsVocabularyProposalv2.pdf - I'm not saying we need to handle all of these things in a single approach, but it is worth standing back and looking at the larger landscape before sticking in a Sensor type.

**Comment by thadguidry** [comment]
@danbri no plans to rush.  For many in the ICT industry it starts at the Sensor level, then Device.  Sensors are just 1 component of IOT, but the most heavily used so far in our industry.  In the ICT industry, we have to deal with communications of Devices, both in wireless and landline form.  This issue was to begin creation and documentation of a Sensor type **on paper** and further discussion.

**Comment by danbri** [comment]
OK sounds good. Let's collect Sensor-related design input here, and revisit what we've learned in a month or so. All and any pointers welcomed!

**Comment by danbri** [comment]
Here's a scoping question from a usecase in our '[getting started](http://iot.webschemas.org/docs/iot-gettingstarted.html)' doc. Consider a consumer device like 'wifi connected scales'. E.g. I have a Withings [scale] https://en.wikipedia.org/wiki/Withings#Smart_Body_Analyzer_.26_Wireless_Scale), which records depressing numbers about my weight and relays them to 'cloud' APIs. Would such a complete unit / product itself be considered a sensor, or just the components of the larger product?  The core idea seems to be that there are a set of measurement events (actions?) of some item using some device/system/product.

**Comment by thadguidry** [comment]
Sensors are components of a larger device/system/product/platform.
A home weather station has many Sensors.  Some devices may only have a single Sensor.

See Platform and System already defined very well in SSN and this aligns perfectly in ICT industry as well. 
* http://www.w3.org/ns/ssn/Platform
  * http://www.w3.org/ns/ssn/System
      * http://www.w3.org/ns/ssn/Device
        * http://www.w3.org/ns/ssn/SensingDevice
      * http://www.w3.org/ns/ssn/Sensor
        * http://www.w3.org/ns/ssn/SensingDevice

**Comment by joshsh** [comment]
Yes, granularity of "sensors" is a matter of choice.  The home weather station is a good example, as it contains a hierarchy of sensing devices.  Are the anemometer and wind vane separate sensors, or a single "wind sensor" which observes both wind speed and wind direction?  What about the I2C hygrometer in the weather station, which measures both air temperature and relative humidity?  Two sensors?  Separate from the wind sensors or not?  When there is no need to break down a sensing device into subsystems, SSN does allow it to observe multiple properties.

**Comment by jmcanterafonseca** [comment]
SAREF Ontology and oneM2M use the type `Device` and different categories  to model sensors. So I think the type to start with is `Device`

See http://ontology.tno.nl/saref/

**Comment by thadguidry** [comment]
@jmcanterafonseca I understand where your coming from, but typically in Schema.org we try to find the lowest applicable Types in a Domain and then work our way up from there, abstracting higher ordered Types as we go along in time with discussions, pending reviews and releases.

**Comment by jmcanterafonseca** [comment]
well I come from Spain, :)

now seriously, there are devices which combine both functions sensing and
actuating or actuating and metering and I think it would be wiser to start
with Device instead of Sensor ... and it seems it is what the existing work
suggests ...

2016-10-13 18:42 GMT+02:00 Thad Guidry <notifications@github.com>:

**Comment by joshsh** [comment]
Some upper-level ontologies also organize "sensor" under "device".  For example, WordNet and SUMO have:

`entity > physical entity > object,physical object > whole,unit > artifact,artefact > instrumentality,instrumentation > device > detector,sensor
`

UMBEL has:

`artifact > device > sensor
`

Wikipedia categorizes a sensor as a "tool":

`Category:Equipment,Category:Manufactured_goods > Category:Tools > Category:Measuring_instruments > Sensor
`

In Wikidata, it's a "component":

`physical object > perceptible object > component > electrical component > electronic component > sensor
`

In schema.org, a Device type (as a parent of Sensor) would be applicable to very many things described on the Web.  It would frequently overlap with Product, though.

**Comment by dpjanes** [comment]
Note this parallel discussion here:
https://groups.google.com/forum/#!topic/sdo-iot-sync/SO0ineFpygQ

**Comment by dpjanes** [comment]
One thing I would like to note is that it's very difficult to separate "this Thing is a sensor" from "this Thing is an actuator", as often a Thing will do both sensing an actuating.

A simple example of this would be a WeMo Socket, which has both a sensor - to tell whether it is on or off - and an actuator - which will turn it on or off. (It can also be turned off manually on the Socket itself).

It's also very useful to know the relationship within a Thing between the sensor and a corresponding actuator. In the WeMo example, if you have a web page displaying "this WeMo in ON" and you want to have a control to change this, generally you want these to be together.

Note that as you deal with even slightly complicated Things, there's some interesting cases that have to be considered. For example, an Oven Thing has an actuator to set the temperature, but also has a corresponding sensor to tell you what that set point is _as well as_ another sensor to tell you what the actual temperature of the oven is.

**Comment by jmcanterafonseca** [comment]
David pointed out some very good reasons for `Device` being the abstraction to begin with. Then, we can define attributes to convey what functions the device can perform. 

However I don't support the definition of a kind of product named 'IoTProduct' as it is too specific and not certainly needed if we have a `Device` type.

**Comment by dpjanes** [comment]
To bring this alive again, let me introduce the word [Sentroller](https://en.wikipedia.org/wiki/Sentroller): _A Sentroller, used in the Internet of Things is a sensor, controller or actuator or combination of these three_.

I propose it be used as follows:

---
Thing > Product > **Sentroller**
A sensor, controller or actuator or combination thereof. Multiple _attributes_ may be sensed or actuated. 

_Properties from Sentroller_
**attributes**: Attribute: sensing and actuating attribute available to this Sentroller.

---
Thing > Intangible > StructuredValue > PropertyValue > **Attribute**
A single logical sensor or actuator or combination thereof.

_Properties from Attribute_
**isSensor**: Boolean: is a value from a sensor
**isActuator**: Boolean: affects a change in an actuator
**purpose**: URL: define the semantic purpose of the Attribute (cf [here](https://groups.google.com/d/msg/sdo-iot-sync/SO0ineFpygQ/fG48wr_vBAAJ))

**Comment by jmcanterafonseca** [comment]
oh that's really weird word

 and it seems there is no consensus on making Devices a subtype of Product

-1

2016-11-12 16:58 GMT+01:00 David Janes <notifications@github.com>:

**Comment by dpjanes** [comment]
I didn't make up the word, and it exists enough to have a Wikipedia page.

**Comment by nextdude** [comment]
+1 for starting with a *device* concept, as @joshsh,  @dpjanes,  @jmcanterafonseca  mentioned. I'd also suggest a *device deployment* concept that allows one to position the device in space/time. I'm not familiar with the SSN stuff yet, but looking at its concept map, it seems before diving into the details of sensor behavior and detailed measurement processes, we look at the upper part of that diagram (device and deployment).

I'm looking to represent a device that is placed on a race course and reads competitors' time as they move by. I noticed that the current schema.org model doesn't appear to have any notion of a physical device, sensor or otherwise, outside the concept of a product. The clear intent of subclasses of Product seems to involve trade and commerce. It seems the existing concepts of structured values and measurements, as well as the _action_ concept, might be sufficient for many applications if there were a `Thing > Device`. Deployment could be handled simply by interposing a subclass of `Role` between the device and its location.

**Comment by jmcanterafonseca** [comment]
could the device's location just be an attribute of 'Device' ?

2016-12-12 20:51 GMT+01:00 Robert Lyons <notifications@github.com>:

**Comment by dpjanes** [comment]
This has the potential to get into somewhat dangerous territory, where we
start saying "this is what Devices _should_ do" rather than "this is what
Devices (actually) do". Or in other words, one actually starts defining a
new IoT standard, rather than defining useful terms that can be used in
existing IoT standards.

Some devices do have a Latitude and Longitude (and location info in
general) and are fixed in place. Some devices move around and are
continually reporting Lat/Lon. Some deployments might want to have this
information reported with the "Device" concept, some deployments might want
to have this information in a separate data stream, some deployments might
want to have a metadata concept that separates more ephemeral data from
core information like the model number.

IMO (isn't it always) you can't go wrong looking at how you would model the
Belkin WeMo and Philips Hue under any system and seeing how that looks.
Neither really have a strong concept of location embedded into their APIs.

The nice thing I like about schema.org is that of course you can mix and
match this stuff in as appropriate to what you're working with.

D.

**Comment by dpjanes** [comment]
Just to circle back to @nextdude's comment, the difference between a "device" and a "device deployment" is quite interesting, and had tripped me up for quite a while when writing IOTDB. 

One way of looking at it as the difference between a Class and an Object; another is to view it as Prototype vs. Instance. I prefer the latter, as more or less the original prototype device acts somewhat as a template that defines an actual instance out there in the world.

For a Belkin WeMo, this one might look at the "device" (using @nextdude's terminology here) as something like[*]

    name: Belkin WeMo Switch
    manufacturer: http://www.belkin.com/
    model: http://www.belkin.com/us/F7C027-Belkin/p/P-F7C027;jsessionid=FF9B0032273B51E522DEA08C48FCEA00/
    gtin13: 501234567890
    x-this-thing-is-a: Switch, Socket

But then when you actually get the "device deployment" you end up with something like 

    name: My Living Room Christmas Lights
    x-this-thing-is-a: Light Controller
    x-location: Living Room

Slight digression. In IOTDB world this is why we came up with the concept of _[bands](https://github.com/dpjanes/node-iotdb/blob/master/docs/bands.md)_, which says that we really need multiple data sets to describe a single Thing. In IOTDB the "device" is a **model** band and the "device deployment" is the **meta** band (and the data it reports is the **istate** band, and so on).

[*] using `x-` to indicate non-schema.org stuff, the term used is purely for illustrative purposes

**Comment by RichardWallis** [comment]
@nextdude you are right there are several properties of schema:Product that facilitate trade, but as all properties are optional that should not be a barrier to its use in describing the model of a device as demonstrated in @dpjanes's example above.

Both of you highlight the need to identify the location and other attributes of a device, for which we ideally would want a Device type adding to Schema.org.  

If we followed the suggestion of ```Thing > Device``` we would inevitably start discussing how to describe the manufacturer model number etc. of that device.  If we went with ```Thing > Product > Device``` we would inherit all that from the Product Type.   

I would suggest adding the [location](http://schema.org/location) property to such a Device type.  location accepts a [Place](http://schema.org/Place) (which provides the ability to describe both a geolocation or address of a location), [PostalAddress](http://schema.org/PostalAddress), or [Text](http://schema.org/Text).  These would take care of describing static locations from longitude & latitude to simpler locations such as "Living Room".

What it doesn't handle are mobile locations such as attached to a vehicle of some sort.  My suggestion would be to add another property to device (_isPartOf_ or _attachedTo_) which would take a Thing as a value so for example could link to a [Vehicle](http://schema.org/Vehicle) description.

It also does not handle what I would term as _networkLocation_ which would be URL/IP Address/etc.

Picking up on earlier thoughts in this thread, _Device_ could also benefit from a _devicePurpose_ property.

I deliberately have not addressed here how to attach descriptions of device capabilities or measurements etc.  However in my view they could be added via more properties of _Device_.

**Comment by jmcanterafonseca** [comment]
I cannot understand what's your concern with moving devices, location just
will be changing as any other attribute.

2016-12-13 13:16 GMT+01:00 David Janes <notifications@github.com>:

**Comment by nextdude** [comment]
@dpjanes  I think the prototype/instance is a nice way of thinking of device/deployment. Another way of thinking of deployment is as a role played by the device in a particular place and over some particular time period. Following @jmcanterafonseca, we could put a `location` property on `Device` and then use a `DeploymentRole` (subclass of `Role`) to intermediate for people that want to track more than location for deployment purposes.

Simple approach for a device that's deployed in my living room for christmas:

````json
{ 
  "@type": "Device",
  "@url": "http://example.com/BelkinWeMoSwitch-ChristmasLights",
  "name": "BelkinWeMoSwitch-ChristmasLights",
  "model" : "http://www.belkin.com/us/F7C027-Belkin/p/P-F7C027;jsessionid=FF9B0032273B51E522DEA08C48FCEA00",
  "gtin13": "501234567890",
  "location": "http://example.com/MyLivingRoom"
}
````
More complicated, but closer to prototype/instance, separating the deployment from the device:

````json
{ 
  "@type": "Device",
  "@url": "http://example.com/BelkinWeMoSwitch",
  "name": "BelkinWeMoSwitch-ChristmasLights",
  "model" : "http://www.belkin.com/us/F7C027-Belkin/p/P-F7C027;jsessionid=FF9B0032273B51E522DEA08C48FCEA00",
  "gtin13": "501234567890",
  "location": {
    "@type": "DeploymentRole",
    "@url": "http://example.com/DeploymentRole-ChristmasLights",
    "name": "Christmas Lights in My Living Room",
    "startDate": "2016-12-12T07:47:23-0400",
    "endDate": "2017-01-03T00:00:00-0400",
    "location":  "http://example.com/MyLivingRoom"
  }
}
````

**Comment by dpjanes** [comment]
@jmcanterafonseca I can get my argument down to one sentence:

The Location of an IoT Device is no more or less intrinsic to its description than Location is to schema:Product

**Comment by dpjanes** [comment]
Just in case anyone's taking this the wrong way: all I'm saying is schema.org lets you tack on location just like @nextdude just said. But it's no more or less important than adding location to Product.

**Comment by nextdude** [comment]
@RichardWallis I agree with you about putting `Device` under `Product`.

**Comment by dpjanes** [comment]
@nextdude @RichardWallis note this is what I was saying (Product > Device) in my November 12 comment, though I didn't use the term "Device".

Building on @RichardWallis's comment immediately above that there's two different of concepts of "purpose" that have to be considered:

* the purpose of the device
* the purpose of it's various sensors / actuators

In IOTDB I call the first purpose a facet of the device - [list of facets here](https://iotdb.org/pub/iot-facet.html) - and the second a purpose of the attribute - [list of purposes here](https://iotdb.org/pub/iot-purpose.html).

Again I'll go to our trusty friend, the WeMo Switch to illustrate. Note all the bold terms I make below I'm just making up on the spot, but in reality they should have URLs and forma definitions

Out of the box, the WeMo itself has two facets (or devicePurpose, as Richard called it): a **Switch** and a **Socket**. That is, it's like a wall switch in that it has a button, and it controls an electrical socket. It has one way to be manipulated: it can be turned on or off. This is basically an immutable purpose called (for argument sake) **OnOff**. 

Now let's say I connect to the WeMo to a desk lamp. Now its facet / devicePurpose is best modelled as **Lighting**. If I connect it to a space heater, its facet / devicePurpose is now **Climate Control / Heating**. And so forth. 

But note in all cases the purpose of its single actuator remains the same: it can be turned on or off.

[Here's the link to the November 12 comment](https://github.com/schemaorg/schemaorg/issues/1391#issuecomment-260130224).

**Comment by nextdude** [comment]
@dpjanes I take your point, that if you're looking to describe a device then elaborating its purposes and the purposes of its sensors and actuators is important. To my mind, there is another equally important thing that needs description, which is how a particular purpose is realized in a particular place at a particular time. The latter concept is what I was thinking of when I was discussing a `deployment` earlier in this thread. 

As you point out, the space-time coordinate is not inherent to the device itself. But it is inherent to the realization of (one of) that device's purpose(s). Would it make sense to have a `devicePurpose` property on `Device`, with an intermediating `DevicePurposeRole` that can capture the space/time coordinate and possibly other properties of an application of a particular device purpose?

**Comment by dpjanes** [comment]
In terms of schema.org and semantics stuff, my (possibly misguided) philosophy is that:

* do the least we can, that solves the problem,
* discovery is better than invention

Which is why I've tried to illustrate everything with examples of "real world things" - e.g WeMo - or standards - e.g. W3C submissions - and see how it would apply.

Obviously there are some things that are invented - the concept of an `attributePurpose` and a `devicePurpose` let's say - but they're implicitly there in the device and the schema.org realization is very simple.

@nextdude so what I'm afraid of with `DevicePurposeRole` this gets into standards making. That's not to say it's a bad idea, or that disagree with the concept per se, it's just that no one outside of here is actually _doing_ something like this in data, i.e. that we have a Model/Template and then it encapsulates a specific Instance, with a time range, etc..

If we wanted to go down this path (I'm not suggesting we should, just talking out loud here), why not have 

    Thing > Device
    Thing > Device > DeviceDeployment

And have `DeviceDeployment` just inherit everything from `Device` **and** also have the option of just pointing to `Device`

So then you can do

```
{ 
  "@type": "Device",
  "@id": "http://example.com/BelkinWeMoSwitch",
  "name": "BelkinWeMoSwitch-ChristmasLights",
  "model" : "http://www.belkin.com/us/F7C027-Belkin/p/P-F7C027;jsessionid=FF9B0032273B51E522DEA08C48FCEA00",
  "gtin13": "501234567890",
}
```

and (brackets indicating me waving my hands right now)

```
{ 
  "@type": "DeviceDeployment",
  "device": (the URL of the thing above)
  "devicePurpose": (Lighting, Christmas Tree Lights)
  "deviceLocation": (something analogous to schema:Place for IoT devices)
}
```

**Comment by nextdude** [comment]
@dpjanes I think you're subclassing approach is ok...I understand your point. It does cause me some cognitive dissonance, in that a deployment is not a device, it just uses a device. Further, your approach actually implies it *both is a device and uses one*, which I think is confusing. 

The reason I'm trying to apply roles everywhere is because, to my mind, it's an important way of modeling relationships between things and, in the broader schema.org context, I'm dissatisfied with the fact that the technique, while allowed, is hidden from the standard. It's like we all agreed to put verbs in a separate unpublished dictionary and told everyone to focus on the nouns. Seems to me like roles should be used everywhere. 

@djpanes, what did you mean when you said using the role concept would "get into standards making?"

You also say "no one outside of here is actually doing something like [that] in data."  I don't really agree. That concept lies at the center of relational data modeling and certainly graph-based data modeling. 

But enough of my ranting. Your suggested approach is done elsewhere in the schema.org model, so I'm not against it. I'm just hoping to bring roles out into the light.

**Comment by dpjanes** [comment]
@nextdude my thinking is:

* they're types, not classes
* the terms and types describe (actual) data

So (in my thinking) `DeviceDeployment` is a proper superset of `Device`, so we do `Device > DeviceDeployment`, even though I totally acknowledge the object-related conceptual issues involved in this simplification.

The reason schema's existing Types don't have this issue is because they haven't got it it yet. e.g. `schema:Book` exists but there's no `schema:BookInstance` to describe _my actual copy of the book sitting on the shelf behind right now_, even though I could see that being an interesting thing to know more about!

w.r.t. the second point above, what I mean is that everything gets applied to _actual_ data you see somewhere, e.g. like the terms in this: https://moziot.github.io/wot/. So it's more "description of existing things" than "models" (IMO!).

**Comment by thadguidry** [comment]
@dpjanes SIDENOTE: Historically, in Schema.org we apply Actions with verb usage on a Property level, not at a Type level.  Deployment is a verb and hence would typically be associated to a rich property... perhaps that new property Device:deployment could expect a Type of DeploymentAction.  A full list of our existing Actions is found at http://schema.org/docs/full.html and where we already know and recognize that ControlAction, InteractAction, and others will be useful again for IoT and extended as necessary in the future.

All:  Please continue the discussion but perhaps try to focus more on usecases... give us the kinds of data and concepts that your struggling with describing...or that you have questions on "how would I describe a scenario where ... blah ?".  Those kinds of questions are what we are most interested in and should be posted on our mailing list sdo-iot-sync@googlegroups.com and not in our general issue here about the Sensor Type.

**Comment by dpjanes** [comment]
Not to get too meta, but Deployment is most certainly (and only) a noun. As a side note, I don't care for the word (I'd maybe prefer Instance) but the _concept_ is solid in the context of IoT. And maybe Books.

And we are discussing use cases. With actual things - and how they're used! e.g. WeMos, Philips Hue, random Raspberry Pi sensor devices.

The issue with this discussion in general is we're (bad analogy coming) trying to build a vehicle and we don't even know what it is suppose to do yet, let alone how what size wheel it is supposed to have. If we want to talk about "Sensor Types" almost inherently its worth taking about actuators and the devices they're going to be put into. Hence, some leeway is begged for meandering discussions.

**Comment by thadguidry** [comment]
@dpjanes Meandering discussions are best posted on our mailing list sdo-iot-sync@googlegroups.com please if you don't mind for now.  We want the larger IoT community, who are already signed up on the mailing list, to have a view of important topics and discussions such as all those that your bringing up.  This single issue regarding a Sensor Type... is not the right vehicle for those discussions.  Github issues are not used for that, but instead focused on a single clear issue.  Since things are unclear still, agreed, I'd like to see your views being talked about by others than just the 4 or 5 on this Sensor issue...i.e.  I am trying to help you spread your love :)  so please move the great conversation to our mailing list.  Thanks David, see you on the list.
