### ISSUE TITLE
Clarify description on MusicStore

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1395]
To help developers (and Thad with Wikidata mappings)

Does it currently represent:
1. a retail business that sells musical instruments and related ?
2. a retail business that sells recordings ?
3. any store selling anything music related, including an online only store ?
4. ???

**Comment by danbri** [comment]
Since we didn't specify anything very clear, we should probably keep this generic. Also music recording shops are fading away, people buy fewer CDs, vinyl etc.

http://schema.org/MusicStore is under LocalBusiness which has a facet inheriting from Place so there's some emphasis on a bricks-and-mortar presence. However (and for LocalBusiness as a whole) I'd suggest that there's no need to overemphasize the physical place aspect on these types.

Something like: "A local business presence focussed on music, including record stores, instruments and related activities."

At a stretch this would even cover providers of piano lessons, I guess; unless we have a better home for those kinds of service.

**Comment by vholland** [comment]
Is this for the Wikidata mapping work?

**Comment by thadguidry** [comment]
@vholland yeah for WP mapping, but its also for general public and developers.

@danbri yeah, I like your something like definition much better and its generally what I have seen being used...since we do have the specific subtype of MusicInstrumentStore.
