### ISSUE TITLE
Addiction-Related Vocabulary Proposal

### ISSUE THREAD

**Issue by kevinawilson** [schemaorg/schemaorg#1402]
I would like to propose the addition of vocabulary related to addiction and the treatment of addiction. The accompanying diagram shows the proposed additions in red along with their relations to existing vocabulary in the core and the health-lifesci extension.

![addictiontreatmentcenter](https://cloud.githubusercontent.com/assets/21245789/19354497/e5cafac4-9134-11e6-8c06-a9674d17c46e.png)
# AddictionTreatmentCenter

The first class to be added is **AddictionTreatmentCenter**, which is a subclass of **MedicalOrganization** and **MedicalBusiness**. It is at the same level as other **MedicalOrganization** subtypes such as **Physician**, **MedicalClinic**, and **Hospital**. The properties are:
- _onsiteDetox_, which takes a **Boolean** value. This indicates whether the center has its own detox facilities on site or makes use of those at another entity such as a hospital.
- _typesOfPrograms_, which takes a **Text** value. Standard values would include inpatient, outpatient, and residential. I suggest Text as a type instead of enumerations for flexibility.
- _availableService_, which takes a **MedicalTherapy** as its type. This property is currently used on **Hospital**, **MedicalClinic**, and **Physician**. It may make sense to make _availableService_ a property of the parent class **MedicalBusiness** because it is used on so many of the subtypes. On the other hand, _makesOffer_ is already a property that **AddictionTreatmentCenter** would inherit. The **Offer** could indicate the service that is available, so _availableService_ may not be necessary.
# AddictionDisorder

The second proposed class is **AddictionDisorder**, which is a subclass of **MedicalCondition**. **AddictionDisorder** could be used as a value for _healthCondition_ on the **Patient** class. The term **AddictionDisorder** corresponds to the language of _DSM-V_, and covers both substance and behavioral/process addictions. The properties are:
- _addictedTo_, which would take a **Drug** or **Text** as its type. This indicates the drug(s) or process(es) to which the patient is addicted and would be parallel to the language “drug of choice” that is used in addiction treatment.
- _addictionType_, which would take **Text** as its type. This would be used to indicate whether an addiction was a substance addiction or a behavioral addiction (e.g., sex, gambling, eating disorders).
# MedicalSpecialty Enumerations

I also propose two enumerations be added to **MedicalSpecialty**. These are **AddictionMedicine** and **AddictionPsychiatry**, which are the two specialties recognized by the American Board of Medical Specialties. This has been discussed in issue [#1334](https://github.com/schemaorg/schemaorg/issues/1334), and [Leeza Rodriguez](https://github.com/LeezaRodriguez) suggested using these two enumerations. **AddictionTreatmentCenter** would use these enumerations for the property _medicalSpecialty_ it inherits from **MedicalOrganization**. This would allow them to indicate whether they provided medical or psychological treatment for addiction (or both).
# Issues of Accreditation

Leeza also raised valid concerns about addiction treatment centers marketing themselves without having any parent boards that regulated them (akin to problems in the past with pain management providers). I considered proposing a property of _accreditedBy_ for **AddictionTreatmentCenter** to allow organizations to list credentials. CARF International and The Joint Commission are the two main accrediting bodies for addiction treatment. **MedicalEntity** has a property of _recognizingAuthority_ that is described as “the organization that officially recognizes this entity as part of its endorsed system of medicine.” I’m not sure whether this would correspond to an accrediting agency and therefore could be used as a property on **AddictionTreatmentCenter** or whether _accreditedBy_ would be a better property. Either way, I would propose that it take **MedicalOrganization** as its type.
# Coding

I have written the RDFa definitions for the proposed items, along with JSON-LD and RDFa markup examples. Unfortunately, I am having trouble getting the schema.org app to work (see issue [#1384](https://github.com/schemaorg/schemaorg/issues/1384)), so I am currently unable to put these up for comment. I will make these available as soon as I can.

**Comment by LeezaRodriguez** [comment]
hi Kevin--wow, this is a well thought out proposal. I haven't digested everything, but thank you for taking my Accreditation comments into consideration. I believe that identifying _recognizingAuthority_ and _accreditedBy_ is a critical step in helping the search engines and the consumer figure out which centers are the legitimate and well credentialed organizations **and** physicians.   

With Accreditation, just for clarity, I believe are dealing with two variations of Accreditation:

1) **Organization** accreditation ( CARF and The Joint Commission)
 This is similar to the type of accreditation that out patient surgery centers and hospitals attain. It is granted to the organization.

2) **MedicalSpecialty** certification ( the Medical Board that has oversight of Board Certification of a Physician person). Board Certification is granted to the **Physician person.** 

Allow me to rant about #2....
This is a particular hot button for me because  the provenance of **MedicalSpecialty** is with the Physician, the person, and not the organization. But the **Physician-person** is currently non existent in the schema.org hierarchy.  **Physician** is currently an organization, and NOT a person. @twamarc is aware and he proposed some solutions in this thread here: https://github.com/schemaorg/schemaorg/issues/492#issuecomment-252326168
Recap of concerns:

_MedicalSpecialty originates with the Physician person(s) in the organization._
 If the Physician-person leaves with no replacement, the organization **MedicalSpecialty** is lost.  It is the Physician, the person, who gets Board Certification in a particular MedicalSpecialty.  Each MedicalSpecialty has a MedicalBoard who issues the Board Certification to the Physician person. Furthermore, each MedicalBoard has an oversight board.  In  your example, the individual physicians have Board Certification with either **AddictionMedicine** (issued by American Board of Preventive Medicine)  or **AddictionPsychiatry** (issued by American Board of Psychiatry and Neurology) . The trainings are different pathways with different focus and each one of these Boards are regulated by the **American Board of Medical Specialties (ABMS)**.   Approximately 80% of US physicians are under this system in the USA. @twamarc  had stated that ~a similar type structure applies to the EU.  

_Ontology alignment concerns_
 **Physician** was asserted as a person in Freebase, and it is a person in Wikidata.  **Physician** only exists as an organization in schema.org.   We need to make a data type for **Physician, the person**, and disambiguate it between the person and the organization.  If not, this is going to be a hot mess when Insurance and Clinical Trial vocabulary are introduced.  With Insurance, the Physician person and Physician organization are two different entities with different NPI numbers.  In Clinical Trials, the PI (primary investigator) of any trial is a **Physician person**, NOT a Physician organization. 

Apologies for the tangential rant. 

Nevertheless, I support adding the two ABMS MedicalSpecialty enumerations of **AddictionMedicine** and **AddictionPsychiatry**. As I understand it, the next iteration would overhaul the list of enumerations. Here is my working spreadsheet to help address this.
https://docs.google.com/spreadsheets/d/1y7KIP0icoqowZ1uX4H33rVJKfj5WAjIeqkEpnuN6A9U/edit#gid=0

Thanks for taking the time to think all of this through. _It's so important that we get this right so that the future AI engines will be able to deliver answers that can disambiguate the well credentialed providers from the posers._

**Comment by kevinawilson** [comment]
I have the testing app up and running on the Google App Engine for people to review. The link to the main entry is at [http://health-lifesci.3-2.sdo-addiction.sdo-addiction.appspot.com/AddictionTreatmentCenter]. The only change from the proposal above is the accreditedBy property that has been added pursuant to @LeezaRodriguez's comment.

The portal to the app is at [http://sdo-addiction-dot-sdo-addiction.appspot.com], but this is resulting in an https error when you try to go into the health-sci extension. For some reason, adding 3-2 to the URL makes it work. I'm also not sure why the AddictionTreatmentCenter page is giving the same example twice. It is only in the file once.

I look forward to input/feedback.
