### ISSUE TITLE
openingHours for Organisation and email for LocalBusiness

### ISSUE THREAD

**Issue by stevenkellow** [schemaorg/schemaorg#1427]
I think organisation and local business should share more features, so for instance organisation should have openingHours that they are contactable and LocalBusiness should definitely have the email attribute, as almost all local businesses will have an email address now.

**Comment by RichardWallis** [comment]
@stevenkellow 

**email**
As [LocalBusiness](http://schema.org/LocalBusiness) includes all the properties from both Organization and Place, [email](url) is available to use when defining a LocalBusiness.

Having said that, there seems to be an error on the http://schema.org/LocalBusiness page, where the email property is not showing up.  This is symptomatic of a known problem which will be fixed in the next release of schema.org - if you check out the draft version of the next version here <http://webschemas.org/LocalBusiness> you will see the correct display.

**openingHours** 
Organization, and therefore LocalBusiness includes a [contactPoint](http://schema.org/contactPoint) property, which expects a [ContactPoint](http://schema.org/ContactPoint) type.  This enables the description of several ways to contact an organisation such as "accounts", "Customer Support", etc. ContactPoint includes an hoursAvailable property which addresses your concern.
