### ISSUE TITLE
Feature Request: LocalBusiness -> store -> MedicalSupplies

### ISSUE THREAD

**Issue by inetbiz** [schemaorg/schemaorg#1428]
https://schema.org/Store I would like to feature request a store type of Medical Supplies.

**Comment by jeannieh** [comment]
I would be interested in this, too, for several clients.

That makes sense in view that we have something for many so far:
AutoPartsStore
BikeStore
BookStore
ClothingStore
ComputerStore
ConvenienceStore
DepartmentStore
ElectronicsStore
Florist
FurnitureStore
GardenStore
GroceryStore
HardwareStore
HobbyShop
HomeGoodsStore
JewelryStore
LiquorStore
MensClothingStore
MobilePhoneStore
MovieRentalStore
MusicStore
OfficeEquipmentStore
OutletStore
PawnShop
PetStore
ShoeStore
SportingGoodsStore
TireShop
ToyStore
WholesaleStore

Is there a better way to go about this than to create a new attribute object?

**Comment by thadguidry** [comment]
We currently have the http://Schema.org/naics property that can be used to
classify the type of Retail Store (and in a way, the type of products that
the Retail Store sells).  "Medical Supplies - Store"

For the use case of a Medical Supplies store, you would use Naics Code
446199 - All other health and personal care stores
https://www.census.gov/econ/isp/sampler.php?naicscode=446199&naicslevel=6

Naics covers only the general types of Retail Stores unfortunately, and for
niche product selling, it resorts to using a generic Naics code like "all
other types...blah blah".

The most appropriate way to handle a use case where Naics does not help
further classify, is instead....
just use http://schema.org/additionalType and supply the URL of that
additional type of Store... perhaps for Medical Supplies you could use
http://id.loc.gov/authorities/subjects/sh00005773 but that would be telling
folks that your type of Local Store is a type of "Medical Supplies"... not
exactly what your trying to say... your trying to say it sells products in
that category... so yes...it can be improved I think by switching out the
Naics property to be a property called "industry" and have it expect a type
of Text, URL, or Naics code.

>

**Comment by jeannieh** [comment]
I appreciate your answer, Thad.

When adding http://schema.org/additionalType and a URL of that additional type of Store, can you add clarity as to if where and how on an individual page you would add this? I am testing a lot of applications. 

It seems best, in general, if additonalType is used it is best if schema.org descriptions that are used match the corresponding human-facing content.

**Comment by thadguidry** [comment]
>
> I appreciate your answer, Thad.
>
> When adding http://schema.org/additionalType and a URL of that additional
> type of Store, can you add clarity as to if where and how on an individual
> page you would add this? I am testing a lot of applications.
>
http://schema.org/additionalType is at the Thing level... so you can add it
in whenever and wherever you need to.

> It seems best, in general, if additonalType is used it is best if
> schema.org descriptions that are used match the corresponding
> human-facing content.
>
You lost me on this.  Can you reiterate with a good use case example and
question around it ?  Then I'll try to answer as best I can.

**Comment by jeannieh** [comment]
Okay, I will thin this to one page and use example.

Question: Concerning Correct Use of JSON "additionalType"?

Schema.org lets us know how additionalType can be used for a product, but what is current and correct for a LocalBusiness or Person when used on an article page? Is there a way to use additionalType to expound on the article subject? I have written this article because I do SEO/SEM currently for 3 medical client sites. 

So how should one use Wikipedia or Wikidata to further define my business services using an entry that relates to my business type AND niche here? Because the article is about SEO/schema for  Medica Diagnosis or Medical Research, what is the incorrect use of the wiki entry?

Is the following code example considered acceptable? Does Google regard this as adding information from a trusted source - Wikipedia ( being that it contributes value for defining what the article is about)? 

Or is it better to add the definition visibly in the body of the article and credit (with a link) Wikipedia for it?

<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "LocalBusiness",
    "address": {
        "@type": "PostalAddress",
        "addressLocality": "Farmington",
        "addressRegion": "MN",
        "streetAddress": "621 Oak St",
        "postalCode": "55024",
        "addressCountry": "USA"
    },
    "description": "Helping companies advance in search and make better marketing and business decisions.",
    "name": "Hill Web Creations",
    "telephone": "16512062410",
    "additionalType": ["https://en.wikipedia.org/wiki/Medical_diagnosis", 
"https://en.wikipedia.org/wiki/Medical_research"],
    "sameAs": ["https://www.facebook.com/Hill-Web-Marketing-1795387700688037/","https://twitter.com/essentialskill","https://www.linkedin.com/in/jeanniehill1",
"https://www.pinterest.com/HillWeb/",
"http://www.slideshare.net/jhill510",	
"https://plus.google.com/+HillwebcreationsMinneapolisMarketing"]
}
</script>

Here is the web page in question: <a href="https://www.hillwebcreations.com/medical-search-technology-relies-on-google-alphabet-big-data/">Medical Search Technoloogy</a>.

**Comment by thadguidry** [comment]
@jeannieh  of course.  Your talking about Article http://schema.org/Article , and notice that it can use the "about" property from CreativeWork...that "about" property expects a type of Thing...and I already said that Thing has a property for additionalType.

You wrote an article about "Medical Search Technology"...now use Thing->additionalType to classify what Medical Search Technology IS A class of...maybe its just a http://webschemas.org/Product ? who knows, depends on your context there.

If the article is about Medical Research...then use additionalType to classify what "Medical Research" IS A type of... probably just a http://schema.org/BusinessFunction or it might be also a http://schema.org/Specialty or even a http://schema.org/OrganizationRole or a http://schema.org/Service ...

See our full list of types: http://schema.org/docs/full.html
and upcoming types: http://webschemas.org/docs/full.html
