### ISSUE TITLE
serviceAudience vs. audience

### ISSUE THREAD

**Issue by elf-pavlik** [schemaorg/schemaorg#145]
http://schema.org/audience
http://schema.org/serviceAudience

related email: http://lists.w3.org/Archives/Public/public-vocabs/2014Oct/0023.html

I would suggest removing serviceAudience and using generic audience. If some reasons exist for not doing so maybe at least defining serviceAudience as subPropertyOf audience?

**Comment by danbri** [comment]
@elf-pavlik 's proposal seems sensible to me. @vholland - any thoughts?

**Comment by vholland** [comment]
Sounds good to me.

**Comment by elf-pavlik** [comment]
PR #285

**Comment by danbri** [comment]
Thanks. Historically it is pretty rare for us to actually erase terms, so far we usually just mark as supersededBy. In this case maybe that is too conservative and best to avoid clutter. Any thoughts?

**Comment by sesuncedu** [comment]
You could mark the obsolete terms in HTML with <s>. In the type rendering
you could group the obsoleted terms together with the term that obsoleted
them.

I've been treating superseded as implying sub property and obsolete .

The sub property relationship might be wrong, if a superseding property can
have a narrower meaning than the older term.

**Comment by elf-pavlik** [comment]
@danbri if you like I can revert | drop this change and then use *schema:supersededBy* instead!

**Comment by danbri** [comment]
Yes, I think schema:supersededBy would be most appropriate here. @elf-pavlik could you tweak your branch that #285 draws from? I've filed this for the next release, and can't see it proving controversial.

Simon is right that we could say more about what it means. We have never said that it implies subPropertyOf, since it is easy enough to assert that independently at the same time where needed.

In this case I believe serviceAudience would also be a sub-property of audience.

**Comment by danbri** [comment]
I'm going to take the pull request, then add back in 

-    <div typeof="rdf:Property" resource="http://schema.org/serviceAudience">		
-      <span class="h" property="rdfs:label">serviceAudience</span>		
-      <span property="rdfs:comment">The audience eligible for this service.</span>		
-      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Service">Service</a></span>		
-      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/Audience">Audience</a></span>		
-    </div>

and use supersededBy instead of deletion.

**Comment by danbri** [comment]
I've implemented this manually after failing with the pull request.     I tweaked the definition to be "An intended audience, i.e. a group for whom something was created." rather than use "item" or "subject" to refer to the thing that has the audience. Also "an" rather than "the" since the property is repeatable.
