### ISSUE TITLE
Q: Why does schema.org still use MicroData?

### ISSUE THREAD

**Issue by ayumihamsaki** [schemaorg/schemaorg#1485]
Hi,

I would like to ask a simple question, why does schema.org still use MicroData when MicroData API is not supported by any web browser see here: http://caniuse.com/#search=microdata

Surely schema.org should tell users to use or migrate to JSON-LD or RDFa?

Sorry am I missing something here? (So I thought I'd ask this question)

**Comment by danbri** [comment]
The API component of Microdata, as you point out, was not very successful. It was removed from WHATWG version of HTML specs, and I have recently joined the W3C Web Platform WG to help @chaals and friends with a similar update to the W3C version. 

Microdata itself remains very popular. It is used on many millions of sites. There are a few situations in which RDFa can work better, and there are also many arguments in favour of JSON-LD, but there is no need for a "mass migration". Schema.org is designed so that it can be expressed in different syntaxes but still be understood. In the future, we might see other approaches, e.g. structured data in CSV files, or using "Web component" markup, as ways of using schema.org.

The failure of the Microdata API also means that we should probably start thinking again about how structured data might someday be used more within Web browsers, and browser-based applications. But Microdata's API is only a small (and obsolete) part of Microdata. Most of Microdata is about the markup format, and it is still fine to use. Hope this helps.

**Comment by ayumihamsaki** [comment]
Thank you very much for your answer, totally understand what you are saying and thanks for the answer.

**Comment by danbri** [comment]
Thanks for asking - it helps to know how these things are perceived...

**Comment by ayumihamsaki** [comment]
Yes you read my mind.
