### ISSUE TITLE
Compositional Terms

### ISSUE THREAD

**Issue by rvguha** [schemaorg/schemaorg#1493]
One of the primary goals of schema.org is to facilitate maximum interoperability while minimizing the number of distinct terms that need to be shared. Having the ability to refer to the business/profession/… associated with an activity, as soon as the activity or product is introduced into Schema.org, without having to wait for the corresponding business/profession etc. to be explicitly introduced as a Schema.org term would be convenient.

Here is a proposal that is targeted at facilitating this. This is meant to be a starting point for a discussion.

https://docs.google.com/document/d/1AbxUOflXe-cNrLd4ZIOcBuG7O5QDB-ExZqFzlz5Ud6c

**Comment by jvandriel** [comment]
_"Can we have a full example for how this would be used by webmasters?"_

Could you please elaborate on what types of common situations you think this would help resolve?

Reason I ask is because trying to understand it makes my brain hurt because of the - for me - too abstract description, thus making me sceptical about the practicality for everyday webmasters. Or isn't it intended for everyday markup?

**Comment by jvandriel** [comment]
> "I thought maybe JSON-LD inline contexts could create a short label for the long URL."

Is this something that can be done with microdata as well?

**Comment by danbri** [comment]
@jvandriel the basic idea is to do with consistency and maintainability of schema.org. We often have the same underlying concepts appear in several places in the hierarchy, as part of more complex concepts. So for example we might have GolfCourse (which combines the idea of a place where you do a sport i.e. a SportsActivityLocation with some specific sport, Golf). But we might also have a (something like...) GolfSportsMatch, which combines that same sport - Golf - with a different concept - the idea of being a kind of SportsEvent devoted to a particular sport.  

As schema.org grows, we get more and more of these situations. It becomes a burden to keep track of the different ways in which we've built terms that combine simpler underlying ideas (like specific sports). We don't want to clutter schema.org with every possible sensible combination of these ideas e.g. a GolfingTutorial or a CricketSportsEvent or a CyclingCompetition or a CricketTutorial or a GolfingSportsEvent or a GolfingCompetition or a CyclingTutorial. The combinations soon become unmanageable. But we do want to make it easy to describe all these situations in ways that search engines can understand. While the underlying logic is reasonably straightforward it is not totally clear how things should look in actual markup yet, which is why we've started this conversation. I had a go at drafting JSON-LD in the above doc but it is just a sketch. Microdata/RDFa need consideration too, but potentially there are other possibilities.

Beyond this, we also have a longstanding interest in plugging in external lists from projects like Wikipedia, so that we can go deeper into specialist domains without schema.org having to maintain everything. So you might reasonably want to have a "..._Competition", "..._Tutorial", "..._SportsEvent", "..._Place" for any kind of sport that is listed by Wikidata or SportsML. It is possible that this is too ambitious an idea to mix with the compositional terms approach, but it is worth exploring.

**Comment by danbri** [comment]
@jvandriel - maybe you could say a bit about how the actual schema.org site fits into your actual workflow, if you are doing some work that involves getting schema.org onto someone's site. Do you browse the hiearchies much, or search, or start from other docs like Google/Bing/Yahoo/Yandex's own product pages? Or do you find you just remember type names after a while...?

**Comment by jvandriel** [comment]
Thanks for the additional explanation @danbri, I (think) I get it now. At least I definitely can relate to:
> "We don't want to clutter schema.org...combinations soon become unmanageable...easy to describe all these situations..."

As for:
> "So you might reasonably want to have a "..._Competition", "..._Tutorial", "..._SportsEvent", "..._Place" for any kind of sport that is listed by Wikidata or SportsML." 

Now maybe I should let everything sink in before making suggestions but after having read it all a couple of times I can't help wonder whether we don't already have all the building blocks we need to be able to express pretty much the same.

More specific types for example is something we already can handle through multi-type entities:
```"@type":"Product, "http://www.productontology.org/id/Fire_extinguisher"```

While we can use ```additionalProperty``` + ```PropertyValue``` for specifying properties that don't exist in schema.org (and also can be expressed in microdata):
```
"@type":"Product, "http://www.productontology.org/id/Fire_extinguisher",
"additionalProperty":
{
  "@type":"PropertyValue",
  "@id":"http://example.com/some-property",
  "name": "some property",
  "value": "some value"
}
```

Anywhozel, just my first thoughts...

> "...how the actual schema.org site fits into your actual workflow..."

Well, after having kept up with schema.org ever since it was first mentioned on W3C mailing lists, most of what I do is based on memory and not so much on what I find on the site - especially for those domains I regularly work on. So I might not be the most representative 'webmaster' in that regard.   ;)

Though when I have to do work for domains I don't have any experience with my first goto page definitely is the [type hierarchy](http://schema.org/docs/full.html) - something I'd LOVE to have for properties as well (would make life a lot easier). From there I normally start with CTRL(CMD)-F + $thing-im-searching-for. If that doesn't do it, I simply scroll through the list to see if I find synonyms for the thing I'm looking for and check those. And if I can't find what I'm looking for then I generally select a less granular type (often enough ```Thing```) and specify a secondary type based on what I can find in Wikipedia and change the address to a productontology item.

Furthermore I noticed I've started looking more at GS1's websites when doing ecommerce work, though that's mostly for categorization purposes. And when I want to learn more about a specific domain/industry I generally mail around to see if anybody knows any domain/industry specific vocabulary I should read.

Now of course I also keep an eye out for what the sponsors publish (although it might be said that following @Aaranged usually suffices for that) but given the fact that I use both Google's and Yandex's validators there's not much need to read their guidelines unless I run into errors that don't make sense to me. As for Bing, sorry to say but there's not much sense in taking it into account since it's 'validator' is hopelessly outdated and limited.

**Comment by lanthaler** [comment]
What was the reasoning behind using a microsyntax in the form of a URL (`<Function>?arg1name=arg1value&arg2name=arg2value....`) instead of using a more structured representation?

**Comment by rvguha** [comment]
Well, it *is* structured and doesn't break existing parsers. One can of
course create alternate representations, much like SOAP created an
alternate representation for passing arguments to cgi functions.

guha

**Comment by RichardWallis** [comment]
At first read of this I tend to concur with @jvandriel's initial thought that we already have the building blocks for more specific types using techniques such as productontology plus additionalTypes.

I wonder how many of these function created values (eg. TennnisCoaching) do not already exist or could easily be added to WikiPedia/WikiData

Beyond that my main reactions to are: 
- the function based URLs, how the average webmaster would get their head around creating & applying them,  and how un-_**[cool](https://www.w3.org/TR/cooluris/)**_ they would be.
- Yes the approach is structured but the implementation pattern would be so unlike the rest of Schema.org the result would be as unnatural as a shotgun marriage between SOAP and REST.  Both pushing the same direction but a union incomprehensible to the outside world.

Having said that I applaud the desire to solve this, and encourage the view from the average webmaster to be taken into account when reviewing proposals.

**Comment by jvandriel** [comment]
_"I applaud the desire to solve this"_
Couldn't agree more with you @RichardWallis. 

I've been doing my best to help out with the health-lifesci extension over the last 2 months yet find myself stuck trying to decide whether things should be subtypes, schema.org enumerations or external enumerations (both ```CategoryCode``` as well as Wikidata items).

So not only am I happy this proposal can help keep schema.org more maintanable but also because it helps making certain decisions that need to be taken for the health-lifesci extension a lot easier (yay).

**Comment by rvguha** [comment]
Richard, could you show me how you would construct Tennis Coach, Tennis
Match, etc. etc. from just Tennis, using what we already have? I am pretty
sure that is not possible.

These things aren't really targeted at the webmaster who is manually adding
markup. They are targeted at the numerous broad and vertical specific
platforms (such as drupal) that are responsible for the vast majority of
Schema.org markup that is around today.

And beyond simple web markup, there are a bunch of applications (in bio,
energy, etc.) where standard schemas are needed and these could be very
useful.

And I am very sorry that you find it uncool, but I never quite made into
the cool list. So, thats ok.

guha

**Comment by lanthaler** [comment]
> Well, it *is* structured and doesn't break existing parsers.

From schema.org's point of view perhaps. From a client's perspective definitely not. It goes directly against the principle of [URI Opacity](http://www.w3.org/TR/webarch/#uri-opacity) as described in the *Architecture of the World Wide Web*:

So, if we decide to use such URLs (which is completely fine), we need to have the means in the vocabulary to describe their semantics. Something like

```
{
  "@id": "<Function>?arg1name=arg1value&arg2name=arg2value....",
  "@type": "<Function>",
  "arg1name": "arg1value",
  "arg2name": "arg2value"
}
```

which should be available at `<Function>?arg1name=arg1value&arg2name=arg2value....`.

This would not only make their meaning explicit and stay within the framework we operate under, but also allow third parties like WikiData to describe their concepts in these terms.

In most cases, btw., it probably would make sense to have more explicit properties than `arg1name` and `arg2name`.

**Comment by RichardWallis** [comment]
@rvguha Anything you can encode into a URI can still be serialised in an entity description as per the current model of Schema:
```
{
  "@type": "<Function>",
  "arg1name": "arg1value",
  "arg2name": "arg2value"
}
#Appropriate naming of Types and properties needed
```
So the semantics of what you are proposing would remain.  My main issue is with the proposal to introduce yet another way of serialising data. On top of microdata, RDFa, & JSON-LD you are adding encoded-URIs.

If your main target for this is the vertical specific platforms such as Drupal, the choice of serialisation is not a major problem - clever motivated folks will just code it.  The significant long-tail of web developers who provide many of the millions of sources of Schema data on the web, are those that we need to validate this approach with.  It is this long-tail that has much to to do with the establishment and spread of Schema implementations.  I believe it would be leave some of them behind by getting over complex.

My concern with the proposal as it stands is the unnecessary introduction of techniques that run contrary to long established web principles such as W3C's [CoolURIs](https://www.w3.org/TR/cooluris/), [URI Opacity](http://www.w3.org/TR/webarch/#uri-opacity), etc.

I am not worried about the coolness of the proposer, we are all cool in our own way ;-)  My concern is how cool, in W3C terms, our proposals are.

**Comment by jvandriel** [comment]
OK, it's obvious you're all much cooler than I am as I tend to think in markup as opposed to abstracts, so let me propose 1 possible solution before moving to the sidelines (until I can't resist proposing yet another naive solution).

If we would add a ```schema.org/Function``` type could we then not get away with something like this?
```
{
  "@context":"http://schema.org",
  "@type":["Function","http://www.productontology.org/id/Coaching",
  "additionalProperty":
  [
    {
      "@type":"PropertyValue",
      "name":"arg1name",
      "value":"arg1value"
    },
    {
      "@type":"PropertyValue",
      "name":"arg2name",
      "value":"arg2value"
    }
  ]
}
```

**Comment by jvandriel** [comment]
> "They are targeted at the numerous broad and vertical specific platforms (such as drupal)..."

About that, first off, I've literally lost count of the amount of times I've seen theme developers utterly destroy graphs because they don't really understand how Drupal works (and/or aren't aware that structured data is part of its core). Often leading to developers disabling those parts of Drupal that add structured data to a page. So unless @scor would get involved in the gazillion custom templates out there I wouldn't get your hopes up about seeing a lot of proper implementations .

And as for Wordpress (that really represents the bulk of the web), I dare to believe I know most people behind the established structured data tools for that CMS, and even though many of them are some pretty smart people , I expect some pretty serious mistakes will be made. Let alone the fact that I don't see how they're going to explain this to their clients/audience.

**Comment by jvandriel** [comment]
OK, one last question... 

Does the meaning of the document's example equal this?
```
<script type="application/ld+json">
{
  "@context":"http://schema.org", 
  "@type":"Course",
  "name":"Advances in modern Tennis coaching.",
  "description":"A course all about coaching in tennis.",
  "provider":
  {
    "@type":"Organization",
    "name":"University of Tennessee",
    "sameAs":"http://www.ut-eureka.example.edu"
  },
  "about":
  {
    "@type":["Tennis","http://www.productontology.org/id/Coaching"]
  }
}
</script>
```

**Comment by jvandriel** [comment]
Correction, _"one last question"_ should have been two last questions.

In regards to _"could you show me how you would construct Tennis Coach, Tennis
Match, etc."_ If ```specialty``` were to be added to ```schema.org/Thing``` couldn't we than express the following :
```
<script type="application/ld+json">
{
  "@context":"http://schema.org", 
  "@type":["Thing","http://www.productontology.org/id/Coach_(sport)"],
  "specialty":
  {
    "@type":"Tennis"
  }
}
</script>
```

and
```
<script type="application/ld+json">
{
  "@context":"http://schema.org", 
  "@type":"Event",
  "specialty":
  {
    "@type":"Tennis"
  }
}
</script>
```

**Comment by Aaranged** [comment]
Pretty aligned with the opinions expressed by @jvandriel and @RichardWallis here, but hesitate to say much more until somebody (@danbri?) provides a full example rather than what's in the referenced "Compositional Term" document - i.e. with values supplied for:
`"http://schema.org/<Function>arg1name=arg1value&arg2name=arg2value"`

My primary concern is that - however elegant such a solution may be - it will be incomprehensible to the majority of webmasters, and that this complexity, in consequence, will thwart adoption.  Which is important because IMO one of the primary goals of schema.org should be to create, maintain, and promote structured data on the Internet in a fashion that's accessible to reasonably knowledgeable webmasters.

**Comment by danbri** [comment]
For the sake of focussing, may I suggest we take as a **given** that there is value in having complex terms (i.e. types, properties, property IDs etc, but particularly types), **and** that while these terms can be described using schema-defining triples, we will specifically want them to have them encoded _somehow_ into URLs (aka URIs, IRIs, etc.).

I suggest we step back from the webmaster simplicity concerns for now and focus on the logic of the proposal @rvguha is outlining. Once the logic of the proposal is a bit more settled, then absolutely yes let's review its concrete representation(s) for usability/simplicity etc. Right now there are two many layers of the discussion interacting and I fear this is going to be hard for all participants to follow.

**Comment by Aaranged** [comment]
Thanks @danbri - I like your approach, and will shelve that ancillary discussion for now in the interest of, as you say, focusing on the nuts and bolts of the proposal.

To that end may I request again some dummy data in the previously-provided example so I can (hopefully) better understand it?

**Comment by rvguha** [comment]
I think I have not clearly communicated the intent of my proposal.

I don't expect the webmaster of a small site to understand in great depth
the concept of compositional terms. Indeed, when we started Schema.org in
2009/2010, one of the guiding principles was that most people creating the
markup should not have to understand Knowledge Representation.

As the vocabulary in Schema.org grows, we are seeing proposals to cover
services, business types, professions and so much more. Unfortunately, we
are trending towards somewhat less than completely coordinated coverage in
these different areas. While I strongly believe that we need to extend our
coverage to these areas, it is equally important that these expansions be
well coordinated. And the only way we can do that is to give ourselves the
representational tools to do so. Compositional Terms (aka non-atomic terms)
are a good way to do them.

I expect that the Schema.org site will have terms corresponding to the
composed terms. i.e., not just Tennis, but also TennisCoach, TennisEvent,
etc. Webmasters will not have to understand the structure of the url
anymore than they need to understand the structure of a Youtube url when
they embed a Youtube video on their site. And when someone wants to refer
to a more exotic sport, such as Mosur idli throwing, perhaps from some
different namespace, that person might want to delve into constructing
terms for the Coach, etc. for this sport.

guha

**Comment by jvandriel** [comment]
> _"we will specifically want them to have them encoded somehow into URLs (aka URIs, IRIs, etc.)."_
+
> _"I suggest we step back from the webmaster simplicity concerns for now and focus on the logic of the proposal @rvguha is outlining."_
+
> _"the only way we can do that is to give ourselves the representational tools to do so."_

You know it's OK to tell me to shut up for a moment right? ;)
It certainly isn't my intend to drag the discussion into direction you're not ready/willing to take it (yet).

And I agree with @Aaranged's: _"I request again some dummy data in the previously-provided example so I can (hopefully) better understand it?"_

I just hope your goal, and any possible end result doesn't exclude 'webmasters' being able to express composite terms as well - that's it (well that, and the fact I'd like to understand it out of personal interest).

**Comment by RichardWallis** [comment]
Clearly I am failing to visualise the simplicity, for the webmaster of a small site, of what appears on the surface quite a complex proposal.

So I not only echo the request of others for some dummy (or real) data examples, but also an impression of how things, on the Schema.org site, might look to the person trying to find out how to mark up the [Tennis]Coach providing the [Tennis]lessons at her Sports Club, in a way that would also help the webmaster for a Golf tournament. 

I think such examples would greatly facilitate this discussion and hopefully move it forward on to the core issues.

**Comment by rvguha** [comment]
It would be no different (for the webmaster of a small site) than if we had
created TennisCoach, TennisLesson, etc. one by one.

guha

**Comment by RichardWallis** [comment]
Ok my visualisation capabilities are definitely failing me now.

Thinking that 10 minutes, coffee, and a whiteboard would totally change my view of this proposal.  Unfortunately coffee & whiteboards don't seem to be on the Github issues options list :-(

**Comment by rvguha** [comment]
The webmaster, through navigation or search finds themselves on a page
(ignore the details of the url of the page for now), which is the term for
Tennis Coach. Today, they don't care about how that page was created,
either at the process level (i.e., these kind of discussions) or at the
technical level (i.e., through app engine, etc.). They will continue to not
care about it. Whether the URL looks like http://schema.org/TennisCoach or
http://schema.org/CoachFn?sport=Tennis should not matter to them.

guha

**Comment by thadguidry** [comment]
All,

Guha is just trying to get a nice way for us to slap 2 Types (or more) together...without having to do much work...He says Compositional... but it might be easier to just think Concatenation instead...or Subtyping....(but it doesn't have to be limited to just Types) ...all the same thing basically.

Another way for @jvandriel to think about this is a cool way to Subtype things... and get specific...without have super long syntax for being specific ! :)
(and other cool possibilities at programmatic levels)

Puter - Coach:
  Human or App - Uhh...you can't just tell me coach, I need specifics Mr. Computer...what kinda coach again ?
Puter - sports=Tennis
  Human or App - Oh !  A Tennis Coach !
Puter - return True
:)

**Comment by rvguha** [comment]
Thank you.

**Comment by RichardWallis** [comment]
Thank you both!
Making more sense now....

I see a few interesting challenges then:

- Where to get the matrix canonical values from (we can't expect Schema to hold all possible sports/occupations/business types etc) WikiData/authoritative sources/knowledge graph?
- How to map those (URI) values to id's that would populate such URL arguments
- The design of the lookup function both on the Schema.org site and possibly an embeddable function
- The URL construction that doesn't break established design guidelines for coolness etc.

**Comment by lanthaler** [comment]
> The webmaster, through navigation or search finds themselves on a page
> (ignore the details of the url of the page for now), which is the term for
> Tennis Coach. Today, ...

Just to make sure we are on the same page. The intent wasn't to give webmasters the tools to create TennisCoach themselves?

**Comment by rvguha** [comment]
They can, if they want to, if we haven't. Like they can do interesting
mashups with namespaces. But the hope is that 95℅ of the time, they won't
have to

Guha

**Comment by westurner** [comment]
> They can, if they want to, if we haven't. Like they can do interesting
mashups with namespaces. But the hope is that 95℅ of the time, they won't
have to

-  "a TennisCoach" is a "Person" who Coaches who specializes in Tennis

**Search queries**

- search("tennis coach")
- search(''' "tennis coach" ''')
- search("tennis coach <\<location>\>")
- search(("www.wikidata.org/wiki/"), "Tennis")
  - "Tennis" https://www.wikidata.org/wiki/Q847
- search("en.wikipedia.org/wiki/", "Tennis")
- search("en.dbpedia.org/resource/", "Tennis")
- ``SELECT Person as p WHERE p.specialty IN lookup_uris('schema:specialty', {"tennis", "coaching", "tennis coaching"}))``
  - [ ] https://schema.org/specialty domain:
    - [x] *domain*: [WebPage]
    - [ ] *domain*: [[WebPage, Person, Organization]
    - [ ] *domain*: [Thing] ?
- search("a person who teaches tennis courses in <\<location\>>")

```
    SELECT Person as p, Course as C
    WHERE (c.name LIKE %tennis%
                  OR c.description LIKE %tennis%
                  OR _:Tennis IN c.about
                  OR _:Tennis IN c.about.url)
    JOIN Person.url == Course.author.url
    WHERE Person.location IN ?location
```

**MedicalSpecialty / SportSpecialty**

- From https://schema.org/MedicalSpecialty :

    **MedicalSpecialty**
    Defined in the health-lifesci.schema.org extension.
    Canonical URL: http://schema.org/MedicalSpecialty
    Thing > Intangible > Enumeration > MedicalEnumeration > **MedicalSpecialty**
    Thing > Intangible > Enumeration > Specialty > MedicalSpecialty

    Any specific branch of medical science or practice. Medical specialities include clinical specialties that pertain to particular organ systems and their respective disease states, as well as allied health specialties. Enumerated type.

    Usage: Between 1000 and 10,000 domains

- [x] https://schema.org/sport r: {Text, URL}
- [ ] https://schema.org/sport r: {Text, URL, **Thing**(url=, name=)}

.

- [ ] Thing > Intangible > Enumeration > Specialty > **SportSpecialty** ?

**Comment by danbri** [comment]
@westurner - I'm afraid I don't understand much of what you've written here :( It is evocative but looks like it is coded in a language unique to you, especially the "search queries" section. A short paragraph in English to give more explicit context would probably help others (me at least) parse what you're trying to say.

One point - _"a TennisCoach" is a "Person" who Coaches who specializes in Tennis_ - does echo something I've been thinking about, which is that what @rvguha is looking for has some similarities with OWL, except that we are likely to care more here about composing URLs to name composite type terms. We may also care more about non-type terms than most of OWL, I'm not sure.

**Comment by westurner** [comment]
> @westurner - I'm afraid I don't understand much of what you've written here :( It is evocative but looks like it is coded in a language uniquthesee to you, especially the "search queries" section. A short paragraph in English to give more explicit context would probably help others (me at least) parse what you're trying to say.

Practically, this information is useful for indexing on structured attributes. Is search the primary use case? If so, the queries used to find this information are important for modeling the cognitive domain. (and far more complex than, say, full-text search of JSONLD documents.)

- C: Class //  P: Property
- C: https://schema.org/MedicalSpecialty
- P : https://schema.org/medicalSpecialty
- MedicalSpecialty begged the question of an abstract Credential 
  - https://github.com/schemaorg/schemaorg/issues/492#issuecomment-213429305
  - https://github.com/schemaorg/schemaorg/issues/1402#issuecomment-253852596
- Course discussions begged the question of an abstract Credential
  - #195
  - [signed [in a blockchain]]
  - Are these skos:Concepts, schema.org/Classes, schema.org/Thing(url=URI), Enumerations?
    - Might there need to be unique domain references
- Credential discussions (and Medical **Credential** #195 Types/Enums) 

> One point - "a TennisCoach" is a "Person" who Coaches who specializes in Tennis - does echo something I've been thinking about, which is that what @rvguha is looking for has some similarities with OWL, except that we are likely to care more here about composing URLs to name composite type terms. We may also care more about non-type terms than most of OWL, I'm not sure.

re: OWL:
- http://topbraid.org/schema/
  - Unfortunately, AFAICT, these transformations are only of schema.org core: they don't include extension vocabularies; so e.g. MedicalSpecialty is not a thing.

**Comment by mediaprophet** [comment]
+1 for "Compositional Terms".  

in terms of visualisation of how it might be used (via a wordpress plugin for instance) someone might have a search UX to identify terms they can drag/drop into a sequence, and then label. 

ie: medicalClinic  and daySpa = medicalSpa (give definition, perhaps add url: http://www.americanmedspa.org/ or wikipedia reference (which may auto get the wiki-data page), that i cannot find for this example atm)..

IMHO: this goes to embodiments.  Another example would be recipes.  People make the same food thing in a number of ways, yet each require primitives (which all may have different trade names, or brands or author preferences (ie: 'organic')) and the use of these ingredients in different ways, with different methods of preparation, etc.  ends-up with a different result. 

Another example: https://www.ted.com/talks/thomas_thwaites_how_i_built_a_toaster_from_scratch 

Therein; "primitives" or perhaps schema.org/primitives (subclass of https://schema.org/DataType ) which contains schema.org/embodiment (name|URL|sameAs(wikidataRef) and likely also schema.org/author & https://schema.org/license (noting one issue may be that the result could strip the revenue model away from the author of the creative work (seeAlso: https://en.wikipedia.org/wiki/Copyright_Clause ) 

beyond the complexities, benefit is the creation of structured data that can be used by emergent web experiences powered by WebOfData (without electing a world where google owns all the knowledge ;) )
