### ISSUE TITLE
New type for library systems

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1495]
We currently have http://schema.org/Library as a type described as "a library". It would be useful to separate out library systems from individual branches. I propose adding a new type for LibrarySystem.

@RichardWallis who knows about libraries.

**Comment by dbs** [comment]
I've been modeling this in the existing vocabulary using http://schema.org/parentOrganization and http://schema.org/subOrganization to indicate parent / child relationships, with http://schema.org/Library from the top to the bottom of the hierarchy.

Upon reflection, though, it might be cleaner to use http://schema.org/Organization at the top of that hierarchy, and for each sub-system that occurs in the hierarchy, and reserve http://schema.org/Library for only physical entities.

For this proposal then, rather than LibrarySystem, perhaps LibraryOrganization would be created as a child of http://schema.org/Organization to parallel the naming and structure of http://schema.org/EducationOrganization and its siblings, with http://schema.org/Library becoming a child in turn.

**Comment by erimille** [comment]
In short, the combination of the classes Organization and Library, along with the predicate parentOrganization, covers a fairly common pattern found in most library systems from local to consortia.  Here is just one example - http://link.houstonlibrary.org/ 

We've used this as a general pattern as there is a lot of nuance in describing Libraries when you get into specifics of international, domain, etc.

So +1 in supporting attempts at richer descriptions. That said, I think we all benefit from a better understanding of what such nuance provides in terms of actionable outcomes.

**Comment by RichardWallis** [comment]
@dbs and @erimille have captured well the essence of how libraries are organised.

One library 'organisation'  (City Library, University Library, etc.) can have  zero or more branch or sub-libraries.  eg. New York Public Library has over 90 local libraries such as New Amsterdam Library.  As @dbs demonstrates the current parentOrganization/subOrganization/department properties of Organization/LocalBusiness/Library can capture this.  

I can see some reason in his thought as to replicating EducationOrganization pattern with LibraryOrganization.  However I believe EducationOrganization is one of what should be maintained as a very small grouping of organizations - government, education, medical, sports.  I believe library to be possibly too specific to qualify here.  This area could easily rival LocalBusiness as a popular candidate for subtype proposals.

Getting back to the proposal....
A library, and it's branches, can also be part of a organisational grouping, usually referred to as a consortia.  An example of this being the [Orbis Cascade Alliance](https://www.orbiscascade.org/member/)  in Noth West USA.   Modelling this at the moment would use Organization which infers some form of ownership/control by the parent organisation which isn't really correct for a consortium.

As consortia are common not only in the library world (eg. http://www.lgbtconsortium.org.uk/ http://www1.uwe.ac.uk/et/consortia/constructionconsortium.aspx) I propose a new Organization subtype _Consortium_ "An association, typically of several companies or other organizations."

A _Consortium_ type with _member_ Organizations that have _subOrganization_(s)and/or _department_(s) I believe would capture what you are trying to describe in the library domain as well as other sectors.

**Comment by erimille** [comment]
The [Houston Public Library]( http://link.houstonlibrary.org/ ) example is a member of HALAN (Houston Area Library Network) consortium and similar to Orbis Cascade Alliance mentioned. 

Marion & Ed Hughes Public Library - http://link.ned.lib.tx.us/
Effie and Wilton Hebert Public Library - http://link.ptn.lib.tx.us/
and 8 others are also members of the HALAN Consortium. 

In this case, we've modeled these entities in a similar manner

Houston Public Library (Org) -> member -> HALAN (Org) 
Houston Public Library (Library) -> subOrganization -> Houston Public Library (Org)
Walter Neighborhood Library (Library)  -> subOrganization -> Houston Public Library (Org)
etc.

Again, Organization + Library *can* capture such relationships, but +1 again in supporting attempts at richer descriptions of this domain. Consortium in this cases seems much more like a missing piece of the puzzle (with the caveat that there are "lots" of different kinds of consortium in the Library space)

Again, however, I think we all benefit from a better understanding of what such nuance provides in terms of actionable outcomes.  Are use cases part of such proposals?

**Comment by danbri** [comment]
One thing to mention here which has tripped up deployment pragmatics previously: Google's Structured Data Testing Tool is now more tolerant of multi-typing (from unrelated parts of the hierarchy). So e.g. if we had Consortium somewhere else, it could be used as a 2nd type without that tool confusing people...

**Comment by vholland** [comment]
+1 to a type like Consortium.

The problem with using the suborganization pattern is there is no way to specify something is the top of the hierarchy without listing the entire hierarchy.

**Comment by thadguidry** [comment]
All,

Whats so hard about using member and memberOf properties to handle any Organization heirarchy ?  Just treat the Consortium as an Membership Organization.

Is it that the word Organization is to broad and you want to know that it is an also type of Consortium ? Then like Dan hints, just use additionalType for that.

Easy to me.
But if @RichardWallis really wants a Schema.org type for Consortium's and not have to use additionalType all the time, then +1 I guess.

**Comment by Dataliberate** [comment]
:-)

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by vholland** [comment]
@thadguidry We need a type to use, whether it is through MTE or additionalType.

**Comment by thadguidry** [comment]
@vholland That's fine... but I'm still going to treat a LibrarySystem as an Organization and just use additionalType: https://www.wikidata.org/wiki/Q28324850  Simpler to deal with, and Consortium gets a bit confusing outside of English languages.

**Comment by danbri** [comment]
Are there any cases in which a single Library (or parent org) has multiple distinct parent orgs in one of these hierarchies? Can a Library or its parent be part of multiple "systems"?

**Comment by thadguidry** [comment]
For USA, your look at the the PLS survey... the docs are here:
https://www.imls.gov/sites/default/files/fy2013_pls_data_file_documentation.pdf
pages 29 and 30 specifically the codes 201, 202, 209, 210 for example...

LD—Library District. A library district is a local entity other
than a county, municipality, township, or school district that is
authorized by state law to establish and operate a public
library as defined by FSCS. It has sufficient administrative and
fiscal autonomy to qualify as a separate government. Fiscal
autonomy requires support from local taxation dedicated to
library purposes (e.g., a library tax).

MJ—Multi-jurisdictional. An entity operated jointly by two or
more units of local government under an intergovernmental
agreement which creates a jointly appointed board or similar
means of joint governance; to be distinguished from a library
which contracts to serve other jurisdictions and from special
library districts.

Data is here:  https://data.imls.gov/Public-Libraries-Survey/Main-Libraries-Branches-and-Bookmobiles-FY-1992-20/rbw5-brn5/data

Having said that.... YES sometimes... a small city college/vocactional library that also serves as the towns main library.  and a few other such cases within Native American tribal colleges, etc.

**Comment by RichardWallis** [comment]
Good background @thadguidry.

I would also add that in addition to what you describe there are multi-directional relationships.  

For example a college library may be in a 'library system'  (_a difficult term for me as that is what the software that is used to operate a library is called_) with other colleges associated with a university.  Via that university it may well be part of a consortium of academic libraries sharing cataloguing resources. Whilst also being in a local loaning consortium with its local city library [system] enabling  each other's patrons to loan books from both libraries.

**Comment by vholland** [comment]
Per @thadguidry's data set. There is an entry for the Cambridge Public Library, which is really for the public library system (for lack of a better word) in Cambridge, MA.

The Cambridge Public Library is part of the Minuteman Library Network, a consortium of libraries in eastern Massachusetts.

It would be nice if the Cambridge Public Library system could mark up its page and identify itself as a system without also having to list member libraries.

It would be nice if the Minuteman Library Network could mark up its page and identify itself as a consortium without having to list members.

Even if they did include members, it would be difficult to infer system vs consortium, so I go back to my original proposal for a ```LibrarySystem``` type and also a ```Consortium``` type.

**Comment by RichardWallis** [comment]
As per previous comments I think the current _Organization_ (utilising _parentOrganization_, _subOrganization_, _member_, _memberOf_) plus a new _Consortium_ subtype is sufficient to cover this use case.  

I believe a _LibrarySystem_  type would cause confusion: as to what it means and when to apply it; how a library system differs from an organisation of libraries; plus, as I pointed out earlier, the term means something totally different (a software system) in different geographies.  This leads me to believe that it would be applied inconsistently if at all.

**Comment by thadguidry** [comment]
@RichardWallis (I worked for Nicholson Memorial Library System for 7 years in Garland Texas.)
and what minimal property did we choose to put under Consortium ? :)

**Comment by erimille** [comment]
@thadguidry, your [Nicholson Memorial Library System](http://nicholsonmls.library.link/) is currently described in a similar (Library parentOrganization Organization) manner as your previous comment. But feel free to suggest more properties ;) 

@danbri, echo'ing the point made by others, the short answer is 'yes' Libraries can most certainly be part of multiple "systems".

**Comment by danbri** [comment]
Let's be clear then if we want to avoid mixing up memberships of different systems. I'm not sure it can be done with simple unqualified hierarchy - probably needs an explicit link too.

**Comment by RichardWallis** [comment]
That's where _Consortium_ comes in I think.

A single simple hierarchy for Organisational relationships whilst being a member of zero or many consortial groups (or multi-organisational groupings)?

**Comment by vholland** [comment]
I am happy to use something rather than ```LibrarySystem``` if we can think of a name. I am looking for a type which allows someone to know whether the Cambridge Public Library is referring to a single library or a larger grouping of libraries. Inferring based on the presence of parentOrganization or subOrganization is error prone. Authors often leave these properties out.

**Comment by RichardWallis** [comment]
@vholland LibraryGroup and LibraryService come to mind.

However I am intrigued at the use case here.  What value will this extra level of information add when someone is looking for a library.  Equally how much more reliable will authors be defining a Library-System/Group/Service than a Library and its parent/subOrganizations?

**Comment by vholland** [comment]
As an example, my local public library is part of the Minuteman Library Network (MLN) consortium. When I reserve a book, it may tell me it is available in "Cambridge", but I have no idea if they mean the main library or one of the branches. I click reserve and a day or so later, get an email message telling me I can pick up at my local library. Most of the pages do not list their members and for the most part, as a user, I do not care. It seems silly to make them list members in their metadata when the pages don't relate to the member organizations.

Similarly, some of the pages on the Cambridge Public Library website relate to the parent organization and some relate to the main library. It would be nice if they could differentiate which is which without having to add metadata for branches to every page related to the overarching organization.

**Comment by RichardWallis** [comment]
@vholland Minuteman makes an excellent example of the need for a Consortium type - several organisations woking together with no other connection other than being in a consortium.

Having been around libraries, and the systems they use, a while I can think of several reasons why the scenario you describe exists, most of them are nothing to do with the lack of appropriate web markup capabilities.

- In many library organisations there is little connection between those that manage the organisation web site and those manage the library's Integrated Library System (ILS) software that tracks the location of items, identifies the holding branches, and powers the search interface.  

- Many ILSs do not integrate well with external systems so it is quite possible that the "we have that book but cannot tell you where it is" answer, to a query from another library in the consortium, is best efforts.

- Equally, even within a group of libraries managed by the same ILS, if you reserve an item not in your local branch, it will not tell you where it is going to get the item from.

- ILS's commonly only utilise arcane (when compared with Web APIs) [library world specific APIs](https://en.wikipedia.org/wiki/Z39.50) to provide limited access to the data they hold.  Also many do not provide access to the user search interface to embed Schema.org and don't allow search engine crawler access to the UI as it kills performance.   _It has been one of my missions over the last decade or so, to change attitudes and systems to work around that last one_.

Because of the above I am of the opinion that even if we introduced what you are proposing there would be very few implementations.

**Comment by vholland** [comment]
@RichardWallis I think we are talking past one another. I don't imagine they would generate the markup from their ILS. Rather I expect they would use these types on public pages.

**Comment by RichardWallis** [comment]
@vholland "I think we are talking past one another" -  now that has never occurred before. ;-)

Taking from your scenario: _When I reserve a book, it may tell me it is available in "Cambridge", but I have no idea if they mean the main library or one of the branches._...

Regardless of if the markup to answer your question is on the public pages generated by the ILS, or on the public pages generated by the library organisation, it would have been sourced from the ILS.

BTW.  Most of the search, reservation, and other pages to do with the items in a library and their availability are normally generated by the Library's ILS.    The Web presence, usually generated by the libraries 'web team' are usually constrained to location, image of the building, events, and a link to the ILS.

**Comment by thadguidry** [comment]
@vholland @RichardWallis Why don't we just reach out to the big 3 ILS vendors in the USA and ask them what and how they currently expose parent, child, consortium, etc...when it comes to borrowing locations ?

http://www.sirsidynix.com/
https://evergreen-ils.org/
http://www.koha.org/

I've reached out to all of them just now to participate in this discussion and answer how they expose or expect to expose borrowing locations, consortiums, etc.

**Comment by erimille** [comment]
@thadguidry - SD, Innovative and EBSCO are doing just this for Public Libraries via The [Library.Link ](http://library.link/)Network. In 2016 we have collectively published over 1000+ Library Systems and over 2000+ physical locations. 

The vocabulary for describing Organizations and Libraries we've been collectively using is [mentioned above](https://github.com/schemaorg/schemaorg/issues/1495#issuecomment-275239422). The [consortium suggestion](https://github.com/schemaorg/schemaorg/issues/1495#issuecomment-277111893) would address the further non-hierarchical membership grouping that is (at a high level) our reality. 

In our hundreds of discussions / interviews, etc. asking questions related to "libraries near me" is about as detailed as patrons get and our goal is to make the data available that helps answer these sorts of questions.

**Comment by thadguidry** [comment]
@erimille So you yourself have immediate need to expose both LibrarySystem and Consortium ?

**Comment by chrissharp123** [comment]
@thadguidry I administer the Georgia PINES Library consortium, which is a state-agency-run union catalog for 53 public library systems across Georgia.  Our agency originally developed the Evergreen ILS specifically for our consortium, and many of its organizational assumptions were created to accommodate our structure.  At the top of the organizational tree is "PINES" - the **consortium**.  Under that organizational umbrella are the library **systems**, which are either regional or county-run multi-unit organizations.  Under each system, the child units are known within Evergreen as **branches**, or "Library" in the sense that @dbs described it.  Evergreen also accounts for **sub-libraries** and **bookmobile** units, which would theoretically exist under branches, but they are not in use within PINES - we just have the three-tiered structure.

As far as our users go, they see PINES as the main unit they interact with, and they think of their local libraries as "PINES libraries" - this is probably different than other consortial models where end users may not even realize their local libraries belong to a larger unit.  Our end users are also aware of the regional or county systems to which their libraries belong to.  The reason I'm putting a fine point on this is that I think the vocabulary should accommodate all three levels, at least in our case.

I hope that's helpful.

**Comment by RichardWallis** [comment]
Thanks @erimille and @chrissharp123 ! - that has saved me a whole load of typing something similar.

**Comment by thadguidry** [comment]
@chrisssharp123 give me some good properties you would use under the proposed Consortium, and LibrarySystem type and I'll plus 1 the hell out of them if they make sense.

**Comment by phasefx** [comment]
@thadguidry I don't know enough about schema.org to weigh in directly, but I can tell you some how an Evergreen instance models its libraries if that would help.  The main mechanism is an org tree or hierarchy, where a given org unit has an org type (which can provide a label such as Branch, System, Bookmobile, Department, etc., as well as define whether an associated org unit can directly have users and/or items) and a parent org unit field.  Orgs can be very abstract or very specific.  A less-used mechanism allows arbitrary groupings of org units out of the org tree.  Finally, libraries can present completely different "org trees" to patrons that can intermix org units and a different concept, shelving location groups, and there is also a mechanism for hiding parts of the org hierarchy from certain users.  Consortia using Evergreen tend to follow the 3-tier layout that Chris mentioned for PINES, but other hierarchies are possible.

**Comment by dbs** [comment]
I've attempted to avoid rejoining this conversation because I agree with @RichardWallis recent points, having also been an advocate for schema.org adoption by libraries. I'll note a few things:

a) The Library.Link network approach creates a shadow subset of web pages to parallel the libraries' human-oriented web and catalogue pages--an approach which (apart from https://www.ampproject.org/ - and even that at least provides bi-directional linkage between the full and AMP pages via `@rel` properties) has been strongly discouraged by search engines as an approach to SEO.

b) As @chrissharp123 noted, I already said what we currently do in Evergreen. If a generic type like `Consortium` is created, we could easily generate an MTE for the corresponding entries in the hierarchy based on criteria like "has children Library instances". And we could add more specific properties in Evergreen to support more fine-grained distinctions for each entry in the hierarchy, if there was an actual need.

c) Despite advocacy efforts such as "White Hat Search Engine Optimization (SEO): Structured Web Data for Libraries" (https://journal.lib.uoguelph.ca/index.php/perj/article/view/3328) and corresponding conference presentations, the actual adoption of schema.org markup in human-oriented library web pages is dismal. My last analysis of the known home pages for Canadian libraries in all sectors  (https://dialled.ca/) showed that in September 2016 (time for an update), 5 libraries out of 4,801 identified themselves using http://schema.org/Library, and only 215 even used http://schema.org/name, usually as a result of the defaults in their CMS.

d) Having published all of the available metadata, physical locations, and availability and terms of library items for a library of over a million items with a corresponding sitemap (available out of the box for all instances of Evergreen), I have seen an (at the time paid) instance of Google Custom Search Engine decide to stop indexing those pages *at all*, rather than, say, happily indexing them and surfacing them in search results in geographic proximity to the searcher, or in relation to their profile's  affiliation with a given institution. This does not encourage the effort that is required to adopt rich, fine-grained vocabulary, even as a default in existing library systems.

So colour me cynical that human-oriented library web pages will adopt any more specific library vocabulary that we might propose here. Without any compelling reasons for doing so, beyond the happy theoretical advantages that have been bandied about for years (including by me), it's going to be hard to convince people to add even *more* complicated expressions to their markup.

**Comment by RichardWallis** [comment]
@dbs  +1

On the issue of Consortium - it was not part of the original request here.  It was suggested by me in response to some of the scenarios put forward to respond to a need for a way to describe a grouping of organizations (_A consortium is an association of two or more individuals, companies, organizations or governments (or any combination of these entities) with the objective of participating in a common activity or pooling their resources for achieving a common goal._).

I don't believe the library domain alone provides sufficient need to introduce a new Consortium type, but it does have much broader applicability than that.

As to @thadguidry's question about what properties would be used from Consortium - most any that it inherits from Organization - or as @dbs suggests use it as an MTE.

**Comment by erimille** [comment]
@dbs the reason Library.LInk is publishing (on behalf of the Library) the raw data pages independent of human-oriented ones is to address all of the reasons you cite for being cynical that this will never happen by Libraries. And to further address the reality that many libraries and vendors simply can't handle high volume consumption.

But regardless of philosophy or business model, I think we're in agreement (regardless of how its done) that the current schema.org vocab (Organization and Library) are adequate. Yes? 

Again, I'd be open to supporting Consortium but again, flagging the desire to see a use case.

**Comment by thadguidry** [comment]
Create the 2 types "Consortium" and "LibrarySystem" and let's freaking close this issue and move on.
If they get used, Great.  If not, still freakin Great.
We all have better things to do and I'm moving on from this issue now.
Thanks all.

**Comment by RichardWallis** [comment]
Create "Consortium" +1
Create "LibrarySystem" (as long as the description is clear as to it being what @vholland considers to be a LibrarySystem - not a software system for running a library) +1
Do _something_  and move on +2

**Comment by danbri** [comment]
Ok, I'm +1 for adding both Consortium and LibrarySystem, but we'll also need example markup in at least JSON-LD. Any candidate text?

**Comment by danbri** [comment]
I took a run at defining these, both going into Pending. I think we are close here, so I'd like to focus discussion on LibrarySystem + Consortium. As @RichardWallis points out, the Consortium type needs attention beyond this library-specific discussion, but seems useful.

**Comment by danbri** [comment]
Draft for review (still need examples) 

 * http://pending.webschemas.org/LibrarySystem
 * http://pending.webschemas.org/Consortium

(site is sluggish currently, I think because it was just restarted... @RichardWallis ?)

**Comment by RichardWallis** [comment]
Created examples for _Consortium_ in PR #1539.

Someone want to have a go at some for _LibrarySystem_

**Comment by danbri** [comment]
We just published v3.2 of schema.org, it has: http://pending.schema.org/LibrarySystem and http://pending.schema.org/Consortium but no explicit connection between them. Hopefully that is a basic enough building block for everyone.

**Comment by vholland** [comment]
I'll close this and we can create other issues for other enhancements.
