### ISSUE TITLE
Expanding on property award for CreativeWork

### ISSUE THREAD

**Issue by mrshannonyoung** [schemaorg/schemaorg#1504]
It feels for [creative works](CreativeWork) in general `award` only seems to have scope for [awards](https://schema.org/award) won, I think there is potential for a property like `nominatedFor`, which can list out nominations?

Going further there are [organisations](https://schema.org/Organization) based on the whole nomination/winning process:
- TV/Film award ceremonies (Oscars etc)
- Creative works that are nominated/win prestigious awards such as [D&AD](https://www.dandad.org/)

This can be expanded for [Person](https://schema.org/Person) also:
- Person (Leonardo DiCaprio - finally got an Oscar after countless **nominations**)

Just feels like a missing piece of great information.

**Comment by thadguidry** [comment]
There's a lot to say about any particular Award, like when it was first awarded, if its a physical award, who designed it, what materials it is made of, the presentation ceremony it is attributed with (Noble Prize ceremony), etc.

So, I think we should make the award property take a new "Award" type so that we can have more fun with Awards themselves, physical or manifest.
For instance, the [Stanley Cup](https://en.wikipedia.org/wiki/Stanley_Cup) is a physical "trophy" that is awarded, but also has a "current holder" like the Pittsburgh Penguins.  

And Wikidata has a new property for ["trophy awarded"](https://www.wikidata.org/wiki/Property:P4622)

**Comment by vholland** [comment]
There was a brief discussion of this in issue #668 . Awards get complicated fast, so it would be worth creating some use cases and going from there.

**Comment by Aaranged** [comment]
FWIW I also did some modelling around a Prize type [here](https://docs.google.com/document/d/1QMKM-8eZk7Jme6RvEeAV-vLtBWpg1Uly-0uiwmaVAlc/edit#heading=h.m71c4xdlvfuq).  Awards do indeed get complicated fast. :)

**Comment by nsputnik** [comment]
This is something that could eventually be displayed as Rich Results similar to the way that review ratings are so maybe it could be thought of this way, to aid searchers on picking the best page results.  Or is that the assumption with all schema.org proposals?
