### ISSUE TITLE
How to extend the property of existing "type" or "class"

### ISSUE THREAD

**Issue by HimanshuN** [schemaorg/schemaorg#1505]
Can anyone tell me how to create new property of existing type. For example, there is a type named "Physician" and I want to add a property name "Experience". I am not finding the right document or procedure to do this.
I read somewhere that we can also create our own schema from scratch, new types and its properties and that is called "Schema Extensions". But not getting right procedure to implement it.

Please revert back if anyone is having solution, I am very new to it.

Thanks and regards,
Himanshu

**Comment by thadguidry** [comment]
@HimanshuN Depending on your needs, you might not need to extend at all.  Can you give an example of what you are thinking about and how you would fill in for "Experience" for an example doctor called John Smith M.D. ?  experience = ???

**Comment by mfhepp** [comment]
There are a few options that are underutilized:

1. You can put descriptions in the http://schema.org/description property. A consuming client (e.g. major search engine) can use NLP to try to understand that, and this is much easier as compared to text scattered around the HTML tree, because the consuming client knows this is the description.

2. For products and places, you can use http://schema.org/additionalProperty. This is actually the most powerful way for adding properties that do not yet have a dedicated element in schema.org. See the many examples at 

    http://schema.org/additionalProperty#examples

Best
Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by HimanshuN** [comment]
@thadguidry I was thinking to fill it with number of years he has worked or "less than a year" in case of fresher or having experience of less than one year. Moreover, I want to learn the procedure how can I make custom class or type in schema.org, one should know if he is working with schema.org

Thanks

**Comment by HimanshuN** [comment]
Can anyone help me to know how can I create external extension for my website. Unable to understand the procedure

**Comment by RichardWallis** [comment]
@HimanshuN If you want to experiment with producing a potential extension Schema.org you may find helpful my "_schema.org in practice_" articles: [part 1](http://dataliberate.com/2016/02/10/evolving-schema-org-in-practice-pt1-the-bits-and-pieces/), [2](http://dataliberate.com/2016/02/25/evolving-schema-org-in-practice-pt2-working-within-the-vocabulary/), and [3](http://dataliberate.com/2016/03/01/evolving-schema-org-in-practice-pt3-choosing-where-to-extend/).
