### ISSUE TITLE
RangeIncludes

### ISSUE THREAD

**Issue by ekkis** [schemaorg/schemaorg#1532]
one other question: I often see this in definitions:

 ```
        {
          "@id": "http://schema.org/prescriptionStatus",
          "http://schema.org/rangeIncludes": [
            {
              "@id": "http://schema.org/DrugPrescriptionStatus"
            },
            {
              "@id": "http://schema.org/Text"
            }
          ],
        },
 ``` 

so it's clear that a prescription status can be a *DrugPrescriptionStatus* or a text field.  but why not define it simply as a *DrugPrescriptionStatus* and define that as a text field?

if we look at drug prescription status, it's of type 'rdfs:Class' but derives from MedicalEnumeration, whose type is 'rdfs:Class'.  so ultimately we don't know what the basic type for this is... shouldn't we be  narrowing down definitions ultimately to basic types e.g. string, number, date, etc?

**Comment by RichardWallis** [comment]
Hi @ekkis 

It might be worth you reading the [Data Model](http://schema.org/docs/datamodel.html) documentation page, at least as far down as the mention of Postel's Law as it fills in some of the background as to why some of the patterns in the Schema.org vocabulary seem a little different to those you may find in a traditional ontology.

**Comment by ekkis** [comment]
thank you.  I did read through that page but in re-reading it (and now that I have access to support), I'm wondering: why was the range defined at the property level? it seems to me that a property would have one or more domains, which are types and would have a range of their own, in other words, ranges should be properly a part of the type, not the property

the current design facilitates issues like defining a domain without a matching range or declaring a range for which there is no domain, no?

**Comment by Dataliberate** [comment]
> the current design facilitates issues like defining a domain without a matching range or declaring a range for which there is no domain..

Within a single definition file, from which the Schema.org site and outputs are derived, yes that is true.  However the final definitions are derived from an aggregate of definition files, for extensions etc.  Conformance checks are applied as the site is loaded to detect anomalies such as you describe.

This approach facilitates the enhancement of domain and range values that are only applicable when viewing extensions.  Although not perfect, this approach has served us well as a compromise between flexibility and rigour so far.

**Comment by ekkis** [comment]
it occurs to me that perhaps I'm getting my feet tangled up in the nomenclature.  when I think of domain and range I think of a function where the domain constrains the types of inputs to the function and the range describes the function outputs e.g. for x = y / 2, if the domain (y) is the integer space, then the range (x) would be the real numbers

I think in this case the terms means something else altogether.  domain here seems to indicate the types that use a given property and range indicates the types of values (because rdf:Property is too abstract) the property can hold.  am I getting this right?

**Comment by Dataliberate** [comment]
>it occurs to me that perhaps I'm getting my feet tangled up in the nomenclature.

I think it is more we are talking past each other because of the nomenclature.

With Schema.org we are not talking about an ontology to constrain how a data model is defined, we are talking about a vocabulary to identify how an Thing (instance of a Schema Type) can be described or marked-up on the web.  The difference in implementation is subtle but important.

An obvious symptom of this being domainIncludes vs domain and rangeIncludes vs range, also we reference Types not Classes.

domainIncludes identifies which Types you may use a property with, rangeIncludes identifying the expected Types you can use as values for a property.  A sub-type (defined internally using subclassOf) indicating that a Type inherits the available properties from a its parent(s).

By analysing the internal structures as you are, and there is nothing wrong in that, you are exposing more clearly than for most that interact with Schema.org some of these differences.  

Also when you are working within the vocabulary to identify use cases and how it handles them, you may find areas other than the health-lifesci extension provide more everyday examples with broader understanding in the community.  The health-lifesc extension and it's medical based Types & properties are somewhat involved.
