### ISSUE TITLE
browser support for videogames schema type

### ISSUE THREAD

**Issue by EddieOne** [schemaorg/schemaorg#1542]
Hi, I work for Y8 and we do web games. We work around problems like Chrome blocking Unity WebPlayer, WebPlayer working better on FireFox compared to WebGL, no Flash support on mobile. In some cases we transcompile games into more than one format. Say Flash works better on old machines but html5 works were Flash doesn't. It would be helpful for search engines to know about the filtering we do for users.

The current setup almost seems to assume a videogame is something you put into a console or install locally. However, web games have been around for a long time. I'm interested in hearing from others about this topic. Plugins are on the decline, so this filtering has become much more important recently.

**Comment by thadguidry** [comment]
Hi @EddieOne .

Yeah, this is addressed in Wikidata already.

The idea was a "runs on" / "depends on software X"

1. **depends on software** https://www.wikidata.org/wiki/Property:P1547
2. a Platform https://www.wikidata.org/wiki/Property:P400
3. an Operating System https://www.wikidata.org/wiki/Property:P306
4. a software engine https://www.wikidata.org/wiki/Property:P408
4. a programming language https://www.wikidata.org/wiki/Property:P277

My hunch is that your probably looking for a property in Schema.org that is the same as # 1 ?

( HINT: You probably want to at least begin using some markup on your individual pages such as https://search.google.com/structured-data/testing-tool#url=http%3A%2F%2Fwww.y8.com%2Ftags%2FHTML5 )

Here's a list of what I see your talking about on your site:

* http://www.y8.com/tags/HTML5
* http://www.y8.com/tags/Flash
* http://www.y8.com/tags/unity3d
* http://www.y8.com/tags/webgl
* http://www.y8.com/tags/online  ?????  (not sure the benefit on this one)
* http://www.y8.com/tags/Android_game
* http://www.y8.com/tags/touchscreen  <- interesting one, depends on Peripheral Type = Input : touchscreen

Any others I missed from your site ?  

So those except "online" and "touchscreen" I would definitely type as a Platform for the sake of argument and where the Property on a game would have "depends on software X to run" which expects a type of Platform from your list above.

**Comment by EddieOne** [comment]
Hi @thadguidry 

Yeah number one is the one I want. I was searching for something like that on Schema.org. However, your suggestion of using operating system and platform would work well.

We do filtering based on operating system already, so I have already begun adding meta data on game pages about supported systems. For example, some Unity WebGL games don't play well on 32-bit systems. It gets really granular and we don't have tags setup for all the possible technologies.

Thanks for the hint about the tags page, I didn't think of using that or integrating meta data there. It makes sense to make this info visible to players as well, tags is a good option for that. About the online category, good eye! Looks like you found the poorly label multiplayer tag. We have since changed the definition of multiplayer to 'online' before it was 2+ player on a single computer. A lot of work to do. 😁

Thanks for the feedback and also showing me Wikidata. Any time I find a huge data source, it really gets the gears turning about the possibilities with processing such information!

**Comment by thadguidry** [comment]
@EddieOne  
So... if you really need # 1... looks like we already have that with the property called [softwareRequirements](http://schema.org/VideoGame) and available for any VideoGame since its already a subType of [SoftwareApplication](http://schema.org/SoftwareApplication)

[softwareRequirements](http://schema.org/VideoGame) 
"Component dependency requirements for application. This includes **runtime environments** and shared libraries that are not included in the application distribution package, but required to run the application (Examples: DirectX, Java or .NET runtime). Supersedes requirements."

 Or you can optionally treat your # 1 usecase and use [gamePlatform](http://schema.org/gamePlatform) property we already have on [VideoGame](http://schema.org/VideoGame) ?

Sometimes it might be a gamePlatform ... but if the usecase is always about REQUIRES a type of gamePlatform .. then you might be better off just using softwareRequirements.  Either one can take Text or URL and I'd encourage the use of a Wikidata URL pointing to the entity your describing like HTML5 or Android, etc.

Can we close this issue now ?  Ya good ?

**Comment by EddieOne** [comment]
Yeah I would say plenty of options, thanks for you help!
