### ISSUE TITLE
Extended use for property employee

### ISSUE THREAD

**Issue by sascha-hendel** [schemaorg/schemaorg#1555]
It should be possible to use property "employee" on  type "person", not only "organization" and same for reverse property "worksFor".
(My usecase: architects, which work as employees for other (famous) architects. The name of the relating office (= organization) is often nearly unknown, because Architecture is more targeted to persons than to orgnizations)

**Comment by chaals** [comment]
+1 There are lots of other examples of people who work for other *people* instead of organisations - and cases like movies where there might be a formal corporate structure but it isn't relevant in understanding  how often some actor worked with a particular director, hair-stylist or wardrobe malfunction developer…

**Comment by Dataliberate** [comment]
Makes sense.

At the same time you would want to expand the range of ‘worksFor’ to
include ‘Person’ and tweak the descriptions of both.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by vholland** [comment]
+1 to updating both properties.

**Comment by sascha-hendel** [comment]
Any news on that?

**Comment by sascha-hendel** [comment]
Any news on that?
Property "affiliation" is another candidate, which should be expanded to allow persons!
