### ISSUE TITLE
webschemas.org/ sitemap.xml is listing schema.org URLs

### ISSUE THREAD

**Issue by AymenLoukil** [schemaorg/schemaorg#1573]
The http://webschemas.org/ website is showing http://schema.org URLs. The base root domain should be variable and not static with value schema.org. Sitemap.xml is for listing a website internal URLs and not external ones.

**Comment by RichardWallis** [comment]
As webschema.org is the pre-release/development view of upcoming versions of Schema.org we do not want it to be crawled by search engines as it could cause potential confusion.

To that end, it does not have a /sitemaps.xml file, and the actual sitemap (docs/sitemap.xml) is not referenced in the robots.txt file which also contains a do not crawl instruction ('''Disallow: /''') for the whole site.

The docs/sitemap.xml file is still included on the site so that what will be on Schema.org in the next release can be previewed.  When it is released the Schema.org robots.txt file references it ('''Sitemap: http://schema.org/docs/sitemap.xml''') so that the crawlers can find it.

**Comment by AymenLoukil** [comment]
But webschema.org is indexed : [https://www.google.com/search?q=site%3Awebschemas.org&oq=site%3Awebschemas.org&aqs=chrome..69i57j69i58.840j0j4&sourceid=chrome&ie=UTF-8](https://www.google.com/search?q=site%3Awebschemas.org&oq=site%3Awebschemas.org&aqs=chrome..69i57j69i58.840j0j4&sourceid=chrome&ie=UTF-8)

And it is a duplicate of schema.org. The pre-release view should implement noindex meta robots tags and be sure that it is not indexed on search engines (Google and others).

I believe that is a real issue and need to be open @RichardWallis  :)

**Comment by RichardWallis** [comment]
Replaced by #1574
