### ISSUE TITLE
Add a new type CriticReview as a more specific type of Review

### ISSUE THREAD

**Issue by gmackenz** [schemaorg/schemaorg#1589]
Many websites (e.g. EazyDiner, Dine Out, Ou Bruncher, etc.) provide markups for both critic reviews (reviews written by professional critics) and user reviews using schema.org/Review. As schema.org/Review does not provide a clear distinction between critic reviews and user reviews at this time. It would be very useful to be able to differentiate which reviews are by critics.

I propose the adding  CriticReview as a more specific of Review.

Example markup:
```json-ld
{  
    "@context":"http://schema.org/",
    "@type":"CriticReview",
    "itemReviewed":{  
        "@type":"Restaurant",
        "image":"http://www.example.com/seafood-restaurant.jpg",
        "name":"Legal Seafood"
    },
    "reviewRating":{  
        "@type":"Rating",
        "ratingValue":"4"
    },
    "name":"A good seafood place.",
     "author":{  
          "@type":"Person",
          "name":"Bob Smith"
     },
    "reviewBody":"The seafood is great.",
    "publisher":{  
        "@type":"Organization",
        "name":"Washington Times"
     }
}
```

**Comment by danbri** [comment]
This seems a worthwhile distinction to articulate, but would you care to also propose a definition for "CriticReview" too? Without a definition I fear we'll just see everyone start using CriticReview because it sounds like "an important review".

The definition ought to make fairly clear who counts as a "critic". You mention "professional", which is terminology we avoided for ClaimReview since you don't need to be paid to be a fact checker to check facts. Similarly, you might be a well regarded film, TV or food critic on the path to professional recognition e.g. via an independent popular blog.  We can say "professional" but it should be softened to allow bloggers etc and not imply that a certain form of employment or business model is necessarily required.

Perhaps something like: "A 'CriticReview' is a review written or published by a source that is specifically known for its reviewing activities. These can include newspaper columns, travel and food guides, TV and radio shows, blogs and other independent Web sites. CriticReviews are typically more in-depth and professionally written. For simpler user/visitor/viewer/customer reviews, it is more appropriate to use the Review supertype.

Note that this is inconsistent with the example whose body ("The seafood is great.") doesn't meet the definition I sketch above. Perhaps we should look at distinguishing review summaries / excerpts from full article-length reviews, or just make clear that the reviewBody is simplified for sake of clear examples? Long form reviews generally require real formatting (links, paragraphs and other markup), for which both Microdata and JSON-LD property values are poorly suited, and even in RDFa it's painful.

**Comment by danbri** [comment]
Some example scope questions -

* Is http://www.aintitcool.com/node/77598 a CriticReview? Why? How could you tell objectively? 
* Is http://thelambshankredemption.blogspot.hr/2014/07/waitrose-wine-challenge.html ?
* Is http://www.capalert.com/capreports/2fast2furious.htm ?
* Is https://david-smith.org/blog/2016/04/04/a-nerds-review-of-the-tesla-model-s/ ?
* http://www.telegraph.co.uk/cars/tesla/tesla-model-s-review/ ?
* https://forums.tesla.com/forum/forums/model-s-mans-review-x ?

**Comment by thadguidry** [comment]
@danbri @gmackenz I like the wording in Dan's example description.  However I think "professional" should not necessarily be softened.  The word "professional" can still allow bloggers.  Its just alluding to bloggers that are professional in their reviews and criticisms.  Most folks understand the difference in quality between my review blog and Harry Knowles' blog.  So saying "professional" can mean paid occupation, but it can also mean respected, recognized, etc.  So if you still want to avoid "professional" maybe "respected or recognized critic...blah blah".

Metacritic.com says this "Metacritic's proprietary Metascore distills the opinions of the most respected critics writing online and in print to a single number."

And they also say this:  "Several other websites that provide links to movie reviews have weighed the quantity vs. quality issue and come out in favor of quantity. These sites typically include links to as many reviews as there are available on the net. And lately, with every Joe Schmo posting a movie review both before and after movie releases, there are quite a few reviews for each movie (we're talking 100's of reviews for the more popular titles). True, some of these Joe Schmos--or at least the Harry Knowles--do have quality sites with useful reviews and information. But the quality of many is inconsistent at best. In addition, there is such a thing as too much information, and statistically, once we include a certain number of reviews in our calculations, adding additional reviews will not change the overall METASCORE much in one direction or another."

**Comment by gmackenz** [comment]
How about with some slight tweaks of Dan and Thad's helpful feedback.

"A '[CriticReview](http://pending.webschemas.org/CriticReview)' is a more specialized form of [Review](http://schema.org/Review) written or published by a source that is recognized for its reviewing activities. These can include online columns, travel and food guides, TV and radio shows, blogs and other independent Web sites. CriticReviews are typically more in-depth and professionally written.  For simpler, causally written user/visitor/viewer/customer reviews, it is more appropriate to use the Review supertype. Review aggregator sites such as Metacritic already separate out the site's user reviews from selected critic reviews that originate from third-party sources."

**Comment by danbri** [comment]
s/causally written/casually written/ otherwise LGTM

FYI I've been discussing some possible improvements around NewsArticle with the thetrustproject.org team, see #1525. They had also suggested some kind of "review" subtype or sibling type around the News area, to distinguish "news proper" from reviews (and other related kinds of article that news orgs publish e.g. sponsored content, satire, analysis, opinion, background reading etc.). It looks from a first pass that CriticReview may already meet that need. I'd like to bounce the definition about around a few News-related folk to see how it looks.

My only other concern is that by adding this we create a kind of lumpy expressivity, in which the only way to say that a review is an end-user review is by not saying it is a critic review. If we can think of a viable name (UserReview?) perhaps we should add that at the same time. I think it would be reasonable for its definition to refer to CriticReview, e.g. "By contrast with a CriticReview, a UserReview is a simple review of something provided by an end-user, viewer, visitor or customer rather than from a source devoted to reviewing.". There's naturally some grey area in the middle I guess.

**Comment by danbri** [comment]
ping @chaals @nicolastorzec @scor @tmarshbing

**Comment by nicolastorzec** [comment]
+1

The definition works for me.

Regarding user reviews versus critic reviews, I'd rather explicitly add a UserReview class rather than rely on Closed World assumptions and fall back logic.

My reasoning below:
- It's seems more straightforward for users, even though they may disagree on what qualifies as a CriticReview, or both classes may eventually look alike if they have the exact same properties.
- UserReview and CriticReview are probably not the only types of review in the World (i.e. a review that is not a CriticReview may not always be a UserReview), and we may want to refine review types further later (i.e. to distinguish paid reviews, etc.)

**Comment by danbri** [comment]
Ok, I'm coding this up to give a concrete review target, in a branch for now as it fits alongside some NewsArticle improvements we're exploring in #1525.

**Comment by danbri** [comment]
Please take a look,

* http://pending.webschemas.org/CriticReview
* http://pending.webschemas.org/UserReview

**Comment by nicolastorzec** [comment]
Works for me.

**Comment by rstar333501** [comment]
Please take a look on these websites
http://www.sscguide.in/
http://www.cbsetyari.com/

**Comment by chaals** [comment]
I'm not really happy about this.

First, anyone can put `CriticReview`s in their content to prove they are recognised as reviewers, which seems backward. 

Second, "everyone's a critic". If you want to note that the author is a widely read and respected critic of e.g. Afghan bread shops, that sounds like something you should describe about the author (and there's a vector for fake news...), or in reviews of the review. A serious high-quality review can be performed by someone who has never produced one before - as is the case for the first review every critic publishes.

**Comment by ebunton** [comment]
I agree with @chaals. CriticReview isn't sufficiently differentiated from Review in my eyes to warrant a different entity type being introduced. 

The author/creator/publisher may have a widely (or not so widely)-recognised "critic" status, and confer that importance to the review.

> I'm not really happy about this.
> 
> First, anyone can put `CriticReview`s in their content to prove they are recognised as reviewers, which seems backward.
> 
> Second, "everyone's a critic". If you want to note that the author is a widely read and respected critic of e.g. Afghan bread shops, that sounds like something you should describe about the author (and there's a vector for fake news...), or in reviews of the review. A serious high-quality review can be performed by someone who has never produced one before - as is the case for the first review every critic publishes.

**Comment by Prabodhan-P** [comment]
Looks Yandex don't allow itemReviewed types other than vehicle and organization. But throws error if I skip it. How can I define itemReviewed value for product reviews? Any idea?

**Comment by RichardWallis** [comment]
@Prabodhan-P The vocabulary definition indicates that [itemReviewed](https://schema.org/itemReviewed) can reference a _Thing_ and therefore any subtype of _Thing_.

If any consumer of data implements a more restrictive use, that is an issue to be discussed via their support channels.

**Comment by Prabodhan-P** [comment]
@RichardWallis I tried Thing and other subtypes though. Yandex does not support it. I chose to ignore it because Google shows it a perfect and valid schema code.
