### ISSUE TITLE
ItemAvailability availability enumeration missing OnBackorder / BackorderOnly

### ISSUE THREAD

**Issue by taur** [schemaorg/schemaorg#1632]
I find this lacking in the enumeration, could this be added or should one resonably use PreOrder for this eventhough it's not the same thing ?

**Comment by philsward** [comment]
I'll agree with this request.  OnBackorder would be the ideal enumeration text IMO.

I have products that occasionally go on backorder.  Considering Google Merchant, it would keep us from having to hide or remove the product from Google Merchant.  From a search standpoint, it would show the search user that a product is on backorder instead of in-stock.  It sucks for the ecommerce site, but better UX overall for the end-user.
