### ISSUE TITLE
Google Structured Data Testing Tool erroneous error for ScholarlyArticle types

### ISSUE THREAD

**Issue by cboettig** [schemaorg/schemaorg#1656]
The [testing tool](https://search.google.com/structured-data/testing-tool) claims that ScholarlyArticle types need a `headline` property and `image` property to be valid.  

It's not entirely clear to me where required and optional types are being stated in the schema, since the schema.org documentation pages give no indication of what properties are and are not required (e.g. [ScholarlyArticle](http://schema.org/ScholarlyArticle)).  

I'm guessing there's some RDF somewhere that is indicating these are required, but would greatly appreciate someone pointing me to any documentation / easy way to discover what elements are and are not required.

Aside from this documentation issue, it seems incorrect to make these required elements for the `ScholarlyArticle` type.  Perhaps the requirements are simply inherited from `CreativeWork` (though plenty of `CreativeWork` types don't have an obvious `image` associated with them), and I have no idea what `headline` is meant to refer to  (potentially the title, though clearly `name` is the appropriate property there, as shown in the examples).  Note that none of the examples on http://schema.org/ScholarlyArticle  have the `image` or `headline` properties.

(Apologies if the Google Data Testing Tool implementation is orthogonal to the work here, I'm just assuming it's based on the schema.org ontology and not some additional arbitrary specification of what is and isn't required).

**Comment by unor** [comment]
> […] if the Google Data Testing Tool implementation is orthogonal to the work here […]

It is. Schema.org doesn’t require any properties.

When Google’s SDTT reports an error that certain properties are missing, it means that these properties are required to get one of Google’s search result features. Unfortunately the error message doesn’t make this clear, which often leads to confusion.

See also, about `headline`:

* [Schema.org 'name' and 'headline'](https://webmasters.stackexchange.com/q/98430/17633) (Webmasters Stack Exchange)
* [What is the name property in schema.org?](https://stackoverflow.com/q/38000771/1591669) (Stack Overflow)
* [AMP HTML format specification requires schema:headline instead of schema:name](https://github.com/ampproject/amphtml/issues/483) (ampproject/amphtml issue)

See also, about `image`:

* [schema.org microdata - image required for Article](https://stackoverflow.com/q/33069318/1591669) (Stack Overflow)
* [Schema.org NewsArticle: invalid value for logo property](https://stackoverflow.com/q/36135578/1591669) (Stack Overflow)
* [Use Schema.org for Article without image property?](https://stackoverflow.com/q/39033220/1591669) (Stack Overflow)

**Comment by cboettig** [comment]
:+1: 

@unor Thanks so much for setting me straight, this is super helpful. Wish they'd include this in the documentation of SDTT ;-).
