### ISSUE TITLE
Add "subjectOf" as a reverse for "about"

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#1670]
tl;dr: I propose adding http://schema.org/subjectOf as a named reverse property of http://schema.org/about. The domain would be http://schema.org/Thing and the range would be http://schema.org/CreativeWork and http://schema.org/Event.

There are lots of cases where the main subject of given page is a Person, Organization, etc and authors want to mention there is a work about that entity. It would be nice to have a "subjectOf" property to link to the work. (In JSON-LD, you can use @reverse, but there is no reverse mechanism in microdata yet.)

**Comment by jvandriel** [comment]
Well, there is a proposal for adding @itemprop-reverse to microdata. If that'd exist would you still want to add ```sujectOf```?

Maybe @danbri or @chaals can give us an update about the @itemprop-reverse proposal?

**Comment by vholland** [comment]
Honestly, yes. Most authors I know get confused using @reverse in JSON-LD and resort to naming the reverse in the @context, so why make them go through the extra work.

**Comment by jvandriel** [comment]
> _"I know get confused using @reverse in JSON-LD"_

I hear ya (really) and 'm not saying we shouldn't introduce _subjectOf_ but the difficulty I have with the above statement is that IMHO it's an excuse many use for not having to make the effort of explaining how @reverse works.

Most I introduce it to are confused at first due to being completely unaware of the existence of a reverse mechanism, though I haven't encountered anybody who wasn't able to grasp it - after some explanation. Maybe a bit more guidance and education could do the trick already (through some schema.org notes, or even by having the sponsors state something about it in their webmaster guidelines).

**Comment by danbri** [comment]
we should do both, imho.

**Comment by akuckartz** [comment]
If `subjectOf` is added then please include a comment to that and `about` in the reverse mechanism.

**Comment by vholland** [comment]
Added to pending.

**Comment by HughP** [comment]
Am I correct to notice that there subjectOf is a superset of http://schema.org/WriteAction? I am just noticing that there appears to be nohttp://schema.org/SpeakAction or http://schema.org/RecordAction for the audio modality corollary to the written modality described in http://schema.org/WriteAction. I'm not sure where to make that remark.

**Comment by RubyMoonProductionCo** [comment]
I personally think the domain should be Http:/19/GIG-thing.org

**Comment by RubyMoonProductionCo** [comment]
please and thank you  :)  if possible or at least let me contribute since I have very personal intimate connection to the Iot device.

**Comment by thadguidry** [comment]
@danbri Hmm, why does "about" still show in pending ?  Does [pending](https://pending.schema.org/) view not get cleaned up by some process or manual intervention ?

**Comment by RichardWallis** [comment]
@thadguidry there is a, probably too subtle, visual clue.  Its colour is red, although other terms  defined in extensions are blue.

_about_ appears in the pending listings, because part of its definition (inverseOf _subjectOf_) is declared in pending.

**Comment by danbri** [comment]
Feedback: we've been using this at Google in various feeds-oriented settings and it seems to make markup more natural and idiomatic. I suggest we add it to core rather than continue the "about" (core), "subjectOf" (not core) split...

**Comment by rvguha** [comment]
I agree. the core vs non-core split is confusing at best.

guha

**Comment by Os10melhores** [comment]
Am I correct to notice that there subjectOf is a superset of http://schema.org/WriteAction? I am just noticing that there appears to be nohttp://schema.org/SpeakAction or http://schema.org/RecordAction for the audio modality corollary to the written modality described in http://schema.org/WriteAction. I'm not sure where to make that remark.

http://os10melhores.net/

**Comment by chrisspradling1980** [comment]
similar of the newly described noticed inside of the contextual information
provided in this thread.

Notice:

To reorganize the Department of Defense and strengthen civilian authority
in the Department of Defense, to improve the military advice provided to
the President, the National Security Council, and the Secretary of Defense,
to place clear responsibility on the commanders of the unified and
specified combatant commands for the accomplishment of missions assigned to
those commands and ensure that the authority of those commanders is fully
commensurate with that responsibility, to increase attention to the
formulation of strategy and to contingency planning, to provide for more
efficient use of defense resources, to improve joint officer management
policies, otherwise to enhance the effectiveness of military operations and
improve the management and administration of the Department of Defense, and
for other purposes.

Marking the responsibility "_type" of scope providing consultable
notifications.

Respectfully,

Christopher M. Spradling

**Comment by chrisspradling1980** [comment]
More information would conclude within the Goldwater-Nichols Act: Wikipedia
<https://en.wikipedia.org/wiki/Goldwater%E2%80%93Nichols_Act>

Respectfully,
Christopher

**Comment by chrisspradling1980** [comment]
Please take notice to the "nohttp" indicator which points to the server
side and excludes the front client side ineffective.

Inside gmail editor, the #to the is for some reason indicating inside
reply. This is not normal punctuation creation and I'm not a Latin editor
philosopher either lol.

Good luck everyone,

Chris "by the Way" Spradling

**Comment by Os10melhores** [comment]
Nós fazemos o trabalho duro e filtramos entre as diversas opções, os melhores produtos e serviços do mercado, para você.
Address: 974 Trường sa - Phường 12- Quận 3 - Hồ Chí Minh
https://os10melhores.weebly.com/

**Comment by mohasaksa52-boop** [comment]
ggh
