### ISSUE TITLE
inconsistent use of span / meta, best practice

### ISSUE THREAD

**Issue by CEWebDesign** [schemaorg/schemaorg#1678]
Following (inconsistent?) use of span / meta is not clear to me:
Are all these examples (from data/example.txt) valid and best practice?

`<span itemprop="priceCurrency" content="USD">$</span>`
`<span itemprop="priceCurrency" content="USD" />$`
`<meta itemprop="priceCurrency" content="USD" />$`

`<span property="price" content="13.00" />`
`<meta property="price" content="13.00" />`

**Comment by unor** [comment]
> `<span itemprop="priceCurrency" content="USD">$</span>`

Invalid, because in HTML+Microdata the `content` attribute is only allowed on the `meta` element. (there are plans to change this: https://github.com/w3c/microdata/issues/20)

> ` <span itemprop="priceCurrency" content="USD" />$`

Invalid, for the reason mentioned above (`content` attribute) and because the `span` elements needs a closing tag.

> ` <meta itemprop="priceCurrency" content="USD" />$`

Valid.

> `<span property="price" content="13.00" />`

Invalid, because the `span` elements needs a closing tag.

> ` <meta property="price" content="13.00" />`

Valid.

**Comment by joo7** [comment]
@unor Thank you very much. 
I changed invalid tags in data/example.txt #1676 
I hope it helps in case someone needs valid output.

**Comment by RichardWallis** [comment]
Conversation now transferred to PR #1675
