### ISSUE TITLE
Improve ClaimReview documentation for TV/video/radio/media content, including clips

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1686]
This may involve figuring out new or tweaked markup for talking about subsections of content.

Here's a rough draft with an example (a simplistic fact-check of a claim made by Obama within a much longer speech): https://gist.github.com/danbri/96d6265756577e5f21ad4141f053b76d

DesignIssues:

* how to say when a clip starts? e.g. startTime? (definition needs adjusting)
* endTime? or custom URLs?
* how to represent duration? are we explicit that this is seconds? or e.g. milliseconds?
* we can also point to transcripts, but don't need to.

We'll need conventions for e.g. whether the item-reviewed is the smallest part (the Clip) or the larger (e.g. a TV Episode or VideoObject).

(Aside: Google's structured data testing tool complains a lot - this can be addressed elsewhere)

**Comment by cguess** [comment]
I'd like to first address the bullets with some ideas from my perspective.

- _how to say when a clip starts? e.g. startTime? (definition needs adjusting)_
  - In video editing the phrase 'in' is usually used to indicate the the start of a cut or subclip. Though the term may be less known to developers and journalists, I would argue that we should use industry standard terms borrowed from the video editing world if we're working with video.
- _how to say when a clip starts? e.g. startTime? (definition needs adjusting)_
  - Same as above, 'out' is the common term within video editing for the end of a cut or subclip.
- _how to represent duration? are we explicit that this is seconds? or e.g. milliseconds?_
  - Video players usually use a format of "xx:xx:xx:xx:xx" representing "day:hour:minute:second:frame" (zero indexed) e.g. "00:02:32:11:20" being the 21st frame of the 12th second of the 33rd minute of the third hour of the first day.
  - I would suggest using this same format for 'in' and 'out' as well, since if you're looking at a video editor it's the most common format. Frame can be set to '00' if unknown
  - We may consider leaving frame number off, but that could also cause some complications if using a proper video editing suite.
- _ we can also point to transcripts, but don't need to._
  - I'd make this optional, since the statement would already be required in the schema in addition to clip.

_We'll need conventions for e.g. whether the item-reviewed is the smallest part (the Clip) or the larger (e.g. a TV Episode or VideoObject)._
I would think that video source (full episode etc.) should be required, followed by clip being highly encouraged, but only a warning issued, not an error.

I'm going to think through a few more things and the sample schema and off suggestions if necessary, but I hope this gets a good start to the conversation going.

**Comment by thadguidry** [comment]
@cguess In regards to your bullet points, Schema.org tries to accommodate "for the masses".  TimeCode is a legacy production format "for the wire" and its not constrained to be continous, which is a problem.  ISO 8601 is a format "for the masses and databases" with a base against UTC - Universal Coordinated Time.  See pages 3, 13, 14, 15 in https://tech.ebu.ch/docs/tech/tech3295v2_2.pdf

I would instead rather we continue to develop Schema.org "for the masses" while also aligning to the industrial domains as much as possible.  I think the property terms and their value representations allow for more sharing of data and collaboration.  Your suggestion would allow much less sharing of data and collaboration.

I'll let others chime in against your other points.

**Comment by danbri** [comment]
related: https://www.w3.org/TR/media-frags/

**Comment by rtroncy** [comment]
Hey @danbri ! Indeed, the W3C Media Fragments URI specification enables to specify a fragment of a media resource, in particular, according to the time dimension for videos. You can specify the start and end time for an excerpt of a longer video. Time codes can be expressed in NPT (and in past WD, we even thought about using SMPTE and wall-clock time code for live shows)

**Comment by danbri** [comment]
@rtroncy can you help us work out an example? how would  https://gist.github.com/danbri/96d6265756577e5f21ad4141f053b76d look if we used media fragment IDs?

@cguess - thanks for the detailed thoughts!

**Comment by danbri** [comment]
See also https://blog.archive.org/2017/10/05/tv-news-record-1340-fact-checks-collected-and-counting/

**Comment by danbri** [comment]
I've added the rough-cut from above into http://webschemas.org/ClaimReview but I expect it will need some tweaks...

**Comment by rtroncy** [comment]
Hey @danbri, sorry for this delay. Following the [Media Fragments URI 1.0 specification](https://www.w3.org/TR/media-frags/), the line 21 of your gist could simply be:
```
"url": "https://www.youtube.com/watch?v=B_889oBKkNU#t=350,370",
```
Unfortunately, YouTube does only understand the start time but not the end time of the fragment. Therefore,
```
"url": "https://www.youtube.com/watch?v=B_889oBKkNU#t=350",
```
enables to jump/seek to 5'50 of the speech but it will not stop 20 seconds after

**Comment by danbri** [comment]
Here are some notes, a little old, that came from discussions at Archive.org with their TV / fact checking team: 

https://docs.google.com/document/d/1_YxG42aEbhu33ZoZDPX0oTkKN7tr1B_5gYH33LJYIZk/edit# 

If anyone can't access the Google doc let me know and I'll figure out another way.
