### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by Download** [schemaorg/schemaorg#1690]
So I asked a couple of questions and got answers from the community (thanks!) and thought I'd contribute my new gained knowledge to the documentation. So I was looking at forking this and making a pull request... But it seems there are 41 PRs still open, most ready to be merged. Many are months old and have zero comments...

E.g:
https://github.com/schemaorg/schemaorg/pull/1646
https://github.com/schemaorg/schemaorg/pull/1634
https://github.com/schemaorg/schemaorg/pull/1477
https://github.com/schemaorg/schemaorg/pull/1474
and many more.

Is this project still maintained? 
Why do those PRs have no comments?

If I make a PR, will it be looked at?

**Comment by chaals** [comment]
The project is still maintained. If you make a PR it will be looked at.

But perhaps not as fast as you would like :(

**Comment by Download** [comment]
Fair enough!

I have some ideas for PRs but no promises because I have ideas all the time  :p

**Comment by danbri** [comment]
Yeah what @chaals said! The dynamics of a project like this are kind of different to opensource *software* development...

**Comment by Download** [comment]
OMG the irony of the bot comment

**Comment by danbri** [comment]
@Download yeah, quite! 

The four examples you gave have been closed, and we are working on the backlog in various ways including separating issues that are suggestions / brainstorming from those that come with some intent to implement in a data-consuming service. We have been somewhat overwhelmed by the number of suggestions and (as you have noticed) cannot accommodate them all. The open issue count on the main repo here is now 592 instead of [1000+](https://github.com/schemaorg/schemaorg/issues/2573) a few weeks ago.
