### ISSUE TITLE
Clean up Comment vs UserComments vs CommentAction

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#170]
http://schema.org/Comment
http://schema.org/CommentAction
http://schema.org/UserComments

Schema.org currently has three overlapping types:

Comment: A subtype of CreativeWork described as "A comment on an item". Oddly enough, it does not allow for including the body of the comment. One can only describe the comment (e.g. author, date published, etc.)

CommentAction: "The act of generating a comment about a subject." It also does not include the body of the comment.

UserComments: A subtype of UserInteraction. It is the "event" of commenting. The only way to include the comment body.

The only place where Comment and UserComments are used as an expected type is on the "comment" property of CreativeWork.

This is all very confusing and should be cleaned up.

## Status (May 1) for sdo-gozer

TODOs before closing this issue

- [x] first phase implemented, see http://sdo-gozer.appspot.com/docs/releases.html#sdo-gozer
- [ ] update the text of UserComment + markup with deprecated:True or whatever #465 resolves
- [ ] deprecate UserInteraction and all of its children; also interactionCount (cf #137)
- [ ] final check that /docs/releases.html represents these changes clearly.

**Comment by danbri** [comment]
Noting discussion in #137 and expectation that interactionCount will go away. Shall we monitor that departure here?

**Comment by vholland** [comment]
SGTM. I would like to take this up again once sdo-gozer is complete.

**Comment by danbri** [comment]
Oh, I was talking about closing #137 since it is somewhat covered by this issue #170, which I thought we would try to address during gozer. 

Do we have rough consensus that 

 * UserComments (as a weird kind of action) is supercededBy http://schema.org/CommentAction
 * Its functionality is also somewhat replaced by existence of http://schema.org/Comment - this should be mentioned
 * We need to confirm that we are ok with keeping the relation http://schema.org/comment and type http://schema.org/Comment (the former is listed in https://github.com/schemaorg/schemaorg/issues/417 ).
* We need new text for UserComments explaining this.
* We need to remove or rework any examples using UserComments.
* The general result of an Action is indicated with the 'result' property. We have the convention of defining sub-properties of these generic relations to make type-specific vocabulary more usable. However that doesn't work when the property also has a non-Action usage too, i.e. we wouldn't want to declare 'comment' a subPropertyOf 'result'. 
* This leaves us with a gaping hole: how do we point from a CommentAction to the resulting Comment? either 'result', or 'comment'? The former works today, the latter would need an extension to domain of comment.
* If UserComment is marked somehow as superseded or deprecated, we should avoid advertising it on the per-property page like http://schema.org/comment ( -> file a new python/site impl issue)

I believe this issue tracks the "what to do about Comment vs CommentAction's relationship", and #138 tracks everything else relating to removal of the UserInteraction terms.

**Comment by vholland** [comment]
I'm trying to make progress on this. I created pull request #466, which:

1. Removed http://schema.org/UserComments from the range for http://schema.org/comment.
2. Updated the description of http://schema.org/creator to no longer mention UserComments.
3. http://schema.org/language supersededby http://schema.org/inLanguage.
4. Added http://schema.org/resultComment to http://schema.org/CommentAction.
5. Cleaned up the CommentAction example.

@danbri Once we have decided on how to deprecate without replacement, I would like to deprecate UserInteraction and its children, including UserComments as mentioned in issue #138.

/cc @elf-pavlik who I don't see on this thread, but has expressed interest in other, overlapping threads.

**Comment by elf-pavlik** [comment]
Do you plan to create for each *FooAction* type a matching *resultFoo* property? ATM I really don't understand need for not simply using *result*.

**Comment by vholland** [comment]
@elf-pavlik It's not my intention to create a resultFoo for every FooAction, but I think it is useful to have subproperties where people will almost certainly want a result of a specific type. The Action model can be confusing for authors, so handholding on common use cases can be helpful.

**Comment by danbri** [comment]
Thanks @vholland. I've merged this initial step, and updated docs/releases.html to remember what we did. The language/inLanguage one might be a good nudge for us to document how to use controlled strings vs Language and properties (which?) of that type. I'll leave this issue open as we have a bit more yet to do on deprecation via #465.

**Comment by danbri** [comment]
http://sdo-gozer.appspot.com/docs/releases.html#sdo-gozer

I've updated the issue description above with some final TODOs

**Comment by danbri** [comment]
I'm going to close this. For now the deprecation is handled in human-facing text. We have other bugs tracking deprecation-related infrastructure so I'll close this. Thanks all!

**Comment by GaryJones** [comment]
Please forgive me if this isn't the right place for this question, but do the changes enacted here basically result in [this](https://gist.github.com/GaryJones/0eacb2437749838155d0#file-3-diff-diff) change of markup?

**Comment by vholland** [comment]
Yes. Thanks for the example!
