### ISSUE TITLE
Example on BusTrip is about BusReservation

### ISSUE THREAD

**Issue by lyrixx** [schemaorg/schemaorg#1701]
Hello.

On http://schema.org/BusTrip the json+ld example is about http://schema.org/BusReservation

Thanks.

**Comment by lyrixx** [comment]
Too bad, it has not been fixed

**Comment by danbri** [comment]
Thanks for your feedback. As far as I can see this is not a bug, since it shows how to use the [BusTrip](https://schema.org/BusTrip) type as part of a BusReservation-based description. It might not be obvious but Schema.org does not formally place any particular emphasis on the first schema terms in a piece of markup, although often the first type mentioned is the most important. In several places we also have relationships (properties) that point in both directions, e.g. alumni vs alumniOf, so the emphasis could be different even while communicating the same basic facts.

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BusReservation",
  "reservationId": "123456",
  "underName": {
    "@type": "Person",
    "name": "John Smith"
  },
  "reservationStatus": "http://schema.org/ReservationConfirmed",
  "reservationFor": {
    "@type": "**BusTrip**",
    "provider": {
      "@type": "Organization",
      "name": "Bolt NYC"
    },
    "departureBusStop": {
      "@type": "**BusStop**",
      "name": "Port Authority, NYC"
    },
    "departureTime": "2017-01-04T12:30:00-05:00",
    "arrivalBusStop": {
      "@type": "**BusStop**",
      "name": "Boston South Station"
    },
    "arrivalTime": "2017-01-04T17:10:00-05:00"
  }
}
</script>
```
