### ISSUE TITLE
Add repeatFrequency to Periodical

### ISSUE THREAD

**Issue by thadguidry** [schemaorg/schemaorg#1716]
Many Integrated Library System's (ILS) have a property for frequency for a Periodical.  Such as 'weekly', 'monthly', 'daily', 'quarterly', etc.
@dbs did some nice work on Wikidata & Evergreen for Periodical structures also and probably has a need now for this as well. :)  

But Wikidata has 2 properties... one a subproperty of the other.
For publications, [publication interval](https://www.wikidata.org/wiki/Property:P2896) which is a subproperty for [frequency of events](https://www.wikidata.org/wiki/Property:P2257) 

Should we add [repeatFrequency](http://schema.org/repeatFrequency) or some kind of interval property to [Periodical](http://schema.org/Periodical) ?

**Comment by dbs** [comment]
Yes we probably should! I believe we briefly discussed adding frequency/enumeration properties in October / November 2013 and then opted to leave it for later, as it's one of those properties where the first 80% is easy and the last 20% is a known cause for insanity. "$w - frequency" at  https://www.loc.gov/marc/holdings/hd853855.html represents the library world's 80% approach that defines the following common frequency patterns:

  a - Annual
  b - Bimonthly
  c - Semiweekly
  d - Daily
  e - Biweekly
  f - Semiannual
  g - Biennial
  h - Triennial
  i - Three times a week
  j - Three times a month
  k - Continuously updated
  m - Monthly
  q - Quarterly
  s - Semimonthly
  t - Three times a year
  w - Weekly
  x - Completely irregular

And something like this is perhaps enough for a good number of periodicals. But the "fun" part is that many (most?) long-lived periodicals end up changing their patterns multiple times throughout their lives, and that seems harder to represent meaningfully in schema.org, unless we also added a new class to support reification of this property.

In contrast, Wikidata is actually pretty well set up to be able to handle this by having date qualifiers for properties so that you can reflect when a bi-monthly became weekly became irregular became tri-weekly... along with that special New Year's issue they always have, except on leap years.

**Comment by RichardWallis** [comment]
We could go for the compromise of adding the _repeatFrequency_ property but adjust the description to indicate that it is the 'current' frequency.

Beyond that there might be be a role for _Role_ here - maybe a [Role](http://schema.org/Role) subtype called something like _DatedValue_ which could be used as an optional [Wikidata-like] way of qualifying values of all sorts across the whole vocab by date

**Comment by VladimirAlexiev** [comment]
- Relate to prop `dct:accrualPeriodicity`. 
- mention the following as possible value lists:
  -  "$w - frequency" at https://www.loc.gov/marc/holdings/hd853855.html 
  - http://purl.org/cld/freq/ and http://dublincore.org/groups/collections/frequency/ that define resources for:
Triennial [freq:triennial]
Biennial [freq:biennial]
Annual [freq:annual]
Semiannual [freq:semiannual]
Three times a year [freq:threeTimesAYear]
Quarterly [freq:quarterly]
Bimonthly [freq:bimonthly]
Monthly [freq:monthly]
Semimonthly [freq:semimonthly]
Biweekly [freq:biweekly]
Three times a month [freq:threeTimesAMonth]
Weekly [freq:weekly]
Semiweekly [freq:semiweekly]
Three times a week [freq:threeTimesAWeek]
Daily [freq:daily]
Continuous [freq:continuous]
Irregular [freq:irregular]

**Comment by RichardWallis** [comment]
I think this makes sense to both:
1. Add Periodical to the domainIncludes of repeatFrequency
2. Enhance the description to include reference to the DC examples. 

This would enhance, and possibly provide some simplicity to, the original use of the term with Schedule (for Weekly, Daily schedules), and make it useful in the Journal area.

An example of each would be good as well.

/cc @ldodds

**Comment by VladimirAlexiev** [comment]
I now counted and see the DC CLD people (good chaps!) defined resources for all of the 17 LOC MARC codes. So there's no need to mention "$w - frequency" at https://www.loc.gov/marc/holdings/hd853855.html
