### ISSUE TITLE
hasMap can be applied to LocalBusiness, but not to Organization

### ISSUE THREAD

**Issue by e-orlov** [schemaorg/schemaorg#1734]
As in subject, is it not a bit against the logic, that LocalBusiness, being a subtype of Organization may have hasMap, but not the Organization, being a parental type of LocalBusiness.

According to this works the testing tool too: on testing of Organization with hasMap an error is fired, on testing LocalBusiness with hasMap the markup passes the test.

**Comment by RichardWallis** [comment]
[hasMap](http://schema.org/hasMap) is available on [LocalBusiness](http://schema.org/LocalBusiness) as LocalBusiness is a subtype of [Place](http://schema.org/Place), as well as [Organization](http://schema.org/Organization).

Which is logical as you would expect to find a place on a map whereas not necessarily an organization.

**Comment by jvandriel** [comment]
I have to say I agree with @e-orlov on this one. After all, there are plenty of organizations/corporations that have a head office which nobody would consider a ```LocalBusiness``` yet for which it would be handy to be able to express it can be found on a map.

Now of course one could create an MTE for this like ["Organization","Place"] but to me this feels cumbersome and an over-complication of things and therefor am in favor of expanding ```hasMap```'s domain to ```Organization```.

**Comment by DDeering** [comment]
I also have to second that.  Many organizations can't be labeled "local businesses" but they still indeed have an office location, hours of operation, and so on.  I tend to think that all properties of LocalBusiness should also be a part of Organization so that each organization/corporation could utilize the properties that fit their particular situation.

**Comment by mfhepp** [comment]
I tend to contradict - why not use the clean route and link from the organization to a place? we may need a superproperty like hasOffice for hasPOS, but that make sense anyway.

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by RichardWallis** [comment]
I tend with Martin to contradict also.

There are many organizations (_an organized group of people with a particular purpose, such as a business or government department._) that have no specific location.

I think the real problem is the semantics being applied to the name of the LocalBusiness type. which brings to mind a local hardware store or ice cream shop.    The head office (branch) of a global organization is an equally valid use of LocalBusiness as for a small town branch of a national bank.

I would be in favour of tweaking the description of LocalBusiness, and maybe adding some examples, to indicate its use to describe a place specific organization.  In addition Martin's suggestion of hasOffice makes sense.

**Comment by jvandriel** [comment]
The combination of adding a ```hasOffice``` to ```Organization``` and tweaking the description of ```LocalBusiness``` sounds good to me.

**Comment by vholland** [comment]
What is the difference between the proposed ```hasOffice``` and the existing ```location``` property? Are we trying to differentiate headquarters or a main office?

**Comment by DDeering** [comment]
I'd be in favor of changing the description of LocalBusiness so that it applies to organizations/corporations that have a physical location if the majority here would like that.  But I could also foresee a problem with users getting confused about the use of LocalBusiness if their business serves a national or international customer base and customers do not actually come to their location to do business.  

So while I understand and always try to defer to Martin and Richard, my thought is that it would be easier to simply copy the properties of LocalBusiness into Organization and that would address multiple problems and deficiencies of Organization.

**Comment by rvguha** [comment]
I think it will be very confusing to call every business that has any local
presence a LocalBusiness.

Amazon.com has offices in Seattle (and other places). It would be very very
confusing if it was considered a 'LocalBusiness'.

Martin, Richard, exactly what is the problem we are trying to solve here?

guha

**Comment by RichardWallis** [comment]
@rvguha That confusion is what I was referring to with "_the real problem is the semantics being applied to the name of the LocalBusiness type_".

From my initial involvement with SDO I have understood an organization (_an organized group of people with a particular purpose, such as a business or government department._) to be not necessarily associated with a physical location, but if it was it would have an _address_ property.  In most cases I would expect this to be the head office, or registered, address.

If an organisation has multiple locations (a shopping chain, bank, etc.) there are currently two approaches that can be used: a) _location_ or _hasPOS_ linking to a Place (or LocalBusiness) description or; b) _department_ or _subOrganisation_ properties linking to LocalBusiness descriptions.

We also have the use of LocalBusiness type on its own which is ideal for describing small chains, or individual businesses and their premises such as cafés, repair shops, etc.

In principle there is no difference in the descriptive requirements between the 2nd branch of a local coffee shop and the local branch of a global bank, or the London office of Amazon.com.  However the use of 'local' in the type name does cause some semantic confusion/problems.  Although Amazon's London office could be considered as a place where they carry on business focused in the London/UK locality, no way could they be considered a local business.

Over the years with varying levels of success I have encouraged implementers to interpret LocalBusiness to mean the local[ized] presence of an organization of any type, size, or global presence.

Threads such as this (and the often failure of such encouragement) lead me to believe that we might make things simpler [for implementers] if we interposed a new type between Organization and LocalBusiness.  It would be a subtype of both Organization and Place and named something like BusinessLocation and introduce a new property (locationType ?) to enable the definition of attributes such has "Head Office", "Distribution Centre", "Warehouse", etc.

An alternative to this, as @DDeering suggests, would be to add all that capability to _Organization_ effectively making it another subtype of _Place_.  I believe this blurring between an organisation and its physical location(s) would be a wrong move.  For example attributing a statement to an organization (government, W3C, Amazon.com, Google, Amazon.com, Alphabet Inc, etc.)  could easily be wrong if the description of the organisation is confined to a single location.

I believe most folks get the difference between an organisation and the place(s) from where it carries out its activities, hence my BusinessLocation suggestion above.

**Comment by rtroncy** [comment]
I fully agree with the concerns made by @RichardWallis if SDO was mixing location and organizations. A different perspective comes from the Natural Language Processing research field where we teach machines to extract and disambiguate named entities of various types. One common mistake of all systems, is the proper distinction between the ORG and the LOC types, precisely because the way we use those entities in common language is confusing. Nevertheless, this distinction is important (challenges are even made to properly tackle this difficulty) and it has been proposed to use SDO markup to better train those NER systems. To make the story short, don't blur the lines between the Organization and Place types, but accommodate the fact an ORG can have offices located in places.

**Comment by rvguha** [comment]
Ok, got it and agree that we should make the distinction, but consumers of
the data should be prepared to cope with markup that has it confused.

The problem with forcing the distinction is that for the little family tea
shop round the corner, you are forced to have to entities. One for the
business and one for the business location. While this is 'ontologically'
more pure, it does complicate things for publishers.

But we do want to be able to make the distinction. How about we introduce
terms for DistributionCenter, OfficeLocation, RetailOutlet, etc. so that
when we talk about Google's London office or the starbucks in grand
central, the publisher can say what kind of thing it is. And yes, they can
all be subclasses of BusinessLocation, but we should make sure we don't
need two entities for the local small business.

guha

**Comment by danbri** [comment]
http://schema.org/branchOf
http://schema.org/department make related distinctions

**Comment by mfhepp** [comment]
Actually, I missed that we have 

    http://schema.org/location

This allows linking any Organization to one or more Place entities, that themselves can have all the properties for geo-related information, including hasMap.

So I see no need for an extension.

Simply model the offices as Places and you are fine.

One could argue that a subtype "Office" of schema:Place could be needed, but I would counter that unless you need this distinction for any major consumer of data, using the plain "Place" type should be fine.

We might find that some properties should move up from LocalBusiness to Place, but I did not check for candidates.

But I strictly oppose copying properties that model aspects of a physical location to Organization as a legal entitity. There are organizations that have no physical location (e.g. the Schema.org Steering Group), and there are places that are not legal agents.

Martin


-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by RichardWallis** [comment]
@mfhepp thanks for pointing that out, I'd missed it also.

So in essence we have the mechanism to associate an _Organisation_ to the _Place_(s) (via the _location_ property) that it operates from that cannot be considered to be a _LocalBusiness_

**Comment by RichardWallis** [comment]
_oops, pressed the close button by mistake!_

Continuing my comment....

As to identifying the type of location, we have the option of using the _name_ of the place ("Global Corp Head Office", "Global Corp South American Distribution Center").

If there is concern that that is not detailed enough I would suggest a new subtype of Place (BusiniessPlace) with its own  set of subtypes (Office, HeadOffice, Warehouse, ManufacturingLocation, DistributionCenter, ResearchCenter, etc.)

**Comment by rvguha** [comment]
Martin,

 I think we should be open to copying some of the Place properties to
organization. Metonymy happens.

 One option is to have the concept of a 'primary' domain/range, with other
domain ranges being seen as metonymical uses.

guha

**Comment by mfhepp** [comment]
Dear Guha:

I tend to disagree - it is straightforward to define an Organization and then link to its Place or Places via schema:location and attach all required properties thereto.

Or if you really want to go the route of having just one entity, then make it a multi-typed being both an Organization and a Place.

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by vholland** [comment]
To @rvguha's point, every ontology I have worked with has either been very verbose or conflated organizations and places. (The details of the conflation differ.) Schema.org has always had the philosophy that if there is a conflict, we make things easier for authors not readers.

Large sites like OpenTable already use things like Restaurant for chains, so if you are reading schema.org data, you either don't care about splitting the entities, or you have had to sort through splitting Ruth's Chris the Organization from Ruth's Chris, the location where I have my reservation.

**Comment by thadguidry** [comment]
@rvguha pointed out the stem of the problem.  making it easier for publisher AND having a clear distinction between a place and an organization.  I already use location for my needs and use the name of the Place, its fairly easy.  Dunno what the big deal is in this thread actually.  All the parts I need are already there and easy enough.
