### ISSUE TITLE
overly specific prop names/descriptions in Extensions

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#1736]
@danbri @tfrancart @RichardWallis 

When creating an extension, it's easy to lock your mind to that domain, and forget that Schema is universal and some day may cover any domain.

The Health-LifeSci extension defined a number of generic prop names with overly specific descriptions, eg http://health-lifesci.schema.org/warning, http://health-lifesci.schema.org/procedure, http://health-lifesci.schema.org/procedureType, and worse of all http://health-lifesci.schema.org/status.
From the prop name, one could never guess the description, so the description is **incorrect**. 
This will force any new extension `foo` that needs eg status to declare `fooStatus`, thus proliferating many new props having the same meaning, just different names.

All properties of the http://pending.webschemas.org/Legislation extension have the word `legislation` in their name. This is better, since all of them are correct in relation to their description. But some of them are **overly specific**, and with a bit of rethinking they (can) apply to a wider domain:
- `legislationDate` is very close to `schema:dateCreated`, imho
- `legislationType` is about the same as `schema:additionalType` (but that's a resource and the prop is related to rdf:type; if a mix of resource/text is needed, let's create eg `schema:type`)
- `legislationIdentifier` continues the (imho bad) practice of creating subprops of `schema:identifier` rather than using a resource (like `adms:Identifier`) indicating the identifier issuer/type
- `legislationVersion` was happily spared (`schema:version` being enough), but then `legislationDateVersion` was created (why not `versionDate`)?

Reworking either of the two extensions is probably too late. But I think the aspect raised by this issue must be considered for every new extension. 
Wikidata's process requires each property to pass independent discussion: since Schema discusses extensions mostly an-block, it's easy to slip into this "silo" thinking.

**Comment by tfrancart** [comment]
Thanks for your comment. It comes at the right moment since I was thinking about adressing some other comments made juts before the extension was published into pending (especially the inverse properties). 

> All properties of the http://pending.webschemas.org/Legislation extension have the word legislation in their name. This is better, since all of them are correct in relation to their description. But some of them are overly specific, and with a bit of rethinking they (can) apply to a wider domain.

When naming the properties we have adressed [that comment](https://github.com/schemaorg/schemaorg/issues/1156#issuecomment-230306739).

> legislationDate is very close to schema:dateCreated, imho

It is close but there is a clear and super-important distinction between "the date at which the text has been created/written" (schema:dateCreated) and "the date at which it has become an official law (by being signed by a president/king/queen or adopted by a parliament)"; this latter notion is captured by schema:legislationDate (defined as a subproperty of schema:dateCreated)

> legislationType is about the same as schema:additionalType (but that's a resource and the prop is related to rdf:type; if a mix of resource/text is needed, let's create eg schema:type)

Yes we considered schema:additionnalType but it is really closer to rdf:type and what we needed is "weak-semantic", closer to the notion of schema:genre / dcterms:type (we actually though about making legislationType a subproperty of schema:genre, but finally decided this was not close enough).

> legislationIdentifier continues the (imho bad) practice of creating subprops of schema:identifier rather than using a resource (like adms:Identifier) indicating the identifier issuer/type

We have followed [that comment](https://github.com/schemaorg/schemaorg/issues/1156#issuecomment-251648860), but I think this discussion goes beyond the scope of our extension and should be adressed separately.

> legislationVersion was happily spared (schema:version being enough), but then legislationDateVersion was created (why not versionDate)?

I am not against making this more generic (It's just that I didn't fell we had the mandate to propose generic properties). Probably @danbri or @RichardWallis can take this decision.

> Reworking either of the two extensions is probably too late. But I think the aspect raised by this issue must be considered for every new extension.

I don't think it is too late for _slight_ improvements in the extension; typically I could turn legislationDateVersion into a generic versionDate if it is fine for everyone.

**Comment by VladimirAlexiev** [comment]
Thanks for your replies! 
- @danbri how about making a weak `schema:type` ?
- @tfrancart So in legislation, you really got that many dates: creation, signing/ratification, publication, coming in force? Oh well :-)

**Comment by chaals** [comment]
@VladimirAlexiev Great general comment - the names we give things cause an amazing number of problems... and while we sometimes overthink that, generally the problem is not choosing carefully enough to start with.

Yes, there are *lots* of key dates in legislation - like most fields where people have been working for a while, inside the complexities that are hard to unpick on first glance, there are further complications :-)

I think the decision that the legislation extension should avoid taking terms that are too geeneric was the right one, but that does imply a need to review carefully for when things really are too specific. I think I would be happy with a `schema:type` following the pattern of have `schema:identifier` plus something that defines the type of identifier, but this is not just a "no-brainer" since it requires everyone to start thinking ina  aprticular way about how they model their information. (And many people _don't have_ a formal model, they just have some stuff to say...)

Likewise if `versionDate` works I think that is a generic concept - it applies in my world of specifications (including those that are adopted as legislation ;) ) - and in software releases, and I have run across it for things like cars and parts of them in my ordinary life.

**Comment by tfrancart** [comment]
> So in legislation, you really got that many dates: creation, signing/ratification, publication, coming in force? Oh well :-)

Yes, and we haven't talked yet about the dates of applicabilities (the date at which a legislation becomes _applicable_ (in a certain context/area), which is different of the date when it comes into force.
Actually one the benefits of the legislation extension is to be able to capture/distinguis these dates.

**Comment by danbri** [comment]
Quick note to say that I am very glad for this discussion, and +1 to "and with a bit of rethinking they (can) apply to a wider domain". This is one of the reasons to park this (generally excellent) work in "pending" for a little while. We might consider at least using the "sub-property" mechanism to tie together domain-specific definitions with more general ideas.

**Comment by VladimirAlexiev** [comment]
The worst example is schema.org/action "Obsolete term for muscleAction": the lifeSci extension appropriated many such generic words for it's own...
