### ISSUE TITLE
What is the difference between schema:name and rdfs:label?

### ISSUE THREAD

**Issue by benjamingeer** [schemaorg/schemaorg#1762]
Is there a semantic difference between schema:name and rdfs:label? What would be the advantage of using the former instead of the latter?

**Comment by chaals** [comment]
The semantics are **similar** - enough that in practice they probably mean the same in most cases.

An advantage to using `schema:name` is that it is more likely to be recognised by schema.org-specific processors, most obviously search systems which are the "primary consumers" for which schema.org was developed.

On the other hand, generic RDF processors are much more likely to recogise `rdfs:label` - and because we don't obviously promote anything that associates the latter with the former in a simply processable way, they are less likely to make the semantic connection that people will when reading about them.

Perhaps we should do this for a few basic features of schema. /@danbri ??

**Comment by danbri** [comment]
The idea of a 'name' is slightly stronger than that of a label, so I'd suggest that there could be rdfs:labels that aren't schema:names. I've added a subPropertyOf assertion to the definition file that says this. The name property also means the same thing as [dc:title](http://purl.org/dc/terms/title) too, which is also "A name given to the resource.", so I've added an 'equivalentProperty' link there too. None of this has UI in the site yet, but it is still useful to document the basic situation in our schemas.

**Comment by danbri** [comment]
To answer the question about advantages of 'using the former instead of the latter', afaik there are no large scale schema.org implementations that currently apply multi-namespace RDFS inference or that will understand rdfs:label in place of schema:name. But it depends what you're doing, which application, etc. I can say at least for Google, we aren't currently likely to understand rdfs:label in places where we expect schema:name.

**Comment by benjamingeer** [comment]
Many thanks for these clarifications.

**Comment by danbri** [comment]
Thanks for nudging into clarifying! I'll close this issue now, though it doesn't stop further comments.
