### ISSUE TITLE
clarification: re representing star ratings for github repos via SoftwareSourceCode

### ISSUE THREAD

**Issue by SignpostMarv** [schemaorg/schemaorg#1780]
We've got [SoftwareSourceCode](https://schema.org/SoftwareSourceCode), we've got [starRating](https://schema.org/starRating), github repos can have star ratings, yet it seems SoftwareSourceCode cannot have starRating.

This strikes me as odd.

Thoughts?

**Comment by RichardWallis** [comment]
Looking at the description of [starRating](https://schema.org/starRating):

> An official rating for a lodging business or food establishment, e.g. from national associations or standards bodies. 

and the [documentation of Github Stars](https://help.github.com/articles/about-stars/):

> You can star repositories to keep track of projects you find interesting and discover similar projects in your news feed.
> 
> Starring a repository makes it easy to find again later. You can see all the repositories you have starred by going to your stars page. 

leads me to the conclusion that they are different concepts - one a measure of official approval (usually in the form of * - *****), the other a simple count of bookmarks of interest (for reasons good or bad) by users.

If we were to apply _starRating_ to the description of Github repositories or similar, the description of the term and associated examples would need some significant work so as not to introduce confusion in other established areas.  

My inclination is that if there is broad justification for sharing such [github style] information for _SoftwareSourceCode_, a new property should be proposed that could associate a [Rating](https://schema.org/Rating) value.   Using _Rating_ would allow a description of the rating value.  It might be useful to add such a property to CreativeWork (the super-type of _SoftwareSourceCode_) to broaden its applicability.

**Comment by thadguidry** [comment]
@RichardWallis be very careful here please.  In general, any Thing can have a "popularity" vote or http://schema.org/LikeAction applied on it....as well as a https://schema.org/starRating

The Github Stars are just a 0-1 Rating range (instead of a 0-5 or whatever) where the value is either "like" and "Favorited" OR "I don't care" (0 or empty).  The 0 does not mean Hate it....and that's a big difference.

Please treat Github Stars as what they are, a http://schema.org/LikeAction (there is no Dislike or Hate token to apply...just a non-click that means "I don't care") ...where someone's algorithm can eventually sort and compare the popularity between SoftwareSourceCode's.

Please use http://schema.org/InteractionCounter for this.  We've already done with work and addressed this need long long ago.

Reference:  http://schema.org/LikeAction and http://schema.org/UserLikes which were both superseded to http://schema.org/InteractionCounter and where its description no longer says anything about "popularity" or "likes" or any sort...and probably @RichardWallis why you didn't find anything already existing. :)

**Comment by RichardWallis** [comment]
Thanks @thadguidry for pointing the conversation in a [LikeAction](http://schema.org/LikeAction) direction and recommending the use of the [interactionStatistic](http://schema.org/interactionStatistic)-> [InteractionCounter](http://schema.org/InteractionCounter) to capture the results of the analysis of _LikeAction_ counts [Github Stars].

It was that use of the word star led me to make the wrong assumptions and forget an area I hand not looked into for a while.

**Comment by SignpostMarv** [comment]
@thadguidry so something like this?

```html
<div itemscope itemtype="https://schema.org/SoftwareSourceCode">
    <meta itemprop="alternateName" content="schema.org">
    <a
        itemprop="codeRepository"
        href="https://github.com/schemaorg/schemaorg"
    >https://github.com/schemaorg/<span
            itemprop="name"
        >schemaorg</span></a>
    <div
        itemprop="interactionStatistic"
        itemscope
        itemtype="https://schema.org/InteractionCounter"
    >
        <meta
            itemprop="interactionType"
            content="https://schema.org/LikeAction"
        >
        <meta
            itemprop="userInteractionCount"
            content="2046"
        >
    </div>
</div>
```

**Comment by thadguidry** [comment]
@SignpostMarv yeah something like that.

**Comment by SignpostMarv** [comment]
Cool, thanks :)
