### ISSUE TITLE
Who uses NewsArticle,  AnalysisNewsArticle, BackgroundNewsArticle, OpinionNewsArticle, ReportageNewsArticle, ReviewNewsArticle schema? 

### ISSUE THREAD

**Issue by haneef95** [schemaorg/schemaorg#1846]
Hi,

I'm considering on implementing all of these schema [NewsArticle, AnalysisNewsArticle, BackgroundNewsArticle, OpinionNewsArticle, ReportageNewsArticle, ReviewNewsArticle] in full on some news sites.

But, I need to convince them that there's a benefit to this, like SEO and etc...

Any visualisable benefits would be better.

Thanks,

**Comment by WeaverStever** [comment]
Your best case study would probably be Fact Check (http://pending.webschemas.org/ClaimReview).  Google is already linking fact check articles with the original claim in Google News results.
https://developers.google.com/search/docs/data-types/factcheck

The reason to use the news article markup is because you are at a disadvantage if you don't.  Most news providers are using schema and several other ontology markups.

**Comment by danbri** [comment]
We don't catalogue products or search features using this markup here, although I appreciate that this would be a nice-to-have. This repository is more about developing the schema.org vocab itself, and we are not set up to ask these kinds of question (maybe StackOverflow or similar is better suited). 

Currently at Google we are generally supportive of the new more detailed NewsArticle subtypes but have nothing published that explicitly uses them in a way that you can see.

**Comment by mfhepp** [comment]
Here is a handy table of announcements and a developer documentation timeline for major search engines, kudos to Aaron Bradley!

https://docs.google.com/spreadsheets/d/16O1n4vbA2wXB0Q9jSblqE-fU9yHb3Hjlh5sWnTBvFfE/edit#gid=0

Best wishes
Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp
