### ISSUE TITLE
domainIncludes/rangeIncludes don't appear properly on website

### ISSUE THREAD

**Issue by VladimirAlexiev** [schemaorg/schemaorg#1852]
- http://schema.org/domainIncludes says this and then points to itself:
  `The term 'domainIncludes' is not in the schema.org core vocabulary, but is defined in an extens`
- http://meta.schema.org/domainIncludes claims `Defined in the None.schema.org extension`.
  It  says appropriately `Values expected to be one of these types: Class` and `Used on these types: Property`
  But no description.
- http://schema.org/domainIncludes.jsonld returns a good description and domainIncludes/rangeIncludes.

So this bug is that the same metadata returned in JSONLD should be returned in HTML. 
Same for `rangeIncludes`.

@RichardWallis @danbri if possible give it some priority: these props are one of the most important innovations of Schema, and I hope https://github.com/OnToology/OnToology/issues/383, https://github.com/dgarijo/Widoco/issues/274 will include them in ontology documentation generators.

Cheers!

**Comment by RichardWallis** [comment]
Noted - both defect and urgency.

~Richard

**Comment by VladimirAlexiev** [comment]
Unfortunately no doc generator supports schema:domain/rangeIncludes, except schema's own generator :-(. I made requests for these two generators, but when would they be implemented...
- https://github.com/lambdamusic/Ontodocs/issues/16
- https://github.com/OnToology/OnToology/issues/383

@RichardWallis, @danbri Are there instructions how to deploy Schema's doc generator? 
I need it for https://rawgit.com/euBusinessGraph/eubg-data/master/ontology/index.html (generated with Ontodocs, but does not show meaningful domain/range)

**Comment by dbs** [comment]
@VladimirAlexiev By "instructions for how to deploy Schema's doc generator", do you mean https://github.com/schemaorg/schemaorg/wiki/AppEngine ?

**Comment by VladimirAlexiev** [comment]
@dbs Thanks for the pointer!
What's the master source file that generates individual term pages like eg http://schema.org/workPerformed?

From some commits it seems it is https://github.com/schemaorg/schemaorg/blob/master/data/schema.rdfa (plus examples that are pulled from elsewhere). 
Our ontology is currently in Turtle, but the term pages use only the RDF content, so I think if I run our ontology through ttl->rdfa conversion: http://rdf-translator.appspot.com/convert/n3/rdfa/http%3A%2F%2Fdata.businessgraph.io%2Fontology, it may work.

But in any case I think the schema doc generator is too tailored to schema's specific file structure, so it'd take a lot of work to adapt it for another ontology. Eg our examples are in skos:example and are mere text, not whole marked up separate files. I'll be better off adding schema:domain/rangeIncludes to one of the doc generators mentioned above...

**Comment by RichardWallis** [comment]
@VladimirAlexiev I think you are correct that it would be, currently, difficult to adapt the structure of the Schema.org site and supporting software to another vocabulary.  Its initial design was to produce the term pages on-the-fly  from the single source file data/schema.rdfa, since supplemented by rdfa files for each extension (data/ext/{ext-name}/*.rdfa).

Over the seven years since its introduction, the vocabulary and supporting software has grown and evolved introducing features that assume only the schema.org vocabulary and the significant traffic the website attracts.

We have often received requests for, a more easily, accessible version of the vocabulary in various serialisations.  As you previously identified accessing the canonical URL for each term, suffixed by .ttl, .jsonld, .csv, etc. facilitates the retrieval of term definitions in non-html forms.  This is described in more detail on the [Developers page](http://schema.org/docs/developers.html), where you will also find an [option to download ](http://schema.org/docs/developers.html#defs) definitions of groups of terms in files of various formats.

For example you could download the definitions of all current terms in turtle format by downloading the ```all-layers.ttl```  file.  Note: when selecting the required file in the desired format, the path to that file is displayed above the _Download_ button.  The benefit of this being that a developer can identify how to programatically download such a file by accessing ```http://schema.org/version/latest/all-layers.ttl```.  These files are generated as part of the release of new versions of the vocabulary under the path ```version/{version number}/{file name}``` - the special path ```version/latest/{file name}```, always redirecting to the latest version.

It is worth noting that the ```all-layers``` files contain the terms in the core vocabulary, plus all extension vocabularies, with the exception of the _attic_ extension which contains _an archive area for terms which are no longer part of the core vocabulary or its extensions_.

This brings me to one of the things you raised at the start of this issue; the difference in the behaviour when accessing the html definition of a term in an extension, as against accessing its machine processable definition ether by applying a file suffix or by using content-negotiation.

The grouping of terms into extensions is a construct of the documentation and administration, that reflect areas of focus in the development of the vocabulary.  The [meta](http://meta.schma.org) extension being focussed on terms terms primarily designed to support the implementation of the Schema.org vocabulary itself, and not necessarily designed for wider usage.

All terms, be they in the core or an extension, have canonical URLs in the ```http://schema.org/``` namespace.  So for example the term displayed at http://meta.schema.org/rangeIncludes has a canonical URL of ```http://schema.org/rangeIncludes```.

When using a browser [requesting html] to access the canonical URL of a term in an extension (e.g. http://schema.org/domainIncludes ), the user flow is interrupted by a screen indicating that they are moving into, or between, extension vocabularies.   This device was introduced, along with extensions themselves, to help with understanding of the organisational and developmental structure of the vocabulary.  Whether that is still appropriate or not is a question open for discussion.

I hope the above helps you in your understanding of, and use of, the terms within Schema.org.

The only defect you raised in this issue, in the way the schema.org site is currently expected to operate, has been fixed:

> - http://meta.schema.org/domainIncludes claims Defined in the None.schema.org extension.
It says appropriately Values expected to be one of these types: Class and Used on these types: Property
>  But no description.

I am therefore going to close this issue, but would welcome the raising of follow-on issues/requests about how the current site currently operates, or could operate, in these areas.

~Richard
