### ISSUE TITLE
Property "variablesMeasured" WITH AN S does not exists in csv file  (attached to type "CompleteDataFeed") + similar property "variableMeasured" WITHOUT ANY S attached to the same type

### ISSUE THREAD

**Issue by khalyomede** [schemaorg/schemaorg#1881]
The property `http://schema.org/variablesMeasured` is not found on the file `http://schema.org/version/latest/all-layers-properties.csv`, but is included in properties of at least the type `http://schema.org/CompleteDataFeed`.

Plus, I noticed that this type `http://schema.org/CompleteDataFeed` points to 2 similar properties, `http://schema.org/variablesMeasured` (WITH AN S) and `http://schema.org/variableMeasured` (WITHOUT ANY S). Is that intentional?

**Comment by thadguidry** [comment]
@danbri This happened here: https://github.com/schemaorg/schemaorg/commit/f62a9ced272bfd8131580b35cf6be5ef3bb662cd

**Comment by danbri** [comment]
The eventual intention was to have the property named *without* the 's'. 

It did exist for a short time with an 's' while the design was being sketched (this history is recorded in attic.schema.org) but from now on, without is the way to go. 

The corresponding discussion was in https://github.com/schemaorg/schemaorg/issues/1083#issuecomment-259060727

Since the property was very new and barely used beyond the parties involved in the discussion, I didn't make a big fuss about the change. Generally, for a more established property, we would have a clearer papertrail. Apologies for any confusion!
