### ISSUE TITLE
Question about Namespaces

### ISSUE THREAD

**Issue by ayumihamsaki** [schemaorg/schemaorg#1914]
Hi,

I understand The Semantic Web is built using Namespaces, for example, Schema.org uses the following Namespace:

`http://schema.org/`

And if we wanted to use the Article Ontology schema we just add Article to the Namespace to make:

`http://schema.org/Article`

`schema:Article`

When I learned about Linked Data back in 2005, these namespaces are meant to last 'forever'. The trouble with this is that the internet has huge amounts of link rot and web pages get deleted all the time.

A Namespace URL just seems to be an RDF XML file to me?

I got two questions about Namespaces:

1. Why we can't use https and the server 303 redirect it to the http namespace or vice-versa?

2. HTTP 1.1 - HTTPs - HTTP/2 is an old protocol and seems very poor with regards to Semantic data, surely using a newer protocol like IPFS where the link actually does last forever would be a better place to store a NameSpace. Just wondered if there were any plans to upgrade schema.org Ontology over to the newer IPFS protocol.

Thanks - I know this is not an issue just interested in this subject and wanted to learn the reasons.

**Comment by RichardWallis** [comment]
Hi @ayumihamsaki  

Thank you for your [not an issue] question.  It conflates a couple of concerns that often cause confusion. These being the format of the identifiers used in ontologies and vocabularies such as Schema.org,  and the use of the http/https protocols to access web pages.  I think it is worth exploring these to, both answer your questions and, hopefully clarify things for others.

Let me first address the identifier question.

As you say, this has evolved from semantic web and linked data technologies from a decade or so back.   I won't go into great detail here, if others want some more background I suggest reading up on [Linked Data principles](https://www.w3.org/DesignIssues/LinkedData.html), [RDF](https://en.wikipedia.org/wiki/Resource_Description_Framework), and [triples](https://en.wikipedia.org/wiki/Semantic_triple).

A core principle of this technology is the use of  a [Uniform Resource Identifier (URI)](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) to identify things and concepts.  The most important letter in the URI acronym is the '**I**' — identifier.  In effect a URI is a, potentially abritory, string of characters that identifies something.  

Following the Linked Data principles these strings often take the form of a http URI (a string that starts 'http://some-domain-name'), one significant benefit of this being that the inclusion of an Internet domain in the string provides global uniqueness.  A secondary benefit being that by using the URI as a [URL](https://en.wikipedia.org/wiki/URL)(web address), it should be possible to look up the meaning of the concept, or description of the thing, that is identified by the URI.

As you also identify these concept identifiers are grouped together under a common namespace.  i.e. the Schema.org terms are all under the _http://schema.org/_ namespace (all the term identifiers begin with 'http://schema.org/'), all the [FOAF](https://en.wikipedia.org/wiki/FOAF_(ontology)) terms are under the _http://xmlns.com/foaf/0.1/_ namespace, etc.  For simplicity/readability these namespaces are often represented using  a prefix, so when processed by systems, the string **schema:Book** is translated into the full URI **http://schema.org/Book**.

Link rot has been an issues since the beginning of the web and gives rise to the oft asked question: "_What happens if the website/domain describing the terms in a vocabulary goes away - does it invalidate the URI I have used?_" . The simple answer is _**No**_.  You may not be able to conveniently look up what the meaning of a term (or description of a thing), but it is still a valid identifier.  If, in a data set, two entities both say that they _knows_ (http://xmlns.com/foaf/0.1/knows) another Person, those relationships (in that dataset) will always be valid, even if the FOAF website was to disappear.

As in simple terms a URI is a string of characters that uniquely identifies a concept or thing, any differences in those [URI] strings indicate different URIs - different identifiers.

The result of this being that, in data terms, these two URIs are different:  _https://schema.org/Thing_,  _http://schema.org/Thing_.   In data consumption and processing terms, this provides a challenge and significant overhead in rationalising the difference/similarities.

This brings me to the issue of using http/https to access websites.  

There are many arguments, which I support, in favour of implementing all websites to operate using the https protocol by default, and using techniques, such as 302 redirects, to ensure users only see the https version.

The Schema.org site, which is used to look up the meaning of URIs in the schema.org namespace, (and other associated documentation) operates both using http and https.  Visiting these two URLs result in the same display: [http://schema.org/Thing](http://schema.org/Thing), [https://schema.org/Thing](https://schema.org/Thing).   

Note, on both of them the canonical URL is represented as http://schema.org/Thing — this is the value to be used as the identifier (URI) for the concept when storing it, or declaring it, in data.  

The challenge for the Schema.org site, is the knock on effects of enforcing a policy of only using https.  Yes it would address privacy concerns for human visitors, but it would also potentially produce new URI identifiers for the some 1,500 terms in the vocabulary, introducing a significant overhead for, and potentially breaking, datasets and support tools that have evolved over the last seven years since the vocabulary was established — something not undertaken without much thought!.

As an aside: With well written software and systems, there should be no need for the the schema.org URI to be accessed when declaring that something is of type http://schema.org/Book or it has the http://schema.org/name of "War and Peace".  Only those [developers, data analysts, interested users, etc.] who are looking to understand the vocabulary should need to visit the associated pages.  Analysis of logs indicate that this is not always the case.

This question has been the subject of an issue (#1325) for some time, including some useful suggestions for adjustments to the webpages to improve the situation (for users wishing to only visit https pages).  This is not an issue that should be closed or forgotten, and we do need to look more deeply into the consequential impacts of what on the surface looks like a simple change to make.

Finally, in your second question, you reference several versions of the http protocol and the potential for using other protocols such as IPFS.  In principle the choice of protocol to use to talk to a website is independent from the use of URIs as identifiers.  

Once a vocabulary/ontology has been established with its associated namespace, it can be exceedingly difficult, if not impossible, to change the protocol that has been defined as part of that namespace without breaking something.  If a new vocabulary/ontology is being established, that is the time when new such protocols could/should be considered.  This provided the standard tools, to process such data, can accommodate the new protocols by default. 

As this was a question, not an issue, I will close the issue - suggesting further comments for implementation of https in Schema.org should be addressed on issue (#1325).

**Comment by ayumihamsaki** [comment]
@RichardWallis Thank you for taking the time to explain everything to me! You should add this really useful information to the [schema blog](http://blog.schema.org/)

**Comment by Lomilar** [comment]
It may also be worth noting here that, in what I see as compatibility with what @RichardWallis is saying, there is an HTTP assumption pitfall here as well. 

When linking to a resource, it can be tempting to link to a resource using a different URI or alias that changes how the record is retrieved, such as a URI that specifies a specific version independent of a latest version, a URI that retrieves the record in a different format or schema, or a URI that is local to your system.

All of these make an assumption that HTTP is available to redirect or resolve the link. In short, this places the locatability of the object (the second benefit) over the identifiability of the object (the first benefit) as mentioned here:

>Following the Linked Data principles these strings often take the form of a http URI (a string that starts 'http://some-domain-name'), one significant benefit of this being that the inclusion of an Internet domain in the string provides global uniqueness. A secondary benefit being that by using the URI as a URL(web address), it should be possible to look up the meaning of the concept, or description of the thing, that is identified by the URI.

Should the data be exported to a linked data system that can't resolve the data in an HTTP-centric fashion, such as a local RDF environment, the links will break, and the data won't be linked any more. 

Further, should the system that resolves the aliases and redirects cease to exist, the data will also be unlinked. It may be strictly worse (certainly problematic) to use URLs for location over identification, though it sure is tempting at times.
