### ISSUE TITLE
Too much text-indent in the search box? 

### ISSUE THREAD

**Issue by martin-nc** [schemaorg/schemaorg#1956]
The placeholder text in the search box is cut off because there is a `text-indent: 48px` on the  `<input>` element. It says "Custom Sear" before being cut off. Tested on Mac (Chrome, Firefox, Safari) and Ubuntu (Firefox). Is the text indent needed? Would `text-align: right` be simpler to align the text to the right, even though it will affect the user's text as well? Or just leave the placeholder text left-aligned because that's how the text is when the user inputs it?

Also it would be nice if the search box and button were the same height. Perhaps reduce the line height of the search box and increase the padding a bit on the button?

Sorry if these schemaorg issues aren't for aesthetics!

**Comment by RichardWallis** [comment]
@martin-nc These issues are as much for aesthetics as they are for bugs and vocabulary tweaks.

We were hoping to fix this pre-V3.4 release, but because those elements come in from Google Custom Search Engine, along with their css, it wasn't quite as easy as we thought.   There is a bit of cruft in the schemaorg.css around this area that has accumulated over time.  Hoping to fix this as part of a bit of cleanup in this area soon.

**Comment by danbri** [comment]
Yeah, it's worth handling, and worth documenting here. I might separate out the software/python issues for better management of the vocabulary, now that Github has a few more administration options than when we started.
