### ISSUE TITLE
New schema definitions for Workplaces

### ISSUE THREAD

**Issue by srahul07** [schemaorg/schemaorg#2004]
We would like to include json-ld for following things on our website which is a marketplace for Commercial properties. 

The distribution of the types of office spaces is as follows:

- Full Office
  - Furnished: _Fully furninshed office_
  - UnFurnished: _Bare shell / empty office_
- Shared Office: _Office partially shared by owner or leaser with someone else._
  - Desk: _Single Seat_
  - Cabin: _Multi seat private area_
-  CoWorking
   - Desk
     - Flexi Desk: _Single seat_
     - Dedicated Desk: _Single seat / Team Table / Cubical_
   - Cabin: _Multi seat private area_
- Virtual Office: _Office used only for communication purpose._
- Meeting Rooms
  - Meeting Room
  - Training Room / Class Room
  - Conference Room
- Studio: _Dance Studio / Music Studio / Gym / Yoga_
- Clinics
- Warehouse
 
We could not find specifications for these in schema.org information except MeetingRoom. Hence, would like to know is there any way to include these custom types which can be identified by search engines easily.

Also, I would like to propose to include these as standard schema types. And if required can put my time to introduce these [Will need guidance].

**Comment by danbri** [comment]
Thank you for the suggestion. Are you aware of anyone proposing to use (consume, harvest) etc this new markup? We do have other threads of discussion here around real estate markup, which is tracked in https://github.com/schemaorg/schemaorg/issues/241 . By mentioning #241 here it is automatically cross-mentioned in that issue, so I'll go ahead and close this one so that discussion doesn't get spread across too many issues. At this stage with real estate we're more in a kind of fact-finding mode, so it is useful to have suggestions like these even if we're unlikely to act upon them immediately.
