### ISSUE TITLE
Q: What is the point?

### ISSUE THREAD

**Issue by dalu** [schemaorg/schemaorg#2010]
It all started when I wanted to create yet another recipe sharing site.
I was searching for standards and found https://schema.org/Recipe
I had completely forgotten about this.

So I wanted to write a converter to Golang structs, but this is... well it's not impossible but I feel like it far from reality.

It seem like this (the schema.org schemas) is some abstract work out of touch with reality.

It seems like if you follow this schema it's easy to scrape the content of your sites and import it as yours. And that's a problem. You see my partners and me, I create the means so they can publish content. We live off content and visitors and ad clicks.

Ok but let's assume we are going to follow this schema. How would you even derive your data models from this schema. Manually? Is there no better option? Outputting the schema definitions as let's say postgres, mysql, cassandra, graphql files or even Golang structs.

But while the human mind understands things like an URL schema type with no definition, a machine won't.

So this is imho a half-assed approach. It should provide common schema definitions. But sadly it's all written in Python which I personally have no clue of, as I don't belong to the generation of recently indoctrinated Pythonists but I started to learn to write code (and quite literally sometimes) when there was no internet. Sure you can say you know one, you know them all, but it's not that simple.

So what is the point of those schema.org schemas when they're often too abstract and how do you convert them into something usable?

**Comment by dalu** [comment]
Example:

https://schema.org/QuantitativeValue

A point value or interval for product characteristics and other purposes.

Why not just number?
Are there type aliases I'm missing somewhere?

**Comment by thadguidry** [comment]
We have Numbers, Floats, Integers... lots of Datatypes and Types... Take a look at the list of Properties that can take an instance of a https://schema.org/Number  and where we have the full list of Types on one page: https://schema.org/docs/full.html (just scroll to the bottom for the Datatypes)

For tooling or programming with Schema.org, there are many software libraries and products, or you can just roll your own.  Search the web, or just click on your language of choice on the left side of this Github Search https://github.com/search?q=schema.org

You might also want to subscribe to and search the [Semantic Search Marketing community](https://plus.google.com/u/0/communities/103048251221048356778) which has thousands of members that often ask the same questions as you.

We are very much into "reality" and practical usage of Schema.org for publishers like yourself.   Especially of Recipes, because many of us around here are Foodies. 🥘 

If you need further help, just ask on our Mailing list. https://github.com/schemaorg/schemaorg/wiki

**Comment by dalu** [comment]
Thank you
