### ISSUE TITLE
Clarify what data types are acceptable

### ISSUE THREAD

**Issue by steelstring94** [schemaorg/schemaorg#2043]
In the schema.org tutorial [here](https://schema.org/docs/gs.html#schemaorg_expected), it says it's okay to use plain text or a URL as a property value. Yet on the various schemas, the "expected type" sometimes includes Text, and sometimes it does not, which leads me to believe Text is acceptable sometimes, but other times not. This seems like contradictory information and is confusing to me.

Perhaps there's a good reason for it to be like this, but if not, I'd like to propose that either Text be removed or added as an expected type for everything. Rationale: If it's always okay to use Text, there's no need to mention it. Or, if we must mention it to be extra-clear it's okay to use, then mention it on every property, otherwise it sends mixed signals and seems like it's sometimes not allowed.

**Comment by RichardWallis** [comment]
As per [the documentation](https://schema.org/docs/datamodel.html#conformance):

> ..... We also expect that often, where we expect a property value of type Person, Place, Organization or some other subClassOf Thing, we will get a text string, even if our schemas don't formally document that expectation. In the spirit of "some data is better than none", search engines will often accept this markup and do the best we can. Similarly, some types such as Role and URL can be used with all properties, and we encourage this kind of experimentation amongst data consumers.

The values defined as "expected types" are just that, expected - a guide to use.  However, in any case as described above, it is acceptable to provide _Text_, _URL_, or _Role_ as values for any property.

You are right, in theory we could add _Text_, _URL_, and _Role_ to all expected type definitions.  In practice that would massively increase the amount of values on each term page and significantly dilute the current 'guide to use' of the current expected types.

**Comment by philbarker** [comment]
On 22/08/18 14:19, Richard Wallis wrote:
> You are right, in theory we could add /Text/, /URL/, and /Role/ to all 
> expected type definitions. In practice that would massively increase 
> the amount of values on each term page and significantly dilute the 
> current 'guide to use' of the current expected types.

Which I think leaves open the question of why have 'Text' as the 
expected type for any property that has another expected type specified. 
I think the answer is that sometimes it is expected that 'Text' is what 
will be provided, while at other times it is just accepted that there 
might be no better data available. So,

citation    CreativeWork or Text    A citation or reference to another
  creative work, such as another publication, web page, scholarly article, etc.


I guess has Text as an expected type because the citation may be an 
academic reference (e.g. "Finney, J. (1970). Time and again. New York, 
NY: Simon and Schuster."). It may not be possible for the publisher to 
break such references up into schema.org CreativeWorks and it would have 
an inhibiting effect on the use of the property if its definition 
implied that was expected.

Quite often Text is an alternative to URL because there may be no URL 
available that identifies the object.

While I wouldn't suggest that there is perfect consistency across all of 
schema.org, I think that the intent is pragmatic and makes sense.

Pihl

-- 

Phil Barker <http://people.pjjk.net/phil>. http://people.pjjk.net/phil
PJJK Limited <https://www.pjjk.co.uk>: technology to enhance learning; 
information systems for education.
CETIS LLP <https://www.cetis.org.uk>: a cooperative consultancy for 
innovation in education technology.

PJJK Limited is registered in Scotland as a private limited company, 
number SC569282.
CETIS is a co-operative limited liability partnership, registered in 
England number OC399090

**Comment by danbri** [comment]
* The pairing of "Text and URL" is often our way of saying "we haven't explicitly modeled how to handle values for this property". Sometimes we add more structure later, other times we leave it open.
* We also sometimes say "Text" for cases where most values will be a more precise datatype, but we know up front that a lot of people have some content that isn't going to fit into stricture values. 
 * example: https://schema.org/version (we want to permit versions like "1.0A").
* We did originally at launch in 2011 say "ok we'd prefer more structure but will deal with text if that's all you've got". That was when nobody used Schema.org and nobody knew if it would succeed. Now that it is in millions of sites, and now that we have the cleaner JSON-LD syntax as an option, we're seeing a gradual emphasis on more precise data structures, since it makes it easier to consume the data. However we have kept our founding concern to make things as easy on webmasters/publishers as possible. 

I'm going to close this issue now, in the spirit of #2050 but we can keep talking of course...
