### ISSUE TITLE
Question: mainEntity property of CreativeWork type

### ISSUE THREAD

**Issue by danzhik** [schemaorg/schemaorg#2045]
Hello guys!

I'm currently creating Q&A page on my website, marking it with 'QAPage' schema type. Structured Data Testing Tool tells that 'mainEntity' property is required by this type, but I don't fully understand what is supposed to be as content of this property. Could you please clarify it somehow?

Thanks in advance!

**Comment by danbri** [comment]
The configuration of Google's validation tooling is out of scope for Schema.org. Schema.org itself has no notion of mandatory or required properties. Schema.org isn't Google - we can't offer any kind of support for Google (or other search engine) products and services here. I'll close the issue, but if others happen to have useful pointers, they can of course share them here. Otherwise you might try the Google Product Forums, eg https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Astructured-data%7Csort:relevance%7Cspell:false

**Comment by unor** [comment]
You would typically want the `Question` to be the `mainEntity` ([minimal Microdata example](https://stackoverflow.com/a/52255952/1591669)).
