### ISSUE TITLE
Adding a property for literary form

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2084]
I was talking to someone about how to markup short stories in schema.org and we discussed genres vs literary forms. (Full disclosure: I fall into the literary forms are different than genres camp.)

Is there any opposition to adding a ```literaryForm``` property? I realize some systems mix genres and forms, so they won't be able to leverage this property, but for those who split them out, it makes the data a bit cleaner.

@RichardWallis, thoughts?

**Comment by RichardWallis** [comment]
@vholland the issue of ShortStory as a CreativeWork subtype came up a while back  (See PR #1979) along with others such as, Manuscript, Poster, Drawing, Play, SheetMusic.

In retrospect, it may have been a better track if we had gone for a more genre/form property based approach instead of quite so many subtypes.  However, the referenced PR covers off most of what is left outstanding (in questions and comments from the library folks).  I recommend we continue in that vein, and apply that PR, instead of changing the pattern just to clear up the residue of needs in this area.

**Comment by vholland** [comment]
Sounds good to me. Thanks for the reference.
