### ISSUE TITLE
organisation type

### ISSUE THREAD

**Issue by pierreozoux** [schemaorg/schemaorg#2096]
Hi,

Currently there are missing some organizational type.
How can I PR them?
I'm thinking about:
 - cooperative
 - association
 - informalOrganisation

What do you think about it?

Thanks!

**Comment by VladimirAlexiev** [comment]
- Are you proposing classes? What are the benefits of doing it this way rather than just using `additionalType`?
- do you have an authoritative list in mind? I've worked with company types from various jurisdictions, and it's a real mess. Eg have you explored the Wikidata class hierarchy of "Organization"?
- where do you draw a line? Eg where would Circus, Opera and Philharmonic fall in your hierarchy? (These are actual examples from the BG Bulstat register)
