### ISSUE TITLE
Question: How to link a keyword to an entry in a controlled vocabulary?

### ISSUE THREAD

**Issue by adamml** [schemaorg/schemaorg#2152]
There are a few of us working on representing metadata about ocean science data in Schema.org.

Many times our keywords are registered in Controlled Vocabularies as Linked Data resources (with URLs).

It seems to us that keyword in Schema at the moment doesn’t allow us to preserve the provenance of our keywords by providing the plain text label and a link to the original resource. Are we missing something?

**Comment by philbarker** [comment]
[DefinedTerm](https://schema.org/DefinedTerm) is what you are looking for (or possibly its subtype [CategoryCode](https://pending.schema.org/CategoryCode)).

**Comment by fils** [comment]
Given that both of these (Defined Term and Category Code) are:
`Thing > Intangible`

To hang this off Dataset it seems we would have to use property `about` and drill down.  Is the the way we would have to do it? 

Could we propose extending the range of https://schema.org/keywords to include DefinedTerm and CategoryCode?

Note..   a quick check shows DCAT keyword to be Range:Literal too.   Looking at the proposed schema.org mappings (https://w3c.github.io/dxwg/dcat/#dcat-sdo  then scan down for it) looks like it also doesn't provide any link to a defined URI reference.   Obviously it had to propose mappings that reflect the state of schema.org.    

@dr-shorthair what would be the way to define a keyword term with a URI in DCAT right now?   Any extension to https://schema.org/keywords range we would want to be able to map to from DCAT.

Thanks @adamml for starting this....

**Comment by dr-shorthair** [comment]
In a DCAT context there are 4 slots for classifiers (apart from the rdf:type)

-          `dct:type` – “Recommended best practice is to use a controlled vocabulary such as the DCMI Type Vocabulary [DCMITYPE]. To describe the file format, physical medium, or dimensions of the resource, use the Format element”

-          `dct:subject` – “Typically, the subject will be represented using keywords, key phrases, or classification codes. Recommended best practice is to use a controlled vocabulary.” And “This term is intended to be used with non-literal values …”

-          `dcat:keyword` – `owl:DatatypeProperty`, range `xsd:string`, singular, with the implication that multiples should be in separate properties, rather than comma or semi-colon delineated list in a single text string

-          `dcat:theme` – `owl:ObjectProperty`, range `skos:Concept`


The dct: properties are rdf:Property and do not have a defined rdfs:range, so either literals or non-literals could be used. I guess the ambiguity around this was the motivation for `dcat:keyword` and `dcat:theme` which are more tightly defined.

So I think the answer to your specific question “what would be the way to define a keyword term with a URI in DCAT right now?” is to use `dcat:theme`.

Simon

**Comment by fils** [comment]
Simon ( @dr-shorthair ),
   thanks..  very clear..      Adam ( @adamml ) reminded me our current plan looked something like this

```
{
                "@context": "http://schema.org",
                "@type": "Dataset",
                "keywords": [{
                                "@type": "PropertyValue",
                                "additionalType": "http://www.w3.org/2004/02/skos/core#Concept",
                                "name": "Salinity of the water column",
                                "propertyID": "http://vocab.nerc.ac.uk/collection/P02/current/PSAL/",
                                "propertyVersion": "http://vocab.nerc.ac.uk/collection/P02/current/PSAL/2/",
                                "sameAs": "http://vocab.nerc.ac.uk/collection/P02/current/PSAL/",
                                "url": "http://vocab.nerc.ac.uk/collection/P02/current/PSAL/"
                }]
}?

?
```

I'm not sure I see an immediate manner to map that to dcat:theme though.   I notice schema.org/keywords looks to be range text too, so perhaps we were taking some liberties with that approach?

What does it mean that dcat:theme has schema:domainIncludes schema.Dataset??
I'm not able to directly use dcat:theme as a property of schema.Dataset am I?   If so that would be slick.

Thanks
Doug

**Comment by adamml** [comment]
Just to clarify, the proposed approach which @fils mentions would be if
there was no canonical way to do this in schema.org and we propose and have
accepted that keywords have a range of Text or PropertyValue

Adam

**Comment by fils** [comment]
@adamml   good point and thanks..   I'm being a bit poor at representing the approach I fear...  :)

**Comment by adamml** [comment]
@philbarker Many thanks for pointing us to DefinedTerm. This does indeed look to be what we need, so I’m going to close this issue.

I will have a deeper look next week, but may open a new issue if there are any suggestions we have concerning DefinedTerm.
