### ISSUE TITLE
Request for keywords->DefinedTerm

### ISSUE THREAD

**Issue by adamml** [schemaorg/schemaorg#2176]
Recognising that DefinedTerm is still in pending, and referencing #2152, we would like to propose that when DefinedTerm moves to the main branch, that keywords is extended to accept DefinedTerm.

The use case is the referencing of controlled vocabulary terms in keywords, while maintaining the provenance of the terms and the integrity of the reference to their URL.

e.g.
```javascript
{
    "@context": "http://schema.org/",
    "@id": "http://foo.bar/dataset/baz",
    "@type": "Dataset",
    "name": "A test dataset",
    "keywords": [
        {
            "@type": "DefinedTerm",
            "name": "Practical salinity of the water body",
            "termCode": "PSLTZZ01",
            "inDefinedTermSet": "http://vocab.nerc.ac.uk/collection/P01/current/",
            "url": "http://vocab.nerc.ac.uk/collection/P01/current/PSLTZZ01/",
            "version": [1,"http://vocab.nerc.ac.uk/collection/P01/current/PSLTZZ01/1/"]
        },
        {
            "@type": "DefinedTerm",
            "name": "Temperature of the water body",
            "termCode": "TEMPPR01",
            "inDefinedTermSet": "http://vocab.nerc.ac.uk/collection/P01/current/",
            "url": "http://vocab.nerc.ac.uk/collection/P01/current/TEMPPR01/",
            "version": [1,"http://vocab.nerc.ac.uk/collection/P01/current/TEMPPR01/1/"]
        }
    ]
}```

Looping @fils, @ashepherd

**Comment by RichardWallis** [comment]
@adamml How would this differ from using the [about](https://schema.org/about) property to reference DefinedTerms?

**Comment by adamml** [comment]
@RichardWallis It'd certainly be more semantically clear if keywords accepted definedTerm. I'm not sure in the use case of marking up a scientific/environmental dataset that "about" would be as precise, and certainly not as clear cut as in the examples on the Schema.org page make it.

@asheperd, @fils do you have anything else to add? Maybe from your conversations on the Global Change Master Directory keywords?

**Comment by fils** [comment]
@adamml @RichardWallis   
This ability to connect to a defined term (with a resolvable URI) is going to be vital to building out the use of schema Dataset and to tools like Google's Data Set Search [1].   For many in the sciences,  an ability to connect to GCMD (Global Change Master Directory) or other term servers (like NERC in Adam's example) is vital to the addressing FAIR Data patterns.  [2].

Also, DCAT is currently making revisions and DCAT is heavily used in data set description.  We need a good way to bind to the DCAT keyword mapping to schema.org [3].  @dr-shorthair 

[1] https://toolbox.google.com/datasetsearch
[2] http://www.copdess.org/enabling-fair-data-project/
[3] https://www.w3.org/TR/vocab-dcat-2/#dcat-sdo

**Comment by RichardWallis** [comment]
> and certainly not as clear cut as in the examples on the Schema.org page 

@adamml Which page are you referencing here?

The current definition of ```keywords``` (_Keywords or tags used to describe this content. Multiple entries in a keywords list are typically delimited by commas._), and its plural name, leads one to assume its use would be similar to the HTML meta tag of the same name.   ie. A text string of one or more comma separated words.

The use case you are describing is similar to the semantic relationship to individual subjects or topics. This is why I was leaning towards the use of ```about``` (_The subject matter of the content.
Inverse property: subjectOf_)

```about```, as for all properties in Schema.org, can take a URI as a value in addition to the description of any```Thing```.   Therefore the capability you are looking for is already in place, even if the property names used are not your first preference.

As ```about``` can take any```Thing``` as a value, it can take references to a Place, Person, Event, etc. in addition to  aDefinedTerm.

For information the bibliographic world, who are often very concerned about the accuracy of subject references, seems comfortable with using ```about``` as I described.  See this example extract:
```
 {
      "@id": "#trilogy",
      "@type": "Book",
      "name": "Lord of the Rings",
      "about": "http://id.worldcat.org/fast/1020337",
      "hasPart": [
        {
          "@id": "#book3",
          "@type": [
            "Book",
            "PublicationVolume"
          ],
          "name": "The Return of the King",
          "about": "http://id.worldcat.org/fast/1020337",
          "isPartOf": "#trilogy",
          "inLanguage": "en",
          "volumeNumber": "3",
          "author": "#author"
        },
```

**Comment by adamml** [comment]
@RichardWallis I was referring to https://schema.org/about  

> "The subject matter of the content".

This seems ok to me for some of the high level concepts in the vocabularies we wish to reference (e.g. the ISO topic category "oceans") but I'm less sure that subject matter of the content well describes the more detailed vocabulary terms (e.g. "temperature of the water body"), hence the request. I'd also point you to @fils comment for some additional thoughts on the use case.

**Comment by RichardWallis** [comment]
I think we are all agreeing on the use case - the ability to reference definition(s) of  subjects/topics/terms/concepts that a CreativeWork (Dataset) is relevant to/for (being deliberately vague here).

Whichever of the two existing properties we propose using (```keywords```, ```about```) are not ideal, mostly because of their description.  "_subject matter of the content_", "_a keywords list are typically delimited by commas_".

Perhaps we should be discussing some tweaks to those descriptions.  

With its associations with HTML meta tags, and its common usage in marking up web pages, I still feel that ```keywords``` is not appropriate for this use. "_temperature of the water body_" is not really a key-**word**

Dropping the word '_matter_' from the description of ```about``` would broaden its usage a little. Resulting in the inference from your example:

_**temperature of the water body**_ is one of the **subject**(s) of this **Dataset**

I believe, with the established use of ```about``` for other CreativeWork types, plus some tweaking of its description, it is the most appropriate property for this use.

The alternative possibly could be the creation of a more specific property, which would probably end up being a sub-property of ```about```.  As such it would be difficult to justify without significant usage predictions.

**Comment by ashepherd** [comment]
Looking at the proposed schema.org mappings at [DCAT v2 - https://www.w3.org/TR/vocab-dcat-2/#dcat-sdo
](https://www.w3.org/TR/vocab-dcat-2/#dcat-sdo)

<img width="836" alt="Screen Shot 2019-05-21 at 12 55 34 PM" src="https://user-images.githubusercontent.com/2117576/58115437-08a1ae00-7bc8-11e9-97d2-5ef78c4877a3.png">

It seems @dr-shorthair agrees there might be a mismatch between `dcat:keyword` and `schema:keywords`.  NOTE: I added a table border in the attached picture so we could see which mappings and properties belong to dcat:keyword

If the intent of schema.org `keywords` is to mirror the meta tag `keywords` that makes sense now, and maybe we update [https://schema.org/keywords](http://schema.org/keywords) to clearly specify that intent?

@adamml and @fils make good points about needing a structure to describe scientific keywords.
Like the hierarchical SKOS used in the [initial issue](https://github.com/schemaorg/schemaorg/issues/2176#issue-423169959), NASA will have this problem with their hierarchical [GCMD Science Keywords vocabulary](http://earthdata.nasa.gov:443/about/gcmd/gcmd-keywords) ([JSON](https://gcmdservices.gsfc.nasa.gov/static/kms/sciencekeywords/sciencekeywords.json)).  These hierarchies are really helpful for improving precision and recall in search, and enabling a harvester to find and traverse that hierarchy could be very useful. But it's also important to be able to distinguish these conceptual ideas from other entities that the CreativeWork could be about.

The proposal to make a sub-property by @RichardWallis seems like a nice solution so that we can disambiguate the targets found from using `about`. Would a property like `containsConcept` work?

```
{
  "@context": {
    "schema": "http://schema.org/",
    "bibo": "http://purl.org/ontology/bibo/",
    "dc": "http://purl.org/dc/elements/1.1/",
    "dcat": "http://www.w3.org/ns/dcat#",
    "dct": "http://purl.org/dc/terms/",
    "dcterms": "http://purl.org/dc/terms/",
    "dctype": "http://purl.org/dc/dcmitype/",
    "eli": "http://data.europa.eu/eli/ontology#",
    "foaf": "http://xmlns.com/foaf/0.1/",
    "owl": "http://www.w3.org/2002/07/owl#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfa": "http://www.w3.org/ns/rdfa#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "schema": "http://schema.org/",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "snomed": "http://purl.bioontology.org/ontology/SNOMEDCT/",
    "void": "http://rdfs.org/ns/void#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "xsd1": "hhttp://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "containsConcept",
      "@type": "rdf:Property",
      "rdfs:comment": "Indicates a concept, subject, or general idea contained within a CreativeWork.",
      "rdfs:label": "containsConcept",
      "rdfs:subPropertyOf": {
        "@id": "schema:about"
      },
      "schema:domainIncludes": {
        "@id": "schema:CreativeWork"
      },
      "schema:rangeIncludes": {
        "@id": "schema:Thing"
      }
    }
  ]
}
```

Example: 
```
{
  "@context": "https://schema.org/",
  "@type": "Book",
  "@id": "https://www.wikidata.org/wiki/Q174596",
  "name": "Moby Dick",
  "containsConcept": [
    {
      "@type": "DefinedTerm",
      "@id": "https://www.wikidata.org/wiki/Q42767",
      "name": "whaling"
    },
    {
      "@type": "DefinedTerm",
      "@id": "https://www.wikidata.org/wiki/Q331432",
      "name": "fisher"
     }
  ]
}
```

**Comment by dr-shorthair** [comment]
[DCAT](https://w3c.github.io/dxwg/dcat/) also has 
- [dcat:theme](https://w3c.github.io/dxwg/dcat/#Property:resource_theme) which is a reference to a value from a 'controlled vocabulary'

`dcat:theme` is a sub-property of `dct:subject`. 

Of course DCAT is aimed at 'Dataset catalogs' (e.g. Google index?), for which there is a [specific class - `dcat:Catalog`](https://w3c.github.io/dxwg/dcat/#Class:Catalog) which can carry pointers to the controlled-vocabularies used to classify datasets in scope for the catalog, using the [dcat:themeTaxonomy](https://w3c.github.io/dxwg/dcat/#Property:catalog_themes) property. 

[Figure 1](https://w3c.github.io/dxwg/dcat/#dcat-scope) provides an overview of the DCAT model.

**Comment by RichardWallis** [comment]
We are seeing here the natural conflict between a domain specific vocabulary, DCAT for example, and a generic vocabulary such as Schema.org, that is not unique to the dataset domain.

In simple terms we have a Schema property that amongst other things can capture the relationship between a CreativeWork, and/or an Event, and a controlled vocabulary term - ```about```.

Understandably practitioners in that [dataset] domain are expressing concerns that it is not specific enough to describe that relationship to the level of detail required for the domain.  Hence, we have floated the possibility of proposing a more specific property to satisfy that need.

@ashepherd suggests a sub-property of ```about``` named ```containsConcept``` - "_Indicates a concept, subject, or general idea contained within a CreativeWork._"

Taking into account the generic nature of the applications of Schema.org, I have to wonder how such an additional property would add to the usability of the vocabulary.  How would those producing markup decide when to use either, or both properties?  Will data consumers be able to reliably differentiate between the values assigned to them, and how might their processing differ if they do? 

I note from following the links that ```dct:subject``` includes "_Recommended best practice is to use a controlled vocabulary._" in its description.  I would be in favour of adding something similar to the description of ```schema:about``` to provide a bit more of a hint to developers.

I believe the semantic value you are striving for, will more likely come from the the entity (DefinedTerm) identified by a URI, than from the specific name/description of the property it is a value for (beyond the current ```about```).

I still remain to be convinced that the current situation is not sufficient to capture the _about-ness_ of a dataset to aid its discovery and description. The equivalence mapping of properties such as ```dcat:theme``` then being to ```schema:about```.    For those wishing to add more semantic depth to their mark up, there would be no reason why they should not also publish DCAT along with the Schema - leaving it up to the consumers as to if it is used or not.

**Comment by adamml** [comment]
@RichardWallis To come back to your earlier comment, I think that your suggestion of altering the definition of Schema.org/about is probably the best approach for all our needs here.

What would be your recommended approach to push that discussion forward? Closing this issue and opening a new one, but referencing the discussion here? Or renaming this issue?

**Comment by RichardWallis** [comment]
@adamml I suggest a new issue, referencing the discussion in this issue which should be then closed.

Issue should contain a proposed rewording of the property description plus a _brief_ overview of why it is being proposed.

The addition of a new example or two, including one linking to an external authority may well also be helpful.

**Comment by adamml** [comment]
@RichardWallis Thanks you. And thanks for the constructive feedback and discussion here.

**Comment by dr-shorthair** [comment]
@RichardWallis in what sense do you refer to DCAT as 'domain specific'?

**Comment by RichardWallis** [comment]
@dr-shorthair  the domain of those attempting to describe datasets/catalogs, as against those describing bibliographic works, news articles, products for sale, events to attend, etc.
