### ISSUE TITLE
sameAs link language

### ISSUE THREAD

**Issue by dronur07** [schemaorg/schemaorg#2178]
Hello there.
I want to use schema.org/MedicalProcedure on related service/procedure page and under /availableServices in main page.
Dental crown (in english) = Kaplama diş (in turkish)
But when i check wikipedia for procedure i couldn't find any article in Turkish language.
Can i use an english version of this service?
	"sameAs": "https://en.wikipedia.org/wiki/Crown_(dentistry)",

```
<script type="application/ld+json">
{
	"@context": "http://schema.org",
	"@type": [
		"Service",
		"MedicalProcedure"
	],
	"alternateName": [
		"Kaplama Diş",
	],
	"name": "Diş Kaplaması",
	"url": "https://example.com/kaplama-dis/",
	"sameAs": "https://en.wikipedia.org/wiki/Crown_(dentistry)",
	"@id": "https://example.com/kaplama-dis/"
}
</script>
```

Thank you

**Comment by RichardWallis** [comment]
@dronur07 There are a couple of aspects to your question:
By referencing via sameAs another definition of what you are describing, you are referencing the concept of that thing, regardless of the language used in its description and the page on which it is described.

If you checkout the Wikidata term http://www.wikidata.org/entity/Q143720 (which is preferable to reference, than the Wikipedia text page) you will see that 'Crown' is labeled in English, French, German and several other languages including Turkish - 'Kuron'.

If that is incorrect you always have the option to suggest changes in Wikidata, or even create a Turkish page in Wikipedia.

As this issue is off topic for the issues around the Schema.org vocabulary itself, I will now close this issue.
