### ISSUE TITLE
Add Vehicle subtypes "Train", "Aircraft" and "Watercraft"

### ISSUE THREAD

**Issue by DarkenedSky** [schemaorg/schemaorg#2187]

**Comment by RichardWallis** [comment]
... and "Spacecraft" ?

**Comment by darkenedsky** [comment]
May eventually need to add other emergent transportation types such as Hyperloop.

**Comment by MichaelAndrews-RM** [comment]
I think the value of subtypes is when one identifies unique properties associated with them that are not available in an existing type.  Can @darkenedsky suggest some properties for each of these subtypes that would be useful and that aren't currently represented?

**Comment by darkenedsky** [comment]
Train might have # of cars, rail type (maglev or standard), and feature things like isPassenger or hasDiningCar, hasCowCatcher, etc. 

Watercraft would deal with things like wake and hull depth, hull construction, perhaps number/type of sails, registration number, port of call, etc.

Aircraft might need to know numberOfSeats (really this makes sense in base Vehicle), whether it has features like autopilot, emergency features, black box data, tail number...

Spacecraft might need to track things like missions, its power source (nuclear vs. solar vs. battery), whether it's crewed, whether it can dock with (or IS) the ISS, satellite frequencies and orbital identifiers, the space agency that operates it (NASA vs. DOD vs. ESA vs. SpaceX vs. Roscosmos, etc.) 

I don't know enough about Hyperloop as a technology to make an intelligent suggestion there.

**Comment by MichaelAndrews-RM** [comment]
Ok, there are different properties associated with different vehicle subtypes.  What decisions will be made with these properties?  People may choose a train with a Dining Car rather than one without one.

The core difference between train/aircraft/spacecraft and other vehicles such as cars is that cars are commonly bought, whereas trains are a mode of transit.  It may make more sense to talk about dining in the context of a [TrainTrip](https://schema.org/TrainTrip) rather than a train.  

Aircraft have different properties of interest to owners versus passengers.  This is the kind of detail within properties that need to be fleshed out.  How would people searching for information be considering these properties to make decisions?

**Comment by rvguha** [comment]
How about the transporter?

**Comment by darkenedsky** [comment]
@MichaelAndrews-RM You might use the train fields for things like train museums, or even *model* trains. Railroad museums or historical sites might use them, too. A TrainTrip might want to be associated with the Train it's on, just as a CruiseTrip (if that exists) would be associated with a Watercraft and an AirlineTrip would be associated with an Aircraft. Hopefully, a SpaceshipTrip is a thing soon too. ;)

Aircraft and watercraft are not AS commonly bought, but they certainly *are* commonly bought - personal planes and boats are certainly a thing. 

When I'm booking a flight, I look for things like "is it one of those turboprop planes?" It's certainly feasible, though I am no FAA engineer to know all the settings, to track valuable plane information for passengers. If I could look at two flights, and know one of them is on a plane with an extra 6 inches of legroom, for example, I'd be willing to pay an higher price for that.

Cruises in particular can be booked for many lengths and destinations, but they normally list not just the model of boat (because they're unique), but a SPECIFIC ship - so you might want to associate all the amenities and measurables of say, the Disney Magic, with the cruises you can book on it.

**Comment by danbri** [comment]
Unless there is a *consuming application* needing data with such distinctions (and eventually, properties devoted to these subtypes) why don't we just point to Wikipedia for special kinds of vehicle, -

e.g. 
> "additonalType": "https://en.wikipedia.org/wiki/Transporter_(Star_Trek)" ...

**Comment by mfhepp** [comment]
Or better, use the identifiers from www.productontology.org, which are more precise as identifiers for classes of products.

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by rvguha** [comment]
There are a ton of schemas out there, including Dr. Hepp's
productontology.org, which have identifiers. Just make sure that you use
one that is recognized by the consuming application.

**Comment by WeaverStever** [comment]
@mfhepp 

I'm curious as to what www.productontology.org does.  The tool seems to create a URI for just about any Wikipedia article, regardless as to if it is a Product.  The http://schema.org/additionalType property has Thing as an expected type. Is there a benefit to using productontology when the item isn't exactly a product?

Additionally, the Wikipedia 'community' has become quite hostile to anyone wishing to enter information about a product or organization, is somebody addressing this?

**Comment by danbri** [comment]
Or Wikidata.

**Comment by sdml** [comment]
@WeaverStever 
www.productontology.org is a convenient provider of a http://schema.org/Product or owl:Class when you need one (Wikipedia URLs are not classes).
It's not a product dictionary because, as you noticed, not every Wikipedia article makes a valid product class, but citing www.productontology.org: there is absolutely no harm in providing a nonsense class definition, unless someone uses this to annotate an object.
