### ISSUE TITLE
MedicalStudy -> generic study

### ISSUE THREAD

**Issue by rektide** [schemaorg/schemaorg#2228]
It would be useful to be able to talk about a study. For instance, the Public Life Data Protocol [defines a Study object for itself](https://github.com/gehl-institute/pldp/blob/master/Public%20Life%20Data%20Protocol/PLDP_BETA%20Publication%20-%2020170927.pdf#page=). 

There exist some related ideas already-
https://schema.org/MedicalStudy
https://schema.org/CohortStudy - which is weirdly totally empty & not derived from anything like a thing

In general let me just quietly say I find the addition of Medical[X] to schema.org to be hugely kludged. MedicalThing was a mistake, done of convenience for some end users, but best expressed piecewise, and very few of it's properties are specific to medical entities: other entities ought have study, relevantSpecialty, recognizingAuthority, legalStatus, guideline, code. This weirdly bodged on secondary vocab deserves better than this fate.

**Comment by RichardWallis** [comment]
On the subject of [CohortStudy](https://schema.org/CohortStudy).  You are seeing an issue (#2215) with the latest release (3.5) where certain enumeration values are not connected with their enumeration type.

You can see what it will look like (in 3.6) on the development site: https://webschemas.org/CohortStudy

**Comment by MichaelAndrews-RM** [comment]
I was not involved in creating the MedicalEntity section, but it seems to me very successful in capturing important kinds of data.   Schema.org is a general-purpose vocabulary, and medical data has wide interest for different kinds of consumers, including platforms and applications used by healthcare provides and patients, as well as by research scientists.  The relationships between data relating to studies and other entities is well-established and widely-utilized across different use cases.  Patients may have a condition and need to know what clinical trials relate to that condition.  The properties are defined specifically as relating to medical studies, rather than to other sorts of studies.

I would be surprised if a more generic definition of terminology relating to 'studies' would be as successful capturing these relationships between entities.  

Other kinds of studies relating to physical sciences or social sciences may not have the same widely-used predictable relationships that apply to medical studies, and they would likely not have as wide interest that medical study data  enjoys.  I would expect that other ontologies exist or are being developed that address different kinds of studies relating to specific fields of knowledge.

**Comment by twamarc** [comment]
Let me jump in this discussions, and thank @MichaelAndrews-RM highlighting the usefulness of the vocabulary. As someone involved in shaping it we are expecting having it growing based on community needs. Also some issue are continuously being fixed (thanks to @RichardWallis tests... and other raised issues). Like other initiative that are working together (or worked together with schema.org like [https://biocaddie.org/](url), it would be nice to see how the Public Life Data Protocol can help shaping some items. @rektide please visit https://www.w3.org/community/schemed/ for more info, and get involved.

**Comment by RichardWallis** [comment]
Closed in favour of issue #2229

**Comment by RichardWallis** [comment]
PR #2614 should have improved things here
