### ISSUE TITLE
Schema for educational programs

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2289]
When designing http://schema.org/Course, the original thought was we could use the type for individual classes like "Physics 101" and programs like "Masters of Science in Physics".

After exploring websites and the data available, we propose the following. Thanks to @philbarker and @stuartasutton for early feedback particularly in linking to the work around credentials.

Thing > Intangible > EducationalOccupationalProgram: A program written by an institution which determines the learning progress to achieve an outcome, usually a credential like a degree or certificate.

Thing > Intangible > EducationalOccupationalProgram > WageBasedTraining:  A program with both an educational and occupational component.

Properties include:
occupationalCredentialAwarded: An occupational credential awarded by the program.
programPrerequisites: Prerequisites for enrolling in the program.
timeToComplete: The expected length of time to complete the program if attending full-time.
trainingSalary: The estimated salary earned while in the program.
salaryUponCompletion: The expected salary upon completing the training.

And modify the following properties to include EducationalOccupationalProgram in the domain:
occupationalCategory
offers
provider

I will attach examples in a follow up pull request.

**Comment by vholland** [comment]
See PR #2290

**Comment by philbarker** [comment]
@vholland thanks for putting this together. It looks pretty much like I expected from our discussions. 

Some questions:
 
Doesn't this also add:
  hasCredential: "A credential awarded to the Person or Organization." 
to Person and Organization (which I think is a useful addition).

How would I say which courses are associated with a EducationalOccupationalProgram ? There's scope for requiredCourse and optionalCourse properties. But some requirements can be complex (e.g. "any two from these six, plus two others at level 4"), so maybe raise an issue to discuss these separately?

Would it be better if the definition of occupationalCredentialAwarded mirrored that of  [educationalCredentialAwarded](https://schema.org/educationalCredentialAwarded) ? I particularly dislike that the proposed definition "An occupational credential awarded by the program" seems to give the program agency which kind of muddies understanding of what the Program is.

Maybe also add occupationalCredentialAwarded to Course?

I may have missed it, but do you change the domain of educationalCredentialAwarded to include EducationalOccupationalProgram ? (It should be changed, and I see it used in the examples)

**Comment by vholland** [comment]
1. Yes, I added hasCredential, but I forgot to list it as the domain is Person or Organization rather than EducationalOccupationalProgram.

2. I hadn't gotten to linking courses to EducationalOccupationalProgram as it is complicated. (As you know.) and hoped to tackle that separately.

3. Yes, I meant occupationalCredentialAwarded to mirror educationalCredentialAwarded. I can update that.

4. Yes, adding occupationalCredentialAwarded to Course makes sense.

5. I think I missed updating the domain for educationalCredentialAwarded in the PR. I can update that.

**Comment by stuartasutton** [comment]
@vholland & @philbarker, as per Vicki's no.2 and Phil's comment on associated courses and the potential complexity: Because of the selection complexities that Phil notes (as well as course prerequisite structures imposing sequencing), I assume the use down the road of a pathway entity to frame such choices, prerequisite sequencing etc. In cases where we are simply looking at markup, trying to capture this complexity may be overkill--quite another matter if one wants to provide fuller descriptive metadata on EO programs.

**Comment by danbri** [comment]
Thanks all. Sounds like this is shaping up well. Phil/Stuart, from your perspective would this be better off published in Pending area of Schema.org (on the understanding it may get tweaked a little during feedback/discussion), or should we discuss a little more here first?

@vholland - if you get time to update the PR with the points above that would be great, otherwise the todos look fairly straightforward so I can pick it up if you prefer

**Comment by philbarker** [comment]
I would like to discuss it here first, but not for long. @danbri -- are you planning a 1 August release? Though I could live with it going in now and being tweaked later.

I'ld like to check how the definition works alongside that Course. How do we make it clear to, for example, the University of Edinburgh that the things in [their Course finder](https://www.ed.ac.uk/global/study-abroad/course) are programs not courses? (or are they both?)

Could we say that a Course cannot contain a Program, but a Program can contain Courses? Or say that a Program will normally have several courses and/or occupational placements?

We all agree about associated courses and potential complexity, but calling out how to list the component courses (as the [University of Bristol does](https://www.bris.ac.uk/unit-programme-catalogue/RouteStructure.jsa?byCohort=N&ayrCode=18%2F19&programmeCode=2PHYS001U)) seems one way of clarifying what a program is. As to it being overkill--yes, putting in all pathway options would be, but simply saying that "you're going to have to do a lot of maths" or "yes, you can take some philosophy classes" seems useful in discovery use cases.

**Comment by stuartasutton** [comment]
+1 on first quickly seeing how this meshes with Course. Phil, this is obviously one of those cases where a national common use (i.e., UK Course as both/either course or program) rubs a bit uncomfortably with a context that wants to distinguish the two. We did recognize with Course that explaining to the rest of the world that it denoted both was equally problematic...even in the US it can be blurry; e.g., a common phrase for what we are defining here as program is "course of study" :-(.  

Nevertheless, this EducationalOccupationalProgram and its companion Course, is clean and calls for less fuzzy explanations. 

+1 on lists of component courses (and not so much on expressing "this or that course " or "pick any two from this array of 10 courses" without reference to a yet non-existent Pathway entity intended to handle such complexity.).

**Comment by alanepaull** [comment]
I'm not certain that programmes in the UK usually contain the "pick any 2 from 10" kind of options at programme level. This is usually handled at course / pathway level. The programme is the overarching thing that contains the courses or pathways. Then, each of those courses or pathways may require mandatory and / or optional module selections by the student.

This would tend to make the programme / program simpler to understand. For example, The Open University has one of our most complex qualification frameworks; many of their programmes have a "main" pathway (like Computing & IT), and multiple specialist pathways (like Computing & IT and Business). Each pathway has different choices for students to make for their specialist pathway, but may have compulsories and optionals for the main pathway.

A student always does a specific course or pathway; they don't do a programme in this particular definition. They're picking a course or pathway from a programme, and may sometimes be able to change direction.

"Thing > Intangible > EducationalOccupationalProgram: A program written by an institution which determines the learning progress to achieve an outcome, usually a credential like a degree or certificate."
In many cases, the programme might lead to one or more of several outcomes for each individual student. Maybe this definition could be "... a range of outcomes, usually credentials like a degree or certificate."?

**Comment by philbarker** [comment]
Picking up on @alanepaull's points, while the OU is not a typical example of how UK Universities arrange programmes / courses, it may be closer to the US Higher Ed approach.

So is EducationalOccupationalProgram here intended to cover what UCAS calls Courses in its search tool https://digital.ucas.com/search ? 

In which case Alan's pathways such as 'Computing & IT' and specialist pathways 'Computing & IT and Business' would be different EducationalOccupationalPrograms, even though they share many courses/units/modules. Even within these there are often still course (i.e unit/module) choices to be made. These are what a searcher would want to find if they wanted to know how to get a bachellor degree in Computing & IT

If not, the I guess theEducationalOccupationalProgram is something like everything the Computer Science department teaches, In which case what would the 'courses/pathways/programmes' on UCAS be classed as?

All the more reason for a clear definition.

**Comment by science** [comment]
As one of the maintainers of the open source [Credential Registry](https://github.com/CredentialEngine/CredentialRegistry/) project, having more of this type of data available in schema.org is immensely helpful. +1 in support.

**Comment by alanepaull** [comment]
The UCAS system contains things that students actually apply for. Some of these will be straightforward single subject courses, or defined combined subject courses, but the main differences are in more general combined subject courses or broad subjects of study, like Humanities or Natural Sciences. These latter can contain many pathways, even though the student applies for the general 'programme' - see Lancaster Natural Sciences for an example: https://digital.ucas.com/courses/details?coursePrimaryId=415be518-7edf-c936-9396-6364acac1709&academicYearId=2019
https://www.lancaster.ac.uk/study/undergraduate/courses/natural-sciences-bsc-hons-gfc0/

The complexity here led us in the XCRI-CAP development to decide that a 'course' was whatever a university wanted it to be, as a good definition was pretty much impossible. So, a broad definition of EducationalOccupationalProgram is a very good idea, the fewer restrictions on how folks handle this and associated properties, the better.

Multiple pathways and multiple credentials from one programme would be a good idea. For example, the Lancaster Natural Sciences can lead to MSci or BSc etc. PG programmes often include Masters, PgDip and PgCert as possible outcomes.

**Comment by vholland** [comment]
@danbri @philbarker 

I updated the pull request. PTAL.

**Comment by jkitchensSIUC** [comment]
Hi all.  Am I too late to this conversation?  I have some feedback on "Thing > Intangible > EducationalOccupationalProgram > WageBasedTraining: A program with both an educational and occupational component."  

If Career and Technical Education (CTE) program and many postsecondary degree program faculty saw this, they'd say that all of the programs have both educational and occupational components.  The term EducationalOccupationalProgram already implies this. The definition of the term WageBasedTraining as proposed with this issue is puzzling.  The label implies "training formatted so the participant is earning wages within the occupation for which they are preparing." 

At least in the U.S. middle grades to secondary/high school grades offer CTE programs that all include academic (e.g., math, science, social science, reading) and job--specific competencies.  Many postsecondary degree programs require an internship, either paid or unpaid, or some type of work-based learning to complete graduation requirements. 

If the purpose of the WageBasedTraining is to differentiate programs that are formatted so participants are earning wages within the occupation for which they're preparing, the definition could be clearer.   

Also, I'm wondering if terms such as "trainingSalary" will be included with JobPosting and I know Educational Occupational Credential is still in Pending https://schema.org/EducationalOccupationalCredential but it's properties are applicable here.  Will Educational Occupational Credential be moved to core in tandem with EducationalOccupationalProgram as the two are complimentary?

**Comment by philbarker** [comment]
Agree with @jkitchensSIUC especially about the definition of WageBasedTraining not capturing what distinguishes it from other types of program.

@vholland  I've not been able to get the latest pull request to validate and am having difficulty in seeing what has changed. Sorry, won't be able to look at it soon as I'm away from work for two weeks from Friday.

**Comment by danbri** [comment]
Heads up that I plan to fold this in to (pending area of) next release, on expectation that we can continue to tweak the definition based on ongoing discussions. Getting it into the site should help engage others in the discussion.

**Comment by danbri** [comment]
Ok, this is accessible now via https://webschemas.org/EducationalOccupationalProgram and nearby

Quick fixes welcomed, as I will soon send around this v3.9 draft site for release review.

**Comment by danbri** [comment]
Some more thoughts on tweaking these definitions. We have been exploring the use of this kind of markup at Google.  To see (in the US) the pilot product in Virginia, try “job training in Richmond, VA” in Google Search.  Users can click to explore in-demand job fields and the local programs that help them get there.

For the definitions:
* EducationalOccupationalProgram: A bundle of discrete opportunities (e.g., job, courses) that together constitute a program with a clear start, end, set of requirements, and transition to a new occupational opportunity (e.g., a job), or sometimes a higher educational opportunity (e.g., an advanced degree).
* WageBasedTraining: There is a spectrum from a purely educational program to a pure job.  EducationalOccupationalProgram is in the middle.  WageBasedTraining is closer on the spectrum to a job, but still falls under an educational program.  The key difference is not if a paid opportunity is available, but that it is guaranteed.

The current draft text implemented is:
* EducationalOccupationalProgram: A program offered by an institution which determines the learning progress to achieve an outcome, usually a credential like a degree or certificate.
* WageBasedTraining: A program with both an educational and occupational component.

I'd like to go ahead with updating these towards incorporating the text/ideas above, for the August 1st Schema.org 3.9 release, unless there is any great dispute about the wording.

**Comment by stuartasutton** [comment]
Dan, just a couple of observations regarding the revised definitions:

1. With EducationalOccupationalProgram, is it that any old "bundle of discrete opportunities" is OK? Or is it some form of "prescribed bundle of discrete opportunities". Even a program that is tailored to an individually ends up being prescribed in that the sense that it is official only when some qualifying entity approves it. 
2. With WageBasedTraining, what's being alluded to with "key difference"? Different from what? EducationalOccupationalProgram? What's guaranteed? Availability or pay?

In the end, the definitions are a bit long...

**Comment by jkitchensSIUC** [comment]
Dan, your comment indicated, "The key difference is not if a paid opportunity is available, but that it is guaranteed."  What is the guarantee?  Is it that any employer is 100% committed to bringing a person on the payroll based on them completing an EducationalOccupationalProgram?  If the answer is yes, I would think there would be dependencies beyond completing the program making the program only part of the requirements to get the job.  In the US, I still feel that label eludes to a learn and earn program such as apprenticeship.  If a property is needed to indicate the employer requires the program, and those who complete it will be hired, it could be labeled differently and you may want to consider a term for programs that require on the job training that earns income while completing qualifications for a work-based program such as apprenticeship.

**Comment by perani** [comment]
Thanks for the additional comments.  I'm working on this with Dan.  Stuart -- I agree with you on the prescribed bundle of discrete opportunities.  That makes sense to me.

With regards to WageBasedTraining: the key distinguishing factor from EducationalOccupationalProgram is that these trainings guarantees a wage to the person in the program while in the program, should the person be selected. WageBasedTraining would not apply to a program that advertises itself as having an occupational component (such as an internship) but does not actually pay or make sure that the trainee is paid.  The guarantee isn't about employment after completion of the program.

**Comment by philbarker** [comment]
Thinking about WageBasedTraining after a short break I have a question: if an employer pays for an employee to go to university (including tuition fees and maintenance) does that count as wage based training? There are a number of ways that this can happen and whether such payments count as a "wage" seems to depend on factors more related to tax law than the nature of the educational programme.

It seems to me that the key distinguishing factor of apprenticeships and the like compared to college courses is that the training is work-based rather than classroom-based. This seems similar to what UNESCO call work-based learning (see https://unevoc.unesco.org/go.php?q=TVETipedia+Glossary+A-Z&id=463 ), though work-based learning can be a component of a conventional college-based program. So how about WorkBasedProgram or WorkBasedLearningProgram?  Defintion: an EducationalOccupationalProgram based at a workplace structured with the aim of instilling competencies related to an occupation.

**Comment by perani** [comment]
Phil, this idea is interesting.  Both WorkBasedLearning and WageBasedLearning designation can build a bridge between education and jobs designations.  It can be hard with WorkBasedLearning, though to draw the line, whereas WageBasedLearning has a more clear delineation.  I'd consider unpaid internships or hospital rotations while in medical school.  We also see health care employers running work-based health care schools.  These are certainly work-based, but don't pay a wage to the student.  In the US, at least, the fact that the position is for a wage makes it closer to a real job than the typical educational program.  What do you think?

**Comment by perani** [comment]
Dan and I put our heads together after the feedback.  We propose this updated set of definitions for the August 1st Schema.org 3.9 release:

**EducationalOccupationalProgram**: A program offered by an institution which determines the learning progress to achieve an outcome, usually a credential like a degree or certificate.  This would define a set of discrete opportunities (e.g., job, courses) that together constitute a program with a clear start, end, set of requirements, and transition to a new occupational opportunity (e.g., a job), or sometimes a higher educational opportunity (e.g., an advanced degree).
**WageBasedTraining**: A program with both an educational and occupational component. WageBasedTraining is distinguished from EducationalOccupationalProgram in general, through offering roughly "paid to learn" roles that involve a strong commitment to a wage. These are often but not necessarily work-based rather than classroom-based.

**Comment by philbarker** [comment]
@perani You mention WorkBasedLearning/WageBasedLearning. I think it is true that many educational programs will have an elements of work based learning and classroom based learning, which is why I would focus on the nature of the **program**. I don't think a short internship / work experience makes a College based programme work-based.

Is "wage-based learning" similar to any term in use in the US? I can find 9 results for it through google (with quotes), and "wage-based program" finds a couple of thousand but I think these mostly relate to (non-education) social security programs.  "Work-based learning" is an established term in education, yielding 5 million results. I think that using this familiar term to define the nature of the program will help people understand what is intended.

Iterating on my suggested term name and definition:
WorkBasedProgram: an EducationalOccupationalProgram based at a workplace, predominately structured around work based learning, with the aim of instilling competencies related to an occupation. Such programs often involve employment with organization at which they are based.  Used to distinguish programs such as apprenticeships from school, college or other classroom based educational programs.

Whatever the you decide for the label, I think that definition is a lot better than the current draft (but feel free to adapt & improve where it doesn't fit).

**Comment by perani** [comment]
I like your suggestion.  How about:

WorkBasedProgram: A program with both an educational and occupational component. Typically based at a workplace and structured around work based learning, with the aim of instilling competencies related to an occupation. Such programs tend to involve employment with the organization at which they are based. Used to distinguish programs such as apprenticeships from school, college or other classroom based educational programs.

**Comment by philbarker** [comment]
@perani still not sold on leading with "A program with both an educational and occupational component" as most post-secondary programs would match that criterion as @jkitchensSIUC [says above](https://github.com/schemaorg/schemaorg/issues/2289#issuecomment-507811766), but as a whole I think that definition makes the intent clear. How changing that first sentence to "A program with both an educational and employment component"

**Comment by danbri** [comment]
This is shaping up. I'd like a sense for how much weight we put on the strength of the commitment to paid employment. While "tend to involve employment" feels a little weak, and it is such a broad range of situations covered here, I think we somehow want to keep the work aspect central otherwise it is hard to see why a dedicated schema type would be needed. 

Actually as I drafted this, Phil suggests the leading sentence changes to "A program with both an educational and employment component", which I think helps here

**Comment by danbri** [comment]
OK, thanks everyone. I think this is where we are now:

* EducationalOccupationalProgram: A program offered by an institution which determines the learning progress to achieve an outcome, usually a credential like a degree or certificate. This would define a set of discrete opportunities (e.g., job, courses) that together constitute a program with a clear start, end, set of requirements, and transition to a new occupational opportunity (e.g., a job), or sometimes a higher educational opportunity (e.g., an advanced degree).
* WorkBasedProgram: A program with both an educational and employment component. Typically based at a workplace and structured around work-based learning, with the aim of instilling competencies related to an occupation. WorkBasedProgram is used to distinguish programs such as apprenticeships from school, college or other classroom based educational programs.
 
These seem to be clear improvements on the currently staged draft definitions so I'll get them updated for the upcoming monthly release. We can continue to refine these in the light of experience, of course.

**Comment by stuartasutton** [comment]
One comment, Dan. There is a difference between a "discrete opportunities" and "discrete set of opportunities".  The latter was what I had suggested. The former leaves the problem I saw initially in place...i.e., it's not just any set of opportunities but a discrete set.

**Comment by danbri** [comment]
So:

"EducationalOccupationalProgram: ... This would define a set of discrete opportunities"
becomes
"EducationalOccupationalProgram: ... This would define a discrete set of opportunities" ?

**Comment by perani** [comment]
@danbri 

Works for me.

**Comment by perani** [comment]
@danbri 

"discrete set of opportunities" makes sense.

**Comment by danbri** [comment]
Drafts queued for release,

* https://webschemas.org/EducationalOccupationalProgram
A program offered by an institution which determines the learning progress to achieve an outcome, usually a credential like a degree or certificate. This would define a discrete set of opportunities (e.g., job, courses) that together constitute a program with a clear start, end, set of requirements, and transition to a new occupational opportunity (e.g., a job), or sometimes a higher educational opportunity (e.g., an advanced degree).
* https://webschemas.org/WorkBasedProgram
A program with both an educational and employment component. Typically based at a workplace and structured around work-based learning, with the aim of instilling competencies related to an occupation. WorkBasedProgram is used to distinguish programs such as apprenticeships from school, college or other classroom based educational programs.

**Comment by danbri** [comment]
https://schema.org/docs/releases.html#v3.9 was just published. It 
includes https://schema.org/WorkBasedProgram and https://schema.org/EducationalOccupationalProgram in the pending section! Let's keep this issue rolling to handle feedback and improvements.

**Comment by danbri** [comment]
I forgot to say: *huge thanks* to everyone who helped here. This is a difficult and slippery topic to standardize around, and we couldn't do it without the group effort...

**Comment by RichardWallis** [comment]
Implemented in [Release 4.0](https://schema.org/docs/releases.html#v4.0)
