### ISSUE TITLE
Proposal for representing Aggregate Statistical Data

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2291]
Proposal circulated to various lists by @rvguha,

* [public-schemaorg](https://lists.w3.org/Archives/Public/public-schemaorg/2019Jun/0021.html)
* [Google doc version](https://docs.google.com/document/d/139jXakeQk4ChwCkGjqq5wJfCPMDnwIV94oCH-JzJrhM/edit?usp=sharing)
* nearby: [publishing-statistical-data](https://groups.google.com/forum/#!forum/publishing-statistical-data), [public-semstats](https://lists.w3.org/Archives/Public/public-semstats/2019Jun/0000.html) lists.
# Vocabulary

* new type: StatisticalPopulation
 * new properties: populationType, numConstraints, constrainingProperties
* new type: Observation 
 * new properties: observedNode, measuredProperty, measuredValue, observationDate, marginOfError, measurementMethod

# Related work 
* See also extensive [related reading](https://github.com/laurentlefort/semantic-statistics/wiki/RDF-Data-Cube) list (RDF Data Cube etc), from @laurentlefort
* [linked-sdmx](https://github.com/csarven/linked-sdmx)

**Comment by RichardWallis** [comment]
Implemented in V3.9

**Comment by VladimirAlexiev** [comment]
# constrainingProperties Bug

Compared to the proposal https://lists.w3.org/Archives/Public/public-schemaorg/2019Jun/0021.html, this task is not implemented well and should be reopened.

https://schema.org/StatisticalPopulation says:
> The properties numConstraints and constrainingProperties are used to specify which of the populations properties are used to specify the population. 

But:
- there is `constrainingProperty` not `constrainingProperties`
- `constrainingProperty` has range integer. Instead it should have range `s:Property` (and should be multivalued)
- The examples from the proposal are not implemented
- One example uses prop `median` which is not explained (other statistical concepts to be covered are average, min, max, variance, stdDev, quartiles...)
- Many examples use `measuredProperty: count`. Please give a real example how to express count, because it's the most common measure.


One of the examples goes like this:

```turtle
:pop a s:StatisticalPopulation;
  s:populationType s:Person;
  s:numConstraints 1;
  s:constrainingProperty s:homeLocation;
  s:homeLocation :East_Podunk_California.

:obs a s:Observation;
  s:observedNode :pop;
  s:measuredProperty: :POPULATION; # HOW to express this?
    # This is SDMX population, or some GS1 prop, or maybe I can omit it since it's just a count?
  s:measuredValue 10000;
  s:observationDate "2020-10-30"^^xsd:date.
```

# Direct Observations

If I have a prop `:POPULATION` at my disposal, why can't I use it directly like this?
```
:obs a s:Observation;
  s:observedNode :East_Podunk_California;
  s:measuredProperty: :POPULATION;
  s:measuredValue 10000;
  s:observationDate "2020-10-30"^^xsd:date.
```

This covers the most common case where you observe some characteristic of an entity, without subdividing the characteristic further. Eg Wikidata has Place.population, Company.turnover, Company.revenue, etc.

How can you express `Google has turnover of 100M USD in 2019` with `StatisticalPopulation` ?? (see example below)

Also, `observedNode` is a terrible name because it's technology-bound. (It's an IT term not an economics or statistics term).

PROPOSAL: rename `observedNode` to `observedThing` and change its range to Thing

# observationDate vs reference period

Consider these observations about Google:
```ttl
:obs1 a s:Observation;
  s:observedNode wd:Q95;
  s:measuredProperty wd:P2403; # total assets
  s:measuredValue 2000000000;
  s:observationDate "2019"^^xsd:gYear.

:obs2 a s:Observation;
  s:observedNode wd:Q95;
  s:measuredProperty wd:P2139; # total revenue
  s:measuredValue 1000000000;
  s:observationDate "2019"^^xsd:gYear. ####
```

- `obs1` is ok, it says the assets as of that point in time were that much.
- But `obs2` is not quite ok because sales (revenue) are not measured at a point, they occur over a period (year, quarter, etc). So we need something like this:

```ttl
# yearly revenue 2019
:obs2 a s:Observation;
  s:observedNode wd:Q95;
  s:measuredProperty wd:P2139; # total revenue
  s:measuredValue 1000000000;
  s:observationPeriod "2019"^^xsd:gYear.

# quarterly revenue 2019Q1
:obs2 a s:Observation;
  s:observedNode wd:Q95;
  s:measuredProperty wd:P2139; # total revenue
  s:measuredValue 250000000;
  s:observationPeriodStart "2019-01"^^xsd:gYearMonth;
  s:observationPeriodEnd   "2019-03"^^xsd:gYearMonth.
```

Actually it's better to use precise dates and to always do it with two props:

```ttl
# yearly revenue 2019
:obs2 a s:Observation;
  s:observedNode wd:Q95;
  s:measuredProperty wd:P2139; # total revenue
  s:measuredValue 1000000000;
  s:observationPeriodStart "2019-01-01"^^xsd:date;
  s:observationPerioEnd    "2019-12-31"^^xsd:date.

# quarterly revenue 2019Q1
:obs2 a s:Observation;
  s:observedNode wd:Q95;
  s:measuredProperty wd:P2139; # total revenue
  s:measuredValue 250000000;
  s:observationPeriodStart "2019-01-01"^^xsd:date;
  s:observationPeriodEnd   "2019-03-31"^^xsd:date.
```

**Comment by VladimirAlexiev** [comment]
# Can't Record Multiple Measures of Same Point

How would you you represent this: an air balloon is rising, and every 10s records altitude, pressure and temperature.

Compared to W3 Cube, this is ill-conceived and badly executed.

**Comment by dr-shorthair** [comment]
@VladimirAlexiev suggest you create a new issue? (linked back to this one, which is already closed).

**Comment by VladimirAlexiev** [comment]
@dr-shorthair You think it's worth it? Don't want to waste my time:
Google's faling the schema.org community https://github.com/schemaorg/schemaorg/issues/2573

**Comment by smrgeoinfo** [comment]
The term 'observation' has a much broader meaning in the physical science community (see https://www.w3.org/TR/vocab-ssn/#SOSAObservation), so limiting the rangeIncludes on  schema:observedNode property to schema:StatitisticalPopulation is unnecessarily constraining. This is based on the correlation of 'schema:observedNode with [sosa:hasFeatureOfInterest](https://www.w3.org/TR/vocab-ssn/#SOSAFeatureOfInterest).

Alignment with the SOSA model would be really useful for those of us working on [Science on Schema.org](https://github.com/ESIPFed/science-on-schema.org). To that end, the schema:Observation model would need to include properties like schema:measurementTechnique (analogous to sosa:usedProcedure), phenomenonTime, resultTime, and madeBySensor to specify the instrumentation used.   

One niggling question is what are the use cases that distinguish schema:Observation from schema:PropertyValue, i.e. what is the domain of schema:Observation if not schema:Dataset?  (SpecialAnnouncement??? )  

see also https://github.com/ESIPFed/science-on-schema.org/issues/143

**Comment by dr-shorthair** [comment]
I did a mapping SOSA <--> schema.org here: https://github.com/w3c/sdw/blob/gh-pages/ssn/rdf/sosa-sdo-mapping.ttl

**Comment by stain** [comment]
As a historical note - these terms (which pointed to this issue) were removed from _pending_ in release 16.0:

- [http://schema.org/constrainingProperty](https://web.archive.org/web/20220601153100/http://schema.org/constrainingProperty)
- [http://schema.org/measuredValue](https://web.archive.org/web/20220607033103/https://schema.org/measuredValue)
- [http://schema.org/observedNode](https://web.archive.org/web/20220608082318/https://schema.org/observedNode)

16.0 added these statistical terms (#3238 #2564):

- http://schema.org/ExampleMeasurementMethodEnum
- http://schema.org/MeasurementMethodEnum
- http://schema.org/ConstraintNode
- http://schema.org/StatisticalVariable
- http://schema.org/constraintProperty
- http://schema.org/measurementDenominator
- http://schema.org/measurementMethod
- http://schema.org/measurementQualifier
- http://schema.org/observationAbout
- http://schema.org/statType
