### ISSUE TITLE
Effective Schema Markup or Data Structure for Banking, Financial, or Loan Business

### ISSUE THREAD

**Issue by johnomahoy** [schemaorg/schemaorg#2310]
Hi guys, I just wanna ask what are effective schema mark up for types of business like Banking, Financial, Loans. Its services include personal, home, and mortgage loans. I have heard about banking and financial institution markup as well as conceptual map and hierarchical financial extension.

**Comment by johnomahoy** [comment]
thank you for this

**Comment by fourdata** [comment]
The idea of having a standard for investment funds is very interesting.

Fund data is very difficult and prohibitive to get hold of. The idea of standardising the data points for funds is welcome and probably overdue. The industry has struggled to really get anything working. And the idea of embedding/tagging data points already present in websites is a great idea.

Looking through the list of fields, it is a bit bare, and some of them not making too much sense in the context of funds.

To make it useful, I'd expect to see.

-InvestmentAssetClass (Equity/Bond/Commodity/Mixed)
-InvestmentSubClass (<Country>/<Region>/<Currency>/<TypeOfCommodity>)
BondCharacteristics(Corporate/Govt/Supranational/Long/Medium/Short/InvestmentGrade/HighYield/...)
-LegalStructure (ICVC/ETF/Investment Company/Unit Trust/OEIC/SICAV/...)
-InvestmentObjectiveText
-Benchmark
-CountriesForSaleIn (And which market can buy them inst/retail/exempt)

-EntryCharge
-AnnualManagementCharge
-OngoingCharge (there a quite a few permutations of these, eg MIFID/UCITS/.. and forward looking and backward looking, so not sure how best to capture this, unless all are explicitly given field names)
-ExitCharge
-IsDistributingShareClass

-Valuation (again there are a number of types of price Nav/Bid/Offer/FVMP)
-Valuation date
-Last Distribution
-Last Distribution Breakdown (interest/equity/...)
-Last Distribution XD Date
-Last Distribution Pay Date
(ideally there would be history of such as well, but not sure if schema supports the concept of time series data)


-factsheet-en-us(link to english factsheet document for us residents)
-pointofsaledoc-en-us(link to regulatory point of sale document in english)

How are the set of fields maintained for schema.org/InvestmentFunds?

**Comment by RichardWallis** [comment]
@fourdata  As per the acknowledgement, many of the initial set of types and properties for financial  associated entities came from the work of the [W3C Financial Industry Business Ontology Community Group](https://www.w3.org/community/fibo/) and supporting individuals and organisations.

Since that time there have been no proposals, other than the odd tweak, to build upon their work.

To move things forward in the way you describe, would be best achieved putting together a proposal for such enhancements, with types, properties and their descriptions plus some example markup.  Such a proposal should ideally be accompanied by some real world use cases and an an indication of potential consumers of the data when shared on the web.

For more general information see: [HowWeWork](https://schema.org/docs/howwework.html)

**Comment by trypuz** [comment]
Hi! I was involved in creating the financial/fibo extension to schema.org. Please consult the doc for this extension: https://schema.org/docs/financial.html. It is very helpful. BTW, the financial extension to schema.org was created on the basis of the Financial Industry Business Ontology. I believe that the next extensions should be also aligned with FIBO.

**Comment by RichardWallis** [comment]
Answered

**Comment by mikcaweb** [comment]
Is there a vocabulary or owl group for Personal Financial Data which could be used for a Personal Financial Statement?
