### ISSUE TITLE
How to store the result of a football event

### ISSUE THREAD

**Issue by julienhohm** [schemaorg/schemaorg#2336]
Hello,

I'm working on a project to create an API to get games and rank of a football championship.
I want to store items in database following the schema.org rules.
So, I use **SportsOrganization** for the sports, in case of multi sports API in the future, **SportsOrganization** for the differents championships like Ligue 1, Liga, Champion's League, etc, **EventSeries** to store the calendar of a championship and **SportEvent** to store the game between two teams.

In my **SportEvent**, I have _homeTeam_, _awayTeam_ and _startDate_.
However, after many searches, I still don't know what range should be my property _score_.

Is someone could help me ?
Many thanks

**Comment by Aaranged** [comment]
The short answer here is that, AFAIK, there is currently no way to express the _results_ of a `SportsEvent` using schema.org.

Extending the existing sporting event-facing vocabulary has been much discussed over the years. You can see a number of prior proposals archived [here](https://www.w3.org/wiki/WebSchemas/Sports).

You might also be interested in the [Sports Competition Data Model and Vocabulary Draft Report](https://w3c.github.io/opentrack-cg/spec/competition/) published recently by the [OpenTrack Community Group](https://www.w3.org/community/opentrack/) (although, as the name of the Group suggests, the vocabulary is more oriented toward athletics competition like track and field, rather than team sports like football).

**Comment by julienhohm** [comment]
I have already seen these documents, and if I understand, this is just an improvement not yet integrated in schema.org and maybe never.

So, for the moment, the best solution I found is to use the property _description_ from **Thing**
