### ISSUE TITLE
Add HealthTopicContent, subtype of WebContent, plus an enumeration indicating topical aspects

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2374]
Building on proposed WebContent (see #2358):

A type HealthTopicContent, which is URL-addressable web content (whether a site, web page, or part of a web page) that ... holds content about an aspect of a health topic. This may be comprised of several parts or sections and use different types of media. Instances of WebContent (and hence HealthTopicContent) can be related using hasPart / isPartOf where there is some kind of content hierarchy, and their content indicated with "about" and "mentions" e.g. building upon our existing https://schema.org/MedicalCondition vocabulary.

In addition, I propose an enumeration of the different topical aspects found in such content, as well as a property associating WebContent instances with those identified aspects. 

Specifics will be given in schema definitions for review.

**Comment by danbri** [comment]
We could also note http://schema.org/MedicalWebPage as a subtype of HealthTopicContent

**Comment by danbri** [comment]
I've posted a draft for review in the pending section:


http://webschemas.org/WebContent

http://webschemas.org/HealthTopicContent
  Thing > CreativeWork > WebContent > HealthTopicContent
  HealthTopicContent is WebContent that is about some aspect of a health topic, e.g. a condition, its symptoms or treatments. Such content may be comprised of several parts or sections and use different types of media. Multiple instances of WebContent (and hence HealthTopicContent) can be related using hasPart / isPartOf where there is some kind of content hierarchy, and their content described with about and mentions e.g. building upon the existing MedicalCondition vocabulary.



http://webschemas.org/hasHealthAspect
Indicates the aspect or aspects specifically addressed in some HealthTopicContent. For example, that the content is an overview, or that it talks about treatment, self-care, treatments or their side-effects.

http://webschemas.org/HealthAspectEnumeration
  HealthAspectEnumeration enumerates several aspects of health content online, each of which might described using hasHealthAspect and HealthTopicContent.

http://webschemas.org/BenefitsAspect
  Content about the benefits and advantages of usage or utilization of topic.

etc

**Comment by jvandriel** [comment]
To be honest, I feel several brain freezes coming up based on how does this relate to the medical extention:

(a) Will this proposal be in any form have any relations to types specified in the extention?

(b) Having done quite some markup for medical organizations I'm wondering if the property/Enumeration is intended to be used for web pages as well? (which in my mind instantly because hugely confusing and bloated)

**Comment by jvandriel** [comment]
Oh, and if I remember discussions around the medical extention correctly, types and properties making any beneficial claims were purposely avoided due to such claims being impossible to verify. 

Expectations were that if introduced such types and properties would more often than not contain false claims than medically have no ground.

**Comment by twamarc** [comment]
for me it's fine as far as the intention is purerly to describe the web content.
@danbri: can you maybe fix the property name from ``` webschemas.org/hasHealthHealthAspect``` to ```http://webschemas.org/hasHealthAspect``` ?

**Comment by danbri** [comment]
Hi @twamarc @jvandriel - you found this before I had a chance to forward it around! 

First: the "HealthHealth" thing was simply an editorial error - it should be fixed already.

As far as the relationship goes to our existing large set of medically-oriented terms i.e. https://health-lifesci.schema.org/ - as @twamarc notes the emphasis here is on Web information. We are still in a situation where the medical terms are a large % of schema.org's vocabulary but relatively under-exploited in terms of products/services/features making explicit use of them. My hope is that HealthTopicContent will help us find a few more practical and visible usecases for https://schema.org/MedicalCondition and nearby.

**Comment by danbri** [comment]
FYI, WHO are using this for Coronavirus information, see 

* [WHO site](https://www.who.int/emergencies/diseases/novel-coronavirus-2019)
* [Google SDTT](https://search.google.com/structured-data/testing-tool/u/0/?url=https://www.who.int/emergencies/diseases/novel-coronavirus-2019#url=https%3A%2F%2Fwww.who.int%2Femergencies%2Fdiseases%2Fnovel-coronavirus-2019)

**Comment by jeannieh** [comment]
Thank you for the added examples, Dan Brickley.

To Jarno's point -  types and properties making any beneficial claims were
purposely avoided due to such claims being impossible to verify  - might it
ever be possible to use in tandem with FactClaim?


Jeannie Hill
Hill Web Creations
Digital Marketing, Google Analytics, PPC & SEO Consultant | When you're
serious about marketing, you employ winning strategies.
Office  651.460.2496 <(651)%20460-2496> |Cell  651.206.2410
<(651)%20206-2410>
jeannie@hillwebcreations.com | Hill Web Creations on LinkedIn
<http://www.linkedin.com/profile/view?id=22161273&authType=name&authToken=NBrD&invAcpt=218672614_I176303754_215&trk=eml-comm_invm-b-profile-newinvite&fromEmail=&ut=2B3u0P9-t-NRQ1>
 | Hill Web Creations <http://www.hillwebcreations.com/>

**Comment by danbri** [comment]
This was done - https://schema.org/HealthTopicContent - https://schema.org/docs/releases.html#g2374
