### ISSUE TITLE
expressing JobPosting requirements other than skills and qualifications

### ISSUE THREAD

**Issue by philbarker** [schemaorg/schemaorg#2384]
A JobPosting can list the skills, qualifications, experience and education requirements, but should also be able to list the following requirements:
- citizenship requirement
- physical requirement
- security clearance requirement
- sensory requirement.

These have all been found desirable in the Job data exchange project and discussed in the TalentSignal W3C community group (see [summary](https://www.w3.org/community/talent-signal/wiki/Requirements_other_than_competencies_and_credentials) with link to discussion thread).

physical and sensory requirements could use controlled vocabularies such as that provided by O.Net for [abilities](https://www.onetonline.org/find/descriptor/browse/Abilities/).

Examples:
1. for an electrician
```
{
  "@context": "http://schema.org/",
  "@type": "JobPosting",
  "sensoryRequirement": {
    "@type": "DefinedTerm",
    "termCode": "1.A.4.a.3"
    "inDefinedTermSet": "https://www.onetonline.org/find/descriptor/browse/Abilities/"
    "name": "Visual Color Discrimination"
    "description": "The ability to match or detect differences between colors, including shades of color and brightness."
  }
}
```
2. for a stone mason
```
{
  "@context": "http://schema.org/",
  "@type": "JobPosting",
  "physicalRequirement": "Must be able to lift and carry loads of up to 50kg."
}
```

**Comment by stuartasutton** [comment]
Phil, just a thought about "citizenship requirement".  In the context of employment, I would think that the citizenship question goes to a candidate's legal work eligibility. Some of what HR Open Standards focuses on in this regard are: (a) eligibility types (e.g., "US noncitizen national", "alien authorized to work"; and (b) eligibility documentation (e.g., "permanent resident card", "US passport", "foreign passport with I-94/A form" etc.). Since a "citizenship requirement" might get to some of it, does it do the full trick?

**Comment by philbarker** [comment]
@stuartasutton I'll remove that term from the PR for this issue and we can discuss further in the TalentSignal community group.
