### ISSUE TITLE
thumbnail and thumbnailUrl seem synonyms

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#239]
http://schema.org/thumbnailUrl
http://schema.org/thumbnail

Migrating in from https://www.w3.org/2011/webschema/track/issues/8

```
    The issue initially raised by François Daoust (see http://lists.w3.org/Archives/Public/public-vocabs/2011Dec/0029.html). 

    CreativeWork has 'thumbnailUrl' property of URL type. ImageObject and VideoObject (which indeed CreativeWork' children) have 'thumbnail' property of ImageObject type. Seems more appropriate to have just 'thumbnail (ImageObject)' property in CreativeWork.
```

We now have the supersedes mechanism.     suggest adding <span property="http://schema.org/supersededBy" href="http://schema.org/thumbnail"/> to thumbnailUrl.

See also https://github.com/schemaorg/schemaorg/blob/master/data/schema.rdfa#L8942

**Comment by danbri** [comment]
Just as a data point, YouTube seem to be using 'thumbnailUrl' as a shortcut for the 'url' property of the 'thumbnail' of a VideoObject, e.g. see https://developers.google.com/webmasters/structured-data/testing-tool/?url=http://m.youtube.com/details?v=eXSJ3PO9Tas

**Comment by elf-pavlik** [comment]
I see it very relevant to issue with modeling MediaObject which we face in Social WG
https://www.w3.org/wiki/Socialwg/MediaObject

As well as in schema.org "@id" != "url" since for example following [JSON-LD Embedding](http://www.w3.org/TR/json-ld/#embedding] "schema:thumbnail" could use as value either just URI or an object with "@id".

```json
{
  "@context": "http://schema.org/",
  "@id": "http://www.youtube.com/watch?v=eXSJ3PO9Tas",
  "thumbnail": "https://i.ytimg.com/vi/eXSJ3PO9Tas/hqdefault.jpg"
}
```

```json
{
  "@context": "http://schema.org/",
  "@id": "http://www.youtube.com/watch?v=eXSJ3PO9Tas",
  "thumbnail": {
    "@id": "https://i.ytimg.com/vi/eXSJ3PO9Tas/hqdefault.jpg",
    "width": "480",
    "height": "360"
}
```
@gkellogg what do you think about *propertyUrl* pattern?
* http://schema.org/contentUrl
* http://schema.org/discussionUrl
* http://schema.org/downloadUrl
* http://schema.org/embedUrl
* http://schema.org/installUrl
* http://schema.org/isBasedOnUrl
* http://schema.org//paymentUrl
* http://schema.org/replyToUrl
* http://schema.org/serviceUrl
* http://schema.org/targetUrl
* http://schema.org/thumbnailUrl
* http://schema.org/trackingUrl

**Comment by gkellogg** [comment]
My opinion is that properties such as `thumbnail` should be defined as having `@type: @id`, so that they are interpreted as URIs. This would mean that `"thumbnail": "https://i.ytimg.com/vi/eXSJ3PO9Tas/hqdefault.jpg"` would be equivalent to "thumbnail": {"@id": "https://i.ytimg.com/vi/eXSJ3PO9Tas/hqdefault.jpg"}`. That being the case, if the range of `schema:thumbnail` included `schema:ImageObject`, you could at least say that the the value is compatible with being an ImageObject. If the range had _only_ `schema:ImageObject`, the linter would infer that the object _was_ an ImageObject and output something like the following Turtle:

```
<http://www.youtube.com/watch?v=eXSJ3PO9Tas> schema:thumbnail <https://i.ytimg.com/vi/eXSJ3PO9Tas/hqdefault.jpg> .
<https://i.ytimg.com/vi/eXSJ3PO9Tas/hqdefault.jpg> a schema:ImageObject .
```

**Comment by mfhepp** [comment]
+1

**Comment by elf-pavlik** [comment]
@gkellogg, looking at youtube example shared by @danbri
https://developers.google.com/webmasters/structured-data/testing-tool/?url=http://m.youtube.com/details?v=eXSJ3PO9Tas

Embedded object uses ```url``` not ```@id``` and schema.org context does **NOT** alias ```@id``` to ```url``` while in practice seems to use it as such. Does your linter do something special to handle that mismatch and treats ```url``` as ```@id``` ?

```json
{
  "@context": "http://schema.org/",
  "@id": "http://www.youtube.com/watch?v=eXSJ3PO9Tas",
  "thumbnail": "https://i.ytimg.com/vi/eXSJ3PO9Tas/hqdefault.jpg"
}
```

```json
{
  "@context": "http://schema.org/",
  "@id": "http://www.youtube.com/watch?v=eXSJ3PO9Tas",
  "thumbnail": {
    "url": "https://i.ytimg.com/vi/eXSJ3PO9Tas/hqdefault.jpg",
    "width": "480",
    "height": "360"
}
```

**Comment by gkellogg** [comment]
No, `url` and `@id` are really different things, and it could be a mistake to alias them. `@id` sets the _subject_ of the statements derived from an object, whereas `url` establishes an _object_ value. It is true that `url` is often use for identifying the subject as well, but not necessarily. In many cases, it seems to act like `sameAs`.

In the case of the thumbnail, saying that the `url` is the JPEG does provide a way of separating the JPEG resource itself, from it's description (width/height). It could even be that the native width/height of the JPEG is different that that used by the thumbnail. But, this is similar to the difference between http://example.org/thing, and http://example.org/thing#this, and is typically not a useful distinction for most users.

The distinction between using an anonymous node with a `url` reference to the thing it describes, and using that thing as the subject goes back to many Microdata examples, where the use of `@itemid` is rare. In the end, I don't think the search engines care, and the semantic modelers presumably know the difference. If I were modeling it, I'd typically use `@id`.

**Comment by danbri** [comment]
I don't see an obvious resolution here for inclusion in Gozer. Bumping this to Q2 milestone unless a clear consensus rapidly emerges...
