### ISSUE TITLE
Add isResizable property to 3DModel

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2394]
For some applications like room visualization apps, 3DModels do not allow resizing elements. I propose adding a boolean property "isResizable" to aid knowing whether the model can be resized.

**Comment by vholland** [comment]
See PR #2398

**Comment by danbri** [comment]
I'd like to hear more about the motivating usecase before we move this beyond Pending; it's a bit cryptic. Presumably most things in non-DRM'd file formats are in some sense editable and hence resizable. And resizing is presumably w.r.t. measurements that map it to the world, rather than paper or 3d printing, where you could make a bigger or smaller artifact based on the model.

**Comment by vholland** [comment]
Included in schema.org 6.0
