### ISSUE TITLE
Add properties to EducationalOccupationalProgram to model program duration and application dates

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#2419]
Many EducationalOccupationalProgram pages provide information for determining how long a program typically takes, when terms typically run, and when applications are accepted. I propose adding the following properties to ```EducationalOccupationalProgram``` to allow authors to mark up that sort of data.

The properties include:

- ```numberOfUnits```: The number of units or credits required to complete the program, not including prerequisites for enrollment.
- ```typicalUnitsPerTerm```: The number of units or credits a full-time student would be expected to take in 1 term however 'term' is defined by the institution.
- ```termDuration```: The amount of time in a term as defined by the institution. A term is a length of time where students take one or more classes. Semesters and quarters are common units for term.
- ```termsPerYear```: The number of times terms of study are offered per year. Semesters and quarters are common units for term. For example, if the student can only take 2 semesters for the program in one year, then termsPerYear should be 2.
- ```applicationStartDate```: The date at which the program begins collecting applications for the next enrollment cycle.
- ```applicationDeadline```: The date at which the program stops collecting applications for the next enrollment cycle.
- ```maximumEnrollment```: The maximum number of students who may be enrolled in the program.
- ```educationalProgramMode```: Similar to ```courseMode```, The medium or means of delivery of the program as a whole. The value may either be a text label (e.g. "online", "onsite" or "blended"; "synchronous" or "asynchronous"; "full-time" or "part-time") or a URL reference to a term from a controlled vocabulary (e.g. https://ceds.ed.gov/element/001311#Asynchronous ).
- ```timeOfDay```: The time of day the program normally runs. For example, "evenings".

I also propose extending the domains of the following existing properties to include ```EducationalOccupationalProgram```:
- ```startDate```
- ```endDate```
- ```dayOfWeek```

**Comment by WeaverStever** [comment]
In the **termsPerYear:** property, some courses are not offered annually, after taking Oracle I and II, my community college did not offer Oracle III and IV until they had accumulated several years of lower semester completions.  Perhaps this field should be text to be able to accept words like "biannual" and "biennial"?

There is a taxonomy available for this topic, the CIP codes from NCES.  I don't know if there is an international equivalent, but looking over the proposal, I'm not seeing a description that suggests using the available codes.

https://en.wikipedia.org/wiki/Classification_of_Instructional_Programs

From my work with CIP data, I have also noticed that some specialty degrees are not conferred annually -- the data indicates some are conferred every other year.

**Comment by vholland** [comment]
```termsPerYear``` was more meant for traditional higher education where they might have 2 semesters or 4 quarters per year.

As far as CIP codes, authors could use ```identifier```. Marking up this sort of information seems like it would be helpful to anyone reading their data.

**Comment by WeaverStever** [comment]
@vholland 

**termsPerYear:**
Perhaps we need another property to cover this case then because it is prevalent throughout academia -- where a one semester course will be offered annually.  Or in the case I presented above, where I was halfway through a DBA certificate and do not know if the latter two semesters were ever offered before Oracle 9i, became some other version number.

Prevalent in all colleges, if you can't fit it into your schedule or enrollment too large, you have to wait a year to take the (often required)  second semester.  This could also be part of the purported "on time graduation" statistic. There are so many specialties now, that the course availability doesn't always fit a 5 year graduation expectation.  

**CIP codes:**    
The fields appear to be present, but we usually suggest/link the existing ontologies in the description(s).  

These would be US centric, but I've found that the International ontologies are less verbose.
educationalCredentialAwarded = suggest[ NCES CIP codes](https://nces.ed.gov/ipeds/cipcode/Default.aspx?y=56)
occupationalCredentialAwarded = suggest [NAICS-SOC codes](https://www.bls.gov/soc/2018/major_groups.htm)

**Comment by philbarker** [comment]
@vholland  I don't like that credits and "units" are being treated as interchangeable terms. I assume the "units" of a program would be courses / modules: classes, research projects, placements etc?--it needs further definition. Typically in Europe a year of study would involve 60 or 120 credits depending on the credit scheme used, so using `numberOfUnits = 120` alongside `numberOfUnits = 6` might be confusing.

I would like to see `creditsRequired` as a structured value so that the type of credit can be named, e.g. [ ECTS credits](https://en.wikipedia.org/wiki/European_Credit_Transfer_and_Accumulation_System), and I would like to see `creditsAwarded` added to `Course`, but at program level you could have  `typicalCreditsPerCourse`

@WeaverStever do the CIP codes address more than the subject of the program? They don't really seem to match with credentials awarded.

**Comment by WeaverStever** [comment]
@philbarker 

Yes, I've found that credits, units and semester units can mean different things.  Additionally, some schools now grade on a 5.0 gpa system rather than the traditional 4.0 gpa system.  I always laugh with I see 4.0+ GPA in news articles.

The CIP codes are a field of study, much like a major or minor.  Here are the 2017 codes for "Computer" -- aka fit the Computer Science curriculum.  These cover the gambit, some are certificate courses or associate degree, some at bachelor's level and some are offered in the postgrad level.

01.0106 | Agricultural Business Technology.
11.0101 | Computer and Information Sciences, General.
11.0102 | Artificial Intelligence.
11.0103 | Information Technology.
11.0104 | Informatics.
11.0199 | Computer and Information Sciences, Other.
11.0201 | Computer Programming/Programmer, General.
11.0202 | Computer Programming, Specific Applications.
11.0203 | Computer Programming, Vendor/Product Certification.
11.0299 | Computer Programming, Other.
11.0301 | Data Processing and Data Processing Technology/Technician.
11.0401 | Information Science/Studies.
11.0501 | Computer Systems Analysis/Analyst.
11.0701 | Computer Science.
11.0801 | Web Page, Digital/Multimedia and Information Resources Design.
11.0802 | Data Modeling/Warehousing and Database Administration.
11.0803 | Computer Graphics.
11.0804 | Modeling, Virtual Environments and Simulation.
11.0901 | Computer Systems Networking and Telecommunications.
11.1001 | Network and System Administration/Administrator.
11.1002 | System, Networking, and LAN/WAN Management/Manager.
11.1003 | Computer and Information Systems Security/Information Assurance.
11.1004 | Web/Multimedia Management and Webmaster.
11.1005 | Information Technology Project Management.
11.1006 | Computer Support Specialist.
14.0901 | Computer Engineering, General.
14.0999 | Computer Engineering, Other.
15.1204 | Computer Software Technology/Technician.
26.1103 | Bioinformatics.
26.1104 | Computational Biology.
30.0801 | Mathematics and Computer Science.
30.1601 | Accounting and Computer Science.
30.3001 | Computational Science.
30.3101 | Human Computer Interaction.
43.0116 | Cyber/Computer Forensics and Counterterrorism.
51.0709 | Medical Office Computer Specialist/Assistant.
51.2706 | Medical Informatics.
52.1201 | Management Information Systems, General.

**Comment by perani** [comment]
Re: units vs. credits. The definition should be clear that it is the measurement of an individual class, which could be linked to program cost and duration. I see units and credits (or credit hours) used interchangeably in the US. I like the idea of keeping the definition loose enough to allow an institution to use their preferred type. Not sure what the answer is to that, since it feels odd to use a term that is neither credits nor units.

For example, at Stanford the expected courseload is 15 units per quarter. In this example the typicalUnitsPerTerm is 15, and the termsPerYear is 4. Given a programs full unit count, you could calculate duration and use cost per credit to calculate cost.

John Tyler Community College calls these credit hours, with 15 credit hours per semester, and 3 semesters per year.  In this example the typicalUnitsPerTerm is 15, and the termsPerYear is 3.

Re: timing of program
I like the idea of adding a type that allows the school to note if the program is available this current year. That means that if it is a biennial program, one could know if it was offered.

**Comment by vholland** [comment]
I think I got all the feedback incorporated into PR #2429 

@philbarker Please let me know if I missed anything.

**Comment by vholland** [comment]
Included in schema.org 7.0

**Comment by perani** [comment]
Thank you Vicki!
