### ISSUE TITLE
Add a (wikidata) example to /sameAs

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2482]
Let's use Douglas Adams, @vrandezo 

````{
  "@type": "Movie",
  "name": "The Hitchhiker's Guide to the Galaxy",
  "disambiguatingDescription": "2005 British-American comic science fiction film directed by Garth Jennings",
  "sameAs": "https://www.wikidata.org/wiki/Q836821",
  "titleEIDR": "10.5240/B752-5B47-DBBE-E5D4-5A3F-N",
  "isBasedOn":
  { 
    "@type": "Book",
    "name": "The Hitchhiker's Guide to the Galaxy",
    "isbn": "0-330-25864-8",
    "sameAs": "https://www.wikidata.org/wiki/Q3107329",
    "author": 
    {
      "@type": "Person",
      "name": "Douglas Adams",
      "sameAs": "https://www.wikidata.org/wiki/Q42"
    }
  }
}
```

(this also uses draft EIDR property; I'm suggesting for that /workEIDR and /editEIDR, see #2469)

**Comment by danbri** [comment]
I'm trying to work through how this relates to EIDR in #2469. There are some complications.

# Example 1 - work/title level

This example talks about the movie in its most abstract general  sense first, mentioning a wikidata sameAs link, a titleEIDR, and its name and a disambiguatingDescription. It then lists 4 specific edits with eidrEIDR and disambiguatingDescription for each.

```
{
"@type": "Movie",
  "name": "The Hitchhiker's Guide to the Galaxy",
  "disambiguatingDescription": "2005 British-American comic science fiction film directed by Garth Jennings",
  "sameAs": "https://www.wikidata.org/wiki/Q836821",
  "titleEIDR": "10.5240/B752-5B47-DBBE-E5D4-5A3F-N",
  "workExample": [ {
    "@type": "Movie",
    "editEIDR": "10.5240/0196-4177-FF62-A346-D0F6-Z",
    "disambiguatingDescription": "VUDU version"
   },
    "@type": "Movie",
    "editEIDR": "10.5240/043D-15C4-838D-80F4-E96A-G",
    "disambiguatingDescription": "Censored for India"
   },
    "@type": "Movie",
    "editEIDR": "10.5240/7BAD-7B81-396E-27EF-360F-N",
    "disambiguatingDescription": "Theatrical"
   },
    "@type": "Movie",
    "editEIDR": "0.5240/1DC4-B3E4-ECEB-7197-BF18-B",
    "disambiguatingDescription": "Broadcast"
   }
  ],
  "isBasedOn":
  { 
    "@type": "Book",
    "name": "The Hitchhiker's Guide to the Galaxy",
    "isbn": "0-330-25864-8",
    "sameAs": "https://www.wikidata.org/wiki/Q3107329",
    "author": 
    {
      "@type": "Person",
      "name": "Douglas Adams",
      "sameAs": "https://www.wikidata.org/wiki/Q42"
    }
  }
}
```


# Example 2 - edit(ion) level

This example is all about a specific edition ("expression" in FRBR terminology). Therefore to 
provide information (such as a work sameAs link) we need to 
describe the work as a different entity (here via exampleOfWork).

```
{
  "@type": "Movie",
  "name": "The Hitchhiker's Guide to the Galaxy",
  "titleEIDR": "10.5240/B752-5B47-DBBE-E5D4-5A3F-N",
  "editEIDR": "10.5240/0196-4177-FF62-A346-D0F6-Z",
  "disambiguatingDescription": "VUDU version",
  "exampleOfWork": 
    {
       "@type": "Movie",
         "sameAs": "https://www.wikidata.org/wiki/Q836821",
    }
  }
}
```

**Comment by RichardWallis** [comment]
Being pedantic shouldn't the Wikidata uri be ```http://www.wikidata.org/entity/Q3107329``` not ```https://www.wikidata.org/wiki/Q3107329```

**Comment by philbarker** [comment]
@RichardWallis definition for [sameAs](https://schema.org/sameAs) says it's the "URL of a reference Web page..." so it should be /wiki/ URL not the /entity/

**Comment by RichardWallis** [comment]
_Note to self: RTFM_

**Comment by akuckartz** [comment]
@philbarker But where is "Web page" defined ?

**Comment by RichardWallis** [comment]
Shipped in V11.0 release.

**Comment by ziodave** [comment]
> @RichardWallis definition for [sameAs](https://schema.org/sameAs) says it's the "URL of a reference Web page..." so it should be /wiki/ URL not the /entity/

To be fair the examples here use the dbpedia ID, not the dbpedia page:
https://www.w3.org/wiki/WebSchemas/sameAs

And Wikipedia itself is linking to the wikidata.org/entity link:
https://validator.schema.org/#url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FCrown_(dentistry)

![image](https://user-images.githubusercontent.com/11438/135220828-75e761d7-95fa-4f7b-8db0-e2f0b17830f9.png)

**Comment by WeaverStever** [comment]
This reminds me of a discussion about adding the subtype homePage (#2062). That discussion exposed that some people use social media profiles as their main web-presence, so https://schema.org/WebSite does not always resolve to the document root of the domain.

Further discussion exposed that these social-media sites generally use aliases called folksonomy tags as identifiers which are specific to the domain, usually the ampersand is used to prefix an identity and a hashtag identifies a collection of related topics.

For instance, the politician @ocasio2018, is now far more widely known for the folksonomy tag that twitter gifted to her @AOC.

My suggestion here is that having two new properties, **ontologies** (Wikidata, ISNI etc) and **folksonomies** (ampersand and hashtag identities -- accompanied with the specific domain) might make it easier for data-consumers to do more targeted searches.

I've always used sameAs, to point to the human readable page because many persons and organizations are too new for Wikipedia pages and without a Wikipedia page, you can't get a Wikidata entity.  Additionally, most webpages have the structured data embedded within the human readable version.  (I believe the previous guidance for https://schema.org/sameAs included news articles social media pages as a collection.)

IMHO Wikidata (and therefore Wikipedia) may be trustworthy as "_a reference Web page that unambiguously indicates the item's identity._" for the thing type, but it is highly dubious for persons and creativeworks because the platform has been captured by politicos and special interests.
