### ISSUE TITLE
Changes to 7.0 including fast track Coronavirus-related vocabulary

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2490]
We will add markup to support Coronavirus information sharing, targeted at local organizations who are already updating their sites with information. The intent is to capture with a bit more structure some of that information, and to establish a model that can be iteratively improved during the crisis response period. 

There are also minor changes in other areas of schema.org such as our (already extensively discussed) treatment of online events.

I will publish [7.0](https://github.com/schemaorg/schemaorg/issues/2453) imminently and we can refine things from there, at an accelerated pace.

**Comment by danbri** [comment]
[Feedback Google doc](https://docs.google.com/document/d/1fpdFFxk8s87CWwACs53SGkYv3aafSxz_DTtOQxMrBJQ/edit#), as an alternate to Github. We will summarize into this tracking issue.

**Comment by danbri** [comment]
See http://schema.org/SpecialAnnouncement and nearby.

**Comment by danbri** [comment]
http://blog.schema.org/2020/03/schema-for-coronavirus-special.html

**Comment by JeffreyBurns** [comment]
![image](https://user-images.githubusercontent.com/31894097/77009058-a9bed980-693d-11ea-84d7-6e33cf1eef7b.png)

The description for https://schema.org/SpecialAnnouncement tells us that: "We encourage the provision of "name", "text", "datePosted", "expires" (if appropriate) and "url" as a simple baseline."

However, https://schema.org/datePosted is not available for https://schema.org/SpecialAnnouncement.

**Comment by Tiggerito** [comment]
Small typo in Example 1 JSON-LD for https://schema.org/SpecialAnnouncement.

Line 8 is just a "

datePosted is now in the specification. Google's SDTT does not recognise it yet and throws a warning.

I'm working on an online editor to help people create this markup. Is this the best place to post any issues I see on the way?

**Comment by Tiggerito** [comment]
I've built the first version of my Bing SpecialAnnouncements editor:

https://classyschema.org/SpecialAnnouncement

Most of my observations are about the Bing guidelines compared to the schema.org spec. What's the best place to send them feedback?

The Bing guidelines are a bit confusing with respect to what is required. Sections start with "The following properties represent the minimum information required to be present" and 
then only a few of the properties are stated as 'required: ".

Bing does not clarify if they support WebContent which is an option for many of the properties. All examples use URLs.

Bing implies they only support one entity in spatialCoverage, while the third example on https://schema.org/SpecialAnnouncement shows an array of them. 

The second example in https://schema.org/SpecialAnnouncement for School Closures includes 'webFeed' and 'about' using School. Bings Guidelines does not state either of those properties. It does mention you can add more than stated.

Bings example on https://www.bing.com/webmaster/help/special-announcement-specifications-5cbd6249 includes a description for the DataDownload set to "Number of Individuals Tested". 
I don't quite understand what that is meant to mean? That example also cause a few warnings and errors in the Structured Data Testing Tool, which may confuse/scare people.

**Comment by tmarshbing** [comment]
@Tiggerito , the tool you put together looks great! I would love to hear from you if you get feedback from folks trying to use it so we can improve both schema.org and Bing's guidelines.

Re Bing's implementation, you can send feedback here, or, to save the mailing list since we usually focus on schema.org itself rather than the search engines' implementation of it, feel free to contact me directly at https://www.linkedin.com/in/tom-marsh-2183873/.

Thanks a lot for the detailed feedback on our post and docs.

I agree the sentence before the property table is confusing v. the required v. not-required labels in the table. I'll update the sentences to be clearer.

Yes, we would support WebContent, but we encouraged URLs instead. One reason was that we thought it would be easier to enter an existing URL showing the content v. copying the content itself. The bigger reason was that we expect it to be easier to verify that the announcement is about the same site on which it is posted if a URL is used v. WebContent.

We didn't mean to imply that spatialCoverage should be singular. I will update the documentation to be clearer on that.

On 'about', @danbri , should we recommend spatialCoverage instead in the schema.org example? It's not clear to me why we need about separately for school closures.

On 'webFeed', @danbri , it looks like webFeed is not currently allowed on SpecialAnnouncement, despite its use in the example. Shall we add it?

On "Number of Individuals Tested", that is the title of the table on https://www.doh.wa.gov/emergencies/coronavirus. The markup is just matching what is on the page. That said, the table above that ("Confirmed Cases / Deaths by County") is probably more interesting, so I'll update the example to that.

On the SDTT errors, @danbri , the tool doesn't recognize datePosted yet. I fixed most of the other errors and warnings and will update the snippet in the help docs accordingly.

**Comment by skuonline** [comment]
Hi,

One of my friend's clinic started COVID19 testing facilities. He is planning to display a special announcement area in all pages of his website to convey this to all his visitors. Where should I add the SpecialAnnouncement schema, in homepage or on all pages?

Thanks in advance,
skuonline

**Comment by Tiggerito** [comment]
Another minor example issue. Third example on https://schema.org/SpecialAnnouncement has ""Santa Clara County, CA" three times. 

Several examples have name and text set to the same value. It there any benefit in doing that?

I'd also be interested in where people can best place this markup and make you aware that it exists.

I've updated my editor to cope with multiple spatialCoverage entities and to support all relevant types. And I've added more examples from the schema.org page.

**Comment by Aaranged** [comment]
Since this is still upon will file bug here I guess, rather than opening new issue.  It's bad code on the JSON-LD example for [SpecialAnnouncement](https://schema.org/SpecialAnnouncement).

Pretty straightforward: there's a quotation mark alone on a line after `datePosted`:
```
"datePosted": "2020-03-16",
 "
```

**Comment by tmarshbing** [comment]
@skuonline , assuming it's the same announcement just displayed on multiple pages, I think that adding the markup to the homepage only makes sense. @danbri , thoughts?

@Tiggerito , I'm not sure I fully understand your question about the best place to put the markup. I guess in general, it's better to put markup on pages that get viewed/clicked in search results more often. Although it's certainly not the only criteria, more popular pages tend to get crawled more often, so the markup would be likely to be seen by search engines sooner.

**Comment by Tiggerito** [comment]
@tmarshbing That makes sense. Just wondering if there was a good way to make sure Bing discovers the pages with the content and markup. I guess good SEO practice for crawlability is the way. Links, sitemap, submit URL, don't block etc.

**Comment by RichardWallis** [comment]
Implemented in 7.01, 7.02, 7.03.
