### ISSUE TITLE
Schema Type "MedicalBusiness" is missing in schema-types.csv

### ISSUE THREAD

**Issue by satyam-bala** [schemaorg/schemaorg#2498]
MedicalBusiness type is missing in schema-types.csv, but there are few classes Dentist, Pharmacy, Physician, which have dependency with this class.

**Comment by RichardWallis** [comment]
_MedicalBusiness_ is missing from ```schema-types.csv``` because it is defined in the _ext-health-lifesci_ area of the vocabulary.  The _schema-_ files only contain definitions for the core of the vocabulary.

To get definitions for terms from all areas of the vocabulary the _all-layers-_ definition files are required.  eg. ```all-layers-types.csv```

**Comment by satyam-bala** [comment]
Then, the referring types Dentist, Pharmacy, Physician should also moved to ext-health-lifesci area, instead of schema-types.
