### ISSUE TITLE
Some Types & Properties missing from Schema CSV exports

### ISSUE THREAD

**Issue by zerebral** [schemaorg/schemaorg#2589]
Referring to the latest CSV dumps of Types and Properties - Observing that following Types and their properties are missing from the schema-types.csv and schema-properties.csv files respectively. 

Missing Type: https://schema.org/Drug 
Missing Properties: activeIngredient,administrationRoute,alcoholWarning,availableStrength,breastfeedingWarning,clinicalPharmacology,dosageForm,doseSchedule,drugUnit,foodWarning,includedInHealthInsurancePlan,interactingDrug,isAvailableGenerically,isProprietary,labelDetails,legalStatus,maximumIntake,mechanismOfAction,nonProprietaryName,overdosage,pregnancyCategory,pregnancyWarning,prescribingInfo,prescriptionStatus,proprietaryName,relatedDrug,rxcui,warning 

Few more combinations - 
http://schema.org/ChooseAction 
option

https://schema.org/Dataset
measurementTechnique,variableMeasured
catalog,includedDataCatalog,datasetTimeInterval

https://schema.org/WriteAction
language

https://schema.org/Service
termsOfService 

https://schema.org/EngineSpecification
engineDisplacement,enginePower,engineType,torque 

and many more.. 

Is there any additional file to these two that need to be consumed to obtain info on these Types/Properties?

**Comment by RichardWallis** [comment]
_Drug_ and other terms you mention are missing from ```schema-types.csv```/```schema-properties.csv``` because they are defined in the _ext-health-lifesci_ section of the vocabulary.  The _schema-_ files only contain definitions for the core of the vocabulary.

To obtain definitions for terms from all areas of the vocabulary the _all-layers-_ definition files are required.  eg. ```all-layers-types.csv```

There is an outstanding issue (#2304) to rationalise the contents of the download files which should make things more obvious if/when implemented.
