### ISSUE TITLE
Docker support seems broken

### ISSUE THREAD

**Issue by spacebel** [schemaorg/schemaorg#2602]
Hello,

When mounting the latest version on master to the mentioned docker image (not updated since 5 years), the image fails.

The following command fails (because site/handler.yaml does not exist) 
`docker run --rm -it --name appengine --expose 8080 -p 8080:8080 -v `pwd`:/workspace mgood/appengine-python dev_appserver.py --use_mtime_file_watcher --host=0.0.0.0 /workspace`

Moreover, if I try from the container to install the software using ./runpythonapp.sh , it states first that git is not installed, and after including git that the current directory is not schemaorg/

Is this Docker image still a possible mean for installing / running schema.org.

Thanks.

**Comment by RichardWallis** [comment]
Hi @spacebel 

Although there was a proposed integration (#1007) of docker support into the Schema.org application codebase back in 2016, it was never proceeded with due to perceived complexity.

Since that time the code has moved on significantly, not least the recent move to produce a statically deployable, within Google Appengine, version.

As such the code base has never supported a docker environment.

To run a copy of the development environment you need a (linux / macos) environment with the Google Appengine SDK installed. Plus a clone of the scheaorg repo - see https://github.com/schemaorg/schemaorg/blob/master/SOFTWARE_README.md

**Comment by spacebel** [comment]
Thank you. I think it would really make sense to edit https://github.com/schemaorg/schemaorg/wiki/AppEngine with this statement. The page is confusing regarding that aspect.

Regards

**Comment by RichardWallis** [comment]
Wow that is way out of date!

I'll take a look at editing it.

~Richard
