### ISSUE TITLE
missing in search

### ISSUE THREAD

**Issue by jaygray0919** [schemaorg/schemaorg#2603]
a search for the term `Occupation` does not return https://schema.org/Occupation

**Comment by RichardWallis** [comment]
See issue (#2598) which identified that term definition pages on the Schema.org pages had unintentionally been marked 'noindex'.  This would prevent search engines from indexing them.

As the on-site search is managed by Google CSE, this obviously impacted its performance as you identify.   The fix for this has been only currently been live for 24 hours, it may take some time for the search engine crawlers to catch up and start indexing all pages soon.

**Comment by jaygray0919** [comment]
Good. Missed the previous issue. Not trying to be annoying here.

**Comment by danbri** [comment]
@jaygray0919 thanks for taking the time to report the problem!
