### ISSUE TITLE
Add subtype of /Collection for collections of products (/ProductCollection)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2605]
Add a type indicating a group of products that are offered as a single collection - e.g. camera plus a lens.

**Comment by jvandriel** [comment]
For this I'd normally publish something like this:
```
{
  "@type":"Product",
  "name":"Camera plus a lens",
  "offers":
  {
    "@type":"Offer",
    "price":"xxx",
    "priceCurrency":"USD",
    "itemOffered":
    [
      {
        "@type":"Product",
        "name":"product 1"
      },{
        "@type":"Product",
        "name":"product 2"
      }
    ]
  }
}
```
Would ```Product``` (as mentioned in the example) become ```ProductCollection``` with this proposal?

**Comment by mfhepp** [comment]
Hi all:

The original idea for bundles is

Offer -> https://schema.org/includesObject -> https://schema.org/TypeAndQuantityNode -> typeOfGood -> Product/Service

This allows specifying the quantities of the individual parts of the bundle, as well as the business function. 

Much more flexible and precise - you can also use varying units of measurement ("1 camera + 200 g of rice") etc.

https://schema.org/TypeAndQuantityNode has

    amountOfThisGood - The quantity of the goods included in the offer.
    businessFunction - The business function (e.g. sell, lease, repair, dispose) of the offer or component of a bundle (TypeAndQuantityNode). The default is http://purl.org/goodrelations/v1#Sell.
    typeOfGood -  The product that this structured value is referring to.
    unitCode / unitText - a unit of measurement for being more precise on the amount value (e.g. not units/pieces but grams, liters, gallons)

So 

    https://schema.org/includesObject

is IMO the correct way, since 2008 (1st release of GoodRelations) and 2012 (added to schema.org).

;-)

Best wishes
Martin Hepp

-----------------------------------
martin hepp  http://www.heppnetz.de
@mfhepp

**Comment by jvandriel** [comment]
Thanks for pointing that out @mfhepp (I should have known that without you having to point it out). I guess the example should have been like this instead:
```
{
  "@type":"Product",
  "name":"Camera plus a lens",
  "offers":
  {
    "@type":"Offer",
    "businessFunction":"http://purl.org/goodrelations/v1#Sell",
    "price":"xxx",
    "priceCurrency":"USD",
    "includesObject":
    [
      {
        "@type":"TypeAndQuantityNode",
        "typeOfGood":
        {
          "@type":"Product",
          "name":"Camera"
        },
        "amountOfThisGood":1
      },{
        "@type":"TypeAndQuantityNode",
        "typeOfGood":
        {
          "@type":"Product",
          "name":"Lens"
        },
        "amountOfThisGood":1
      }
    ]
  }
}
```

**Comment by mfhepp** [comment]
Hi Jarno,
Yep, exactly!

**Comment by danbri** [comment]
How about we allow 'includesObject' on ProductCollection, and then re-use that structure for the complex case; there are cases when the collection is not primarily an artifact of a (transient etc.) offer but has some longer term coherence in itself. For simpler cases we might want to skip the TypeAndQuantityNode and just point to the Product?

**Comment by jvandriel** [comment]
> "For simpler cases we might want to skip the TypeAndQuantityNode and just point to the Product?"

Sounds good to me @danbri. Reason I asked whether your suggestion covers products as per the example is because per my experience a lot of ecommerce systems don't have any option (by default) to define 'composite products'. Meaning that providing ```includesObject``` information will be hard (if not impossible) for many out there, and thus having a ```ProductCollection``` type might be a good way to be able to differentiate such products from 'normal' products when further data is missing.

**Comment by danbri** [comment]
https://schema.org/ProductCollection was added in version 9, see https://schema.org/docs/releases.html
