### ISSUE TITLE
Proposal for adding BackOrder as an enumeration member of ItemAvailability

### ISSUE THREAD

**Issue by chollma** [schemaorg/schemaorg#2651]
## Context
Online retailers are especially dependent on schema.org vocabulary as a standardized way to describe the evolving status of their products to a variety of systems including search engines. Today, there are a number of ways that a product can be described using the `ItemAvailability`attribute.

## Problem
I believe there's a significant gap in this list, especially given the current state of consumer demand for online shopping, the encumbered state of our global supply chains during a pandemic, and our commitment to provide the best possible information available to customers.

The current version of the schema.org vocabulary includes `PreOrder` as a enumeration member of `ItemAvailability`. As I understand it, `PreOrder` refers to an item that is available for purchase but has **not been carried** by a business before.

## Proposal
I would like to propose the addition of `BackOrder` to this list of members, because I believe there is a unique difference between `PreOrder` and `BackOrder`. 

## Details
As I understand it, `BackOrder` refers to an item that is out of stock, still able to be purchased and will be available again for customers at some point in the future, rather than being `Discontinued`.

Inclusion of `BackOrder` in the list of enumeration members for `ItemAvailability` will allow consumers of schema.org to describe the status of an item with more granularity than `OutOfStock`. In addition, it will allow other major business to utilize an updated vocabulary to better serve customers with their products (ie. https://support.google.com/merchants/answer/6324448?hl=en)

**Comment by RichardWallis** [comment]
See issue #1977 near by.

**Comment by chollma** [comment]
Thank you, @RichardWallis. I think #1977 is similar in nature to this request but not identical.

**Comment by philsward** [comment]
Yes, this is still a request as per my original request in #1632 

Like I stated in my original request, BackOrder is different than OutOfStock.  Neither of which, have anything to do with PreOrder.

> **Backorder vs. out of stock**
> Out of stock means that a product does not currently have any inventory available and does not have a date for resupply, while ‘backordered’ implies there is a determined date for products to arrive. 
> 
> It’s the difference between “This item is currently unavailable” and “This item won’t ship [until 2 weeks from now, for 10 business days, etc.].” In other words, there is hope in the foreseeable future with a backorder. It might take a while, but you will receive the product. 
> 
> When a product is ‘out of stock,’ there’s a chance that’s the case permanently, or at least will be for so long that the seller can’t predict when they will have it again.

Source: https://www.shipbob.com/blog/backordered-meaning/

This is actually backwards from how I "think" about the two, but if I need to change my thinking, I'll change my thinking.  Point is, each term gives a specific reason for why the product isn't available.

**Comment by chollma** [comment]
I appreciate your comments on this issue, @philsward. Anecdotally, I believe the ideal life cycle of standard product should operate like this:

PreOrder > InStock > LimitedAvailability > OutOfStock > **BackOrder** > Discontinued

How I'm personally thinking about the two options (OutOfStock/BackOrder) from a customer perspective:

OutOfStock: this product was recently available to purchase, but is currently unavailable for purchase. It will likely be back in stock very shortly.

BackOrder: this product was available to purchase in the past and we know that you'll be able to purchase it again soon, but we'd like to set an expectation with the customer that this timeline (from purchasing to receiving a product) might be extended to as much as 30 days.

Given the state of our national and international supply chains for the foreseeable future, I think that better describing the state of an item as it relates to its availability will give consumers of this data more ability to set expectations with their end users.

**Comment by philsward** [comment]
Thanks @chollma 

So you and I see eye-to-eye on the flow of OutOfStock -> BackOrder.  I thought it was interesting that the industry standard apparently has it flip-flopped.

Regardless, it doesn't really matter what the "standard" may be, each term gives a different clue about the status of the product which is why I'm advocating for the inclusion.

**Comment by philsward** [comment]
Here's a thought...

We take one out of the B&H Photo Video marketing playbook and replace both OutOfStock and BackOrder with "MoreOnTheWay"

![image](https://user-images.githubusercontent.com/3436110/88335604-349f4e80-ccf9-11ea-9ea7-ae6c53cecac0.png)

**Comment by HughP** [comment]
"More on the way" is fun, but some "Out of Stock" items at REI are not ever
going to be back in stock.

**Comment by philsward** [comment]
@HughP Thats why I have an availability status of "No Longer Offered" for my sites.  If I said "Discontinued", that would indicate that the manufacturer is no longer making it.  However when somebody says they no longer offer a product, it isn't discontinued.

If a company labels a product as "Out of Stock" because it has been discontinued or is no longer offered, the maintainers of those sites aren't paying attention to detail and don't really care how the customer interprets it.  That or they are strictly sticking to the Schema way of doing it because big brother Google says they have to, which is the whole reason for this discussion.  Google won't budge unless Schema says its: "OK".

**Comment by taur** [comment]
> PreOrder > InStock > LimitedAvailability > OutOfStock > **BackOrder** > Discontinued
For dropshipping the flow would be: PreOrder > BackOrder > Discontinued
here one could argue that "DropShipped" could be it's own availability that would replace InStock, because it's distinctly different from BackOrdered in that you have no intention of ordering it until an order is placed, the alternative would be having both BackOrder and BackOrdered, but the distinction would not be as clear.
BackOrdered in past tense semantically also makes more sense as it'd indicate that it has already been back-ordered and will be back in stock sometime soon.

**Comment by philsward** [comment]
@taur I'll agree that for the most part, drop shipping should go PreOrder > InStock > BackOrder

My business model is mostly dropship and we use backorder for most things that aren't available from the supplier.  Mainly because the majority of the time, it can be 1 - 4 weeks before they have product available.

If we find out a product isn't available through a supplier and they say "We're expecting a shipment in either tomorrow or the next day", then I'll place the product as "Out of Stock".

**Comment by chollma** [comment]
Curious what the group thinks. If an item is OutOfStock or on BackOrder (as this proposal suggests), should that product be available for purchase? 

It seems that there's some incongruousness on availability between websites. 

My goal would be to arrive at some sense of parity so many systems can consume retailer information and display it consistently vs. having different understandings of status.

Let me know your thoughts.

**Comment by stephenhamiltonau** [comment]
No sure where we are at with this, but I think it is important. From my perspective, and that of my colleagues (we have a small ecommerce site with a couple of thousand sku’s for packaging products), out of stock means it will be back reasonably quickly (i.e. at most 14 days), but backorder means a longer wait (sometimes up to a few months).

Generally we prefer to not take payment for anything we are not able to ship immediately, but that will vary from business to business I suspect, and it probably isn’t useful to define that aspect. But having it available for purchase in the sense an order gets placed, then yes, we do that. All existing (back)orders get priority when/if the stock finally arrives.

Naturally, much of the benefit for consumers depends on how diligent retailers are in updating the schema to show the actual current status. I can see this could be a challenge for some where products are marked as backorder, but in fact there is no longer any chance of that item being made available (i.e. it has been discontinued).

I hope this helps.

Stephen

**Comment by philsward** [comment]
@chollma I'm in 100% agreement with @stephenhamiltonau 

That said, if you do some Googling for for "Out of Stock vs Backorder", the when and why for both is completely up-in-the air depending on who you talk to (or who's blog you manage to read).

**Comment by pritoms** [comment]
In response to the proposal: I’d rather stick with the discrete nature over semantics, because the time series models have allowances for these logistics related things. These observations are neither considered “anomaly”, nor attributes; It is already hard enough that we can’t grab 100, but this will almost 100% corrupt the model.

**Comment by pritoms** [comment]
Folks I couldn’t leave without placing a visible flag, exclusively due to the nature of the computation, but we should be using nothing but context free grammar for computational complexity at that level.

**Comment by philsward** [comment]
@pritoms you're going to have to dumb down your thoughts. I have no idea what you're trying to say.

**Comment by philsward** [comment]
Pretty frustrating this is getting thrown to the side for "inactivity". The reason these topics of discussions get no traction is because the vast majority of people who want it, have no idea how to find the place to advocate for it.

Schema.org barely even mentions Github and the people who run mom-and-pop e-commerce sites are not MIT graduates to even know what Github is to come here and push for it.

Even more frustrating that "unless you're advocating from a multi-billion dollar company, nobody cares and nothing gets added."

**Comment by pritoms** [comment]
@philsward Thanks for caring about such esoteric thing, or even linguistics have become obsolete since 90s maybe. I don’t know what is motivating you to be honest, because I took a glance at the type of things this repo tried to do and it seemed like a decent nlp style. But I have always been extremely fascinated with natural language processing but gpt3 made some long lasting traumas in me. Oh let me know if you don’t know about gpt 3.

**Comment by pritoms** [comment]
Btw I intentionally didn’t bring up the points you wanted to know about, because I would be contradicting my whole point. Also it is not a good method of learning abstract concepts either, for example: you only added handful of words to pass your “proposition”, which traveled through my entire summary. Seems pretty unbalanced right?
But think about the “proposition” you had thought to have dealt with, because why else would you bother to formulate on a “causal” case.

**Comment by alex-jansen** [comment]
The proposal to add BackOrder on /ItemAvailability is something that Google also supports and sees as increasingly important for consumers (as well as the general ecosystem), especially during the ongoing pandemic. 

As discussed earlier in this thread, and as opposed to OutOfStock, BackOrdered items are typically in the process of being restocked and can often already be ordered with a deterministic (maximum) delivery date.  Given this clear difference in semantics we support inclusion in the next Schema.Org release.

@danbri

**Comment by philsward** [comment]
@danbri 🤗
