### ISSUE TITLE
Release 10 Pending Properties in Core

### ISSUE THREAD

**Issue by vberkel** [schemaorg/schemaorg#2702]
Among the changes in https://github.com/schemaorg/schemaorg/releases/tag/V10.0-release and prepared here https://github.com/schemaorg/schemaorg/issues/2648 there are several properties which documented as being in pending but are missing the property ``` <http://schema.org/isPartOf> <http://pending.schema.org> ; ``` which allocates them as such. Here are the affected properties:

- learningResourceType
- energyEfficiencyScaleMin
- energyEfficiencyScaleMax
- hasEnergyConsumptionDetails
- hasEnergyEfficiencyCategory

The release documentation shows this, with the highlighted properties: 
![image](https://user-images.githubusercontent.com/1944680/92589803-1c639e80-f269-11ea-87ea-e601cb340a48.png)

**Comment by danbri** [comment]
Thanks. Looks like most of these were in the new energy terms that @alex-jansen and I have been working on recently - and which are very definitely in Pending. It is not so clear from the /docs/releases.html page since the term predates the releases it lists, but learningResourceType was added years ago (part of the LRMI work),  see https://web.archive.org/web/20130601000000*/https://schema.org/learningResourceType and https://blogs.pjjk.net/phil/lrmi-examples-for-schema-org/

I'll get the energy ones fixed! many thanks..
