### ISSUE TITLE
Properties that take an URL in anticipation of an external enumeration should be marked as expecting DefinedTerm

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#2734]
Historically, whenever we had a property that was designed to take externally enumerated code lists, we would simply say it expects a URL. However, there are lots of other uses of URLs in schema.org data, which makes it hard to understand that an external list is needed.

DefinedTerm serves this purpose and https://schema.org/DefinedTerm#incoming (incoming properties) lists 18 properties already. There may be more.

We should at least add https://schema.org/category

@RichardWallis - are there any other obvious URL-valued properties missing here?

**Comment by RichardWallis** [comment]
A quick scan through properties that take URL as a value resulted in this list of candidates:
applicationCategory
applicationSubCategory
artMedium
artform
artworkSurface
bankAccountType
bodyType
category
courseMode
credentialCategory
educationalCredentialAwarded
educationalProgramMode
encodingFormat
engineType
fuelType
gamePlatform
genre
knowsAbout
loanType
material
measurementTechnique
meetsEmissionStandard
occupationalCredentialAwarded
roleName
softwareRequirements
sport
unitCode
vehicleTransmission

**Comment by jaygray0919** [comment]
My observation is that `@DefinedTerm` is being overloaded. My concern is that the only way to understand the meaning of a `DefinedTerm` is in the context of the parent type. Perhaps that is "as it should be" - the meaning is in the context of the Class. However, some level of categorization of enumerated terms might be helpful. Of course, the reason **not** to do this is because it's helpful only to a human reader and not to a data harvester. One way to correct for this issue is to add properties to a `@DefinedTermSet` that further specify the meaning of the terms in the set. Harvesters handle that specification well.
