### ISSUE TITLE
Related learning resource

### ISSUE THREAD

**Issue by AlasdairGray** [schemaorg/schemaorg#2830]
At the moment, there is no property for saying that two learning resources are related. There is a related discussion in #1152, but that seems to have gone stale due to the general nature of the proposed property. Also, based on that discussion, I believe that `schema:isRelatedTo` would not be appropriate.

We would like to capture relationships of the form, "you've completed this learning resource try these ones". The linked resources are generally on the same topic but at a more advanced level, but may be on a closely related topic.

This need has come up in the context of developing a collection of learning resources and aiming to use the embedded schema.org markup within them to 
1. Populate a registry of learning resource (do-able with the current properties)
2. Powering a wizard to help navigate the available recipes (this is where we need a new property)

**Comment by philbarker** [comment]
Yes, especially for informal learning it can be useful to be able to find related resources, where the relationship is weaker than being the next resource in a curriculum (because there is no curriculum) but stronger than being about the same topic.

**Comment by jmarks** [comment]
This is important, but will quickly move into the area of learning maps and
pathways, which is more about the sequence of competencies then the
sequence of materials that address those competencies.

**Comment by philbarker** [comment]
I think the need for this is broader that learning resources:
 
- I'm reminded that I use a WordPress option that puts links to "related posts" at the bottom of each post. 
- When I find someone on LinkedIn it shows me a list at the side of who "people also viewed"
- On Twitter when I look at someone's profile I see a list of accounts "you might like"
- BBC News stories often list ~3 links to related stories after a couple of paragraphs.

These all seem like places where a loose and non-specific `relatedItem` relationship might be useful.

**Comment by jmarks** [comment]
+1 but I am quickly reminded of the AlignmentObject conceptually. (Phil,
maybe you saw that coming?)

**Comment by jaygray0919** [comment]
Sequence-related specifications may be more controversial than point-in-time specifications. But the reference to `@Recipe` and `@HowTo/step` is a good pointer. No one knows if the `@HowTo/step` is proper/true, but at least an author can publish their opinion/experience.

The problem I see is the "conditional" - the assertion that "A" must happen before "B". But here again, we have the `@CreativeWork/isBasedOn` pointer which could be reused to express "B" isBasedOn (successful completion of) "A".

We don't use (and see no need for) `@AlignmentObject` but concluded "it's there because an important constituency wants it" (LRMI project). It's one of those highly specialized terms that's akin to a specific routine in a microprocessor's instruction set to deal with legacy code or the specific needs of a customer. IMHO we should not leverage that term or approach.

So to meet @AlasdairGray request, we might consider a variation of isBasedOn (e.g. isDependentOn or isFollowedBy) combined with a variation of `@ItemList/itemListOrder`

**Comment by AlasdairGray** [comment]
Thanks for the suggestions. As @philbarker mentioned, this is more general than learning resources; another example would be the table of related resources at the bottom of a Wikipedia page, e.g. [wp:Schema.org](https://en.wikipedia.org/wiki/Schema.org)
<img width="1134" alt="Screen Shot 2021-02-11 at 09 19 29" src="https://user-images.githubusercontent.com/1141265/107618997-5be44b80-6c4a-11eb-9a4e-cd902d016048.png">
These are not really items in a list with an order or sequence that they should be taken in. 

I do like the idea of a general `relatedItem`.
