### ISSUE TITLE
Schema version not found

### ISSUE THREAD

**Issue by jjkoehorst** [schemaorg/schemaorg#2846]
I was looking for the ontology file for schema.org and was checking out the latest version but the website gives a 404

https://schema.org/docs/releases.html and then click on **11.0** 2020-11-30 yields a 

Error: Not Found

The requested URL /version/11.0/ was not found on this server.

**Comment by RichardWallis** [comment]
That is a known issue that will be fixed in the next release (slated for release 2021-08-03 #2813) - draft version available at https://webschemas.org/.

In the meantime there are three options:

- https://webschemas.org/docs/releases.html#v11.0 will take you to the appropriate release document section
- The archived definition files for each version are available from GitHub here:  https://github.com/schemaorg/schemaorg/tree/main/data/releases
- https://schema.org/version/latest will always route to the latest version documentation

Part of the known issue is that some of the links in the Releases document(for version 11.0) are incorrect and return 404 errors.
