### ISSUE TITLE
Add /structuredData property

### ISSUE THREAD

**Issue by acka47** [schemaorg/schemaorg#2887]
We are currently thinking how to best add "metametadata" – i.e. information about the structuted data itself (like provider, date created/modified or indication of a metadata profile the structured data conforms to) – using schema.org properties. Provisionally, we have been using [`sdo:mainEntityOfPage`](https://schema.org/mainEntityOfPage) resulting in something like this:

```json
{
  "id": "https://example.org/oer",
  "mainEntityOfPage":[
    {
      "id":"https://example.org/oer.json",
      "type":"Text",
      "provider":{
        "id":"https://example.org/provider",
        "name":"Example Metadata Provider"
      },
      "dateCreated":"2020-01-01",
      "dateModified":"2020-02-02",
      "conformsTo":"https://w3id.org/kim/lrmi-profile/2021mmdd/"
    }
  ]
}
```

(Note, we'd match the `conformsTo` to http://purl.org/dc/terms/conformsTo.)

For different reasons, we do not want to use `mainEntityOfPage` anymore and are thinking about alternatives. (See https://github.com/dini-ag-kim/lrmi-profile/issues/63#issuecomment-848731390 (in German) for context.) 

With #1886 the properties [`sdo:sdPublisher`](https://schema.org/sdPublisher), [`sdo:sdLicense`](https://schema.org/sdLicense) and [`sd:sdDatePublished`](https://schema.org/sdDatePublished) were added to pending to enable statements about the structured data itself instead about the described resource. However, I this does not completely solve our problem as we need to add more information than these three statements about the structureed data itself and I also think that this is not the best approach to address the problem.

That is why I propose to add a property `sdo:structuredData` or similar to schema.org so that one can add metametadata while being able to utilize all the properties from `sdo:CreativeWork` and properties from other vocabularies (like `dct:conformsTo`). Its usage would look something like this:

```json
{
  "@context":{
    "@vocab":"https://schema.org",
    "conformsTo":"http://purl.org/dc/terms/conformsTo"
  },
  "id":"https://example.org/oer",
  "structuredData":[
    {
      "type":"Text",
      "provider":{
        "id":"https://example.org/provider",
        "name":"Example Metadata Provider"
      },
      "dateCreated":"2020-01-01",
      "dateModified":"2020-02-02",
      "conformsTo":"https://w3id.org/kim/lrmi-profile/2021mmdd/"
    }
  ]
}
```

**Comment by Abbe98** [comment]
In my opinion, this would be a super valuable pattern for various metadata aggregation scenarios.

**Comment by acka47** [comment]
@danbri What can I do to bring this forward? Would a pull request help?

**Comment by stain** [comment]
Really agree on this. `structuredData` would effectively make any `CreativeWork` property applicable on the metadata without affecting the actual object it is on, for instance `isBasedOn` or as in #1516 the new `conformsTo` – we won't need `sdConformsTo` etc.

If this goes in, then `sdPublisher`, `sdLicense`, `sdDatePublished` would effectively be deprecated in favour of `structuredData: { publisher: {}, license: {}, datePublished: "" }` – but perhaps we can leave that deprecation to later to see how this goes.

Perhaps `structuredData` could also have `encoding` to downloadable metadata for this resource. For instance we have separate JSON-LD alternates, and it should be possible to find those without having to do content negotiation - we have so far used https://schema.org/subjectOf for that, but this `structuredData` mechanism would allow alternative metadata formats to be grouped together and make it more clear that it's the metadata.

Example:

```json
<script type="application/ld+json">
{ "@id": "https://example.com/archive-1996/",
  "@type": "WebSite",
  "datePublished": "1996-05-27",
  "name": "Archive of 1996 website",
  "structuredData": {
    "@type": "CreativeWork",
    "datePublished": "2021-06-10",
    "isBasedOn": "https://example.com/rss.xml",
    "identifier": "urn:uuid:d4f7c222-a15f-4964-8478-2acc57d2a6ac",
    "encoding": {
      "@id": "https://example.com/archive-1997/metadata.jsonld",
      "@type": "MediaObject",    
      "encodingFormat": "application/ld+json"
    }
  }
}
</script>
```

In this example there is an [archived website](https://soiland.no/archive-1997/) from 1996, with metadata from 2021.  Metadata was derived from an old `rss.xml` file with UUID `d4f7c222-a15f-4964-8478-2acc57d2a6ac` and is also available as a separate JSON-LD download.

**Comment by acka47** [comment]
> Perhaps structuredData could also have encoding to downloadable metadata for this resource.

Yes, I haven't thought about it yet but this would be very useful. [`encoding`](https://schema.org/encoding) is used on `CreativeWork` and a new `structuredData` property should expect values of `CreativeWork` so that this would directly work.

**Comment by smrgeoinfo** [comment]
I have to say that using the label 'structuredData' for an element that is essentially metadata about 'self' seems likely to be confusing for anyone not familiar with its historic usage in the schema.org realm. Couldn't we just use the label 'metadata'?  in all the comments above the content of 'structuredData' is referred to as metadata.   To me 'structuredData' is far too general a label.

**Comment by smrgeoinfo** [comment]
The science on schema.org group [recommends using schema:subjectOf](https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#metadata), and that seems like a better solution

**Comment by Abbe98** [comment]
schema:subjectOf might be confusing on its own I believe, it works well in the science on schema.org group's case as they can utilize the schema:DataDownload type. Many I believe would be stuck with schema:CreativeWork which might make the relation between the metadata work and the actual Thing or Work rather implied:

```
{ 
  "@id": "https://example.com/record/123",
  "@type": "CreativeWork",
  "name": "Mona Lisa",
  "subjectOf": {
    "@type": "CreativeWork",
    "datePublished": "2021-06-11",
    "isBasedOn": "https://example.org/painting-123"
  }
}
```

I imagine this could be addressed in various ways like non-schema.org types and/or elaborative descriptions.

**Comment by acka47** [comment]
Regarding the naming, I am open to a better name. I proposed `structuredData` as it is already a common term in schema.org and is used – as akronym – in the properties `sdPublisher`, `sdLicence` and `sdDatePublished`. I don't think that `subjectOf` is less confusing than e.g. `mainEntityOfPage` so I wouldn't use that.

In the context of our [lobid-resources dataset](https://lobid.org/resources/dataset#!) we are using [`wdrs:describedby`](https://www.w3.org/2007/05/powder-s#describedby) for the same purpose (see [example JSON-LD](https://lobid.org/resources/HT002948556.json)).  I could also imagine using `sdo:describedBy`. Like `structuredData`, it doesn't contain a rather philosophical term like "entity" or "subject".

**Comment by philbarker** [comment]
I think the problem with `subjectOf` is that there is no way to know that value is going to be structured data, it could just as easily be a link to a book about the subject.

**Comment by smrgeoinfo** [comment]
Ooops-- the SOSO recommendation is based on the premise that the 

> schema.org record represents metadata about a Dataset _[think more generically-- any resource]_, many providers will also have other metadata records that may be more complete or that conform to other metadata formats and vocabularies that might be useful

So the rdf:object of the 'subjectOf' rdf:predicate is a resource that is about the same resource the schema.org record is about.  Not the use case here, which (I think) is to provide information about the schema.org record itself-- who created, when was it updated, who should I contact if it contains errors?

**Comment by Abbe98** [comment]
@smrgeoinfo that you for such an elaborative example! I too think that a class is the go-to solution as it allows whoever does the modeling to decide if the "main" object is the one holding "data metadata" or the "thing metadata" rather than having it decided by a property.

**Comment by salgo60** [comment]
Have you looked into Proper Attribution for Curation and Maintenance of Research Collections: Metadata Recommendations of the RDA/TDWG Working Group" DOI: [10.5334/dsj-2019-054](http://doi.org/10.5334/dsj-2019-054) 

* [www.w3.org/TR/prov-o/#qualified-terms-figure](https://www.w3.org/TR/prov-o/#qualified-terms-figure)

![image](https://user-images.githubusercontent.com/14206509/121824049-88b47800-cca9-11eb-8fe9-838c57bc9228.png)

![image](https://user-images.githubusercontent.com/14206509/121824075-a8e43700-cca9-11eb-8300-1c13811f8694.png)

**The user case** I see is that a picture is copied between institution A <-> B <-> C and that you can check in the metadata what structured data is available and also that institution C can ask institution A what metadata they have right now....

I did a small metadata runestoune test with Swedish runestones and Wikidata / Wikicommons where we have semantic interoperability between Wikicommons and WIkidata see [Structured data for GLAM-Wiki Roundtripping](https://meta.wikimedia.org/wiki/Structured_data_for_GLAM-Wiki/Roundtripping/KMB)

![image](https://user-images.githubusercontent.com/14206509/121824178-7ab32700-ccaa-11eb-84a0-fef4c4534699.png)

**Comment by aisaac** [comment]
I too am very much in favour of the proposed pattern, and not using the many (possibily unlimited) properties like `sd:sdLicense`, which are going to be very confusing... Such patterns aligns quite well with what aggregators like Europeana are (or should) be doing.
Regarding the name I find `structuredData` too semantically unloaded. `describedBy` would already be better (or a combination of both)?

For the record the pattern aligns quite well with the _ResourceMap_ idea from OAI-ORE: http://www.openarchives.org/ore/1.0/datamodel#Resource_Map . 
We've adopted that for the Europeana Linked Data service at some point. It's been discontinued since, because, well, there was not a lot of metadata and it was all the same across our published data and data consumers seems not so interested. But that was 11 years ago...
OAI-ORE uses a property called `isDescribedBy` to connect the ORE aggregation (a bundle of aggregated resource in digital libraries). 
But note that for connecting to the "real" object (as opposed to this technical "aggregation" thing), the property we had used was foaf:primaryTopic (so it would be foaf:isPrimaryTopicOf for the direction you're looking at, here).
There's a bit more discussion/examplification in section 5.2 and fig. 3 in the paper here: https://dcpapers.dublincore.org/pubs/article/view/3625
And primaryTopicOf is mentioned in section 4.6 here: http://www.semantic-web-journal.net/content/europeana-linked-open-data-%E2%80%93-dataeuropeanaeu (we had realized the need to use a different property for our two cases only after the first paper)

**Comment by salgo60** [comment]
Recommends to see and learn from this session _Converging Digital Specimens and Extended Specimens - Towards a global specification for data integration Phase 2_
* today they have online sessions you can follow se [Converging Digital Specimens and Extended Specimens - Towards a global specification for data integration Phase 2.](https://discourse.gbif.org/t/digital-extended-specimens-phase-2/2651)
  * twitter [DigExtSpecimen](https://twitter.com/hashtag/DigExtSpecimen?src=hashtag_click)

**Comment by smrgeoinfo** [comment]
@aisaac -- which pattern are you in favor of, sorry its not clear.

**Comment by aisaac** [comment]
@smrgeoinfo I am a bit conventional when it comes to github tickets. By default, I was refering to the very first thing proposed in the description, by @acka47 

> I propose to add a property sdo:structuredData or similar to schema.org so that one can add metametadata while being able to utilize all the properties from sdo:CreativeWork and properties from other vocabularies (like dct:conformsTo).

**Comment by stain** [comment]
> Regarding the name I find `structuredData` too semantically unloaded. `describedBy` would already be better (or a combination of both)?

## Relation to FAIR Signposting and IANA link types

As @aisaac `describedby` is also the [FAIR Signposting](https://signposting.org/FAIR/) link relations used to point to metadata, e.g.

```html
 <link rel="describedby" type="application/x-bibtex" href="https://example.org/meta/7507/bibtex" >  
```

_Note: Lowercase above as is convention for link relations - schema.org convention is camelCase)_

(tagging @hvdsomp) 

However I think we are now moving into a different property that is more for finding URLs of other metadata 
resources, rather than describe `this` metadata (as `sdPublisher` etc is commonly used). 

## Why is it not subjectOf?

(We have [already](https://about.workflowhub.eu/Workflow-RO-Crate/ro-crate-preview.html#example/) used `subjectOf` in combination with `encodingFormat` and `conformsTo` for linking to _other_ metadata files - the fact it is "structured metadata" is then implied from those format properties)

But the question is then what if you want to describe properties of _this_ metadata that the statement occurs in? Ideally on a entity/resource-level rather than JSON-LD-wide level as this property is mainly useful when metadata comes from many sources.

@Abbe98 suggest a pure use of `subjectOf` without `@id` – but really it is just saying the thing has been described some unknown place in 2021 (which for all we know may no be the _metadata you are currently reading_, but an unidentified in-person talk about the subject). So the `subjectOf` property alone is not sufficient.

## describedBy points to StructuredData

If we imagine `describedBy` (or `structuredData`) as a subproperty of https://schema.org/subjectOf then what makes it different from `subjectOf` _A CreativeWork or Event about this Thing_?   The point is we want to talk _about metadata_ (metametadata), so the object on the right is not any odd `CreativeWork` but `StructuredData` (neighbour of https://schema.org/StructuredValue) - data that is machine-readable in some (possibly undeclared) format. 

It should also be possible to have `"@id": ""` (the page you are on) have a different history from its embedded metadata - we see with `sdLicense` etc.

## Mona Lisa example again!

Now we can do @smrgeoinfo's Mona Lisa version and put it upside-down - the main `Painting` is back in focus.

```json
{
  "@context": "https://schema.org/",
  "@id": "http://example.com/famous-art/mona-lisa",
  "@type": "Painting",
  "creator": {
    "@type": "Person",
    "name": "Lionardo di ser Piero da Vinci",
    "additionalName": "Leonardo da Vinci",
    "birthPlace": {
      "type": "Place",
      "name": "Farmhouse outside the village of Anchiano in Tuscany",
      "photo": "https://www.historyhit.com/app/uploads/2020/07/2016_Birthplace_of_Leonardo_da_Vinci_in_Anchiano_03-1.jpg"
    },
    "describedBy": [
      {
        "@id": "#about_leonardo",
        "@type": "StructuredData",
        "description": "THIS Leonardo's metadata was derived from historyhit.com – the #fragment may even be a corresponding HTML <div> with the same metadata",
        "isBasedOn": "https://www.historyhit.com/facts-you-might-not-know-about-leonardo-da-vinci/"
      },
      {
        "@id": "https://dbpedia.org/data/Leonardo_da_Vinci.jsonld",
        "@type": "StructuredData",
        "conformsTo": "https://www.dbpedia.org/resources/ontology/",
        "description": "There's some other metadata over there, but it might not even be using schema.org. We optionally add conformsTo to clarify the PROFILE, for structured application/json data formats in APIs that are often not registered with their own media types, or use general Linked Data formats like JSON-LD.",
        "encodingFormat": "application/ld+json"
      }
    ]
  },
  "describedBy": {
    "@type": "StructuredData",
    "creator": {
      "@id": "https://orcid.org/0000-0001-9842-9718",
      "name": "Stian Soiland-Reyes"
    },
    "isBasedOn": "https://github.com/schemaorg/schemaorg/issues/2887#issuecomment-859770430",
    "description": "This (anonymous) structured data by Stian is about the Painting, and the metadata is further described in this github issue",
    "subjectOf": "https://github.com/schemaorg/schemaorg/issues/2887"
  },
  "description": "enigmatic image of a lady with weird symbolism in the background",
  "sameAs": "https://dbpedia.org/resource/Mona_Lisa",
  "subjectOf": [
    "https://en.wikipedia.org/wiki/Mona_Lisa",
    "https://www.britannica.com/topic/Mona-Lisa-painting"
  ]
}
```

This example have two different `describedBy` to highlight metadata can come from different sources.

Here I built on @smrgeoinfo idea of a local identifier for the `StructuredData` and I think `#anchors` work well as you can include them in RDFa `<div>` as well as long as being careful about the current subject (which is always the case in RDFa!)

**Comment by hvdsomp** [comment]
Signposting is just totally not about semantics but about an attempt to get a common lowest denominator interop layer for repos. Solely based on IANA registered link relation types. No ontologies, no RDF, no “my ontology is better than yours”, but just utterly basic links with types that were somehow formally specified in RFCs etc. With a system that has RDF-style expressiveness built in, it should be a breeze to dumb things down to provide Signposting links. I mean, why not if the info is available and accessibility for less clever clients can be achieved?

**Comment by acka47** [comment]
I like @stain's proposal which boils down to adding a property `describedBy` and a type `StructuredData`.

On a side note, I think https://schema.org/docs/datamodel.html#mainEntityBackground should be updated to incorporate `subjectOf` and – if implemented – the new property to be added via this issue. Also, the properties dealt with in https://schema.org/docs/datamodel.html#mainEntityBackground should have a link to the background paragraph on their respective pages. Currently, the background notes are only linked from https://schema.org/mainEntityOfPage.

**Comment by smrgeoinfo** [comment]
I think there's a problem with @stain 's suggested solution. If you consider the triples represented by the JSON-LD object, you have (from JSON-LD playground) 
`<http://example.com/famous-art/mona-lisa> <schema:subjectOf> "https://en.wikipedia.org/wiki/Mona_Lisa" .`
 
and also
```
<http://example.com/famous-art/mona-lisa> <schema:describedBy> 
    [   rdf:type schema:StructuredData.
       <schema:creator> <https://orcid.org/0000-0001-9842-9718> .
      <schema:subjectOf> "https://github.com/../2887#issuecomment-876635782" .
      _note--other triples whose subject is the blank node are left out_
     ] 
```
meaning--
...famous-art/mona-lisa is the subject of a wiki page about the actual painting
...famous-art/mona-lisa is described by some schema.org structured data that is about the JSON-LD object

The thing that is the subject of these triples is NOT the same thing.  To make assertions about the JSON-LD object (a metadata record about the mona lisa) distinct from assertions about the actual painting, there must be distinct identifiers for these two different things.

**Comment by acka47** [comment]
> To make assertions about the JSON-LD object (a metadata record about the mona lisa) distinct from assertions about the actual painting, there must be distinct identifiers for these two different things.

I see no problem here: The actual painting is identified with `<http://example.com/famous-art/mona-lisa>` and the metadata record has no URI, thus is a blank node, meaning it could or could not be identical  with `<http://example.com/famous-art/mona-lisa>`. It is not wrong to only have a URI and one bnode – or even to have two bnodes for the described resource and the structured description, it would only be wrong if these things had the same identifier. 

Adding this property – whether called `structuredData` or `describedBy` – is all about having a convention to say something about a structured data document itself and doing it in the document itself. In RDF turtle syntax there exists an easy way to indicate the document itself as subject with `<>`, e.g.: `<> dc:title "This RDF file"`. As such an option does not exist for all RDF serializations (like JSON-LD), we have to work around it.

In any case, in the context of schema.org, we can not demand implementers to record a URI for the metadata document when they aren't even asked to supply a URI for the described resource itself. Just take a look at some examples like [`sdo:genre`](https://schema.org/genre) where no URI for the painting "The Madonna with the Long Neck" is given:

```json
{
  "@context": "https://schema.org",
  "@type": "Painting",
  "name": "The Madonna with the Long Neck",
  "genre": "http://vocab.getty.edu/aat/300021143"
}
```

**Comment by smrgeoinfo** [comment]
[@id identifies a node in a graph](https://w3c.github.io/json-ld-syntax/#node-identifiers); in @stain 's example, the metadata record is that node-- it is not a blank node. The node is of type schema:Painting, and that type tells me what properties can be expected to be populated on that node. It is convenient to conflate the digital object (the metadata record that is a node in a graph) with the physical object by assuming that the @id for the node also identifies the physical thing, and this works,  but only until one want's to make statements only about the metadata record (who created it, when is was updated, what metadata profile it conforms to...), which I believe is the point of this discussion.

**Comment by smrgeoinfo** [comment]
So looking at @stain's example again...  on the creator node, there are two 'describedBy' nodes. Under the proposed solution, those  (with identifiers "#about_leonardo" and "https://dbpedia.org/data/Leonardo_da_Vinci.jsonld") should both provide information about the creator node (not about the person).  #about_leonardo does, but "https://dbpedia.org/data/Leonardo_da_Vinci.jsonld" is actually about the person, not the container graph node, so it seems to me that should be the linked via the 'subjectOf' property. 

    "describedBy": 
      {
        "@id": "#about_leonardo",
        "@type": "StructuredData",
        .....
      },
    "subjectOf" :  {
        "@id": "https://dbpedia.org/data/Leonardo_da_Vinci.jsonld",
        "@type": "StructuredData",
        ......
      }

Interesting question is the @type on  the dbpedia jsonld link.

**Comment by aisaac** [comment]
I'm frankly a bit puzzled. From @stain 's example above, my reading would be that neither isSubjectOf nor isDescribedBy alone can be useful. And since there's no good machinery available across the board to indicate "this document". 
In the Europeana-related examples I've pointed to, our pattern worked because at some point in OAI-ORE there's an intermediate construct (the Aggregation) that's connected to the "document" (the ResourceMap) in a one-to-one way. But in the case here, we don't have that.
The only way that I would see is to constraint `isDescribedBy` to have only one possible object. And if other documents/StructuredData describe the same resource, then they should be connected via `subjectOf`. Or the other way round, as people prefer ;-)

**Comment by millionairekim** [comment]
I also facing this issue on my this web: [https://s3rcn.org/](https://s3rcn.org/), I worry about my google ranking
![homepage](https://github.com/user-attachments/assets/aa8023bd-bf3f-40ec-9cb7-7faac77c829d)
