### ISSUE TITLE
Documentation Examples on BlogPosting and LiveBlogPosting Duplicate

### ISSUE THREAD

**Issue by HughP** [schemaorg/schemaorg#2892]
Greetings,

I was using the documentation to look for examples of how to mark up BlogPosting. I notice the example provided is duplicated from LiveBlogPosting. 

https://schema.org/BlogPosting
https://schema.org/LiveBlogPosting

I'm not sure, based on the examples given how these two terms (BlogPosting & LiveBlogPosting) should be differentiated in practice. It looks like maybe the BlogPosting example was mistakenly copied from LiveBlogPosting.

**Comment by danbri** [comment]
That did sound like an error - thanks for taking the time to report it. When I took the look, it seems that this is what's going on:

 * every example we have in our site (and this repo) is tagged with one or more schema.org terms that it illustrates. So in this case, the example in [sdo-social-media-examples.txt](https://github.com/schemaorg/schemaorg/blob/main/data/sdo-social-media-examples.txt#L88) has both LiveBlogPosting, BlogPosting because it shows an example of a LiveBlogPosting which includes several updates made to it, which are typed just as BlogPosting. 
 * LiveBlogPosting is a subtype of BlogPosting, but the relationship isn't explained very clearly.
 * The type [Blog](https://schema.org/Blog) is in 2021 more confusing, because it is increasingly common to refer to the posts on a blog (aka "weblog") as "blogs" too. Blog should have a proper definition.
* Putting these under Article looks awkward.

We can do better. I've queued this for attention in the next release.

/cc @vholland (and #526) who led the original design.

**Comment by danbri** [comment]
I've added fixes to all the aspects I mentioned above, which should go out soon in Schema.org version 13. The only point I didn't touch is the question of modeling these as subtypes of Article. That probably deserves consideration as part of a larger cleanup of the CreativeWork hierarchy. Thanks again @HughP for taking the time to let us know this was confusing!

**Comment by danbri** [comment]
Ok so these improvements *did* go out as part of version 13 release. Thanks again @HughP!
