### ISSUE TITLE
Change domain of associatedMedia to Thing

### ISSUE THREAD

**Issue by jvandriel** [schemaorg/schemaorg#292]
Proposal can be found at: https://www.w3.org/wiki/index.php?title=WebSchemas/SchemaDotOrgProposalsArchive#2011-2014_Proposals_for_Schema.org

Discussion at:
http://lists.w3.org/Archives/Public/public-vocabs/2014May/0224.html

**Comment by danbri** [comment]
From the proposal, https://www.w3.org/wiki/WebSchemas/associatedMediaToThing

    Currently, http://schema.org/associatedMedia, which has a range of http://schema.org/MediaObject and which would otherwise seem suitable for this purpose, has a domain of CreativeWork. 
    This means that http://schema.org/MedicalProcedure and other children of Thing 
    that do not descend from CreativeWork have no straightforward means of 
    including media objects that complement their content.

    See the discussion at http://lists.w3.org/Archives/Public/public-vocabs/2014May/0204.html and http://lists.w3.org/Archives/Public/public-vocabs/2014May/0224.html

    Proposed solution
    Change the domain of associatedMedia to Thing. The benefit of this proposal is that we would 
    cover AudioObject, DataDownload, ImageObject, MusicVideoObject, VideoObject, and 
    any other MediaObject subclass that comes into being.

All of the examples listed in the proposed solution,

* http://schema.org/AudioObject
* http://schema.org/DataDownload
* http://schema.org/ImageObject
* http://schema.org/MusicVideoObject
* http://schema.org/VideoObject

... are already subtypes of CreativeWork they can already be used with http://schema.org/associatedMedia without problems.

The only other type offered as motivation for this was MedicalProcedure.

We would prefer to add specific additional domains to a property rather than just open it up for random use in any situation. Schema.org does not have so many types directly under Thing. So let's take this case-by-case.

Let's consider one: BroadcastService. Currently http://schema.org/BroadcastService is a direct subtype of Thing (and this should probably be reconsidered). An example of this would be the UK's broadcasting service BBC1. According to https://en.wikipedia.org/wiki/BBC#Finances "The BBC has the second largest budget of any UK-based broadcaster with an operating expenditure of £4.896 billion in 2012/13". 
"In December 2012, the BBC completed a digitisation exercise, scanning the listings of all BBC programmes ... They identified around five million programmes, involving 8.5 million actors, presenters, 
writers and technical staff.". What would the associatedMedia for the BroadcastService BBC1 be? All of its output? The property is already vague, but manageably so do to its applicability being scoped to (roughly) "document like objects" i.e. Creative Works.

Every time we admit a new type into the domain of a property we create implicit questions like this (and therefore usability challenges for users of the vocabulary.

Perhaps there are specific scenarios where we could usefully extend associatedMedia - e.g. for describing Event? In each case we'll have such questions. Should the associatedMedia of an Event be a representation of it, if it happened? A photo of a performer if it has not yet happened? etc.

So what are the kinds of non-CreativeWork that are the strongest candidates for use with associatedMedia? MedicalEntity, maybe Event, Action?  

What would it mean to be the associatedMedia of an Organization, Person, Place or Product? Remembering that we already have http://schema.org/about to indicate the subject matter, which captures a related but stronger association between entities and content.

**Comment by jvandriel** [comment]
"So what are the kinds of non-CreativeWork that are the strongest candidates for use with associatedMedia?"

Besides MedicalProcedure the most common examples I get confronted with/asked about is 
"How do I add a VideoObject to a Product or Organization". In most cases this is because folks would like to express they have an introductory video about a Product or Organization.

Now I agree that one could markup a VideoObject and have it's 'about' property refer to the Product or Organization but in this case, given the fact there's no 'mainEntity' property yet, current heuristics of the search engines will cause the VideoObject to be treated as the 'mainEntity', where in these cases the Product or Organization should be considered the 'mainEntity'.

Next to that, because there is no 'associatedMedia' property for Product and Organization, this forces folks to markup multiple entities, leading to more markup than is needed. For example:

'''<div itemscope itemtype="http://schema.org/Product">
    ...
   <iframe itemprop="associatedMedia" src="url-to-some-video"></iframe>
</div>'''

Seems much more efficient and less prone to error than:

'''<div id="about-product" itemid="#about-product" itemscope itemtype="http://schema.org/Product">
    ...
    <div itemscope itemtype="http://schema.org/VideoObject">
        <iframe itemprop="embedUrl" src="url-to-some-video"></iframe>
        <link itemprop="about" href="#about-product">
</div>'''

**Comment by danbri** [comment]
Thanks for the examples, that helps. If we get mainEntity finished, how much of the problem goes away?

**Comment by jvandriel** [comment]
Partially, as it would still prevent simpler markup like:

```
<div itemscope itemtype="http://schema.org/Product">
    ...
   <i-frame itemprop="associatedMedia" src="url-to-some-video"></i-frame>
</div>
```

**Comment by jvandriel** [comment]
I just noticed ```mainEntity``` and ```mainEntityOfPage``` were added to sdo-gozer, which I think is great, but which still leaves me wondering whether or not associatedMedia's domain will be expanded to Thing (or limited to Organization and Product).

Because personally I still don't believe the mainEntity route is enough (as illustrated in my previous post).

**Comment by vholland** [comment]
One example is live (video or audio) broadcasts of an Event. We have "recordedIn", but it is unclear if that should be used for live streams.

**Comment by jvandriel** [comment]
Do you have an url where I can look @vholland?

**Comment by vholland** [comment]
Major League Baseball livestreams games (with a subscription). http://mlb.mlb.com/mediacenter/index.jsp?c_id=mlb&affiliateId=mlbMENU

I suppose they could create a WatchAction or ListenAction as appropriate for each stream.

**Comment by jvandriel** [comment]
I was more thinking about pages like these:
- http://www.volkswagen.nl/modellen/passat (sorry it's in Dutch)
- http://www.apple.com/macbook/ (watch the design film)
- http://www.cosmeticsurg.net/procedures/brazilian-butt-lift/

**Comment by DDeering** [comment]
Hi all, I was hoping that we could renew this conversation about changing the domain of associatedMedia to Thing.  It seems to be a viable solution that could be used to associate various forms of media to various types of entities.

**Comment by DDeering** [comment]
Would it be possible to move forward with changing the domain of associatedMedia to Thing in response to the issues raised here?

**Comment by jvandriel** [comment]
The introduction of https://schema.org/subjectOf in schema.org 3.8 covers the objective of this proposal.
