### ISSUE TITLE
Add vocabulary for course websites

### ISSUE THREAD

**Issue by JonathanReeve** [schemaorg/schemaorg#2997]
As a university instructor, I make a lot of course websites. I'd like to make them semantic, as well, using schema.org vocabulary, perhaps. So it'd be nice if there were a way to describe my courses, and their assigned texts, in a schema.org fashion. The [CCSO](https://vkreations.github.io/CCSO/) lays a nice foundation for an ontology.

**Comment by philbarker** [comment]
Hi Jonathan, have you tried how far you can get with [schema:Course](https://schema.org/Course) and [schema:CourseInstance](https://schema.org/CourseInstance) You can find the motivations (use cases) behind these terms on the [Schema Course Extend](https://www.w3.org/community/schema-course-extend/wiki/Main_Page) wiki. They also play nicely with [oerschema](http://oerschema.org/), for example in [K12OCX](https://k12ocx.github.io/k12ocx-specs/).

**Comment by JonathanReeve** [comment]
That's very close to what I was looking for! What's the plan for getting this integrated into schema.org?

**Comment by philbarker** [comment]
Sorry @JonathanReeve I'm not sure which bits you mean by "this".  Anyway, the Course and CourseInstance parts are already in schema.org.  I don't know of any current plan to integrate the OERSchema part into schema.org. As a whole OERSchema is maybe out of scope or, rather, too detailed for schema.org. Putting it in to schema.org wouldn't have anybenefit unless someone planned to consume the data and use it to provide a service. This would be as good a place as any to report any use cases / proposals to do that, especially if they are linked to small changes like introducing single properties rather than pull in the whole model. OERSchema is, of course, perfectly usable without being part of schema.org.

**Comment by JonathanReeve** [comment]
Ah I understand now. I suppose I'm looking for a way to express that a course assigns a certain collection of texts. This is mainly so I can provide a template for future courses, so that, among other things, [my research project which surveys curricula](https://github.com/JonathanReeve/data-ethics-literature-review) can scrape them, and determine the most-assigned texts, for instance. I'm guessing that's probably best done with OERSchema. Thanks! I'll close this issue.

**Comment by chrisspradling1980** [comment]
Would you mind if I challenged this "scrapping" to a scrap yard or a judge
my friend?
