### ISSUE TITLE
Add /OnlineStore as subclass of /Organization

### ISSUE THREAD

**Issue by alex-jansen** [schemaorg/schemaorg#3028]
**Context** - This is a proposal from Google based on our experience consuming schema.org [/Organization](https://schema.org/Organization) markup and working with similar data from online merchants. If it were accepted, it would make it easier for us and others to recognize which web sites are online sellers.

The /Organization type has many sub-types, but none accurately represents an online seller or store. Detecting the nature of organizations on the web, and e-commerce web sites in particular, is useful for general web site understanding. We therefore suggest to add an /OnlineStore subtype of /Organization.

**Comment by WeaverStever** [comment]
It seems to me that a counterpart to localBusiness, onlineBusiness. might be a better top-level subType so that it might include other businesses that do not offer brick and mortar locations.  

More specific subTypes might someday include:

- onlineStore
- onlineLearning
- onlineConsultant
- onlineEvents
- onlinePersonnel
- onlineData
- onlineLogistics
- onlineSoftware
- onlineInfluencer

**Comment by alex-jansen** [comment]
@WeaverStever Agreed, that makes sense and is indeed more consistent with localBusiness.

**Comment by alex-jansen** [comment]
Thank you @RichardWallis !
