### ISSUE TITLE
Schema.org should have mappings to Gratisdata terms where possible

### ISSUE THREAD

**Issue by ugochimobi** [schemaorg/schemaorg#3049]
This is quite a bold request from a small website, but this is similar to a request made from Wikidata over 7 years ago, specifically https://github.com/schemaorg/schemaorg/issues/280 this issue. 

Everything works similarly just as Wikidata works but this one powers a different project. 
Just as pointed out there;
- mappings (exact, super/sub) from properties and (perhaps to a lesser extent in that the notion isn't so built-in) types to schema.org can be expressed within Gratisdata.
- Schema.org has updated its extension mechanism and is encouraging both hosted and external extensions.

### Useful Links
- List of Gratisdata properties https://gratisdata.miraheze.org/wiki/Special:ListProperties

**Comment by danbri** [comment]
@ugochimobi - interesting. Are you using Wikibase?

How about a slightly larger goal: 

 * we should have a way to find mappings between Schema.org terms and those used in Wikibase installations (beyond Wikidata, c.f. #280). 
  
 There is also the related issue of mapping wikibase installations to Wikidata's core terminology.

(from a quick look it seems like you're using Wikibase, apologies if this is a mistake)

**Comment by danbri** [comment]
I looked into this some more, and my conclusion is that you (and others) should continue to follow the model established at Wikidata: store the mappings to external schemas within the wikibase installation. See https://github.com/okfn-brasil/schemaOrg-Wikidata-Map/blob/master/docs/quering-Wikidata.md for more details!

I don't think there's anything actionable here for Schema.org right now, so I will close this issue. You are welcome to continue posting here - e.g. to report progress with mappings work.

**Comment by ugochimobi** [comment]
Oh, thanks then.

**Comment by thadguidry** [comment]
@ugochimobi @danbri I don't have any other links to share other than Peter's as you gave already for the mapping effort.  I only have a few mapping notes in a Google doc somewhere.

@ugochimobi I agree with @danbri in that you should map your entities in your Wikibase installation using coherent properties (ideally same properties used in Wikidata mappings) to link the vocabulary.  This helps foster the Wikibase federation ecosystem and wider federated querying eventually.  Another additional thing would be for you to publish the mappings inside of Wikidata.org itself as well since Wikidata is shaping up to become a very central hub of the many spokes of linked data.  Gratisdata can serve as one spoke.

That being said, however, you can also store your mappings outside of the Wikibase ecosystem (perhaps with a bit of risk if the concordance becomes inaccessible or non-permanently published) in external concordances such as https://coli-conc.gbv.de/

If you have questions about the Schema.org mappings we did and currently stored in Wikidata.org directly then certainly reach out through the Wikidata public mailing list and cc me.

**Comment by ugochimobi** [comment]
> @ugochimobi No, your structured data looks good to me, for SEO purposes or consumption by any linked data parser.

So a mapping won't be considered necessary because of this? or there anything that can be done to foster the effectiveness of these data?

**Comment by ugochimobi** [comment]
@thadguidry

**Comment by thadguidry** [comment]
@ugochimobi you can have multiple items using Array [ ] in any Schema.org property.  You could certainly use sameAs and give multiple entity IDs or URLs from various published KOS as well as Wikidata.org.  This is a form of localized mapping, I.E. you do the mapping and store the sameAs links in your own KOS.  Most linked data parsers will understand the semantics of what you mean here with sameAs.  However, getting additional linked data from each indexed object in the array is up to the consuming application, like Google, which does do a pretty good job whenever good structured data can be found and parsed from each sameAs link.  Providing sameAs links that have structured data themselves on their pages is the best practice, when you can find them.

Loose working example:
```json
"sameAs": ["https://stias.ac.za/fellows/eghosa-emmanuel-osaghae/", "https://niia.gov.ng/about-us/dg/", "https://gratisdata.miraheze.org/wiki/Q2955", "https://www.strausscenter.org/person/eghosa-osaghae-2/"]
```

**Comment by ugochimobi** [comment]
@thadguidry While going through the documentations about enabling this feature for Gratisdata, I couldn't find any information regarding making it possible to have multiple sameAs properties. I know it's possible, but how can that be accomplished? (_I'm sorry if I'm sounding dumb as I'm relatively new in the linked data network generally_).

How did you get the working example so fast?

**Comment by thadguidry** [comment]
@ugochimobi This is getting beyond the bounds of a Schema.org Issue directly.  Let's move this consultation to our Schema.org [Discussions](https://github.com/schemaorg/schemaorg/discussions/new) to involve others to also assist you.

**Comment by ugochimobi** [comment]
@thadguidry here #3089
