### ISSUE TITLE
	 JSON-LD Missing ':' after object member name.

### ISSUE THREAD

**Issue by shanupshaji** [schemaorg/schemaorg#3072]
<script type="application/ld+json">
        
        {
        ""@context"": ""https:schema.org"", //error in this line
        ""@type"": ""SiteNavigationElement"",

**Comment by RichardWallis** [comment]
@shanupshaji where are you seeing this error?

**Comment by shanupshaji** [comment]
> @shanupshaji where are you seeing this error?

@RichardWallis i am seeing this error while validating schema.

**Comment by Tiggerito** [comment]
Not sure if it's how the code posts here, but your double quotes are doubled up.

It would help to see the original code or even a link to where the code is.

**Comment by danbri** [comment]
This does not sound like a problem with Schema.org itself, but a markup question. If I misunderstand, let me know, but I am otherwise closing this issue as we can't run a general helpdesk for the millions of sites using Schema markup.

It sounds like this issue is that the markup being checked looks like this:

```
<script type="application/ld+json"> 
{ 
  ""@context"": ""https:schema.org"", 
  ""@type"": ""SiteNavigationElement"", ...
```

When it should look like this:

```
<script type="application/ld+json"> 
{ 
  "@context": "https:schema.org", 
  "@type": "SiteNavigationElement", ...
```

- as @Tiggerito puts it, the "double quotes are doubled up".
