### ISSUE TITLE
Learning Resource as Creative Work or Product?

### ISSUE THREAD

**Issue by natecovington** [schemaorg/schemaorg#3154]
Hi, I'm having trouble with Google Search Console validating this page's schema code:
https://www.lovetoteach.org/teaching-tools/x-ray-bones-coloring-page.html

I'm trying to incorporate CreativeWork with the corresponding learningResourceType AND an Aggregate Rating score with code like this:

```
<script type="application/ld+json">
	{
		"@context": "https://schema.org/",
		"@type": "CreativeWork",
		"name": "<?php echo $this->item->title; ?>",
		"description": "<?php echo str_replace('"', '', $this->item->introtext); ?>",
		"learningResourceType": [
			"lesson plan",
			"learning activity"
		],
		"audience": {
			"@type": "EducationalAudience",
			"educationalRole": "teacher"
		},
		"aggregateRating": {
		"@type": "AggregateRating",
		"ratingValue": "<?php echo ($this->item->votingPercentage / 20); ?>",
		"reviewCount": "<?php echo (str_replace(array('(', ')', 'Vote', 'votes', ' '), '', $this->item->numOfvotes)); ?>",
		"bestRating": "5"
	  }
	}
</script>
```

However, it doesn't seem like I'm supposed to use CreativeWork as the primary type, these are what are supported:

`[http://schema.org/Book, http://schema.org/Course, http://schema.org/CreativeWorkSeason, http://schema.org/CreativeWorkSeries, http://schema.org/Episode, http://schema.org/Event, http://schema.org/Game, http://schema.org/HowTo, http://schema.org/LocalBusiness, http://schema.org/MediaObject, http://schema.org/Movie, http://schema.org/MusicPlaylist, http://schema.org/MusicRecording, http://schema.org/Organization, http://schema.org/Product, http://schema.org/Recipe, http://schema.org/SoftwareApplication]`

Should I be switching over to the /Product primary schema structure?

**Comment by philbarker** [comment]
@natecovington aside from what I think is just the result of having PHP in the JSON, your schema.org markup validates at https://validator.schema.org . It also looks sensible to me.

What various products, such as Google Search, accept will be determined by their priorities in how they use schema.org markup. Your issue lies with that choice not the design of schema.org, so you would be better raising it in one of their forums. There is nothing we can do here that will help.
