### ISSUE TITLE
inverse of department on Organization

### ISSUE THREAD

**Issue by cancan101** [schemaorg/schemaorg#3215]
There does not seem to be an inverse property `department` on `Organization`.
This is in contrast to the a similar property: `subOrganization` which has `parentOrganization` and also: `member` which has `memberOf`.

**Comment by danbri** [comment]
Thanks, you are correct. We do not define inverse properties by default, both because they add no new expressivity, but also because it is often just simply hard to find a good and intuitive name for an inverse.

We do sometimes add them, generally because there is some concrete and significant consuming application, and where the markup burden on publishers is significantly simplified. And ideally where we can think of a good name.

**Comment by cancan101** [comment]
This question might be outside the scope of this forum, but my plan to use an inverse relationship is that I have two domains, one for the full organization `www.company.com` and one for the ecommerce site: `shopcompany.com` (not a subdomain). I was planning to declare the Organization -> ecom site relationship in the metadata on the `www.company.com` site and it seemed that `department` was more right than `subOrganization`. I was then going to declare the inverse relationship in the metadata on the shop site but would need an inverse of department to do so. Alternatively I could just use `subOrganization` / `parentOrganization`, though not sure of that is less "right" in this situation.

**Comment by RichardWallis** [comment]
Use of `subOrganization` / `parentOrganization` would _indicate to consumers_ the basic relationship you require.  If some consumers indicate that they would make use of more semantic detail in this area, the question could be revisited.

However, I will close this for now.
