### ISSUE TITLE
/additionalType should explicitly allow Text

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#3304]
Reasoning:
 - people do it anyway
 - we create busywork for folk creating URLs or 404s by demanding URLs here
 - computers are getting better at extrapolating sensibly what such things mean

**Comment by jvandriel** [comment]
I can live with that and actually have used it as such in the past to define very specific `Product` sub types (e.g. hair dryer, multi-styler, etc). Although it was mostly used for internal analytics and not aimed at external parties.

**Comment by rrlevering** [comment]
I'm so torn on this topic, personally.  On one hand, I would be strongly opposed to it if I really cared about additionalType.  This waters down the usefulness of the field as any sort of actual standardized type usage.  It turns it into "typing hint".

However, since it was a hack to put it for a "mistake" made in the Microdata spec I don't really care.  Google currently doesn't consume it as anything more than text for special cases ever (we don't map it automatically in some ways like we do for rdf:type-ish syntax).

**Comment by rrlevering** [comment]
One thing I will agree with is that people do it anyway.

From my data, I can see that it's more often used incorrectly than correctly.  I can see a lot of cases of "Product" or something like a schema.org co-type (even in JSON-LD) without an absolute URI, assuming that it would work like @type where a vocab prefix is assumed.

**Comment by jvandriel** [comment]
To add another use case, if Google Merchant Center ever decides to support `additionalType` as an alternative for their [[product_type]](https://support.google.com/merchants/answer/6324406) attribute, allowing `Text` will mean the values GMC has to deal with can be used 1:1 in any markup.

cc: @rrlevering, @alex-jansen

**Comment by alex-jansen** [comment]
Looks like this was already included in Release 16.0 on 2023-05-16, so closing the issue.

**Comment by saumier** [comment]
Related discussion to `additionalType` https://github.com/schemaorg/schemaorg/issues/2986
