### ISSUE TITLE
TVSeries and TVEpisode have actors and directors, but TVSeason does not

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#336]
The properties "actor" and "director" exist on TVSeries and TVEpisode. We should add TVSeason to the domain to round out the possibilities.

**Comment by vholland** [comment]
See pull request#337: https://github.com/schemaorg/schemaorg/pull/337/files

**Comment by danbri** [comment]
I suggest we add those to http://schema.org/Season instead of to TVSeason. This will then apply to 
RadioSeason and TVSeason, as well as to any others that emerge.

Series is a bit different as it covers more variety, but we could add RadioSeries too while we're at it.

Looking at adding actor/director to each of the Series subtypes individually, my suggestions are: 

* BookSeries [no],
* MovieSeries [yes],
* Periodical [no],
* RadioSeries [yes], 
* TVSeries [already],
* VideoGameSeries [yes]

**Comment by vholland** [comment]
+1. I'll add it to schema.org/Season.

**Comment by vholland** [comment]
It turns out I had already figured this out and put the property on schema.org/Season.

**Comment by vholland** [comment]
Merged into sdo-gozer.
