### ISSUE TITLE
Microdata, multiple item types, and properties not defined by *all* types

### ISSUE THREAD

**Issue by unor** [schemaorg/schemaorg#340]
The Microdata version of [`VideoGame` example 4](http://schema.org/VideoGame#games-4) defines two item types on the same element (which is [allowed](http://stackoverflow.com/a/21969655/1591669) if they are from the same vocabulary):

    <body itemscope itemtype="http://schema.org/VideoGame http://schema.org/MobileApplication">

In this item, the [`gamePlatform`](http://schema.org/gamePlatform) property is used, which is only defined for `VideoGame`, but not for `MobileApplication`.

However, Microdata [defines](http://www.w3.org/TR/2013/NOTE-microdata-20131029/#names:-the-itemprop-attribute) that an `itemprop` token has to be 

> […] a **defined property name** allowed in this situation according to the specification that defines the relevant types for the item […]

And it says in the same section:

> When an element with an `itemprop` attribute adds a property to multiple items, the requirement above regarding the tokens applies for each item individually.

So unless I’m misunderstanding this (please correct me), this example (and probably many more) are not valid Microdata.

This would mean: Microdata examples may only ever contain several item types in the same `itemtype` attribute if *all* properties used in this item are defined for *each* item type.

If only the additional *types* are relevant (and no properties from the additional types are needed), [`additionalType`](http://schema.org/additionalType) could be used:

    <body itemscope itemtype="http://schema.org/VideoGame">
      <link itemprop="additionalType" href="http://schema.org/MobileApplication">

**Comment by danbri** [comment]
Microdata might be a little too uptight here. But it also doesn't specify any particular schema system, so it is also rather relaxed. 

Otherwise we can just say something legalistic in the small-print like, 
"In addition to the main properties that are expected for some type, any other schema.org property is also applicable when the underlying real world item is also a member of another suitable type for which that property is sensible. It is useful but not essential for both types to be used in such descriptions."

**Comment by danbri** [comment]
I'm going to mark this as a question for now, and close it. We might come back to it if/when datamodel documentation is improved, but I don't see an immediate action.
