### ISSUE TITLE
Course Pages 

### ISSUE THREAD

**Issue by clouddevloper** [schemaorg/schemaorg#3413]
I have added the course schema and validated the same in search console as well. It's still not showing up in search results.

![image](https://github.com/schemaorg/schemaorg/assets/87369308/66ff839f-33ec-4536-bf06-4964573b14be)

What should I do next.

**Comment by clouddevloper** [comment]
Can you someone help me out here?

**Comment by philbarker** [comment]
@clouddevloper Your issue is with Google's implementation of schema.org, this repository is about the development of schema.org not how Google uses it. While some people here know about Google, I think you would be better off trying to get help through the Google support forums, https://support.google.com/webmasters/community

**Comment by MatthiasWiesmann** [comment]
Schema.org only defines the schema, not how various systems, including web-indexers will interpret them.
I think you question pertains to the second category.
