### ISSUE TITLE
Linked Open Data: extend rangeIncludes of 'genre' + 'keywords' properties of CreativeWork to include URL

### ISSUE THREAD

**Issue by lazaruscorporation** [schemaorg/schemaorg#346]
Hi

I'd like to suggest extending the rangeIncludes of the 'genre' ~~and 'keywords'~~ property of schema.org/CreativeWork (currently just "Text") to also include URL.

This will allow advanced users to implement more Linked Open Data (LOD) in schema.org, by replacing a free-typed text string in 'genre' ~~or 'keywords'~~ with a URI from a LOD vocabulary.

For example, the "genre" property for a Late Renaissance painting (marked up using VisualArtwork, a sub-Type of CreativeWork) could be set to the Getty AAT LOD URI  "http://vocab.getty.edu/aat/300021143" instead of the text value "Late Renaissance". 

~~Similar LOD URIs (e.g. from Wikidata etc.) could be used in the "keywords" property.~~

There may be other properties that can be included in this enhancement to incorporate LOD, but these two seemed the most obvious.

Thanks,

Paul

**Comment by lazaruscorporation** [comment]
Edit: following the resolution of #347 (thanks to @danbri and @Dataliberate) this request to extend the rangeIncludes to URL (in addition to text) should only apply to the "genre" property, not the "keywords" property

**Comment by realworldobject** [comment]
I agree this would be very helpful for improving library linked data because we could leverage multilingual labels and descriptions such as with http://www.wikidata.org/entity/Q24925.

**Comment by niklasl** [comment]
+1

This [has come up before](http://lists.w3.org/Archives/Public/public-vocabs/2013Nov/0126.html), during the SKOS discussion now tracked in issue #251.

(There is a larger question about whether rangeIncludes URL implies Thing, and perhaps whether genre should be narrowed to e.g. Intangible. But since URL is already used like this elsewhere, this specific case might not be the place to resolve that.)

**Comment by danbri** [comment]
Looking at this again, I see that we implemented it for /genre (with an accidental rollback fixed in #1203 and about to be republished in v3.1, see #1212). But we didn't get there for /keywords. I see also @lazaruscorporation retracted the proposal to do this for /keywords, and that anyway we're discussing that kind of functionality elsewhere including #251. I'm therefore going to close this issue. Thanks everyone!
