### ISSUE TITLE
schema_org_rdfa validator and some release profile report 

### ISSUE THREAD

**Issue by ppKrauss** [schemaorg/schemaorg#361]
For http://schema.org/docs/schema_org_rdfa.html and each [release](http://schema.org/docs/releases.html), is interesting some kind of **validation**  for `schema_org_rdfa`.

See [proposal here](https://github.com/ppKrauss/schemaorg/tree/sdo-gozer/proposals/testing/releases#user-content-release-of-2015-02-07-v194-gozer) with the *gozer* profile as example.

----
Good validators like https://validator.nu/ need good HTML5, see #360. These validators also not check minor validation problems, that are important here, to `schema_org_rdfa` interoperate with any *tool*.

**Comment by danbri** [comment]
I'm afraid this is probably not the best use of your time and energy to do this at the RDFa/HTML syntax level. Our use of RDFa here is very much an implementation detail and likely to change/evolve (including option to use JSON-LD, and adding a real parser toolkit instead of our hack parsers).

You might be interested to look at the Python unit tests we have in tests/ - these operate over the graph we get back from RDFa-parsing the files. It is absolutely useful to look into this general kind of QA but better to do it against the parsed graph. 

See also http://dydra.com/danbri/schema-org/ and http://dydra.com/danbri/sdo-stantz-wip which can be used for developing SPARQL graph queries against the datasets for unit tests.

https://github.com/schemaorg/schemaorg/blob/sdo-gozer/run_tests.py
https://github.com/schemaorg/schemaorg/blob/sdo-gozer/tests/test_graphs.py

**Comment by ppKrauss** [comment]
Hum... ok. Thanks for your reply (!). Well, I need more expertise in Python to collaborate. About my "time and energy": let's put all into the #280 :-) I think we need to do a lot of work there, even though we are able to automate something.

**Comment by danbri** [comment]
Thanks again. Closing this issue for now.
