### ISSUE TITLE
HTML or Compiled Code

### ISSUE THREAD

**Issue by streamich** [schemaorg/schemaorg#363]
There seems to be no Text property where one could provide HTML (or say "compiled") data.

For example, a Thing could be a Markdown object, which compiles to HTML. How would one add the HTML information to the object?

**Comment by danbri** [comment]
Thanks for the suggestion. There are some subtleties here due to the different ways in which Microdata, RDFa and JSON-LD handle literal HTML text. But using Markdown has cropped up a few times - potentially even for our own site system to handle documentation text. I'll file this under 'maybe someday' for now, as it probably requires a lot of careful preliminary work on structured literal text.
