### ISSUE TITLE
Vocabulary for comics

### ISSUE THREAD

**Issue by davide-romanini** [schemaorg/schemaorg#378]
Here:
  http://www.w3.org/community/schemabibex/wiki/Periodicals_and_Comics_synthesis

there is some work done to add comics support to schema.org. I'm using
that on a personal project (http://github.com/davide-romanini/scrooge).
What about integration of that work on main stream? Probably the most useful feature are the additional specialized types.

**Comment by rvguha** [comment]
I think this would be a great extension. comics.schema.org

guha

**Comment by Dataliberate** [comment]
I believe there is sufficient synergy with the concepts discussed within the SchemaBibEx group to consider it part of a broader bib.schema.org<http://bib.schema.org> extension.

~Richard

On 11 Mar 2015, at 18:57, rvguha <notifications@github.com<mailto:notifications@github.com>> wrote:

I think this would be a great extension. comics.schema.org<http://comics.schema.org>

guha

**Comment by danbri** [comment]
As the original poster pointed out, http://www.w3.org/community/schemabibex/wiki/Periodicals_and_Comics_synthesis does integrate the topic of Comics with our recent general improvements around periodicals. The only other major Comics theme that gets occasional discussion is the question of modeling fictitious and partially fictitious universes. Since that is a modeling rathole, I suggest we follow Richard's / @Dataliberate  suggestion and fold a treatment of 'Comics as creative works' into a broader bib extension.

**Comment by danbri** [comment]
The comics vocab is being handled within the bib: extension. We might come back to this topic for fictional character representations etc., but I'll close this out for now.

see also https://github.com/schemaorg/schemaorg/issues/455
