### ISSUE TITLE
no obvious base type for non-product physical things

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#385]
We should consider having a recommendation for how to describe physical things which might not necessarily be best considered members of Product.

**Comment by danbri** [comment]
e.g. for use in describing photos, we can say x is a Photograph, is is about y, and y is a ... Product? Thing? What about a tree, or an aircraft, or (anything....).

**Comment by jvandriel** [comment]
Since I think in markup and not in abstracts, I wonder if I interpret your example correctly, do you mean something like this:

```
<figure itemscope itemtype="http://schema.org/ImageObject">
	<img itemprop="image" src="http://example.com/some-image.jpg" alt="Some image alt">
	<figcaption itemprop="caption">
		<span itemprop="about" itemscope itemtype="http://schema.org/Thing">
			<link itemprop="sameAs" href="http://www.wikidata.org/entity/Q10884">
			<link itemprop="sameAs" href="http://dbpedia.org/resource/Tree">
			A spectacular photo of a <span itemprop="name">Tree</span>
		</span>
	</figcaption>
</figure>
``` 

(or should the 'sameAs' properties be 'additionalType' in case of these external enumerations?)

**Comment by chaals** [comment]
+ reply@- notifications@  17.03.2015, 23:09, "Dan Brickley" <notifications@github.com>:e.g. for use in describing photos, we can say x is a Photograph, is is about y, and y is a ... Product? Thing? What about a tree, or an aircraft, or (anything....).Thing seems reasonable. Just as Person can be a fictional undead person, Thing can be an abstract concept. But I don't think we preclude it being an actual thing… cheers --Charles McCathie Nevile - web standards - CTO Office, Yandexchaals@yandex-team.ru - - - Find more at http://yandex.com

**Comment by danbri** [comment]
Yes, that's the general idea. If "Tree" is what RDF calls a type or class, you could use an additionalType property in Microdata. Within RDFa or JSON-LD you'd use @typeof or @type respectively.

Looking at http://www.wikidata.org/entity/Q10884 I see a subClassOf relation which indicates that the Wikidata (currently :) consider Q10884 to be a type.

**Comment by chaals** [comment]
I'm not sure that there is a reason to give physical things a class. (What about fictional physical things?)

**Comment by Dataliberate** [comment]
One of the reasons for stretching Product to describe things that are not really products is the set of properties that come with it - height, depth, colour, width, weight, isSimilarTo.

Just using Thing, misses those benefits

I can see the attraction of some sort of PhysicalThing base class if it contained such properties.

Thing>PhysicalThing: A Thing with Physical attributes, height, width, weight, etc. (Real or fictional)  For example a rock, an asteroid, an aeroplane, a molecule, or a fossil.
Properties: height, depth, colour, width, weight, isSimilarTo

Theoretically, Product could be a sub type of PhysicalThing

Also under such a proposal, it could be argued for a LivingThing subtype.

Thing>PhysicalThing>LivingThing: A Thing that is or was alive (Real or fictional)  For example a giraffe, a tree, a microbe, or a fish.
Properties:

~Richard

On 18 Mar 2015, at 12:16, chaals <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure that there is a reason to give physical things a class. (What about fictional physical things?)

**Comment by realworldobject** [comment]
schema:SomeProducts is also handy for recording the fact that someone has 3 copies of something in cases where the identifiers for each of them as schema:IndividualProduct haven’t been tracked down yet.

Jeff

**Comment by realworldobject** [comment]
I agree that physicality shouldn't be a requirement for expressing individuality.

**Comment by danbri** [comment]
There are cultural heritage use cases from museums who can't describe their collections using schema.org currently. Related discussion: http://journal.code4lib.org/articles/6400

**Comment by gotsemantics** [comment]
I am in the process of launching a Web site (http://www.somanyaircraft.com) that will publish photographs (and physical books) about aircraft. Specific aircraft types, to be exact (e.g., Douglas DC-3). When describing a photograph (residing on the Web site) or a book (that can be physically bought), we'd like to be able classify the content specifically (e.g., [this book](http://www.somanyaircraft.com/pubs/sma-001/) is about the DC-3 but I am not sure how to say that -- so far that page only has very minimal structured data).

We have a carefully curated in-house vocabulary of approx. 5000 aircraft types that we are thinking of using, but the question is "how?"... My current thinking is that if there was a base type we could extend that by ourselves. "Aircraft" could be a subclass of "Vehicle" (although that is a product and I am not sure what ramifications that has, e.g., if I talk about Boeing 787 *as a product* will the Boeing lawyers have a problem with that?). Rather than extending "Aircraft", we could make instances of "Aircraft" and use an external code (referring to our vocabulary) to indicate which aircraft type it is.

Any thoughts?

**Comment by mfhepp** [comment]
re: "Theoretically, Product could be a sub type of PhysicalThing"

No, because schema:Product includes intangible products, services (which are "happenings" in the conceptual sense), and product models, which are prototypes/ideals of a product or service and thus intangible.

Practically, you could use Product as the main type for all your use cases, afaiks. Products can be physical objects, which is why there are properties for weight etc., but they don't have to be. I think i have explained elsewhere in detail why we need a Product type with such an ambiguous semantics - mainly because most shops cannot reliable provide this distinction from their back-end databases.

**Comment by mfhepp** [comment]
Dear Ora:

I would use 

foo:Picture1 a schema:Photograph;
	schema:about foo:Plane1.

foo:Plane1 a schema:Vehicle, <http://www.productontology.org/id/Airplane> ;
	schema:model <your_namespace:Model1>.

Plane1 would then be the individual plane depicted (e.g. one of the planes listed on http://www.dc3history.org/airworthysurvivors.html), and Model1 the make and model (Douglas DC-3). Formally, it would be a vehicle only, but with the hint to <http://www.productontology.org/id/Airplane> or any other, externally defined type, you can signal that it is actually an airplane.

So if we consider the airplane types individuals, which is perfectly in line with schema:ProductModel, you should be all set and -- not that that matters -- could even stay within OWL DL ;-

Of course, we could also model the plane as an instance of the plane model type, i.e. <your_namespace:Model1> would be a class, not an individual.

Martin

**Comment by gotsemantics** [comment]
Martin, thanks.

FYI, the problem of what is a class and what is an instance has always bothered me. ;-) I'd prefer plane model types to be classes also...


-----Original Message-----

**Comment by mfhepp** [comment]
Ora:
> 
> FYI, the problem of what is a class and what is an instance has always bothered me. ;-)
I know, this is why I hesitated to reply ;-)

> I'd prefer plane model types to be classes also...

The reason why GoodRelations treats product models as instances is mainly that we want to describe them using the same properties as instances, because otherwise we need two properties for each characteristic - one for saying that a certain plane has certain weight, and one for saying that an instance of a certain make and model class will have a certain weight.

Also, if you think of it in an OWL way, modeling models as classes is problematic: Since classes are always approximations, no matter how many axioms you add for describing a model, there could still be an instance that meets all constraints of the class definition yet still is not a certain make and model. An OWL reasoner would however classify that instance under that class.

Of course, that is just history from the Semantic Web Middle Ages, where challenging the authority of OWL DL was a dangerous offense ;-)

Martin


> 
> 
> -----Original Message-----
> From: "Martin Hepp" <notifications@github.com>
> Sent: ‎3/‎18/‎2015 18:59
> To: "schemaorg/schemaorg" <schemaorg@noreply.github.com>
> Cc: "Ora Lassila" <ora@lassila.org>
> Subject: Re: [schemaorg] no obvious base type for non-product physical things(#385)
> 
> Dear Ora:
> 
> I would use 
> 
> foo:Picture1 a schema:Photograph;
> schema:about foo:Plane1.
> 
> foo:Plane1 a schema:Vehicle, <http://www.productontology.org/id/Airplane> ;
> schema:model <your_namespace:Model1>.
> 
> Plane1 would then be the individual plane depicted (e.g. one of the planes listed on http://www.dc3history.org/airworthysurvivors.html), and Model1 the make and model (Douglas DC-3). Formally, it would be a vehicle only, but with the hint to <http://www.productontology.org/id/Airplane> or any other, externally defined type, you can signal that it is actually an airplane.
> 
> So if we consider the airplane types individuals, which is perfectly in line with schema:ProductModel, you should be all set and -- not that that matters -- could even stay within OWL DL ;-
> 
> Of course, we could also model the plane as an instance of the plane model type, i.e. <your_namespace:Model1> would be a class, not an individual.
> 
> Martin
> 
>

**Comment by gotsemantics** [comment]
Also, what about SKOS...?

**Comment by mfhepp** [comment]
Re SKOS: Do you mean to use SKOS relations to link photos and books to topics, or do you mean to build a thesaurus of airplane types in SKOS and use that to indicate the content of the works?

In general, I think modeling the airplane types as ProductModel, the actual airplanes as Product or better schema:IndividualProduct, and linking like

Photo -> about -> IndividualProduct -> model ProductModel

works best.

**Comment by gotsemantics** [comment]
I had been thinking of a thesaurus of aircraft types as a SKOS hierarchy. That's what we have now, in fact, but turning that into something else is not hard obviously.
