### ISSUE TITLE
Hash fragments and navigation for examples

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#396]
I have seen that the syntax for examples now seems to include a mechanism for indicating a name or ID for an example, as in #itemlist-1 

TYPES: #itemlist-1 BreadcrumbList, ItemList, ListItem, itemListElement, item, WebPage

We should do the following:
1. Document that feature somewhere.
2. Improve the navigation among examples in the HTML rendering, e.g. a list or menu to first select the type of example and then select the syntax.
3. Define and add persistent fragment URIs to all examples so that they can be referred to in discussions anywhere on the Web.
4. Maybe extend the mechanism to also define a name and description for each example because we currently have to put it in the comments, which creates redundancy (because it has to maintained in all syntaxes)

**Comment by danbri** [comment]
Thanks for noticing! I'm leaning towards having examples in separate files, rather than mutate this ad-hoc format into some grotesque parody of SGML :) It would also help with running tools over all examples, and perhaps with translations too. Giving a simple ID to each example seemed a practical first step.
