### ISSUE TITLE
LocalBusiness should have a property for service region

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#401]
As someone pointed out on public-vocabs@w3.org, a HomeAndConstructionBusiness may have a headquarters, but that is not where they do business. It would be useful to be able to specify the service region for these types of businesses (plumbers, contractors, etc.)

**Comment by jvandriel** [comment]
"It would be useful to be able to specify the service region for these types of businesses"

IMO we already can by using 'makesOffer' > Offer:
```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "HomeAndConstructionBusiness",
  "makesOffer": {
    "@type": "Offer",
    "businessFunction": {
      "@type": "BusinessFunction", 
      "url": "http://purl.org/goodrelations/v1#ConstructionInstallation"
    },
    "availableAtOrFrom": {
      "@type": "Place", 
      "address": {
        "@type": "PostalAddress",
        "addressLocality": "Philadelphia",
        "addressRegion": "PA"
      }
    }    
  }
}
</script>
```

**Comment by mfhepp** [comment]
This is actually already covered by schema.org / GoodRelations, since you have

a) the legal entity (Organization or Person, gr:BusinessEntity in GoodRelations); this has a legal address (e.g. headquarter mail adress)

b) its point or points or service provisioning (Place); these are places from which a service is available, e.g. a store, a gas station, a fast-food restaurant, a bus stop, etc.

c) an offer, which is the promise to provide a service or grant a set of rights on something

c) can be complemented by information about the region for which this offer is valid.

I think the confusion stems from the fact that schema.org did not adopt the strict distinction between the legal entity and its places from GoodRelations and instead has types that combine the two.

Of course there are many entities where the separation is difficult, but I strongly recommend to not break the main conceptual model by introducing workarounds that are not really needed. I see this as a documentation problem.

Martin

**Comment by mfhepp** [comment]
Addendum: The reason why GoodRelations ties the information to the offer is that this is really where it belongs in my opinion - there may be different offers with differing regional constraints.

**Comment by mfhepp** [comment]
@jvandriel is exactly right. Note that you can also point from the company to it's POS via http://schema.org/hasPOS if you want to create a link that is independent from an offer.

**Comment by ppKrauss** [comment]
Not only `HomeAndConstructionBusiness`, but any other kind of [Organization](http://schema.org/Organization) need to express "where they do business" (as @vholland pointed).

There are some *properties* "resembling" this semantic:
  * [circle](http://schema.org/circle):  objective geographic determination (x,y,r) of this "area where they do business".
  *  **[areaServed](http://schema.org/areaServed)** and   [area](http://schema.org/area), but  they are about "broadcast service": why not suggest here a "semantic expansion" of these properties? Each business have its standards about "region of business". In Wikipedia is a tradition to express in [Template:Infobox_company](https://en.wikipedia.org/wiki/Template:Infobox_company) the `area_served`  or  `areas_served`. Example: the *area served* by [Faber-Castell](https://en.wikipedia.org/wiki/Faber-Castell) is "Worldwide". In company synopsis  is also commom to  use free descriptions, as "the company operated in 22 states", so a "fuzzy (circa) area delimitation" is also valid (no only precise geographical lists or delimitations).

**Comment by jvandriel** [comment]
_"any other kind of Organization need to express "where they do business""_

Any other Organization can. Either by using ```hasPos``` (as pointed out by @mfhepp) or ```offer```.

And as for ```circle```, any ```LocalBusiness``` can use ```geo > GeoShape > circle > text.

**Comment by jvandriel** [comment]
_"Addendum: The reason why GoodRelations ties the information to the offer is that this is really where it belongs in my opinion"_

+1

**Comment by ppKrauss** [comment]
Yes, good to remember `geo > GeoShape > circle`... SchemaOrg offer all "tools" to express geographical delimitations. 

-----

Well, can we consolidate the discussion to check/understand  consensus and directions?

 1. *"LocalBusiness should have a property for service region"* is the initial proposal, <br/>can we expand it to *"`LocalBusiness`, `Organization`, `Person`, country, etc. should have a property for service region"*?  (as @mfhepp explain any "legal entity" that do some business)

 2. Can we use the term **"area served"** instead "service region" or "places from which a service is available"?  Only to avoid noise in the discussion. "Area served" is a term adopted by SchemaOrg and Wikipedia.

 3. Here we see some (but not complete) solutions to express "area(s) served by the local business":

   3.1. *Area* or an *list of areas*. (below suppose "each area").

   3.2. *Geographically delimited area*: 
     3.2.1. a point: the *area served* is the point's "natural neighbors" (each business have a fuzzy ideia of what is this neighbors)... So an [PostalAddress](http://schema.org/PostalAddress) can be a precise point by its [geocoding](https://en.wikipedia.org/wiki/Geocoding).
     3.2.2. a defined area: [circle](http://schema.org/circle) (textual point and radius) and any other [GeoShape](http://schema.org/GeoShape) (with textual definition like UTM-zone, or link to a shape/map illustration). Ex. in continental scale,  the [corn belt](https://pt.wikipedia.org/wiki/Ficheiro:Map_of_USA_highlighting_Corn_Belt.png) is a USA's  LocalBusiness area... In other scale, a [city block](https://en.wikipedia.org/wiki/City_block) can be the  *area served*.
       3.2.3. a "circa/fuzzy area"... textual or illustred.

    3.3. *Non-geographical area*. Ex. an e-business "at Internt" or  "at Facebook"; an english conversation course "at Skype"; etc.   

 4. "This is actually already covered by schema.org"? 

-----

Suggestion for all (@jvandriel, @vholland, @mfhepp, or any other): add a comment to say if agree/not the numbered items... Or to point the item problems.

**Comment by mfhepp** [comment]
To be frank, I do not see any fundamental need for action in here. Schema.org / GoodRelations already provides clear mechanisms for expressing:

a) physical locations from which you can obtain a product or service (Place via availableAtOrFrom)
b) delivery mechanisms via avaliableDeliveryOption
c) constraining the geographical location of the customer via eligibleRegions

These are all attached to Offer, because it is not that a company or business has any such constraints, but that they are details of the offers they make. It may help to familiarize yourself with http://wiki.goodrelations-vocabulary.org/Documentation/Conceptual_model

It does, IMO, not help to blur these three conceptual distinctions a - c, and it does not help to create shortcuts to add these constraints to the business or place directly, because they are mostly bound to a context and not generally valid.

As for your examples: All that works with the current elements. Skype and Facebook are for me DeliveryOptions.

General comment: I may change my mind if you show me concrete use-cases, i.e. multiple Web sites that expose the kind of detail you mention and how consumers of schema.org markup could use that information. It does not help, IMO, to just extend the model of schema.org. Even as of today, the granular methods for constraining offers by region, time or target audience are way underutilized. So instead of extending this, we should promote the use of the existing elements.

**Comment by mfhepp** [comment]
@vholland I would either close this issue or define the action to close it as to develop examples in all syntaxes and add a sdo-local-business-examples.txt file to the codebase.

**Comment by ppKrauss** [comment]
@vholland  and @mfhepp , why not *"enlarge the semantics of [areaServed](http://schema.org/areaServed)"*?  In your opinion it is a valid suggestion?

**Comment by mfhepp** [comment]
Expanding the scope of areaServed as you propose will break the GoodRelations model in schema.org and introduce a second way of modeling the same thing in a worse manner.

Don't do it. Use Offer + eligibleRegion / availableAtOrFrom / avaliableDeliveryOption

You don't have to create thousands of Offers for each business, one that spans broadly all products and services will do the trick. No need to spoil the existing model.

**Comment by ppKrauss** [comment]
Hum... only a "PS" notice,

  * "(...) will break the GoodRelations model in schema.org (...)"... This is new for me, because [Schema.org/docs](http://schema.org/docs/documents.html) not defined the [curation policy](http://www.dlib.org/dlib/september07/treloar/09treloar.html)... On my opinion is a open problem in the project (!), and indefinitions stops motivation for collaboration.

  * @mfhepp,  you have good  and reliable (your experience with GoodRalations and e-business users/community) rationale for your hypothesis, but for SchemaOrg universe it is only a hypothesis. More people must test and discuss the topic, in a broader (SchemaOrg) context.

**Comment by mfhepp** [comment]
Please proceed as you like. I consider this issue a non-issue. We have elements in schema.org that cover the use cases you mention. In practice, schema.org is the new main namespace for GoodRelations; the original one is relevant only for consumption in RDF environments and both will be aligned even further in the future. I fail to understand what you want to say with th link to the curation policy document.

**Comment by ppKrauss** [comment]
@mfhepp sorry to polluted this discussion with my PS/policy, I moved this debate to #403. 

About yor (new for me) information, that "schema.org is the new main namespace for GoodRelations", thanks (!). GoodRelations have an active and qualified community  and mergin with SchemaOrg is a big step forward.

About my opinion: I think we need to look at SchemaOrg as a whole. Today this whole is not so consistent and have "low resuse": I think that this issue is an improvement opportunity.

**Comment by vholland** [comment]
My intention with this issue was to record a request that came from public-vocabs@w3.org as those threads can sometimes be forgotten in the shuffle. I have no allegiance to the term "service region". Indeed, if we added something, using the existing "areaServed" makes perfect sense.

@mfhepp is correct we should consider the existing model. One should not needlessly add schema, but at the same time we should not be limited to keeping things exactly as they are, for that does not allow for growth.

I would rather not close the issue, as there is good discussion going on. Instead, I would rather people continue to discuss use cases so we can evaluate the situation and determine the best course of action, if any.

**Comment by mfhepp** [comment]
I am fine with keeping the issue open. However, I strongly suggest that if so, we should:

1. Start with use cases, requirements, and examples of respective sites / page templates.
2. Check whether the existing elements cover the requirements by producing examples.
3. Evaluate whether the resulting markup is simple enough.
4. If necessary, carefully craft simplifications or shortcuts.

The only real contribution of GoodRelations was that:

1. Products don't have prices, but agents offer rights on some objects and ask for a compensation. This simplifies a lot of things - discounts, seasonal rebates, pricing by customer type, ...

2. Companies don't have opening ours, but their places of service have. And there is a difference between the legal entities address and a point of sales. You do not want to guide people to the corporate headquarters office in a map if they search for a store.

3. Products and product models are not the same things. If I tear one page out of my Python for Dummies copy, the book still has 432 pages for anybody else in the work.

With these five distinctions:

- Business Entitity (Organization or Person)
- Place of Service Provisioning (Place)
- Offer
- Product (IndividualProduct or SomeProducts)
- Product Model

we have so managed to cover all requests from all industries, stages of the value chain, and regional contexts. 

Previous schemas mixed many of these aspects, ending up with different conceptual models for different products, industries, or stages of the value chain, which was not good.

Now, I have nothing against evolving schema.org to cater for the needs of publishers or consumers of data, but quick-and-dirty stove-piping would sooner or later corrupt schema.org as a whole.

**Comment by thadguidry** [comment]
Back to the remaining question within this issue...

@ppKrauss 

http://schema.org/areaServed - is wide open, not locked into a "broadcast service" as you originally thought.  Check it out, use it, and then let us know...but I think the definition of it is fine and not restrictive other than for a ContactPoint ... which any business will have at least one of.

http://schema.org/area - is indeed a property used currently only on the BroadcastService Type

**Comment by ppKrauss** [comment]
@thadguidry  Yes, thanks (!), the *areaServed* property definition is not "so locked" than *area* property... But, on my opinion, both are "insufficiently broader".

Well, need "opinions" (!),  *areaServed*  and many other SchemaOrg definitions are so "fuzzy" and vague... 
We are back to *issue #280*, the vague definitions creates a lot (!) of semantic ambiguity and lost of energy and discussion time... I not found the WikidataID of this "area served" business concept... A candidate (to use in a "definition by semantic intersection") is  [Q869830](https://www.wikidata.org/wiki/Q869830).

 -----

Rebuilding/drafting (please help me with good English!) a new text for the purpose of this issue, that, in this moment of this discussion, is *"enlarge the semantics of [areaServed](http://schema.org/areaServed)"*:

* [areaServed](http://schema.org/areaServed): now have the samantic of "location of [ContactPoint](http://schema.org/ContactPoint)". Is it? The "location" is a "geographically delimited area"? need to be spatially connected region or can be a list of regions?  Can be non-geographical? The SchemaOrg community not need for other uses that are not ContactPoint? (see LocalBusiness applications)

* [area](http://schema.org/area) as [strict BroadcastService concept](https://en.wikipedia.org/wiki/Telephone_numbering_plan#Area_code) (the link shows the exact semantic). We need this property? Why not use *areaServed*?

**Comment by thadguidry** [comment]
@ppKrauss the areaServed uses an Administrative Area. http://schema.org/AdministrativeArea

and YES, an AdministrativeArea has properties like geo

You are not limited to just 1 areaServed ... you could have many, and with JSON-LD it is pretty easy to express an array or list of values.

@ppKrauss Let's instead do this.  Instead of using our GitHub issues to inquire and learn more, can you instead just start a new mailing list thread called "Learning Schema.org more..."  and in that thread, many of us would be very happy to help teach you and answer all the general questions that you have.  That is what our mailing list is very useful for...answering questions and having an elaborate discussion, without mxing-in with solving specific issues that need to be addressed.  In the mailing list, once we see that an issue might need to be addressed, then we can open a new issue here in Github and track it, get feedback, etc.

@ppKrauss We look forward to helping you more on our mailing list !

**Comment by ppKrauss** [comment]
@thadguidry ... sorry my incomplete explanations,

  * **question-marks**: please, I edit (!), check the new parenthesis "the question-marks are **to check consensus**". Some discussions are not terminated, or we think "terminated" but comments reopen... 

  * [AdministrativeArea](http://schema.org/AdministrativeArea): in a continental scale, "administrative are" is a country, and into the country scale there are "standard areas" as cities, and another not exoctic kinds, but, im my opinion, all are [GeoShape](http://schema.org/GeoShape). So if you say "uses" as "AdministrativeArea *is used as value* for areaServed", is ok, but not understand how it changes the issue.  The exact meaning/semantic of AdministrativeArea is  [Q56061](https://www.wikidata.org/wiki/Q56061)... 

  * Beofore "Learning Schema.org more" iniciatives, the homework here is to enhance [schema_org_rdfa.html](http://schema.org/docs/schema_org_rdfa.html) with  WikidataIDs the (see [issue #280  spreadsheet](https://github.com/schemaorg/schemaorg/issues/280#issuecomment-75825221)) ... anybody can help [here at GoogleDocs SchemaOrg-Wikidata spreadsheet](https://docs.google.com/spreadsheets/d/1KeTSrVjSHRfVRwSgg6-LN0pu6nVre7cspUrkf_gfMm8/). 

  * "learning Schema.org more...": I explain the "question-marks" above, but you introduce an important topic, and I agree that is necessary.  Instead a new mailing list, my suggestion is to enhance participation at [stackoverflow with tag `schema.org`](http://stackoverflow.com/questions/tagged/schema.org).

**Comment by danbri** [comment]
@vholland @mfhepp 

I'm catching up from travel, but from a hasty read of this this, I'd suggest

a) adding yet another way to say something we can already express is costly; however-
b) nevertheless, having some high-level property of a LocalBusiness (as 'place of service') which summarizes the general areaServed by its typical offers seems of value

It is always possible to be more precise by breaking things out into a set of offers. But there is also value in aggregation too. So we can have http://schema.org/CafeOrCoffeeShop or we can just describe a place and that it offers, tea, coffee, biscuits, etc etc. There is value sometimes in both levels of detail. Perhaps the same with areas served?

**Comment by mfhepp** [comment]
I am not entirely against such a property, but if we can fix this by a simple markup example with existing properties, I think that is better. And we are just talking of one additional schema:Offer entity to achieve that.

Directing such information towards Offers will lead to a generally better information model. It's not the place that determines the area served or the food available, it is what they decide to offer.

**Comment by mfhepp** [comment]
And as I wrote above:

... I strongly suggest that if so, we should:

1. Start with use cases, requirements, and examples of respective sites / page templates.
2. Check whether the existing elements cover the requirements by producing examples.
3. Evaluate whether the resulting markup is simple enough.
4. If necessary, carefully craft simplifications or shortcuts.

**Comment by jvandriel** [comment]
>
>
>    1. Start with use cases, requirements, and examples of respective
>    sites / page templates.
>    2. Check whether the existing elements cover the requirements by
>    producing examples.
>    3. Evaluate whether the resulting markup is simple enough.
>    4. If necessary, carefully craft simplifications or shortcuts.
>
> +1

2015-03-30 20:39 GMT+02:00 Martin Hepp <notifications@github.com>:

**Comment by ppKrauss** [comment]
Ok (!), let's do something concrete,

 * *"1. Start with use cases"*: how to format and centralize the *use cases*? In a git-fork? or here, like I do in [this other issue](https://github.com/schemaorg/schemaorg/issues/242#issuecomment-76740565)? My suggestion (more simple) is the second option (see link).

 * ... *"2. Chenck; 3.Evaluate; 4..."*, I think all, to go forwards, depends on the *use cases*...

**Comment by mfhepp** [comment]
Let's get away from opinions and let the markup speak. If you want to say that a local business serves a certain area, then simply define one Offer with a broad name and use eligibleRegion:
```
<div itemscope itemtype="http://schema.org/LocalBusiness">
	<div itemprop="name">ACME Pizza Service</div>
	<div itemprop="makesOffer" itemscope="http://schema.org/Offer">
		<div itemprop="name">Pizza Delivery in Bavaria</div>
		<meta itemprop="eligibleRegion" content="DE-BY">
	</div>
</div>
```
This is only one line longer than any solution with a property attached to the place. Since LocalBusiness is a subtype of Place and Organization, we can directly use the makesOffer property.

Now - is that simple enough? I bet so.
But it still works with queries that look for offers including the word "pizza", i.e. it does not introduce a new pattern for saying the same thing.

And people could (but do not have to) be more specific, e.g. by saying which delivery method or business function applies.
```
<div itemscope itemtype="http://schema.org/LocalBusiness">
	<div itemprop="name">ACME Pizza Service</div>
	<div itemprop="makesOffer" itemscope="http://schema.org/Offer">
		<div itemprop="name">Pizza Delivery in Bavaria</div>
		<meta itemprop="eligibleRegion" content="DE-BY">
		<link itemprop="availableDeliveryMethod" href="http://purl.org/goodrelations/v1#DeliveryModeOwnFleet">
	</div>
</div>
```

**Comment by mfhepp** [comment]
Of course, you could also use a polygon or place instead of the ISO code DE-BY for Bavaria. Or you could use validFrom and validThrough to indicate that a certain region is served only during a particular season etc. All this are extensions - it can be as simple as shown above, but I do not recommend to break the straightforward model just to save 64 + 5 = 69 characters in Microdata markup as in 

```
<div itemprop="makesOffer" itemscope="http://schema.org/Offer">
...
</div>

**Comment by vholland** [comment]
All of this discussion pre-dates the creation of schema.org/Service. I will close this and if there is a need that isn't met by Service, we can open a new issue with more timely information.
