### ISSUE TITLE
Explain (and/or vote) the "curation policy" of Schema.org

### ISSUE THREAD

**Issue by ppKrauss** [schemaorg/schemaorg#403]
SchemaOrg and its community need clarity of policy, to do objective collaboration, and to (users and partners) understand decision mechanisms...  An contextualized example [arose here](https://github.com/schemaorg/schemaorg/issues/401#issuecomment-86443726).

Summarizing: 

  * the [evolution mechanism](https://en.wikipedia.org/wiki/Sociocultural_evolution)  need clarity.
  * the criteria in decisions about little and big additions (add new "sub-vocabulary" or little vocabulary changes/adaptions) need clarity.
  * ...
  * an "algorithm" of [version control](http://schema.org/docs/releases.html) must be defined. Addition of new models (fragments of other ontologies like GoodRelations),
     * have "new life" in the SchemaOrg  context, and freedom to adaptations, etc. or 
     * are inherited models that need compatibility with its originators... 
     * ...or in SchemaOrg we use the two approaches (and the elected approach must be defined for each impoted fragment)...

**Comment by mfhepp** [comment]
Just speaking for myself: I do not think that drafting a formal charter etc. will help nor work for schema.org.  I assume that most of the contributors to the current codebase, 

    https://github.com/mfhepp/schemaorg/graphs/contributors

do not want strict W3C-/OMG/-whatever style mechanisms, because they hardly apply to the creative act of defining shared data structures (nor open source software in general).

The W3C and OMG and other have such mechanisms and have not yielded any meaningful Web ontology in decades, and in the case of schema.org, many different dimensions are relevant for comparing modeling decisions.

But if you want to further your proposal, I suggest that you elaborate a draft for a policy document and circulate it for review.

**Comment by Dataliberate** [comment]
Agree.

~Richard

On 26 Mar 2015, at 06:13, Martin Hepp <notifications@github.com<mailto:notifications@github.com>> wrote:


Just speaking for myself: I do not think that drafting a formal charter etc. will help nor work for schema.org<http://schema.org>. I assume that most of the contributors to the current codebase,

https://github.com/mfhepp/schemaorg/graphs/contributors


do not want strict W3C-/OMG/-whatever style mechanisms, because they hardly apply to the creative act of defining shared data structures (nor open source software in general).

The W3C and OMG and other have such mechanisms and have not yielded any meaningful Web ontology in decades, and in the case of schema.org<http://schema.org>, many different dimensions are relevant for comparing modeling decisions.

But if you want to further your proposal, I suggest that you elaborate a draft for a policy document and circulate it for review.

**Comment by danbri** [comment]
As @mfhepp and @Dataliberate have pointed out, this is a fairly scruffy/informal project. However we are  aware as a project that it would help to articulate some of the assumptions and thinking behind the project. This is most likely to show up via blog posts, rather than formal policies. I'll go ahead and close out this issue (since we have 100s of open issues, several of which also touch on this), but note the interest in this topic. Thanks, --Dan.
