### ISSUE TITLE
Rename WarrantyPromise to WarrantyPromiseSpecification

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#427]
Per #316 

After marking the too-generic 'warranty' as supersededBy the already existing 'warrantyPromise', @mfhepp suggests this clarification to avoid type/property differing only in case, and to align with existing naming practice.

/cc @tmarshbing @vholland @rvguha

**Comment by tmarshbing** [comment]
See my comment in #316 on current usage stats.

**Comment by mfhepp** [comment]
Yes, I would also support keeping warranty for the property and maybe WarrantySpecification for the type. WarrantyPromise as a type comes from GoodRelations and is a bit "ontologically inspired" label (and a bit wrong, too, since at least after a transaction, the warranty is no longer a pure promise, but a contractual obligation.

So let's consolidate on warranty and WarrantySpecification. I do not think that http://schema.org/WarrantyPromise is widely used nor consumed at this point.
