### ISSUE TITLE
Add ExhibitionEvent as a subtype of Event (was: add Exhibition as...)

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#445]
Consider adding schema.org/Exhibition as a subtype of Event. It would be for (typically long-running) museum (or gallery, edu etc.) exhibitions. 

No special properties proposed at this point, but examples shojuld show use of 'about' to indicate its topic/coverage.

**Comment by danbri** [comment]
see also #406

**Comment by portableant** [comment]
:+1:  that would be very useful.

**Comment by danbri** [comment]
See also Twitter conversation at https://twitter.com/danbri/status/591131319347843072

Excerpting, 

* Barry Norton: "think so, but guidance needing on modelling permanent collection, loaned objects, etc."
* Mia Ridge: "definitely! There are some nuances (touring etc), ..." + discussion on outreach to relevant mailing lists.

**Comment by jottevanger** [comment]
yes please.

**Comment by Jim-Salmons** [comment]
Re @BarryNorton and @MiaLondon et al -- Whatever you do, Dan, PLEASE do it so as to be a **#cidocCRM-compatible form**. 

Ontologists tend toward descriptive use of the #cidocCRM as a **metaDATA** standard when it is intended to be a **metaMODEL** supporting its use to prescribe *elementary building blocks* (model elements) of software architectures. Until there is wider recognition of the SIGNIFICANT leverage that **metamodel-driven software design** can do for the Digital Humanities, the #cidocCRM will be *as woefully under-utilized as it is currently under-appreciated.*

![cidoccrm_classes_cartoon](https://cloud.githubusercontent.com/assets/546022/7395829/3c628fea-ee62-11e4-92ac-0362b7b5157e.png)

Why do I believe this? I was a lead in a Smalltalk-based skunkworks in IBM's Object Technology Practice doing *"executable business model"* frameworks in the 1990s behind closed doors of corporate consulting. Our work was inspired by David Gelernter's *"Mirror Worlds"* and was based on "self-descriptive" Smalltalk images that were compliant to an actor/role metamodel that objectified Process (an OOP heresy at the time).

Following my horrific cancer battle and a chance to stick my finger in the eye of the Reaper and come back for some Bonus Rounds, I find myself as a **Wolf Child** in the **Wonderland of Digital Humanities' "Golden Moment."** 

When we were trying to do EBMs (executable business models) at IBM, we trolled the various IBM Global Services consulting practices for viable IRRs -- each practice was required to create an Industry Reference Model, AKA a metamodel. These IRRs ran the gamut from worthless tripe to "Wow!? Pretty good!" 

I most enjoyed "pair programming" with my first ontologist, we called him "Doug the Librarian" because he "just modeled" and didn't code. Basically, what we were looking for in partners to do metamodel-driven software development were three things:

* **Subject Matter Experts** (especially if they were verbal, thinkers, and open to being 'pushed' to clarity)

* **Explicit Models** -- Black box expertise (wetware only) can't be executable without first being rendered in some explicit form of communication (usually words and images)

* **Source 'Instances' of these Explicit Models** -- The best way to surface hidden assumptions and contradictions is to look at the delta of models that purport to be instances of the same metamodel 

**THE DIGITAL HUMANITIES DOMAIN HAS EVERYTHING NEEDED TO DO METAMODEL-DRIVEN SOFTWARE DESIGN AND DEVELOPMENT IN THE EXTREME!** :D 

And the **#cidocCRM** is the *BEST opportunity* I've seen to date to move in this direction.

Along these lines, I am working on **#cidocCRM microservice workflows** based on a **'self-descriptive' metamodel subgraph design pattern** for *LAM-based social games* (front-end clients) and *#cidocCRM-compliant collections management and scholarly editing* back-end. 

(BTW, a first step in this regard is to more rigorously express the #cidocCRM in pure-graph form to support vendor- and tech-neutral self-descriptive datastores.)

If anybody is interested in these ideas, please see: http://goo.gl/dpbhPs and http://goo.gl/gS2FJk, etc. at @FactMiners (www.FactMiners.org). This recent Medium.com article is the closest thing to a 'manifesto' on my applied research agenda: http://goo.gl/3Vb0lO.

In closing, I am an unaffiliated independent Citizen Scientist/Historian working from an Outsider POV. Inquiries to clarify ideas as well as explorations of opportunities to collaborate are most welcome @Jim_Salmons, @FactMiners, and @SoftalkApple

**Comment by Jim-Salmons** [comment]
While my 'pitch' for metamodel-driven software design is in general response to Dan's question, I would note that **Exhibition** as kind of **Event** is a perfect example of the "two-faces" of **#cidocCRM Temporal Entities**; 1) as *descriptive elements* -- time-boxing the 'live' event for documentation purposes, while 2) Exhibitions implemented/supplemented by software systems based on such metamodel standards are by nature **self-descriptive** and thereby can be **"self-publishing"** in terms of a #LOD World.

**Comment by anarchivist** [comment]
cc @danbri, @mialondon, and @barrynorton.  I'm interested in this from the perspective of web exhibits. I realize that they are more likely in some senses a `schema:WebSite`, but I'm thinking where the web exhibit may be time-bound.

**Comment by danbri** [comment]
re "#cidocCRM-compatible form." are there any public sites with exhibition event descriptions who have (somehow) used CIDOC CRM for this? There's often a certain amount of "dumbing down" when rich info gets used to generate Web pages, I'm not sure how much CRM shows up in public content...

**Comment by BarryNorton** [comment]
Because we don't include exhibition records at the British Museum LOD site
most objects that 'were present at' an exhibition are so related because
they were made for that exhibition (hence needed the named event in order
to be catalogued), e.g.:

SELECT DISTINCT ?object
<http://collection.britishmuseum.org/sparql?query=SELECT+DISTINCT+%3Fobject%0D%0A%7B%3Fobject+crm%3AP12i_was_present_at+%3Chttp%3A%2F%2Fcollection.britishmuseum.org%2Fid%2Fevent%2F-Queen-of-Sheba%3A-Treasures-from-ancient-Yemen-exhibition%3E%7D%0D%0A&_implicit=false&implicit=true&_equivalent=false&_form=%2Fsparql>
{?object crm:P12i_was_present_at
<http://collection.britishmuseum.org/id/event/-Queen-of-Sheba:-Treasures-from-ancient-Yemen-exhibition>}
<http://collection.britishmuseum.org/sparql?query=SELECT+DISTINCT+%3Fobject%0D%0A%7B%3Fobject+crm%3AP12i_was_present_at+%3Chttp%3A%2F%2Fcollection.britishmuseum.org%2Fid%2Fevent%2F-Queen-of-Sheba%3A-Treasures-from-ancient-Yemen-exhibition%3E%7D%0D%0A&_implicit=false&implicit=true&_equivalent=false&_form=%2Fsparql>


There are also some historical exhibitions that are useful for cataloguing,
e.g.:
http://collection.britishmuseum.org/id/event/International-Postage-Stamp-Exhibition-Stockholm-1974

Where we actually have objects belonging to an exhibition, sometimes things
are broken:
http://collection.britishmuseum.org/resource?uri=http%3A%2F%2Fcollection.britishmuseum.org%2Fid%2Fexhibition%2FFantastic-Creatures&role=object
(You'll see there are no forward relations, not even the typing as a CRM
event, which looks broken)

There are some improvements to be made, clearly, but the impetus to
actually openly make available records of exhibition contents could only be
a good thing...

Barry

**Comment by frankieroberto** [comment]
Hello. I developed the `Exhibition` schema for Freebase: http://www.freebase.com/m/046chf6 (and inputted a few hundred Exhibitions into Freebase).

My suggestion would be that the subtype of `schema.org/Event` should be called `schema.org/ExhibitionEvent`, both for consistency with `TheaterEvent`, `DanceEvent`, etc, and to allow `schema.org/Exhibition` to be a potential subtype of `CreativeWork` instead – which would allow for separation between an exhibition as a conceptual curation of things (which could be permanent, or online-only) and an exhibition event as a visitable thing with start and end dates.  This matters because lots of exhibitions travel to multiple venues.

**Comment by danbri** [comment]
So if we had ExhibitionEvent and Exhibition (a CreativeWork, long term thing or short term thing...), plus a relationship linking them analogous to the way workPerformed is used, would that be about right? Useful? Easy to get rough consensus on?

(We have workPresented queued up for the next release anyway...)

**Comment by anarchivist** [comment]
:+1: from me.

**Comment by danbri** [comment]
If an Exhibition tours, does it tend to have its own Web site that tells the whole story of where it is when?

What are the boundaries here, in terms of scope creep? We are talking mostly so far about museums and similar, are there nearby similar 'exhibitions'? Eg car shows or whatever, who might try to use the same markup...

**Comment by BarryNorton** [comment]
Certainly not always, Dan. One of my favourite of our exhibitions last year
was the Vikings one, where the ship, and other artefacts, came
from National Museum of Denmark and then went to the Staatliche Museen zu
Berlin. I'm not aware of any core site (though someone at Google might know
better than I ;) )

Barry

**Comment by mialondon** [comment]
@danbri some organisations have commercial arms that might have a site for a touring exhibition aimed at selling it to other venues, but that would count as an Exhibition rather than an ExhibitionEvent. I assume most museums would use ExhibitionEvent in their public what's on listings or exhibition microsite (if their CMSs can manage it).

Trade shows have 'exhibitors' so I guess might also use ExhibitionEvent.

**Comment by danbri** [comment]
Thanks, @mialondon, @BarryNorton, @anarchivist  

/cc @mfhepp who might have encountered more e-commerce -oriented exhibition markup on his travels

**Comment by Jim-Salmons** [comment]
Okay, @danbri, @BarryNorton, @anarchivist, and @mialondon 

This is another "note from the fly on the wall" thinking about future implications more than the nitty-gritty of the decision at hand... so this is parenthetical but hopefully a useful perspective 

I believe the **#cidocCRMdev** comments I contributed earlier are relevant to this most recent thread inquiring about the **Exhibition** as a Real-Time event. I would characterize the Exhibition's *website* as its [*"Mirror World"*](https://global.oup.com/academic/product/mirror-worlds-9780195079067?cc=us&lang=en&) **alt** or **proxy**. And as @BarryNorton suggests, in addition to the question of web presence, there are all manner of *E10 Transfer of Custody* activities, etc. that transpire as an **Exhibition** *"happens"* as an **E2 Temporal Entity** in **Museum World**.

![20140823_051646000_ios](https://cloud.githubusercontent.com/assets/546022/7438639/1d5fb484-f02d-11e4-8a61-512dcb2c351a.png)

By the **#cidocCRMdev** *hashtag* I mean **#cidocCRM-compliant metamodel-driven software design and development**. Under such an approach, we can do **#cidocCRM microservice composition** by *specifying executable model instances as domain-specific extensions the #cidocCRM*. By being *"self-descriptive"* -- using a *metamodel subgraph* or comparable design pattern -- writing a "new set of applications" is reduced to thoughtful composition of its executable model, not writing one-off applications.

So to the Point of this discussion, there are obvious advantages in building cultural artifact preservation, curation, and collection management systems that are compliant with the #cidocCRM ISO Standard. **But why stop there?**

We really start to get **#cidocCRMdev leverage** when such *self-descriptive/self-documenting* frameworks are used to build other ["Social Machines"](http://www.SOCIAM.org) in **Museum World** -- **a #cidocCRM-compliant microservice system to implement an Exhibition**, for example. In this sense an Exhibition is seamlessly interwoven, not just into the overall system of the Exhibiton's location-host, but each participating collaborators' systems are equally seamlessly networked for the transient interplay of the Exhibition. The obvious example being the seamless, self-documenting flow among the participating Cultural Institutions' various **E21 Persons** as **E39 Actors** in **E10 Transfers of Custody** activities, etc.

In this way, a **Museum World Exhibition** is not dissimilar to a *network of persistent creative participants* who come together in Hollywood via a *temporary production company* to **make a movie** then go their separate ways. Sustainable, adaptable **Museums of the Future** will certainly need the creative freedom and expressive flexibility of such composable, dynamic systems. 

**I believe the #cidocCRM can provide significant guidance in creating the web-friendly microservice systems essential to realizing the Museums of the Future.**

Further, once we realize that Exhibitions end in the Museum World but keep on going in Digital Museum World, it becomes all the more important to build such systems in a manner that are easily composed, shared, and when the time comes either handed off to others or "turned loose" into the wild of Digital Museum World.

This is what I see when I look at the as-yet-realized potential of the #cidocCRM. That **E2 Temporal Entity** branch is ripe for exploitation via a **metamodel-driven design strategy**. 

So that's my *"iron in this fire"* -- whatever Schema.org decides on this and similar pragmatic decision of an ontological nature, the closer whatever you decide to do is to #cidocCRM-compliance, the better the chances that developers like me will be able to use the #cidocCRM effectively. Thank for you considering this input.

![cidoc-crm-class-hierarchy](https://cloud.githubusercontent.com/assets/546022/7400685/491f6f74-ee84-11e4-8dec-d41e637f55e9.png)

**Comment by frankieroberto** [comment]
@danbri "So if we had ExhibitionEvent and Exhibition [..] plus a relationship linking them analogous to the way workPerformed is used, would that be about right?" – sounds about right to me. An Exhibition may have multiple ExhibitionEvents if it tours, or none if it's permanent (or perhaps online-only).

In terms of boundaries, I'd be fairly relaxed about car shows, trade shows, art & craft fairs, etc, all using the schema, although there's probably some overlap with `VisualArtEvent` and `BusinessEvent`. The core common meaning to 'exhibition' is probably something like 'things to look at', but there may often be a commerce element too (the [original exhibitions](http://en.wikipedia.org/wiki/The_Great_Exhibition) certainly did).

In terms of websites, most travelling exhibitions seem to get a new website for every location they tour to (partly down to translation & localisation, partly because of the way local marketing is managed). However some might have a website for overall exhibition, with dates of the cities / locations it's toured to, which could be marked up with `ExhibitionEvent`, e.g. [Digital Revolution](http://www.barbican.org.uk/bie/upcoming-digital-revolution).

There may also be examples of exhibitions which are open on non-consecutive days (e.g. for a few weekends), and so which might need to use separate `ExhibitionEvent`s for each weekend opening.

**Comment by frankieroberto** [comment]
@danbri PS +1 on using `workPresented` to connection an `ExhibitionEvent` with an `Exhibition`.

**Comment by frankieroberto** [comment]
PPS #406 makes a good argument for not adding to the list of sub-classes of `Event` (especially if not adding any properties).

**Comment by danbri** [comment]
What do you all think about adding in a 'curator' property while we're at it, linking an Exhibition or ExhibitionEvent to a Person (or Organization too)? Quick-easy-and-useful vs giant-can-of-worms?

**Comment by mialondon** [comment]
@danbri IMO, it's a can of worms, not least because it's only one of many relevant roles (e.g. 3D, 2D, digital exhibition designers etc), it can be a team rather than an individual and to generalise very broadly it works differently for history and art museums. Generic 'related people' or organisations would be useful but Event presumably already has something FOAFy like that.

**Comment by Dataliberate** [comment]
+1

~Richard


On 4 May 2015, at 15:38, Dan Brickley <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you all think about adding in a 'curator' property while we're at it, linking an Exhibition or ExhibitionEvent to a Person (or Organization too)? Quick-easy-and-useful vs giant-can-of-worms?

-

**Comment by frankieroberto** [comment]
@danbri I think a `curator` property is reasonable, even if it applies more to some exhibitions than others. It might make sense for the expected type to be `Person` or `Organization` to address @mialondon's point about teams (although I'm not sure if this would be more useful than having multiple individual curator credits).

Other properties that might be worth re-using are [`productionCompany`](http://schema.org/productionCompany) and [`sponsor`](https://schema.org/sponsor).

**Comment by VladimirAlexiev** [comment]
Of you use workPresented for ExhibitionEvent->Exhibition, how would you model the museum objects that are exhibited? 

In CRM, ExhibitionEvent will be a subclass of Event, Exhibition a subclass of Collection (specially assembled for the event), and then the museum objects would be partOf the Exhibition collection. But I don't know if Schema supports such generic partOf relations, and I feel uneasy making them partOf if we don't also rigorously model the temporary nature of this parthood. As Barry wrote, in the BM CRM data we took the easy way and said exhibition is an Event with appropriate p2_has_type, and the objects were simply p12_present_at it.

From the complications shown above (eg by Mia), it seems to me we need some real data to get this right.

We should also model virtual (web) exhibitions, that's a whole software genre in itself (eg Omeka). Cheers!

From the complications shown above,

**Comment by mialondon** [comment]
I've just seen that the Southbank Centre have an 'Event Open Data Model' that might be useful (via http://digital.southbankcentre.co.uk/how-to-build-an-open-website-part-2/)

**Comment by frankieroberto** [comment]
@mialondon looks like they're re-using the types and properties from schema.org: https://github.com/Southbank-Centre/OpenEvent – no Exhibition type, but they're using nested Events to model, say, a talk as part of a Festival.

There seems to be some ambiguity over whether, say, a 6-week-long run of a play or a 6-week-long exhibition, should be modelled using an `Event` (with `subEvents` for each performance / day of opening), or as a `CreativeWork` with the events associated using the `workPerformed` property.

**Comment by danbri** [comment]
Let's start with ExhibitionEvent...

* work in progress test site: http://sdo-exhibition.appspot.com/ExhibitionEvent
* github branch: https://github.com/schemaorg/schemaorg/tree/sdo-exhibition
* definition(s): https://github.com/schemaorg/schemaorg/blob/sdo-exhibition/data/schema.rdfa#L3296
* example(s): todo

**Comment by frankieroberto** [comment]
@danbri great! What's the best way to contribute? I don't think I can edit that branch directly. Fork and Pull Request to the branch? Or just comments here?

**Comment by danbri** [comment]
Comments here are good. I have merged this into the upcoming release branch (aka sdo-phobos).  I think 6 months of discussion was plenty - there's broad consensus that this is a good thing to do.

http://sdo-phobos.appspot.com/ExhibitionEvent

This change also adds a new property 'workFeatured' which is a super-property for the existing (but often inapplicable here) workPerformed and workPresented properties.

/cc @tilid  @pmika @ajax-als @chaals @vholland  @shankarnat @tmarshbing @rvguha 

We could do with a simple example - gratefully received here.

**Comment by vholland** [comment]
+1

**Comment by BarryNorton** [comment]
Happy to work up an example based on the original British Museum 'History of the World in 100 Objects' exhibition from 2010.

(We already have individual object links to the BBC Radio programmes in RDF at collection.britishmuseum.org)

**Comment by danbri** [comment]
Yes please! We're trying to wrap things up by end of this week for a release, if that isn't too soon for you.

**Comment by frankieroberto** [comment]
@danbri I think it's possibly a bit unclear at the moment what the `workFeatured` property should refer to – i.e. in the case of an art exhibition, should it refer to the individual art works, or to a single (future) `Exhibition` type?  The former is conceptually simpler, easier to author, and probably the most appropriate for the majority of exhibitions which are a one-off event, but the latter removes duplication in the case of exhibitions which travel to multiple venues, and allows all the properties of `CreativeWork` to be used to describe the exhibition.

To take an example from another type of Event, the example for http://sdo-phobos.appspot.com/TheaterEvent seems to point towards a CreativeWork representing the written play of 'Julius Caesar' (which has the creator as Shakespeare) rather than a 'theater production' type of creative work representing the production of Julius Caesar, which might have the director as the creator (and `actor` properties for the cast).

For both TheaterEvent and ExhibitionEvent, it's also unclear as to whether authors should mark up a single event for a whole run (spanning multiple days), or individual events for each performance / opening day?

**Comment by danbri** [comment]
@frankieroberto at this point the draft says

"A work featured in some event, e.g. exhibited in an ExhibitionEvent. Specific subproperties are available for workPerformed (e.g. a play), or a workPresented (a Movie at a ScreeningEvent)."

...which leaves a lot of options open. I think this is an appropriately flexible start since different publishers will have access to different levels of detail. Additional information attached to the CreativeWork might help further, e.g. subtypes like http://schema.org/Painting http://schema.org/Book etc are available, as well as the hasPart / isPartOf properties for hierarchical structure. 

You're right that further clarifications and indicative examples could be helpful. There are also discussions around event series that are relevant - see https://github.com/schemaorg/schemaorg/issues/447 . I hope we can continue to refine things in future releases and that there is nothing in the drafted version that would block future progress or cause too much confusion amongst publishers.

**Comment by frankieroberto** [comment]
@danbri so, if we were to add a future `Exhibition` type as a sub-type of `CreativeWork`, then we’re saying it would be permissible for the `workPresented` property of `ExhibitionEvent` to either refer to an `Exhibition` or, say, a `Painting`?  I guess that does allow for maximum flexibility, at the possible expense of future confusion (e.g. if parsers start expecting `workPresented` to be a list of artworks / exhibits, rather than a single exhibition which itself contains the list of artworks / exhibits).

Any thoughts on whether to advise people (in either the description or examples) to use a single event type for the entire run of an exhibition / theatre performance / movie run or one for each day open / performance / screening? That's an area where I think clear guidance would be preferable from keeping it complete open or unspecified.

**Comment by frankieroberto** [comment]
@danbri PS can you retitle this issue to Add ExhibitionEvent as a subtype of Event`? Then I'll add a new issue for adding `Exhibition` as a subtype of `CreativeWork`.

**Comment by frankieroberto** [comment]
Here's a a quick marked-up example from the [V&A What’s On page](http://www.vam.ac.uk/whatson/) (which is already using schema.org microdata:

```
<div itemscope="" itemtype="http://schema.org/ExhibitionEvent">
  <meta itemprop="location" content="Victoria and Albert Museum">
  <meta itemprop="inLanguage" content="en">
  <h2><a itemprop="url" href="http://www.vam.ac.uk/whatson/event/5150/shoes-pleasure-and-pain-696789408/">
    <span itemprop="name">Shoes: Pleasure and Pain</span>
  </a></h2>
  <p><time class="nowrap" itemprop="startDate" datetime="2015-06-13">Sat 13 June 2015</time>–<time itemprop="endDate" datetime="2016-01-31">Sun 31 January 2016</time></p>
    <p itemprop="description">Explore the transformative power of footwear from around the world as we present over 200 pairs of the most extreme shoes from the last 2000 years. </p>
  <a itemprop="offers" href="http://www.vam.ac.uk/whatson/event/5150/date/20151007/">Book tickets</a>
</div>
```

**Comment by mfhepp** [comment]
Please also include #838.

**Comment by frankieroberto** [comment]
@danbri is that marked-up example helpful at all?

**Comment by rbailly** [comment]
Hello, I suggest to add something like "eventSubject" if its not too broad. Could be a thematic such as pointillism, or a known person such as Marc Chagall. Would be very useful I guess.

**Comment by ostephens** [comment]
@rbailly think http://schema.org/about should be used for the purpose of describing what the event is about?

**Comment by danbri** [comment]
Yes, 'about' is the best fit here. It might help (but not really essential) if we were to say more explicitly that it also expects URL values.

**Comment by rbailly** [comment]
Thanks, I agree. 'about' is a property of 'CreativeWork'. So I guess this is related to #838 ?

**Comment by danbri** [comment]
Added ExhibitionEvent + example in http://schema.org/docs/releases.html#v2.2  - thanks all. There's a lot of discussion here, and we can continue chatting, but I'll close out the issue since we've addressed the main concern.

**Comment by rtroncy** [comment]
Hi @danbri ... to come back to the question of @rbailly: how can one specify what an [ExhibitionEvent](https://schema.org/ExhibitionEvent) is about in the current version of schema.org?

The issue #838 suggests that an ExhibitionEvent could become a CreativeWork which will enable to apply the [about](https://schema.org/about) property. But without a resolution of this issue, how one is supposed to do **now**?

**Comment by danbri** [comment]
As also in #838: How about we just extend 'about', 'isFamilyFriendly', 'genre' to be applicable to Events?

**Comment by frankieroberto** [comment]
@danbri @rtroncy this is an interesting question. I originally proposed that there should be a separate `Exhibition` type as a subtype of `CreativeWork`, which would allow you to specify the `about`, `isFamilyFriendly`, `genre` etc on that, and then connect the `Exhibition` with `ExhibitionEvent` via a `workPresented` (or similar property).

This has the advantage that it works the same way as `ScreeningEvent` and `Movie` (or `BroadcastEvent` and `TVEpisode`) - i.e. the event with its timing/pricing/location properties is separated from the 'work' with its genre/subject/etc properties.  It also makes sense where the work is typically presented/performed at lots of different events.

However there are also lots of one-off events where, in natural language at least, the event and the work are conflated together – e.g. a special exhibition at a museum, or a one-night-only play.

The question for those is whether it's better to adopt some of the CreativeWork properties (like genre, subject, etc) for Events OR to encourage people to use multi-typed entities OR to have two separate entities and link them together.

As a separate, but related, issue – it's currently ambiguous over whether something like a two-week event open Mon-Sat should be encoded as a single event with a `startDate` and `endDate` (but the opening times and middle Sunday closure left unspecified) OR as a separate event for each individual day (with `startDate` and `endDate` as full date-times).  (If the latter, then there's more of a need for a standalone 'work' which each event can link to).

**Comment by rtroncy** [comment]
I like the pattern of distinguishing the ```CreativeWork``` from the ```Event``` with a property that links them together such as ```workPresented``` but I also acknowledge that there are many cases where those two are conflated and that you would like to directly say what an ```Event``` is ```about```. I don't think the multi-typed entities will be something that we recommend in this case since there are just a very little number of properties that we would like to pass on the ```Event```.

Regarding the separate but related issue of repetitive event, there is already the outstanding issue #240 and the associated issue #447 where the ```EventSeries``` type has been proposed.

@danbri any chance to have those issues resolved for the [sdo-deimos](https://github.com/schemaorg/schemaorg/issues/911) release?

**Comment by danbri** [comment]
Event series are well worth some attention. Do you have a feeling how far we are from consensus? (I guess we should move into #240 for this part...). I believe Event series are also quite relevant to learning-oriented course descriptions (see [recent discussion](https://lists.w3.org/Archives/Public/public-schemaorg/2015Dec/0000.html)) .../cc @philbarker @vholland

**Comment by frankieroberto** [comment]
@danbri @rtroncy specifically in relation to `ExhibitionEvent`, would you say that a 3 month exhibition open daily (except Sundays) is an EventSeries, or just a single event with more specific opening criteria than can currently be expressed? I'd argue the latter.

One option may to simply add an `hoursAvailable` property to `Event` which takes an `OpeningHoursSpecification` as a value, as is currently used for `Service`?

On the other issue – perhaps it's worth re-considering adding `Exhibition` as a sub-type of `CreativeWork`, which could then be linked to `ExhibitionEvent`s in cases where an exhibition travels to multiple venues?

**Comment by rtroncy** [comment]
I would also model a 3 month exhibition as a (single) ```Event``` which could indeed have a ```hoursAvailable``` property. EventSeries, for me, correspond to a series of performances (e.g. dates of concert of an artist on tour, play in theater where generally a troupe is performing almost every evening for a month or two, etc.), but I admit that the distinction is subtle.

**Comment by frankieroberto** [comment]
@rtroncy agreed – I guess the [subtle] distinction is that whereas for a theatre performance / concert you'll be there at the start and stay to the end (of the individual performance), for an exhibition you can drop in at any time during its run whilst it's open, and stay as long as you like.

I've added the suggestion to adopt `hoursAvailable` for `Event` at #932.

**Comment by thhap** [comment]
For itemtype ExhibitionEvent are available 'performer' and 'organizer'.
'performer' seems very much to be stage related, being part of a upper level 'artist'.
I would like to suggest itemprop 'artist' as a more general itemprop.
It is used as term in exhibition information of fine art museums, galleries worldwide for 100 of 1000 of exhibitions. It could be a painter, sculpture, video artist etc.
Furthermore I would like to suggest itemprop 'curator'. It is a standard term for the person who organizes an exhibition, selects the artists, the artwork, exhibition layout etc. The term is as well used in every museum or gallery exhibition worldwide.
We at artist-info.com locally already implemented successfully the standard ExhibitionEvent details but would like to add with itemprop 'artist' and 'curator' additional information for ExhibitionEvent.
http://screencast.com/t/9BdCLp1p0R

**Comment by vholland** [comment]
+1 for "curator" for ExhibitionEvent.

I am ambivalent on "artist" vs overloading "performer".

**Comment by thhap** [comment]
'performer' might be more related to a personal action by a living person: A singer, an actor, a musician, a commedian. However, a 'performer' must not necessarily be an 'artist'.
An 'Exhibition' might be something rather static, showing pysical items, being as well an 'Event', meaning go there now and look, listen etc..
Bravo for combining them to ExhibitionEvent!
Exhibited physical items are quite often related to a person, author etc., e.g. a 'maker' (craftsman), or an 'artist' (painter, etc., living or already passed away, e.g. Picasso).
May be having all three itemprops would be a good idea: 'performer', 'maker', 'artist'.

**Comment by Dataliberate** [comment]
+1 for curator, artist, performer.  Would prefer to extend range of 'creator' instead of using maker. 

~Richard

**Comment by thhap** [comment]
@danbri - Until a decision is made regarding possible new itemprop="artist" and "curator" "maker"/"creator"
we implemented "performer" and "organizer" for artist and curator for our table based exhibition history pages
http://screencast.com/t/3TxMp03apuF

**Comment by rbailly** [comment]
+1 for curator  but I disagree with artist or performer. 

The "artist"  ( Andy Warhol in the example of @thhap ) is the subject of the exhibition. You may have exhibitions about "Marie Curie" or about "the internet".  
So +1 for the property about which comes with CreativeWork..

**Comment by thhap** [comment]
@rbailly  The structure of exhibition information starts always with the Exhibition Title + Sub-Title, we use itemprop="name",
Then Start and End Date and location
Then all the artists and curators who take part at this exhibition, sometimes 20 or many more.
In this case it is a Solo-Exhibition of Andy Warhol and he is listed with his name as 'artist' of this exhibition, as the "subject".
Exhibiiton titles want to tease but can't list e.g. 20 or 100 artists taking part at an exhibition.

A "performer" may rather be related to a live-act, Warhol died 1987.
I suggested additional itemprop "artist" and "curator" and "maker" and/or "creator" to better discribe what visitors of an exhibition could expect.
May be itemprop="subject" instead of artists etc. could avoid a too high differentiation.
If the V&A would have an exhibition with furniture makers or fashion designers and need to list their names it would help to categorize them under e.g. "creator" rather than "performer".

**Comment by thhap** [comment]
https://schema.org/ExhibitionEvent listing itemprop
Properties from Event
Properties from Thing
Where are 
Properties from Exhibitions?

**Comment by thhap** [comment]
itemtype ExhbitionEvent
itemprop="artist" isn't possible as it has moved to bib.schema.org/artist
itemprop="creator" is bound to type schema.org/CreativeWork - If it could be used for ExhbitionEvent would be much appreciated.
itemprop="organizer" can be used without problem for "curator".
Curator / curating an exhibition is used more often worldwide, but organizing an exhibition is used, too.

I hope that ExhibitonEvent will have some day itemprops which help describing Exhibitios better.
"performer" is nice for Events like theater, or concert but not for an exhibition of e.g. painting.

**Comment by thhap** [comment]
@danbri Regarding developing https://schema.org/ExhibitionEvent
Would it be possible to add 'Contributor' as itemprop, with 'Person' or 'Organization' range?
https://schema.org/contributor
'contributor' would complement 'performer' and 'organizer' to enable more detailed structure of  the wide range of ExhibitionEvnet information data.

**Comment by gherlt** [comment]
@thhap 
may I ask on this comment:
>itemprop="artist" isn't possible as it has moved to bib.schema.org/artist
makes it imposisble to add or use it in ExhibitionEvent ?
I am not very comfortable using "performer" as atrists, especially for dead artists...
And "contributor" has a connotation of "provides money or work" to the event, I do not see an artist fit into this. 

@rbailly title can be a single artist, but on Andy Warhol (as a dead artist) it would be "Andy Warhol - Pantings from his green period" (or whatever). When an exhibitionit is a group exhibition, there is a single title (think "Green periods of 20th century masters"), there is "Andy Warhol" but maybe another 10 artists. Makes a long (useless and untrue) title.  
Also cross linking is getting difficult.
