### ISSUE TITLE
Add EventSeries as subclass of Series

### ISSUE THREAD

**Issue by wikier** [schemaorg/schemaorg#447]
This is issue is to discuss the PR #446 about how to add support to event series.

It is related with some other ongoing discussions, such as the repeating events modelling (issue #240) and the new event types (issue #406).

**Comment by danbri** [comment]
Thanks! Let's discuss under #240 for now...

**Comment by danbri** [comment]
Can folk here please take a look at the Courses discussion, which has run directly into this topic: https://www.w3.org/community/schema-course-extend/wiki/Main_Page https://lists.w3.org/Archives/Public/public-schema-course-extend/2016Mar/0021.html

**Comment by danbri** [comment]
I've just added EventSeries into the 'pending.schema.org' extension I've created - intent is to avoid things getting stuck in Github limbo for so long. Right now this is just in the upstream/dev site webschemas.org but I hope we'll agree a workflow where proposals can go more quickly to pending.schema.org without waiting for large releases.

See http://pending.webschemas.org/EventSeries

(files are in data/ext/pending/issue-447* ... could do with an example - maybe someone could convert the Turtle in the PR into JSON-LD?)

**Comment by wikier** [comment]
Good to see this moving forward, @danbri!

Since #446 was based on a pretty old branch, I've just added a new PR #1088 with the same proposal we had, but adding an example (both in Turtle and JSON-LD).

**Comment by chaals** [comment]
Can we have a bit more information in the definition please?

(Admittedly I can't think of a clear explanation immediately either :( )

**Comment by danbri** [comment]
How about: 

"An EventSeries is a Series of related events. The nature of the association between the events can vary, but typical examples could include a thematic event series (e.g. topical meetups or classes), or a series of regular events that share a location, attendee group and/or organizers."

I have mentioned 'classes' here which might merit some consideration w.r.t. the courses work. /cc @philbarker

**Comment by chaals** [comment]
Counter offer that also tests whether I have understood what everyone else has:

An EventSeries is a collection of events that share some unifying characteristic. For example, "The Olympic Games" is a series, which is repeated regularly. The "2012 London Olympics" can be presented both as an Event in the series "Olympic Games", and as an EventSeries that included a number of sporting competitions as Events.

"The Ashes" (cricket contest between Australia and England) is repeated frequently, but not according to any long-term stable schedule. The course "Beowulf: the manuscript and the man" can be an EventSeries consisting of individual seminars with the same participants, and an EventSeries of the course being held repeatedly over a decade.

**Comment by unor** [comment]
I’m surprised that `EventSeries` is a `CreativeWork`. 

Are the Olympic Games (as in: the event series) really a *creative work*? And if yes, why not also a single Olympic Games event?

**Comment by wikier** [comment]
I'm happy to improve the description. The porposal by @danbri sounds good for me. I'll await for more feedback before updating PR #1088.

**Comment by danbri** [comment]
@chaals 's example is interesting - can we focus on that one for now? 

We ought to be confident that we can show both usages work sensibly together and that the extra expressivity we bring comes with clear usage guidance. 

For example consider if there is a 2016 seminar series (e.g. each of 6 x 1h sessions on successive weeks), and then later the course is re-run as a 2017 series with the same structure and topic, but different people.  This also relates to whether we want to say that EventSeries is a subtype of Event (or at least carries Event-like properties). 

Aside: please note that the nice diagram in #1088 is out of date w.r.t. the current proposed design which uses superEvent to point to the EventSeries. This confused me today so I thought a warning worthwhile.

@chaals : 

> The course "Beowulf: the manuscript and the man" can be an EventSeries consisting of individual seminars with the same participants, and an EventSeries of the course being held repeatedly over a decade.
* "Beowulf: the manuscript and the man" (an annually repeating sequence of 6 seminar sessions)
  * 2016 Beowulf course
   * 2016 session 1: ...
   * 2016 session 2: ...
   * 2016 session 3: ...
   * 2016 session 4: ...
   * 2016 session 5: ...
   * 2016 session 6: ...
  * 2017 Beowulf course
   * 2017 session 1: ...
   * 2017 session 2: ...
   * 2017 session 3: ...
   * 2017 session 4: ...
   * 2017 session 5: ...
   * 2017 session 6: ...

@chaals outlines two views. One is to see the 6 sessions in 2016 as an EventSeries, the other is to see the sequence of annual runs of the course as an EventSeries. Either way, superEvent would point up the hierarchy, from e.g. '2017 session 3' (an Event) to '2017 Beowulf course' (an Event or an EventSeries) and from there to the top level 'Beowulf: the manuscript and the man' which is presumably an EventSeries but not an Event since it represents just the high level notion of the series rather than something that you can say is happening at a particular place and time. 

The mid-level is the most awkward. Intuition pulls it towards being both Event ("An event happening at a certain time and location" e.g. summer 2016, Madrid) and also an EventSeries (approximately "a collection of events that share some unifying characteristic e.g. relationship"). 

I can't see a way to escape saying "some but not all EventSeries may also be usefully treated as being an Event" i.e. occasional multiple typing at the level of instance data. It seems to me to be over-stretch to bake into the schema definitions the claim that every EventSeries is an Event.

In addition w.r.t. supertypes, I notice with (some embarrassment) that we added CreativeWorkSeries as a parent for various other series-types, but that it seems currently to be unrelated to Series. Looking more closely (opened #1090 ) we had in #417 marked Series in the schema definition files as supersededBy CreativeWorkSeries, but we didn't complete the job (either in site UI or updated definition). I propose we restore Series since it is a natural supertype for both EventSeries and CreativeWorkSeries. On @unor's point, I am comfortable with Series being under CreativeWork because we have http://schema.org/ItemList for a more pure list data structure detached from social context.

**Comment by danbri** [comment]
How about going with Event as the super-type and noting something like:

"EventSeries has been defined as a kind of Event to make it easy for publishers to use it in an Event context without worrying about which kinds of series are really event-like enough to call an Event. In general an EventSeries may seem more Event-like when the period of time is compact and when aspects such as location are fixed, but it may also sometimes prove useful to describe a longer-term series as an Event."

**Comment by wikier** [comment]
Sorry @danbri, I didn't realized that the diagram attached to #1088 was not the latest version. I've just upgraded it.

**Comment by wikier** [comment]
What about having both `Event` and `Series` as super-type? Something like:

```
schema:EventSeries a rdfs:Class ;
  rdfs:subClassOf schema:Series ;
  rdfs:subClassOf schema:Event ;
  ... .
```

**Comment by danbri** [comment]
Would anyone here object to EventSeries being subtype of Event?

**Comment by Dataliberate** [comment]
+1

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by thadguidry** [comment]
Hmm... one thing that I'd like to clarify....Repeated Events.

With EventSeries added, then Repeated Events could be done with SuperEvent as the [PR](https://github.com/schemaorg/schemaorg/pull/1088/files#diff-200232fafee461b4217385c536cb093eR1981) notes with:
`An event happening at a certain time and location, such as a concert, lecture, or festival. Ticketing information may be added via the 'offers' property. Repeated events may be structured as separate Event objects.`

Or Repeated Events could be repeated as individual Events as the existing Event definition says:
`An event happening at a certain time and location, such as a concert, lecture, or festival. Ticketing information may be added via the 'offers' property. Repeated events may be structured as separate Event objects.`

Do we care ?  Going forward, Can both Types be used for Repeated Events ?  Does the existing Event definition need additional hints about superEvent being able to handle Repeated Events perhaps now ?

**Comment by philbarker** [comment]
There seem to be three different things being discussed here: (1) sub/super events, i.e. individual events that are distinct but related, e.g. seminars 1-6 in the Beowulf course, or matches/stages/events in a sports competition; (2) separate offerings/seasons/editions of events, which have some degree of equivalence without being identical, i.e. they are offered to the same blueprint or with the same aims but with different people involved and variations in format (e.g. each edition of the Tour de France has different stages); and (3) repeated events, such as the same play being performed for several nights.

For courses, I think it is fair to say that while a course may repeat annually and include a "sequence of 6 seminar sessions" we should be careful not to limit it to that: it may be offered in other formats and may include other things apart from a sequence of sessions.

Currently in modelling courses we have 
Course, http://course.schema-course-extend.appspot.com/Course a CreativeWork, "A description of an educational course which may be offered as distinct instances at different times and places, or through different media or modes of study. An educational course is a sequence of one or more educational events and/or creative works which aims to build knowledge, competence or ability of learners." 
CourseInstance, http://course.schema-course-extend.appspot.com/CourseInstance an Event. "An offering of the course at a specific time and place or through specific media or mode of study or to a specific section of students."

So Course may be the description of an example of event series in sense (2) and CourseInstance may include an example of event series in sense (1) above.

**Comment by danbri** [comment]
This is published in pending.schema.org. Are there any changes or improvements to make? Would it make sense to progress it into the schema.org core?

**Comment by thadguidry** [comment]
@danbri Small improvement needed I think.... also add term 'event' to the [actor](url) property definition.   It should read ...

An actor, e.g. in tv, radio, movie, video games etc., or in an event. Actors can be associated with individual items, **events** or with a series, episode, clip. Supersedes actors.

**Comment by danbri** [comment]
Thanks @thadguidry, I've added that todo to a similar issue #1290

**Comment by wikier** [comment]
I was expecting that by entering `pending.schema.org` it was just a matter of gathering more feedback until it could go into a release.

I'd love to see this in 3.2. So let's me know what you think is still necessary. I'll check what #1290 is about.

**Comment by danbri** [comment]
@thadguidry looking again, we already say " or in an event.":

> "An actor, e.g. in tv, radio, movie, video games etc., or in an event. Actors can be associated with individual items, events or with a series, episode, clip. Supersedes actors."

**Comment by nextdude** [comment]
I was reading the discussion between @mfhepp and @wikier in #446 discussing whether there is a need for a separate entity called `EventSeries`, vs just using the `subEvent` and `superEvent` relationships in the Event entity. I didn't see discussion there of using `Role` as an intermediary to clarify the relationships. It is a possible solution to the problem that leverages an existing extension point without adding a new abstraction.

**Comment by saumier** [comment]
@nextdude @wikier @mfhepp I am looking into the use of `EventSeries` to model a series of `Events` in performing arts, such as a repeat performance of the same theatre play.  I have considered using the existing relationship `subEvent` and `superEvent` already supported in the Event entity, but find a significant down side leading to confusion when `superEvent` and `subEvent` appear as duplicate Events when searching Events. The use of Role can clarify if you have prior knowledge, but also seems like a down side because it add complexity to queries.  `EventSeries` removes the need to have prior understanding of how the Events are modelled specifically when merging Events with different data sources.

**Comment by rvguha** [comment]
We should probably rename Series to be CreativeWorkSeries.

EventSeries should be a subtype of Event. It is not more a CreativeWork
than a 'series' of rainy days is a CreativeWork.

guha

**Comment by danbri** [comment]
@rvguha - we did exactly that some while ago, and were close to deprecating Series except we didn't have the technical machinery in the site for type deprecation at the time. And then EventSeries appeared so Series was left dangling. In #1090 I asked 

>  is there any value in "Series" over and above having different kinds of series like EventSeries, CreativeWorkSeries?

Regardless, EventSeries should indeed be a subtype of Event.

If we decide to keep Series around as a common supertype, it will need to be subClassOf something. Putting it under Intangible means that we will then have CreativeWorkSeries and EventSeries that inherit from intangible, while also being of types CreativeWork or  Event. Putting it directly under Thing gives it a very high profile, pragmatically.

**Comment by thadguidry** [comment]
@danbri Putting Series under Thing might be best... the only extra class between them might be Group, which we don't have.  That's how its subclassed on Wikidata btw. And their Group is a subclass of Object (sorta close to our Thing) https://www.wikidata.org/wiki/Q20937557 Just Saying.

**Comment by vberkel** [comment]
@danbri in moving the Series, the properties isPartOf and hasPart are no longer available as their domain was CreativeWork. The JSON-LD example for EventSeries series uses hasPart, but that is not available to the Class. Should the domain of hasPart and isPartOf add Series?

**Comment by RichardWallis** [comment]
+1 expanding domain of isPartOf & hasPart to include Series

**Comment by RichardWallis** [comment]
... would also need to add Series to their rangeIncludes

**Comment by ldodds** [comment]
+1 on how this proposal is shaping up. What's need to get it out of pending?

**Comment by JeanCollas** [comment]
I found this thread there:
https://schema.org/EventSeries

Is it ready to be implemented on our websites, or should we wait for a stable release?

I have different kind of event series:
- events of a same organizer (may not be relevant for this property)
- regular events
- seasonal regular events (should probably be 2 levels of event series)

I am still unclear with the overlap with subEvent and superEvent. 

And a bit confused with "long" events, like 15 days, for which each day could be seen as an event, which class to use.
