### ISSUE TITLE
tests failing on valueReference: "No subtype need redeclare a rangeIncludes of its parents. Found: 3"

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#468]
http://sdo-gozer.appspot.com/valueReference has three cases in which we explicitly list (in sdo-gozer) and range for which we already mention a range of a subtype:

*Enumeration 
* StructuredValue
* PropertyValue (implied as these are all StructuredValue)
* QualitativeValue (implied as these are all Enumeration)
* QuantitativeValue (implied as these are all StructuredValue)

Are there other Enumerations and StructureValue types that are relevant, and should be listed instead of the higher types? Are we adding value by highlighting these 3 particular specific subtypes? Is the unit test being too picky?  

/cc @mfhepp @rvguha @vholland @chaals @pmika @tmarshbing  @ajax-als @tilid 

(this is part of property-value additions/changes)

test_needlessRangeIncludes (test_graphs.SDOGraphSetupTestCase) ... INFO:test_graphs:property, class1, [which is subclassOf] class2:
INFO:test_graphs:(rdflib.term.URIRef(u'http://schema.org/valueReference'), rdflib.term.URIRef(u'http://schema.org/QuantitativeValue'), rdflib.term.URIRef(u'http://schema.org/StructuredValue'))
INFO:test_graphs:(rdflib.term.URIRef(u'http://schema.org/valueReference'), rdflib.term.URIRef(u'http://schema.org/PropertyValue'), rdflib.term.URIRef(u'http://schema.org/StructuredValue'))
INFO:test_graphs:(rdflib.term.URIRef(u'http://schema.org/valueReference'), rdflib.term.URIRef(u'http://schema.org/QualitativeValue'), rdflib.term.URIRef(u'http://schema.org/Enumeration'))

**Comment by mfhepp** [comment]
@danbri 

1. This list of recommended types for the range is intended and not in error. Those should be the most useful ones from a Web developer's perspective.

2. Re "Are there other Enumerations and StructureValue types that are relevant, and should be listed instead of the higher types?"
I checked the list and do not see any types that should be added, unless there is a Google/Bing/Yahoo/Yandex use-case that needs respective data.
 
3. Re "Are we adding value by highlighting these 3 particular specific subtypes?"
Yes, I think so.

4. Re "Is the unit test being too picky?"
I think a warning for such logical redundancies is fine to have in the unit tests, at least until we decide upon an implement a mechanism for controlling the human-readable documentation in a more granular way.

**Comment by danbri** [comment]
Yes, I'm inclined to agree re (4.). We had some discussion about this before (I forget which issue as it was an offtopic aside). For example, http://schema.org/foodEstablishment having both Place and specific more food-oriented subtypes of place is perfectly sensible given that many other kinds of place also (without it being obvious or stated) offer food-related facilitiies. At some point we could offer schema-level annotations for particularly indicative subtypes, but for now I think a sanity check via unit tests is fine. I've also marked it as a test expected to fail.
