### ISSUE TITLE
Site HTML should be responsive to people using tiny pocket computers

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#490]
CSS needs some attention. There are still 2 copies of the same thing (#460) in the repo, and it makes no attempt to adapt to mobile-friendly layouts.

**Comment by thgh** [comment]
Here is a proposal for how schema.org could be responsive: https://schemaorg-redesign.now.sh

**Comment by dbs** [comment]
It's a good start--offline support via service workers is nice--but there a few current drawbacks:

- enumeration values are missing (e.g. from https://schemaorg-redesign.now.sh/BookFormatType)
- samples are missing
- all of the RDFa has been stripped out of the pages; compare http://linter.structured-data.org/?url=http:%2F%2Fschema.org%2FProduct vs. https://schemaorg-redesign.now.sh/Product
- at least one of the design changes affects accessibility; for example, the `.strike` class (for superseded attributes like "reviews") receives an `opacity: 0.2` attribute, which makes the text a very hard to read light-grey on white. The opacity attribute appears to not be taken into account by automated accessibility audits like Lighthouse and wave.webaim.org.
- internationalization may be made more difficult by CSS `::before` being used to prepend text ("expects") in a sentence style in responsive mode

While I support the aims of the proposal, instead of a wholesale replacement I would suggest iterating towards responsiveness (e.g. start with a `<meta viewport>`, remove the `font-size: 75%` on the body element, drop the fixed-width CSS assumptions, and move from the current table layouts to something more flexible (a liberal use of `display:block` for table elements in responsive mode works, so why not)

**Comment by RichardWallis** [comment]
Good suggestions.

There is some work in progress to address some infrastructure issues/potential enhancements with the application that supports the Schema.org site over the next few months.  Included in that will be enhancements to the UI.

~Richard

**Comment by thgh** [comment]
Thanks for checking it out! Totally agree on iterating towards responsiveness. This was just an experiment to get to know Sapper/Svelte.

My hope is that schema.org becomes responsive soon and those were my 2 cents 😃

**Comment by danbri** [comment]
Thanks again to @dbs for his changes. While there's always more we can do, I'm going to close out this issue.

BTW the site should now be a lot faster too, which ought to help for the mobile experience.
