### ISSUE TITLE
"an URL" used in docs repeatedly

### ISSUE THREAD

**Issue by connorshea** [schemaorg/schemaorg#498]
"an URL" is grammatically incorrect, as "URL" is pronounced "you-are-el". "An" should only be used when the first sound of the next word begins with a vowel sound, rather than a consonant sound.

This issue is present a few times in [schema.rdfa](https://github.com/schemaorg/schemaorg/blob/1f8ee7cd905d02bff903efd9bb0dc8c895acdcb8/data/schema.rdfa), specifically at [Line 4591](https://github.com/schemaorg/schemaorg/blob/1f8ee7cd905d02bff903efd9bb0dc8c895acdcb8/data/schema.rdfa#L4591), [Line 4563](https://github.com/schemaorg/schemaorg/blob/1f8ee7cd905d02bff903efd9bb0dc8c895acdcb8/data/schema.rdfa#L4563), and [Line 10581](https://github.com/schemaorg/schemaorg/blob/1f8ee7cd905d02bff903efd9bb0dc8c895acdcb8/data/schema.rdfa#L10581).

Sources for the grammar rule:

* [American Psychological Association Style Guide](http://blog.apastyle.org/apastyle/2012/04/using-a-or-an-with-acronyms-and-abbreviations.html)
* [Chicago Manual of Style](http://www.chicagomanualofstyle.org/qanda/data/faq/topics/Abbreviations.html?old=Abbreviations12.html)
* [English Stack Exchange](http://english.stackexchange.com/questions/1016/do-you-use-a-or-an-before-acronyms)

**Comment by chaals** [comment]
Actually a lot of people pronounce it "earl". In the absence of a Royal Academy of English Pronunciation, or a Presidential Commission, or an official by-law of the municipality of Booroondara that is recognised as authority, I think we shouldn't be overly concerned.

That said, consistency isn't inherently bad, and if we decide to "bikeshed" this issue to resolution I'd vote for "a URL" because *I* say it that way.

**Comment by danbri** [comment]
Thanks for your attention to detail, @connorshea. I agree it would be good to be consistent on this, one way or another. This explains why it's "a unicorn" not "an unicorn", which I have wondered about occasionally; I'd heard the rule was letter-based rather than sound-based. As @chaals says, English is not pronounced very consistently so I don't think we can be super strict about these things. But converging on "a URL" sounds reasonable. 

(wonder if @timbl has a view?)

**Comment by danbri** [comment]
I'm assigning this issue to @shankarnat as he's looking for easy issues while learning our tooling/workflow.

**Comment by shankarnat** [comment]
I have made changes and created a pull request to merge the change. @danbri can you please review ? Thanks!

**Comment by danbri** [comment]
Thanks :) although I don't see it inhttps://github.com/schemaorg/schemaorg/pulls yet. But I am looking via phone, will double check when back on a laptop.

**Comment by unor** [comment]
→ https://github.com/schemaorg/schemaorg/pull/500

**Comment by danbri** [comment]
Great. LGTM :)

**Comment by shankarnat** [comment]
Closing this issue now! Thanks.
