### ISSUE TITLE
MusicCompositions should have a way to specify the song lyrics

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#531]
MusicComposition has a `lyricist` property, but not a `lyrics` property. It would be nice to be able to specify the lyrics themselves.

**Comment by vholland** [comment]
See pull request #532.

**Comment by danbri** [comment]
I commented offtopic in the pull request, while meaning to comment offtopic in the issue :)

"Thanks! I was wondering if this should be attached more widely, but talked myself out of it.

If someone applies a 'lyrics' property to a thing typed only as e.g. VideoObject, some validators would probably complain. I think instead of adding 'lyrics' up at a safer generic level we should try to make the culture of schema.org validation softer. A reasonable interpretation of "x is a VideoObject and it has a lyrics property whose value is y" would be to conclude "oh, x is also probably a MusicComposition then". I don't believe its reasonable to require that every usage of "lyrics" on a VideoObject also requires the mention of a 2nd type, MusicComposition. This just adds weight for limited benefit."

**Comment by danbri** [comment]
Fixed by #532
