### ISSUE TITLE
age on date

### ISSUE THREAD

**Issue by ghost** [schemaorg/schemaorg#539]
Add an "age on date" field to indicate a person's age on a given date.

For example, I may know a person is 35 today, but that doesn't uniquely determine their birthDate, even if I use only the year.

**Comment by mfhepp** [comment]
I would not suggest adding such a property and instead rather motivate publishers of data to indicate the date of birth.

**Comment by danbri** [comment]
Role is also relevant.

**Comment by barrycarter** [comment]
@mfhepp What if the age is available but the birthDate is not? I could easily see a situation where people would voluntarily provide their age, but not their exact birth date.

I don't think there is an ISO way of representing "between 28 May 1964 and 27 May 1965" (though perhaps that would be a better approach, since you might, for example, know someone's age and birth sign or someone's age and month of birth, etc). In other words, allow Date to be a DateRange?

**Comment by mfhepp** [comment]
If I understand ISO 8601 correctly, a year <yyyy> is a valid value, so there is no problem for people to publish their year of birth only with e.g. http://schema.org/birthDate.

**Comment by barrycarter** [comment]
@mfhepp OK, I think I see what you mean. If someone is 35 today (but I have no idea whether their birthday has occurred this year or not), I could do this:

````
<div itemscope itemtype="http://schema.org/Person"> 
<time itemprop="birthDate" datetime="1979-05-28/P1Y">35</time> 
</div> 
````

Google accepts this, but I don't think it understands the "/P1Y" part (ISO8601 duration).

**Comment by mfhepp** [comment]
I would simply use

    <div itemscope itemtype="http://schema.org/Person"> 
        Age: <time itemprop="birthDate" datetime="1979">35</time> 
    </div>

This is only an approximation, of course, but so is yours, and trying to model imprecise data more precisely does not really add a lot in a largely distributed setting like the Web, with noise etc.
