### ISSUE TITLE
character should have firstAppearance (and perhaps not be of type Person)

### ISSUE THREAD

**Issue by ghost** [schemaorg/schemaorg#540]
characters aren't always people (they can be animals or fictional creatures as well), and have properties like firstAppearance that people do not.

Perhaps add these fields to Person or break off Character as a separate entity.

**Comment by thadguidry** [comment]
+1 Add new Character type
+1 Add new property firstApperance to the Character type

This is now supported in Wikidata with new property:
**first appearance** - https://www.wikidata.org/wiki/Property:P4584

@RichardWallis make this happen :) so I can see when "Gomer Pyle" made his first appearance in ["The Andy Griffith Show"](https://en.wikipedia.org/wiki/The_Andy_Griffith_Show) or when some such Character made their first appearance in the Harry Potter series.

**Comment by RichardWallis** [comment]
+1

**Comment by vholland** [comment]
If we add a Character type, we should figure out the boundaries.

Is Abraham Lincoln in _Abraham Lincoln, Vampire Killer_ a fictional character? Probably, yes

Is Dorothy Vaughan in _Hidden Figures_ a fictional character? No

What is the line between the two? I don't know.

**Comment by thadguidry** [comment]
@vholland I think in bib extension talks @dbs was for having both if I recall ?  A Character and a FictionalCharacter ?  Dan you there ?

**Comment by chaals** [comment]
There are **lots** of traps in deciding whether a character is fictional or not. I think it is better not to draw a line...

**Comment by thadguidry** [comment]
Also in Freebase, we had a nice property called "basedOn" attached to our Character Type so that you could say that Dorothy Vaughan the Character is "basedOn" another Character or a Person.

basedOn could accept a Character or a Person.

@chaals @vholland @RichardWallis I think just including the basedOn property takes care of all that mess.  It certainly did for us in Freebase.

**Comment by barrycarter** [comment]
I'm probably missing something, but I think we can determine whether a character is fictional based on whether the work is fiction or non-fiction.

This allows for cases where a work of fiction has a fictional version of a real person. In TV shows like the Monkees (and many other more recent examples), the actors play fictional versions of themselves, and there are differences between their real and fictional lives.

**Comment by RichardWallis** [comment]
Just thinking about fictional characters is lifting the corner of a much wider issue.  

Many things can be fictional:
- Oliver Twist - fictional person/character
- Camelot - fictional place
- Hogwarts Express - fictional train
- Mount Doom - fictional mountain

I raised this back in 2013 (pre Schema Github issues) - [proposing a FictionalThing Type](https://www.w3.org/wiki/WebSchemas/FictionalThing)  with properties for referencing the CreativeWork it appeared in and where relevant the real thing that it is a fictional representation of.

This was back when MTEs were not common (and JSON-LD was yet to appear so examples were in RDFa) so didn't gain much traction.   It was raised again in passing a couple of years back along with the suggestion that perhaps Character could be a new type with both Person & FictionalThing as a supertype.

This is not to underestimate the complexities of the relationships between fictional and real things  and the fact that some find the definition of Person [_A person (alive, dead, undead, or fictional)._] a little too broad.

More than happy to resurrect this proposal if it was thought it would be applicable and gain traction now. 

~Richard

**Comment by thadguidry** [comment]
@RichardWallis +1 Your take is that since many things can be Fictional or anything can be fictional, then we add a new FictionalThing Type to cover ANY Type and not just Character, and use MTEs to make that an easier way to handle that.

Would you also be willing to add **basedOn** property additionally to the FictionalThing proposal as a corollary to its fictionalRepresentationOf property ?  Do you see the value in having both or consider them the same ?

Larry the Cucumber ... https://g.co/kgs/iYScL7
fictionalRepresentationOf: a cucumber

Severus Snape ... https://www.barnesandnoble.com/blog/10-fictional-characters-based-on-real-people/
basedOn: John Nettleship

Also adding a **portrayedBy** property as well to FictionalThing so we can have lists that portrayed something ?

Dilbert ... https://en.wikipedia.org/wiki/Wally_(Dilbert)
Creator: Scott Adams
Portrayed By: Ricky Dean Logan (Dilbert's Desktop Games)
Portrayed By: Gordon Hunt (TV series)

**Comment by RichardWallis** [comment]
@thadguidry I would suggest extending the domain of [isBasedOn](http://schema.org/isBasedOn) to include ```FictionalThing``` instead of creating ```basedOn```.   Extending the range to ```Thing``` may be then be also beneficial.

Not so convinced by ```potrayedBy```.   The inverse ```Person->portrayed``` seems more logical to me.

**Comment by thadguidry** [comment]
@RichardWallis Sure, your choice. Just poking holes and giving use cases which helps everyone here understand implications.

**Comment by vholland** [comment]
Do we have a real use case with data we want to explore? Because as @chaals said, there are a lot of traps here.

- Is the London in _Mary Poppins_ the real London or a fictional London?
- Is the Richard Nixon in _Forrest Gump_ the real Nixon?
- What about John Malkovich in _Being John Malkovich_?
- Would Dorothy Vaughan in _Hidden Figures_, the non-fiction book, be a real person, but suddenly fictional in the movie?

```portrayedBy``` is ```actor``` with a ```Role``` under a different name, so I don't think it solves this problem.

**Comment by barrycarter** [comment]
I'm not sure it qualifies as a "use case" (though it may've been the reason I brought the whole thing up in the first place), but I'm annotating Pearls Before Swine comic strips (https://github.com/barrycarter/bcapps/blob/master/METAWIKI/pbs.txt and other files in that directory). 
 
I'm currently using my own tags, but it would be nice to get some standardization if other people do this with other comic strips, TV shows, and other works of fiction.
