### ISSUE TITLE
A new Interface Design for website

### ISSUE THREAD

**Issue by midorikocak** [schemaorg/schemaorg#547]
My proposal is to create a new interface for the website. Current one is not motivating and looks very generic. Also schemas and their relations makes a person anxious.

A more inspiring and efficient design has to be created. I can prepare one. Just let me if there are some other people who are working on this.

**Comment by mfhepp** [comment]
Thanks for the suggestion! I would prefer an incremental approach rather than radical redesign, mostly focusing on adding useful functionality for developers (e.g. examples, links to discussions, etc.). I agree that in terms of fonts, colors, proportions etc., slight changes could greatly enhance the visual appeal.

Also we should keep in mind that this is a standard specification page, which does not need the same level of visual appeal as e.g. a commercial Web page.

Plus, since schema.org is already conceptually a complex site, the rendering components should be as lightweight, transparent, and accessible for as many people and types of devices as possible.

So to put this forward, you could craft a set of small changes that would improve the overall harmony and consistency of the rendering.

**Comment by danbri** [comment]
@mtkocak thanks for the kind offer! Before you spend any time on this, let us have some discussion within the project on whether we're ready. Currently a lot of our HTML generation is very entangled with the Python code that produces it, constraining our options.

One thing is clear, ... it would be good to give some attention to making the site more usefully browsable on the Mobile Web.

**Comment by chaals** [comment]
+1 to making it mobile-friendly.

+1 to making changes incremental - N steps over 3N months, moving us to a design that is nicer while not surprising people who already use the site might be a useful approach. Or the changes might be simple enough that we say "sure, looks nice, nothing got lost, let's do it…"

**Comment by mtkocak** [comment]
Happy to hear from you. Here are some ideas.

I consider schema.org project as the future and very important for information architecture, information hierarchy and information design. Currently information hierarchy and other concepts or design are sadly problematic.

Some brainstorming gets me to:

- A visually appealing approach to encourage people to pay attention on it
- Non tech people has to pay attention and learn information organizing standards
- Using icons for schemas or piktograms. I consider schemas like the universal language of information. Think about olymics where piktograms and icons are champion because of being common language of humanity.
- Instead of having a scary list at schema opening page, a more human landing page for schema could be designed. What is the schema, why is it important, how can be combined with other schemas? What are benefits using it? The list can be on the same page but like a technical tab etc. 
- Examples are very very important, currently most of them are missing. 
- A very good layout for better reading experience. Long lines of text is very hard to read.

Do you have any examples that you want that I have to pay attention. I will make this as a proposal project at my behance account. So even nobody wants a new design I will do it because I am passionate about organization of information.

Also I have some questions:

1. Why people comes to the site?
2. Do you have some analytics data like age range, gender, browsers? Mobile or desktop users?
3. What would you like to have in the website? (Responsive design for devices is not an option is a must today)
4. Do you think a design must feel like personal or universal? I consider universal approach but without boring newcomers...

That's all for now.

**Comment by mtkocak** [comment]
Please check https://github.com/cakephp/cakephp/issues/6679

**Comment by Kenneth-t** [comment]
Well said @mtkocak. The website should clearly communicate the added value of actually using the semantic framework and give some more guidance on how to implement it. Tutorials, examples,... In general, it needs to be task driven, not just a repository.

**Comment by westurner** [comment]
- :+1: to mobile-friendly ("responsive")
  - responsive tables
- readability
  - larger font-size
  - larger line-height
  - https://en.wikipedia.org/wiki/CSS_frameworks
    - https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)
    -

**Comment by JimSaiya** [comment]
Is this done, or is this a 'to-do'?

Jim Saiya
Web Developer / Information Architect
✉ jsaiya@formatdata.com
[in] www.linkedin.com/in/jimsaiya

On Fri, 22 Apr 2016 14:46:11 -0700, Wes Turner  wrote:

   *  to mobile-friendly ("responsive")

   * responsive tables

   * readability

   * larger font-size
   * larger line-height
   * https://en.wikipedia.org/wiki/CSS_frameworks - 
https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)

—
You are receiving this because you are subscribed to this thread. 
Reply to this email directly or view it on GitHub

   *

**Comment by danbri** [comment]
@JimSaiya at this point I think we're just having a discussion.

I should also point out that schema.org is rather boring by design, unfortunately. Since the beginning we have by design drawn quite a strong line between the shared vocabulary + its use. In particular the 4 search engines do not collaborate on products or on their product documentation, so a lot of the more concrete incentives for markup use are documented elsewhere in the Web. We have recently revisited the idea of linking out to those details more specifically (see #652) and I think that is viable.

My sense is that we would do best right now to focus on small incremental improvements for the site, in particular for mobile.

**Comment by JimSaiya** [comment]
@danbri I was specifically referring to the comment by @westurner, which I was looking at in my email.  Guess I should have visited the actual GitHub issue before asking!  XD

And yes, incremental improvements would be the most practical approach, especially considering the Python-based generator.

This is easy for me to say, but if someone (ahem, @midorikocak) would like to build a prototype of what the site *could* look like, it could act as a target for the incremental changes to move toward.  Not to mention, it would be something concrete for the Steering Group to use for discussion.

**Comment by westurner** [comment]
- RDFJS is the new hotness.
  - https://github.com/rdfjs/representation-task-force/wiki/Use-Cases
  - https://github.com/rdfjs/representation-task-force/wiki/Existing-triple-and-quad-representations#comparison
  - https://github.com/rdfjs/rdfjs.github.io/wiki/Projects

**Comment by danbri** [comment]
@midorikocak  - thank you for your kind offer, but given the various constraints (technical and other) around the project I don't think it would work well to take on a substantial redesign at this time. So I will close out this issue, but we can follow up with specific issues for things like accessibility (#718) and mobile (#490).
