### ISSUE TITLE
[Organization] Privacy and T&C Markup

### ISSUE THREAD

**Issue by Lloyd1978** [schemaorg/schemaorg#566]
Hi everyone,
looking through the Schema.org docs I don't see anything to mark up Privacy Policy and Terms & Conditions.
I was thinking something like...

itemprop="privacyPolicy"
itemprop="termsAndConditions"

Within the Organization scope, to mark up the urls.
Anyway, just a thought.
Kind regards

Lloyd

**Comment by nueckman** [comment]
Organization might be the wrong resource for this kind of information as they are often bound to specific applications.

**Comment by danbri** [comment]
Thanks for the suggestion! Filing under 'vocabulary' possibilities.

**Comment by akuckartz** [comment]
@danbri Did you intend to close this issue while assigning it to the famous "The distant, hazy future (or possibly never)" milestone?

**Comment by danbri** [comment]
I did. I don't think every idea that comes through needs to remain 'open'; either way they're in the system. Sorry if this seems brutal but since we wired up a link to Github from the 'more info...' section in each schema.org page it is raining new issues here. In this particular case I would anticipate that it would be relatively unlikely we'll do something soon, due to the social/legal/geo etc complexities associated with machine readable descriptions of privacies and other terms.
