### ISSUE TITLE
Proposal for hasFormat property

### ISSUE THREAD

**Issue by csarven** [schemaorg/schemaorg#581]
Proposal for `schema:hasFormat` (and possibly its inverse `schema:isFormatOf`) property:

It can be along the lines of `dcterms:source` "A related resource that is substantially the same as the pre-existing described resource, but in another format."

That is, the resource (range) as URL to the other representations, e.g., Turtle, PDF, OGG (?)

hasFormat can be a super of properties like `schema:musicReleaseFormat`.

**Comment by mfhepp** [comment]
We already have http://schema.org/encodingFormat - is there anything that cannot be covered by this.

As for inverse properties, the general consensus is to not add them to the vocabulary, since most syntaxes have direct support for this and even for Microdata, there is an itemprop-reverse mechanism available.

With http://schema.org/associatedMedia you can point from one entity to multiple MediaObjects that may have different values for http://schema.org/encodingFormat.

Unless there is a clear scenario in which these existing properties don't do the trick, I suggest to close the issue.

**Comment by csarven** [comment]
`schema:associatedMedia` / `schema:encoding` appears to cover this issue. Thanks for the pointer!
