### ISSUE TITLE
Dataset includedDatacatalog Datacatalog

### ISSUE THREAD

**Issue by agbeltran** [schemaorg/schemaorg#583]
In the [Dataset](http://schema.org/Dataset) class, the property/value pair 

```includedDataCatalog DataCatalog``` 	
is described as "A data catalog contained in the dataset".

Shouldn't it be "A data catalog containing the dataset."?

Thanks

**Comment by danbri** [comment]
Thanks - it does sound like we have an issue here. @vholland - was the renaming of 'catalog' to 'includedDataCatalog' perhaps too hasty? 


Looking at an earlier snapshot from https://raw.githubusercontent.com/schemaorg/schemaorg/bf6df9d3fe7bd96a72b1d929dc6a05d8f1d3e151/data/schema.rdfa we had 

    <div typeof="rdf:Property" resource="http://schema.org/catalog">
      <span class="h" property="rdfs:label">catalog</span>
      <span property="rdfs:comment">A data catalog which contains a dataset.</span>
      <span>Domain: <a property="http://schema.org/domainIncludes" href="http://schema.org/Dataset">Dataset</a></span>
      <span>Range: <a property="http://schema.org/rangeIncludes" href="http://schema.org/DataCatalog">DataCatalog</a></span>
     </div>

**Comment by vholland** [comment]
It looks like an unfortunate typo. It should have been include**s**DataCatalog instead of include**d**DataCatalog.

**Comment by agbeltran** [comment]
Thanks - but the meaning is that the dataset is included in the data catalog, right? And not the other way around as the textual explanation implies.

**Comment by vholland** [comment]
Oh, wait. You are right. The original description was correct, so a better name would be `includedInDataCatalog` or the like.

**Comment by danbri** [comment]
i.e. the associated DataCatalog is the container, yes. So neither includesDataCatalog nor includedDataCatalog are good names.

We should probably change the name (again). Since this is all based on W3C DCAT, let's check back there. We have different constraints so we can't use their exact names but worth a look.

In http://www.w3.org/TR/vocab-dcat/#class-catalog I see the 'dataset' link seems to go from the Catalog to the Dataset. In our most recent terminology that would be 'includedDataset' or 'includesDataset'. Whether and how we name the other direction would be up for grabs. 

At this point I'm inclined towards just using the existing isPartOf / hasPart rather than struggle to find dataset-oriented synonyms.

**Comment by vholland** [comment]
@danbri That works for me to. This property existed before isPartOf was added.

Looking at the usage, DataCatalog's `dataset` property is used far more often, which makes sense; people describe the catalog from the top down.

**Comment by danbri** [comment]
Ah, I had forgotten that the relationship was named in both ways.

I believe then we'd need to just do this:

* declare http://schema.org/dataset subpropertyof hasPart, i.e. that the catalog has a part which is the dataset.
* mark includedDataCatalog as obsolete/archaic/deprecated
* update or add an example that shows isPartOf being used to nest a description of a DataCatalog within a Dataset description.

How does that sound? 

@agbeltran would you happen to have an example in mind that could be contributed here?

**Comment by danbri** [comment]
In the steering group call today (#588) we agreed to proceed along the lines I sketched above. More real world examples would definitely still be welcomed...

**Comment by agbeltran** [comment]
The solution sounds great, thanks. For the dataset specific inverse property (subpropertyof isPartOf), if useful to include, it seems that the label should be dataCatalog.
If you point me to other examples and how they are documented, I will see if I can provide some for this property.
Thanks

**Comment by danbri** [comment]
Thanks. Looking more closely I'm embarrassed that we have no examples currently for Dataset. There are some examples at https://www.w3.org/wiki/WebSchemas/Datasets#Example which should also have been incorporated (but haven't yet).

https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/sdo-map-examples.txt is an example of the specific format we use (including the bogus stuff at the bottom due to quirks in our parser).

**Comment by agbeltran** [comment]
Hi @danbri, I see this issue is still open. Is this the same as what was fixed in #1066? Thanks

**Comment by danbri** [comment]
Yes - apologies for the duplicate issue. We went with includedInDataCatalog. Reviewing the discussion here it seems the only aspect not addressed yet was declaring superproperties to hasPart / isPartOf. I'll close this issue now as http://schema.org/docs/releases.html#g1066 addresses the basic concern.

**Comment by agbeltran** [comment]
ok, thank you!
