### ISSUE TITLE
BUG,RLS: Output sequence in schema_org_rdfa.html

### ISSUE THREAD

**Issue by westurner** [schemaorg/schemaorg#606]
http://schema.org/docs/schema_org_rdfa.html is not in the same sequence as (or maybe should now point to /latest/ or /current/ or /2.0/?):

* https://github.com/schemaorg/schemaorg/blob/sdo-ganymede/data/releases/2.0/schema.rdfa
* 

RDFLib collections.OrderedDicts? (There's a CPython OrderedDict slated for Python 3.5)

**Comment by westurner** [comment]
see #608

**Comment by danbri** [comment]
schema_org_rdfa is the ugly internals, and has an order based on organic history of the project. The releases should be navigable by a-z and other more useful paths. I don't see this mismatch being a huge problem since schema_org_rdfa is for a much smaller audience. The versioned releases are also for a relatively small audience - most people want the live site...

**Comment by mfhepp** [comment]
I would strongly prefer to NOT reorganize the whole file, because it will otherwise be very hard to track changes over time (we would have one big delete / insert). 

At some point in the future, we may want to improve our tooling for evolving the spec, but as Dan said, the number of people actually working on this file is very small, so it is not a priority.


Martin

**Comment by danbri** [comment]
Thanks for the suggestion @westurner, but as discussed above the docs have different roles, audiences and history so we'll keep things as-is for now. If we every migrate to use JSON-LD instead of RDFa for the raw schema files we could revisit the order of things then.

**Comment by westurner** [comment]
So, to followup here, what is the link to the ordered schema resource?
