### ISSUE TITLE
Overhaul of  Place>CivicStructure necessary!

### ISSUE THREAD

**Issue by sascha-hendel** [schemaorg/schemaorg#621]
Hi, I am maintaining a Architecture database (www.archinform.net) and try to include schema.org.
In schema.org buildings are a subset of PLACE, but they are indeed a part of CREATIVE WORK, too. Every building have one or more creators, a date of creation, etc...
The schema.org types for any kind of built structures should be extended to allow to include this information.

Best regards,
Sascha Hendel

**Comment by mfhepp** [comment]
Have you tried to use a multi-typed entity (MTE)? By saying that your object is a place and a creative work, you should be able to apply properties of both types to the building.

If that does not work (tool support for MTEs may vary across search engines and validators), you can always use http://schema.org/additionalProperty to attach the missing properties that you feel are important for your data.

I close this issue because the possible tasks is to verify the MTE support in validation tools and not to extend schema.org. Feel free to reopen it if you want.

**Comment by sascha-hendel** [comment]
Hi mfhepp,
thanks for the immediate answer. I already know the way to describe special things with multi-typed entities (MTE), but I think, that buildings are such a broad and general case, that it will be better to extend schema.org. It is important for a wide audience, which are the persons and firms related to structures, when the structures are built, etc...

**Comment by mfhepp** [comment]
The thing is that types like schema:Product and schema:CreativeWork are roles that many types of objects may have. schema:Place is a very generic concept that is used for representing restaurants, bus stops, mountain tops, campsites, etc. While I see your point that in some cases meta-data about the creative process of constructing them is relevant, I do not think this is the majority case.

Thus, I would not make schema:Place a subtype of schema:CreativeWork. It would simply inherit too many properties that are irrelevant in most cases.

Even the current list of subtypes is already too large for my taste. MTEs will perfectly cover your use case and our general direction for types that define properties of a *role* should be to use them in combination with other types rather than subtyping everything.

The underlying question is whether we want multiple types at the vocabulary level or at the instance level. The instance level will allow us keeping schema.org much cleaner and leaner.

Otherwise, we will have many "Volcanoes have fax numbers" problems ;-)

**Comment by sascha-hendel** [comment]
OK, I understand, that the MTE concept provides a much cleaner and flexible way to describe the world than a strict tree hierarchy. But the actual schema.org ontology doesn't reflect this :(
For CREATIVE WORK there already existing several explicit subtypes, but not any type from the architectural sector. And Architecture is called the mother of the Arts!
So I really like to see a subcategory CreativeWork/Architecture with specific "creative" properties like planner, style, dates (planning/realization), etc. The "geographic" properties should stay in the Place/CivicStructure category. Than it should be possible with MTE (Place/Civic/Structure combined with CreativeWork/Architecture) to define all properties.

**Comment by mfhepp** [comment]
Ok, I see your point. What we need to carry this further is a definite proposal of properties that this new type should have. Ideally not more than ten. It would also help to know how many Web sites might provide such data.

Always keep in mind that for relatively few data sources, or of there is a widely accepted single truth, adding the data to Wikidata or Wikipedia might be a better way of getting the facts into search engines. Schema.org is most useful when information is provided by a large number of sites with little overlap, i.e. when you must collate data from many sites to get a sufficient coverage.

I reopen the issue but assume it is not a priority issue.

**Comment by sascha-hendel** [comment]
I gonna think about the necessary properties and will post them here soon. Hopefully, this will help  to include the extension to one of the next milestones.
