### ISSUE TITLE
Schema.org site markup has accessibility issues that need fixing

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#718]
1) full.html lists

The giant hierarchy of nested lists in http://schema.org/docs/full.html (where list items contain sub-lists) is poorly presented in (some? all?) screen readers. Reported by @LjWatson:

> The trouble with the full schema hierarchy is that screen readers don’t have an efficient means of 
> navigating through complex nested lists. Specifically, they have no way of moving from one li in a 
>  parent list to the next, without traversing all the child/grand-child/great-grand-child lists (and all their li) > in between.
> 
> The full schema hierarchy has lists nested up to five deep. So for example, to get from Action to
> CreativeWork, means navigating down through multiple nested lists – which collectively contain over 
> 100 individual list items. That’s a lot of key presses!   It would be good if the hierarchy could be made 
> interactive perhaps – so the branches could be expanded/collapsed. An example of the kind of thing 
> I’m thinking of is: http://hanshillen.github.io/jqtest/#goto_tree

2) tables in per-term pages

"Unhappy that the "tab-panel" on http://Schema.org  isn't accessible :( https://schema.org/Product  because no hrefs on the anchors. sadpanda", reported in https://twitter.com/stommepoes/status/625928819619307520

3.) selection CSS issue - see https://github.com/schemaorg/schemaorg/issues/1381

/cc @RichardWallis

**Comment by danbri** [comment]
Nearby: https://github.com/schemaorg/schemaorg/issues/177 (this will let us compose URLs that point to specific examples, and then per-format versions of examples).

**Comment by LjWatson** [comment]
For the tabs, there is a whole lot that could be done to improve accessibility for keyboard users and screen reader users. The basic design pattern goes something like this:

```<ul role="tablist" class="selectors">
<li role="presentation">
<a href="#html-panel" id="html-tab" role="tab" aria-selected="true" aria-controls="html-panel">Without markup</a>
</li>

<li role="presentation">
<a href="#microdata-panel" id="microdata-tab" aria-selected="false" aria-controls="microdata-panel" tabindex="-1">Microdata</a>
</li>

...
</ul>

<div id="html-panel" role="tabpanel" aria-hidden="false" aria-labelledby="html-tab"><pre>...</pre></div>
<div id="microdata-panel" role="tabpanel" aria-hidden="true" aria-labelledby="microdata-tab"><pre>...</pre></div>```

The basic overview of what's going on is...

The tablist, tab and tabpanel roles provide semantics for screen readers. There is no native HTML to represent a set of tabs, so screen readers need this information to correctly interpret the visual metaphor.

Elements with the tab role must be children of the element with the tablist role. The presentation role on the ```<li>``` removes the list item from the semantic equation, whilst leaving behind plain HTML as a fallback.

The collection of tabs should represent a single tab stop (for people navigating content using the tab key). The ```<a>``` element is focusable by default, so setting tabindex="-1" on all but the currently selected tab will remove the rest from the tab order.

The aria-selected attribute should be set to "true" on the currently selected tab, and to "false" on the rest. This indicates to screen reader users which tab is currently selected.

The aria-controls attribute establishes a relationship between the tab and the tabpanel (where no relationship is evident in the DOM). This tells screen readers which chunk of content is controlled by the tab.

The href on the ```<a>``` points to the corresponding element with the tabpanel role. This makes sure the tab can be interacted with using a keyboard (irrespective of whether a screen reader is enabled or not). It's also good fallback in the event that JavaScript is not available.

The aria-hidden attribute (when set to "true") removes the content from the browser's accessibility tree (hiding it from screen readers). Set this to "false" for the currently selected tab, and to "true" for the rest. This should be associated with the visual display of the content.

The aria-labelledby attribute associates the tabpanel with its corresponding tab. It provides an accessible name for the tabpanel, so screen reader users know that the panel content relates to the tab they just selected.

Keyboard interaction... When focus is on one of the tabs in the tablist, the right/up keys should move focus to the next tab. The left/down keys should move focus to the previous tab. It should be possible to move continuously through the tabs in a single direction, with focus looping around from one end of the collection to the other.

A tab may be selected (and the corresponding tabpanel displayed) when focus is moved to the tab. Alternatively it may be selected using the enter key. FWIW I prefer it to be selected on focus, but it's entirely subjective.

This jQuery UI example is essentially the right idea (although I wouldn't use the aria-expanded attribute as they have):
https://jqueryui.com/tabs/

**Comment by StommePoes** [comment]
@LjWatson I'm sorry but there's one thing that causes a lot of headache here...
quote "Keyboard interaction... When focus is on one of the tabs in the tablist, the right/up keys should move focus to the next tab. "
When I'm using keyboard, I need my up and down arrows to be able to scroll the page up and down when reading a long panel.  This has prevented me from reading whole panels before as they go offscreen and to scroll down I have to first get out of the whole panel group, get my focus back on the page somewhere, and then shift-tab back and try again. (and yeah it was a site using a jQuery version, not sure how new/old it was)

Can't we at least only highjack the left and right arrows??

**Comment by LjWatson** [comment]
@StommePoes 
Implementing left/right key support alone would work I should think.

**Comment by RichardWallis** [comment]
Applied accessibility enhancements to tabs for examples on term pages and the full listing page in a develop version for comment:
* http://sdo-access.appspot.com/Book#examples
* http://sdo-access.appspot.com/docs/full.html

If comments are positive would duplicate full listing enhancements on to the version specific full release pages (eg. http://schema.org/version/2.1/)

/cc @chaals @LjWatson

**Comment by StommePoes** [comment]
In Book#examples, when I'm here (http://stommepoes.nl/work/examples_screenshot.jpg alt="screenshot of the page where my focus is on the first panelgroup and the panel goes offscreen"), if in Firefox I turn on caret navigation I could move my cursor in there but otherwise, I can't read the rest of a selected panel; tabbing out of the panel so I can do some scrolling in this case won't work because I end up in another tab-panel, so my up-arrow gets eaten there too. 
I can't say for certain that only listening for left-right keys (for panel selection) is the right solution, it could be that there is another, obvious method of moving my scroll down, but right now I have to reach for a mouse in most browsers (and yay I have a mouse, but if I didn't?). So while I want to recommend letting me scroll down the page with arrow keys, I worry that that's really me not being aware of some other method (and I don't mean pageDown/Up, those go too far). I'll see if I can get someone else to have a look.

Also the role presentation on the anchor itself... might make problems, presentation says to AT "ignore whatever role this element ever had" and personally I'd go with @LjWatson's where the list items get role-presentation (so that we don't have "list-items" anymore) and use the tab role on the anchors. 

Very awesome that these are added with JS, it's totally usable without, love it.

Honestly as a lazy developer I'm often going to Schema pages I've already been to just to jump to the examples... possibility of adding a skip link? You can hide them from mousers and everyone else by setting them offscreen and letting them show on :focus, which only keyboarders will ever do.

**Comment by danbri** [comment]
Hmm - I just tried browsing (current and this new one) with JS turned off, and I can't click on the tabs to see the examples, e.g. in http://sdo-phobos.appspot.com/Event - is there some wholesome modern way it can be made to work for JS-free browsing too?

**Comment by StommePoes** [comment]
The Event page has "anchors" but because they're missing hrefs, they are in most browsers not even focsuable, therefore not usable. I guess if you really wanted to avoid hrefs, they'd have to be made into &lt;button&gt;s. But...

The Book#examples link above however has the base (pre-JS) markup with the anchors acting like in-page skip links -- that is, they have href's pointing to the id's of their own "panel". They are focusable and clickable and can visually move the screen and in-browser move the keyboard on-page focus to the correct example. My only issue currently with the no-js version of Book#examples is that the rendered basic font size is calculated to 9px. 
Someone on the team has seriously good eyes it seems! : P

**Comment by LjWatson** [comment]
@Danbri

If you use the design pattern I mentioned before, you'll have the underlying HTML structure you need for a JS-free experience.

If JS isn't available you'll need to make all of the tab panels visible - so the anchors (tabs) act as shortcuts to each of them on the page.

**Comment by danbri** [comment]
Thanks @LjWatson ! @RichardWallis has been investigating. Care to try that, Richard?

**Comment by RichardWallis** [comment]
Will do - My updated tabs version was an out-of-the-box solution from JQuery which with the dependency on JS, and the scrolling issues identified by @StommePoes, has given us a 'different but no better' answer. 

I will revisit this, having rebased the code against the imminent 2.2 release.

Meanwhile, any more comments regarding the tree implementation on http://sdo-access.appspot.com/docs/full.html?  

~Richard.
/cc @danbri, @LjWatson
