### ISSUE TITLE
vehicleModelDate

### ISSUE THREAD

**Issue by Adamich** [schemaorg/schemaorg#721]
Please consider changing to vehicleModelYear
evidence:
http://www.nhtsa.gov/webapi/Default.aspx?Recalls/API/83
http://www.mmucctraining.us/Element/V6

**Comment by alien-mcl** [comment]
I'm somehow confused with overlapping description for vehicleModelDate and modelDate. If both are describing same, one should be dropped, I though that one of these would describe the manufacturing date, but there is also productionDate.

As for using year only - indeed models are bound to the year usually. I cannot recall any situation when a model was released twice same year as this would the only situation to leave date instead of year.

Still there might be no harm in having a range that allows complete date - someone might want to provide a complete release date.
