### ISSUE TITLE
Payload vs. Gross Vehicle Weight Rating

### ISSUE THREAD

**Issue by Adamich** [schemaorg/schemaorg#722]
Please consider http://auto.schema.org/payload to include subclass tongueWeight and trailerWeight.  Also, where can Gross Vehicle Weight Rating - GVWR - be incorporated or substituted?  
evidence - https://en.wikipedia.org/wiki/Gross_vehicle_weight_rating ; http://www.onlinetowingguide.com/guidelines/gvwr.html

**Comment by alien-mcl** [comment]
As for the GVWR - it seems that the payload description mentions that total weight can be provided with weight and payload mixture. I believe having GVWR as a separate property might give some benefits for vans/trucks rather than for cars as usually limits of the allowed GVWR are much above of the cars weight.

As for the tongueWeight and trailerWeight - I don't think it is correct to have those two as a subproperty (I believe you had that in mind rather than subclass) of the payload - payload is a weight of the cargo/persons without a weight of the vehicle, while the other attributes inclide weight of the trailer/tongue. This could cause a logical mismatch.
