### ISSUE TITLE
modelDate

### ISSUE THREAD

**Issue by Adamich** [schemaorg/schemaorg#723]
Please consider changing to modelYear
Additionally, please refer to #721 for similar proposal.
Another historical layer for discussion - https://groups.google.com/forum/#!topic/freebase-discuss/xy08q_9A8ng

**Comment by danbri** [comment]
Thanks. This is for http://auto.schema.org/modelDate /cc @mfhepp

**Comment by mfhepp** [comment]
Since a [Date](https://auto.schema.org/Date) is in ISO8601 format, it can be be just a year without a month or day, so YYYY is perfectly fine.

See e.g. https://en.wikipedia.org/wiki/ISO_8601#Years

An their are cases where being able to specify a model date, e.g. if there are multiple releases per one calendar year. Maybe rare in automotive, but likely useful when re-using this property for other types of goods.
