### ISSUE TITLE
schema.org/Distillery ?

### ISSUE THREAD

**Issue by radusi** [schemaorg/schemaorg#743]
would adding //schema.org/Distillery be acceptable, since neither Winery nor Brewery does not correctly describe a production place for a Bourbon / Scotch ?

Thing > Place > LocalBusiness > FoodEstablishment > Distillery 
Thing > Organization > LocalBusiness > FoodEstablishment > Distillery

**Comment by danbri** [comment]
Seems useful but perhaps low priority? I'm not entirely convinced it is good to add this to the core - there are probably many more kinds of food establishment -related places that we don't include. In particular we should look into places that are more typically visited, as more urgent than a production-oriented place. Perhaps there is a markup model we can find that allows us to pass off such things to Wikipedia? 

Specifically Wikidata has https://www.wikidata.org/wiki/Q1251750 for distillery ...

**Comment by RichardWallis** [comment]
I traded off ease of application against 'part of a bigger concern' against
who might then own it and in this case the first of those won.

Liking the idea of finding a generic way that we can hand off such things,
that don't need to introduce new properties, to WikiData.

**Comment by jvandriel** [comment]
The way I see it we have 2 options: 

*Option A - use ```schema.org/additionalType``` + Productontology*
```
<div itemscope itemtype="http://schema.org/LocalBusiness">
	<link itemprop="additionalType" href="http://www.productontology.org/doc/Distillation" />
	<h1 itemprop="name">Acme Alcohol Inc.</h1>
</div>
```

*Option B - use ```schema.org/sameAs``` + Wikidata*
```
<div itemscope itemtype="http://schema.org/LocalBusiness">
	<link itemprop="sameAs" href="http://www.wikidata.org/entity/Q1251750" />
	<h1 itemprop="name">Acme Alcohol Inc.</h1>
</div>
```

Personally I like the idea of using ```schema.org/aditionalType``` + Productontology very much because it allows one to turn a generic into a specific type..

I feel te downside of using ```schema.org/sameAs``` is that one ends up _comparing_ a generic type with a more specific type.

But he, that's just my personal preference. How do you feel about this @RichardWallis and @danbri?

cc: @mfhepp

**Comment by mfhepp** [comment]
Yes, I also think we should use www.productontology.org, which is also semantically fine (note that the notion of "product" is very broad in schema.org and GoodRelations, and that Place is not disjoint with Product (which also makes sense, since you can very well offer a place for sale or rental).

**Comment by RichardWallis** [comment]
I think that the schema.org/aditionalType option would be a good pragmatic
solution and www.productontology.org as an excellent example to point at.

Wondering though if there should not be a more generic, not so product
focused, solution to sit in front of WikiData - www.thingontology.org ?

Agree with Martin about the technical broadness of 'product', it is more
about perception, and the inevitable questions around is a distillery
really a product.  Maybe that should be part of a wider discussion about
representing things with physical characteristics  [often associated with
Product - color, weight, etc.] that are not  products such as fossils,
rocks, museum exhibits, etc.

~Richard

**Comment by jvandriel** [comment]
_"Wondering though if there should not be a more generic, not so product
focused, solution to sit in front of WikiData - www.thingontology.org ?"_

For quite some time I was using ```schema.org/addtionalType``` for referring to  Wikidata and DBpedia, thinking since those have types I can refer to this way. That is, until @mfhepp and @thadguidry pointed out to me that in most cases this isn't the right thing to do.

Since then I've read some documents published by @mfhepp and what I got out of that is that things go wrong when resolving the semantics (sorry if can't fully explain better, that's the most I could make of it. It's a bit out of my league). 

What I want to explain with this is that for folks like me, who don't know all technical rules by heart, using ```schema.org/additionalType``` + eg, Wikidata seems a very logical solution because:

```schema.org type (machine readable data) > additionalType > Wikidata (machine readable data)```

is how deep most think about it. Now I'm happy to have learned from others that my thinking was wrong, but I wonder if there's anything that can be done so that one can use ```schema.org/additionalType``` (or @id or @typeof) for referring to a second type at locations like Wikidata, DBpedia and Productontology?

Because coming up with a new system or even using my example [a] still forces webmasters to know and think about whether they should use ```schema.org/sameAs``` or ```schema.org/additionalType``` depending on the external enumeration they want to refer to.

IMHO it would help greatly if we could simplify this for the average webmaster so they'd only have to think about whether they're referring to a machine readable enumeration (productontology, wikidata, etc) or a plain webpage (wikipedia, or any other page on the web).

Now I have no idea whether it's even remotely possible or not but looking at this from my POV it'd be great if we could simplify this by using ```schema.org/additionalType``` (@id, @resource) to point to machine readable 'types'  and ```schema.org/sameAs``` for pointing to things like social media, Wikipedia, Github, etc, etc.

**Comment by mfhepp** [comment]
FYI: I want to release a broader variant of www.productontology.org that takes away the "product" notion but essentially does the same thing - providing classes for each and every Wikipedia lemma.

I would suggest that, for the moment, let's use www.productontology.org URIs as the default.

Will keep you posted about the new service when available, but it will take a while.

**Comment by RichardWallis** [comment]
Looking forward to the broader variant of www.productontology.org  and
maybe using it as the basis for answering @jvandriel 's proposals.

**Comment by thadguidry** [comment]
Wikidata does NOT have Types or Classes, their model is a bit different.

What they have are properties and statements....tons....that then .  So
when you want to basically find a Class or Type or Equivalent Type or
Freebase kinda Type.... you have to look at properties.

There are a few properties that make finding Types or Classes a bit easier
on Wikidata (you can ask the Wikidat's themselves btw)
or
find topics that have Statements with one of these properties:

https://www.wikidata.org/wiki/Property:P1709

https://www.wikidata.org/wiki/Property:P279

https://www.wikidata.org/wiki/Property:P1963

And this tool uses the first 2 above to visualize and navigate the
pseudo-imposed Types/Classes :
https://www.wikidata.org/wiki/Property:P1963

Btw, the subclass statements P279 that are thrown around are really
subjective on some topics, so just know that not everyone is a Librarian or
Ontologist or even an SEO expert. :)  (example: Human is a subclass of
Person... https://www.wikidata.org/wiki/Q5  uh, no and yes, but...there is
probably a better way to express it...and I'm a realist anyways)

Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by danbri** [comment]
I have added Distillery as a "pending" proposal in the new pending extension, see http://pending.webschemas.org/Distillery

I still believe (see https://github.com/schemaorg/schemaorg/issues/280 for more) that integrating with Wikidata to bring in a bulk of longer-tail vocabulary as an external extension is the way to go. But the Pending mechanism gives us a way to record sensible proposals like Distillery in a way that can be used and reviewed, while we work out the longer term details. Similarly I have just added http://pending.webschemas.org/WorkersUnion which was nearly agreed back in 2013...

**Comment by danbri** [comment]
@thadguidry is correct btw that Wikidata doesn't have quite our notion of class. Or rather it is a second class citizen, a bit like the way Twitter for a long time didn't have much infrastructure around user-created conventions like @-mentioning people or #-tagging topics. But in practice it has something rather like types, with supertyping and instantiation, and it shares with us a pretty loose pattern for association types and properties. I think it is close enough that communication is possible :)

**Comment by thadguidry** [comment]
@danbri A few points on Distillery.

- Looks like we'll also need to add an "owner" property, in distillery terms and within some laws of some countries this is called a "proprietor".  This leads to the old Ownership property conundrum that some folks around the internet have voiced concern over in Schema.org in the past...which leads to a comment for Martin and a side discussion below.

-  You'll also want to be more clear on the definition and determine if it is inclusive of a "distilled spirits plant" which is what a distillery is called under USA Code of Federal Regulations http://www.ecfr.gov/cgi-bin/text-idx?SID=e3b4dd0310e0d8d38b225edfff8efc48&node=27:1.0.1.1.15&rgn=div5#27:1.0.1.1.15.1.155.1
-  You will also want to determine and state if a http://pending.webschemas.org/Distillery is inclusive of a "distilled spirits plant that makes fuel rather than beverages". Which is also within laws of some countries such as the USA and what can also be called a "distillery".

@mfhepp The intangible https://schema.org/OwnershipInfo has a way to provide ownership for lots of Things in Schema.org, but it looks like it can only be applied against Products ?  I'd like to see the domain expand to also include businesses and organizations.  A definition such as "A structured value providing information about when a certain organization or person owned a certain product, business, or organization".  An issue needs to be opened against it to discuss this need further. 



For anyone else wanting to participate in the long-tail discussion of the  http://pending.webschemas.org/Distillery , a good primer for the industry in the USA is located here: https://www.ttb.gov/spirits/index.shtml

**Comment by thadguidry** [comment]
@danbri Another good property, I just found out from a friend might be "Total annual output" for the Distillery, which could be collected in PG (Proof Gallons) where he has to report this amount on his TBB forms to the government.

Notes:  PG - A proof gallon is a gallon of liquid at 60 degrees Fahrenheit which contains 50
percent by volume of ethyl alcohol having a specific gravity of 0.7939 at 60 degrees Fahrenheit referred to water at 60 degrees Fahrenheit as unity, or the alcoholic equivalent thereof.

**Comment by danbri** [comment]
re "total annual output", @thadguidry - at this point it might be more productive to look at ways of reflecting all of https://www.wikidata.org/wiki/Wikidata:List_of_properties/all into schema.org. Denny and I got some way into this last time we met. This is feeling pretty "long tail"...

**Comment by KoenLeemans** [comment]
Hi,

@mfhepp 
Is the best solution to still use http://www.productontology.org/ URIs for more detailled descriptions of an organization (@Type)? Or are there better options available at this time?

**Comment by kaushiknemani** [comment]
For any word http://www.productontology.org/  is giving error “ERROR (404): No respective entry available”. Try 	http://www.productontology.org/id/Apple . How should I give wikipedia reference ?

**Comment by radusi** [comment]
Canonical URL: http://schema.org/Distillery

Details here: https://pending.schema.org/Distillery 

It works

**Comment by mfhepp** [comment]
it is safe to use productontology URIs for any type that has an entry in Wikipedia - there is a known bug in the service that I will fix asap.
Martin

---------------------------------------
martin hepp
www:  http://www.heppnetz.de/
email: mhepp@computer.org

**Comment by kaushiknemani** [comment]
Thank for your quick response

 

Regards,

 

Kaushik Nemani

**Comment by danbri** [comment]
Tiny sensible addition, let's progress this into the core.
