### ISSUE TITLE
Need a way to specify which event is covered by a BroadcastEvent

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#768]
I propose we add the property ```broadcastOfEvent``` to BroadcastEvent to allow authors to specify when a broadcast is of an event rather than a creative work.

BroadcastEvent currently has the property ```workPerformed``` for broadcasts of creative works like movies, tv programs, etc. While I understand some consider [antelopes to be documents](http://people.ischool.berkeley.edu/~buckland/whatdoc.html), it is odd to consider an event like a sports match or an awards ceremony as a CreativeWork.

One might be tempted to use ```subEvent``` or ```superEvent```, but those don't seem appropriate either. A live broadcast is neither part of nor a parent of the event itself.

**Comment by danbri** [comment]
@RichardWallis, Barry Norton and I were discussing 'workPerformed' on friday, and how it doesn't work well for e.g. ExhibitionEvent, where something like a superproperty "workFeatured" might allow those events to be associated with creative works. Would such a name work here? It seems we could end up with a lot of rather similar event-to-creativework properties otherwise...

**Comment by danbri** [comment]
Ah, I misread. This is between broadcast events and the actual happening...

**Comment by danbri** [comment]
... in which case, +1 for broadcastOfEvent

**Comment by vholland** [comment]
I implemented this in pull request #774 with an example.

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all
