### ISSUE TITLE
Stars for Hotel/LodgingBusiness

### ISSUE THREAD

**Issue by coladict** [schemaorg/schemaorg#780]
I believe one of those should have a property for the official star rating of the business, distinct from the user ratings, that already exist.

**Comment by chaals** [comment]
Whoever provides the rating may be more trusted than a random person who says they liked the hotel or not, but they are essentially still reviews, IMHO.

**Comment by chaals** [comment]
So you can list it as a review whose author is an organisation - the National Tourism Board, the regional car club, "Guide Michelin", or whatever.

**Comment by mfhepp** [comment]
I worked on a full proposal for hotels which addresses this issue in detail, will share a preview with you all shortly (early next week)

**Comment by brewerdigital** [comment]
@mfhepp looking forward to your proposal for hotels. Where are you going to post; can I get a copy emailed to brad at brewerdigitalmarketing dot com? 

I recently led team publishing JSON-LD on 1,000+ location US hotel chain and I'm interested to see if you've converted all your old gr work, or if you're including any markup from opentravel.org to create a single language for travel.

**Comment by danbri** [comment]
@chaals 's observation makes sense to me - "official" stars are just reviews from well regarded authorities. Let's leave the issue open until @mfhepp surfaces his hotels work, since it is not enough for us to have a model for this situation, we also need to make our approach discoverable and understandable too :) @mfhepp does your approach follow @chaals suggestion or take another path?

**Comment by willatkins** [comment]
Hi @mfhepp, just checking if there is any news on the Hotels updates?  We're interested in setting a star rating (from an official body).  A star rating separate from user ratings makes sense to me, as it is used as an attribute when describing a hotel. Most aggregators and Google's knowledge graph usually keep star ratings separate from "normal" user review ratings.

For example, you can see from the below that user ratings and the official star rating are separate:
![image](https://cloud.githubusercontent.com/assets/14161859/10424873/c80524d2-70ca-11e5-87fd-2c7668b88fc1.png)

**Comment by danbri** [comment]
http://schema.org/award is close in meaning to what we want here, except that the 'award' (previously 'awards') property is text-valued. 

Perhaps we can refine "award" to address the star-rating-from-known-authority scenario? 

See also https://github.com/schemaorg/schemaorg/pull/916/files  for @mfhepp 's proposal which defines a starRating as follows (draft at http://sdo-hotels.appspot.com/starRating ):

> "An official rating for the lodging business, e.g. from national associations or standards bodies. Use the name property of a PropertyValue for indicating the type of the rating (e.g. HOTREC, DEHOGA, WHR, or Hotelstars)."

**Comment by vholland** [comment]
+1 to updating award. Something simple that lists organization granting the award, the name of the award, and a rating would solve many problems beyond this use case.

**Comment by mfhepp** [comment]
If your want to reuse schema:award for hotel star ratings, then we need to

- expand the range to include PropertyValue
- allow numerical values instead of just Text and document that this is the number of stars in the case of hotel ratings.

Personally, I think schema:award is a bad fit for hotel ratings. Hotel ratings are actually classifications obtained from an authorized body (e.g. national hotel organization) following a defined procedure. In the simplest case, you have a number of stars as a property, in the more advances case, you should indicate the name of the organization that issued the classification.

See the following examples with the new http://sdo-hotels.appspot.com/starRating proposal:

```
<div itemscope itemtype="http://schema.org/Hotel">
  <h1><span itemprop="name">ACME Hotel Innsbruck</span></h1>
  <span itemprop="description">A beautifully located business hotel right in the
heart of the alps. Watch the sun rise over the scenic Inn valley while
enjoying your morning coffee.</span>
  Star rating: <meta itemprop="starRating" content="4">****
  Room rates: <span itemprop="priceRange">$100 - $240</span>
</div>
```

and

```
<div itemscope itemtype="http://schema.org/Hotel">
  <h1><span itemprop="name">ACME Hotel Innsbruck</span></h1>
  <span itemprop="description">A beautifully located business hotel right in the
heart of the alps. Watch the sun rise over the scenic Inn valley while
enjoying your morning coffee.</span>
  Star rating: <link itemprop="starRating" itemscope itemtype="http://schema.org/PropertyValue">
    <meta itemprop="name" content="DEHOGA">
    <meta itemprop="value" content="4">****
  </link>
  Room rates: <span itemprop="priceRange">$100 - $240</span>
</div>
```

How would you model these with an expanded schema:award property?

We could of course simply use a schema:PropertyValue for this purpose and agree to use schema:value for the rating and schema:name ="star rating" and schema:description for holding the name of the organization.

But IMO that would be awkward and much more difficult to find for developers, because all terminology (award, PropertyValue, value) would be completely detached from the terminology in the domain.

Martin

**Comment by mfhepp** [comment]
One alternative route would be to define schema:StarRating as a subtype of PropertyValue and change the range of schema:award to Text OR PropertyValue. That would save one property but would imply that

1. developers will have to know that star ratings are awards and
2. in the simple case of just a number of stars, you would still need a schema:PropertyValue.

#2 might not be problematic, but #1 is a limitation IMO.

Using schema:Number as a range for schema:award looks very confusing to me.

**Comment by vholland** [comment]
Can we rename the property? In the US, AAA gives out "diamonds". Zagat has a 30 point scale. The name "starRating" is rather specific.

**Comment by mfhepp** [comment]
@vholland 
In Wikipedia, they call it Hotel rating and it seems that there are also alphanumerical values in some countries.

So I suggest to

1. use the proposed http://sdo-hotels.appspot.com/starRating property
2. rename it to hotelRating (as hotels are really the main domain) or accommodationRating (if we want to be more generic)
3. include Text to the range of the property (to allow for "A" and "F" ratings).

See also https://en.wikipedia.org/wiki/Hotel_rating

Note that Zagat seems to be focussing on restaurants and not accommodations.

**Comment by vholland** [comment]
I understand that Zagat focuses on restaurants, but do we really want a different property for each domain with a rating? Michelin stars are not all that different than the use case you have presented.

**Comment by mfhepp** [comment]
I am fine with having one property for star ratings, Michelin, Zagat, whatever, but then please suggest a generic name for the property. Otherwise I suggest to use accommodationRating for now and create a new super-property in a separate step.

What about 

- ratingByOrganization
- venueRating
- rating (my favorite)
- officialRating

Martin

**Comment by mfhepp** [comment]
Completely new proposal: Let's reuse http://schema.org/Rating with a new property named 

- starRating,
- ratingByOrganization,
- venueRating,
- rating (my favorite), or
- officialRating.

http:://schema.org/ratingValue should allow Number as a range, too. The domain could be schema:Place. This will be a mechanism that keeps user ratings and official classifications distinct while reusing the basic mechanism, including properties for indicating the range of the scale.

The source of the rating could co into schema:name or schema:description

**Comment by vholland** [comment]
"rating" would seem the best if we are willing to relax our ban on having properties and types with the same name modulo case.

**Comment by mfhepp** [comment]
What about

ratingByOrganization ?

I think that you fit well to all typical hotel and restaurant rating bodies, from hotel diamonds to Guide Michelin.

rating is very generic and can also be used for insulation in the context of electrical devices, work safety equipment, chemical, medical equipment, etc.

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by vholland** [comment]
Sounds good to me.

**Comment by danbri** [comment]
I'm fine with ratingByOrganization except initially I read that as being the property *of* a Rating that points to the Organization who made it. We should have some way of doing that?

Meanwhile on the stars/awards front, just for the record GS1 have this: http://www.gs1.org/voc/AwardPrizeDetails

**Comment by danbri** [comment]
Relaying from a conversation with a colleague at Google:

> Publishers like "The NY Times", "Timeout" and "Michelin" offer place endorsements in the form of "Critic's pick" or "Micheline star".
> 
> I suggest having the following fields:
> "endorsementType" - "Michelin stars", "Critic's Pick";
> "endorsementValue" (optional) - 1-3 Michelin stars, could be the ratingValue property if we decide to put this in the Rating class. 
> "endorsementLabel" - "1 Michelin star", "3 Michelin stars", "NYT Critic's Pick"

I asked about whether it would be useful to have URLs like http://www.nytimes.com/reviews/movies/critics-picks ...

> The link to the general site is nice to have but I am not sure all publishers will have it (try finding the general Michelin stars site, not so easy). 

The starRating property proposed in the hotels work, and as of today queued up for review in our work-in-progress site, is pretty much in this territory. See http://webschemas.org/starRating - it relates a LodgingBusiness to a Rating.

From the draft hotels-related documentation:

     An official rating for the lodging business, e.g. from national associations or standards bodies.
     Use the name property for indicating the type of the rating 
     (e.g. HOTREC, DEHOGA, WHR, or Hotelstars).

On this design, we would need a well known textual string like "NYT Critics Pick" to be the value of the name property of the Rating, and we would need good documentation examples for non 1-5 situations and especially the case of a "pick" in which there is no scale, just the implied endorsement of having been picked. Can the hotels design handle this usecase? /cc @mfhepp

**Comment by Aaranged** [comment]
Perhaps this is rolled into your thoughts @danbri (as indeed you reference the NYT's Critic's Pick for _movies_), but it's evident, IMO, that the utility of "starRating" is such that should be extended past its current proposed range of LodgingBusiness.

Indeed just in the context of Michelin Star ratings that have been referenced here, those Star ratings are arguably more well-known in the context of restaurant, rather than hotel, ratings.

That is to say, shouldn't star rating (which may or may not be actual "stars") be available anytime that a rating is assigned by an organization (which subsumes "national associations or standards bodies" - and, FWIW, Michelin is neither of these, but a private company)?  I think of use cases, too, like Consumer Reports product ratings, or even something as specific as Cook's Illustrated kitchen equipment ratings.

To this end I especially +1 the endorsementLabel brought up, for when there's a definite rating value, but its not numeric (think PolitiFact - "endorsementLabel": "Pants on Fire!").

This, I think, fills the gap between reviewRating (a rating assigned by an individual) and aggregateRating.

**Comment by danbri** [comment]
@Aaranged - yes, the overlap with non-numeric but definite rating values is what concerned me here. Note that the ClaimReview construction (see note in #1061) has given rise to a related pattern which also augments "Rating" with additional information.

Consider the 2nd microdata example in http://webschemas.org/starRating which has the following attached to a Hotel:

      Star rating: <span itemprop="starRating" itemscope itemtype="http://schema.org/Rating">
        <meta itemprop="name" content="DEHOGA">
        <meta itemprop="ratingValue" content="4">****
      </span>

Compare that with the ClaimReview markup being published c/o the #1061 design, e.g. 

    "reviewRating": {
       "@type": "Rating",
       "ratingValue": "2",
       "bestRating": "5",
       "name": "Two Pinocchios",
       "image" : "https://s3.amazonaws.com/share-the-facts/rating_images/washpo/washpo_pinnochios_2.png"
     },

There is an important difference here that demands our attention. On the first picture, the "name" of each rating is some kind of (uncontrolled but hopefully reasonably well-known) code for the party making the evaluation. In this case, DEHOGA which is (I [read](http://www.hotelsterne.de/start.html?&L=1)) "the German Hotel and Restaurant Association (DEHOGA)". By contrast, on the second picture, the "name" of a Rating, if supplied, characterizes the ratingValue rather than the party who made the evaluation. 

Based on the longstanding definition of the "name" property as "The name of the item.", I don't think we can reasonably stuff a name of the Rating-creating organization into "name". Possible options include "creator"/"author" (which however does not expect Text explicitly) or perhaps http://schema.org/issuedBy, which is a more niche. The issuedBy property is currently only used on Ticket and Permit. We could change the definition from "The organization issuing the ticket or permit." to include application to Ratings explicitly, and to also anticipate Organization names as a textual string. 

For example we could have "issuedBy: The organization issuing the item (e.g. ticket, permit or rating), either described as an organization or identified indirectly via a short name such as DEHOGA.". We could also allow issuedBy to reference an individual Person, addressing @chaals earlier point "So you can list it as a review whose author is an organisation - the National Tourism Board, the regional car club, "Guide Michelin", or whatever.". Note also that while Review is a CreativeWork (and therefore has mechanisms for authorship), Rating is Intangible and only gets CreativeWork properties when there is an associated Review (which the starRating design avoids).

As an aside, some strings may be ambiguous. For example consider http://www.bermondseysquarehotel.co.uk/ which I believe is an alcohol-free hotel.  According to http://www.visitlondon.com/where-to-stay/place/4554729-bermondsey-square-hotel#FmTTe462F0m6jfH1.97 it gets 4 stars from the AA (meaning http://www.theaa.com/hotel/hotel-inspector.html). However you might imagine Alcoholics Anonymous get into the hotel review business, and "AA" becomes non-obvious. We ought to provide at least one long-form example that describes the rating's creator/issuer in full as an Organization with e.g. homepage url. We should also acknowledge that this is a cornercase and many publishers will just want to write something like "issuedBy: AA" and leave it to consumers to disambiguate.

While I am writing, I should clarify the purpose of my post [yesterday](https://github.com/schemaorg/schemaorg/issues/780#issuecomment-233705882), to avoid risk of misinterpretation. I had no intention of injecting last minute "Google requirements" into the almost complete hotels design. Rather, I found that the scenario was close enough to the existing historical discussions here in #780 that it could help push us towards finalizing the wider #668 conversation around non-star, non-hotel awards/ratings/scores. As I wrote to my colleagues:

> There were some sketches in the Github issue that Vicki pointed to - https://github.com/schemaorg/schemaorg/issues/780 - , but I don't believe we got to a very complete design. Your scenarios could help give this a final nudge towards consensus. 

Anyway, where are we? Reviewing the discussion, I suggest that we have rough agreement on the following:

* capturing ratings from known authorities is important cross-domain, but in particular to the lodging/accommodation and restaurant/foodestablishment area. While such authorities can be described in detail using schema.org Organization markup, in practice they are often referred to by potentially ambiguous short strings such as AA and DEHOGA.
* that the notion of "stars" is somewhat metaphorical, and that we want to capture analogous data regardless of the iconic symbol used (e.g. diamonds, or I used to work in a hotel that had 5 'crowns', see also [here](http://www.independent.co.uk/arts-entertainment/travel-choosing-a-hotel-1425281.html), [here](https://www.visitbritain.org/star-rating-and-accreditation-schemes) etc.); various renaming possibilities are discussed above.
* capturing non-numeric strings used to characterize specific ratings is useful, see #1061 and [ClaimReview](http://pending.schema.org/ClaimReview), e.g. "Two Pinocchios"
* capturing non-numeric strings used for Rating-like, award-like endorsements is also of interest, e.g. "Michelin stars", "Critic's Pick". These are less formal than typical "star" schemes, but arguably more formal and well known than a simple Rating created by a known individual. 
* the property we choose to link the rated thing (hotel, etc.) to its Rating will also help with disambiguating any naming strings used on the Rating. For example, if we continue with starRating and it continues to say "official", then this helps clarify that "AA" is not a username of an individual reviewer/rater in some online community. If we go instead with something generic "rating", then it becomes less obvious what is intended by "AA". Options like ratingByOrganization are intermediate on this spectrum.
* that we should document useful additional properties of a Rating that indicate who (individuals or orgs) made the rating assessment, as well as any non-numeric representation of the rating. The existing "name" and "issuedBy" properties could be used for this.
* that we should not allow our generic ambitions to stand in the way of doing something useful for hotels/accommodation in the shorter term, and that the various alternative property names for "starRating" discussed above should be considered ASAP before we proceed with a release candidate based on the design in the current sdo-makemake github branch (i.e. the one currently on webschemas.org).

**Comment by mfhepp** [comment]
I am fine with any modification of the design as long as

1. the use-cases and requirements from the initial hotel domain remain covered
AND
2. the person or group working on this makes sure that any modification will also be incorporated into all examples for hotels (if needed) and the documentation at hotels.html.

I think I have worked on this design for more than 1.5 years now, and I really would like to wrap it up.

So please, anybody raising new requests, please also put in the effort to provide an end-to-end implementation. Talk is cheap.

If we cannot agree on a feasible design, well, then schema.org will be for another year or two without proper support for one of the prime domains of e-commerce on the Web.

Martin

**Comment by danbri** [comment]
Thanks @mfhepp. Everyone is keen to see this wrapped up ASAP.

On the "do we call it starRating or something else" front, I checked in with Yuliya from Yandex to get a better understanding of things in Russia. Relayed here with permission:

> Dan Brickley: Can you say anything about the situation in Russia. Do you talk about hotels having “stars” from standard, somewhat-official reviewing organizations?
> Yuliya Tikhokhod: Yes, star is a common way to talk about hotel and (sometimes) restaurants in Russia too.  As for crowns and diamonds I hear about it in connection with hotels first time.

**Comment by thadguidry** [comment]
@danbri I can also confirm that stars are also used in China as well.  Ctrip.com is one of the most popular in China for families to book hotels and tours.  Here's an example were the user has a dropdown selected with the searchHotelLevelSelect and star levels:

```
<div class="s_item_cont">
    <div class="s_item">酒店级别<select id="searchHotelLevelSelect" name="Star">
        <option selected="selected" value="0">不限</option>
        <option value="5">五星级/豪华</option>
        <option value="4">四星级/高档</option>
        <option value="3">三星级/舒适</option>
        <option value="2">二星级以下/经济</option>
        </select>
    </div>
</div>
<div class="s_item_cont">
    <div id="hotelAddressDiv" class="s_item w100">关键词
        <input type="text" _cqnotice="（选填）酒店名/地标/商圈" id="HD_TxtKeyword" name="keywordNew" class="w01 inputSel" autocomplete="on" maxlength="50">
        <input type="hidden" id="hotelAreaName" name="keyword" value="">
        <input type="hidden" id="positionArea" name="positionArea">
        <input type="hidden" id="positionId" name="positionId">
        <input type="hidden" id="zoneId" name="zoneId">
        <input type="hidden" id="locationId" name="locationId">
        <input type="hidden" id="metroId" name="metroId">
        <input type="hidden" id="landMarkId" name="landMarkId">
        <input type="hidden" id="forTW" name="city">
        <input type="hidden" id="district_city" name="district_city">
    </div>
</div>
</form>

```

**Comment by danbri** [comment]
Thanks @thadguidry. I [asked about Japan](https://twitter.com/danbri/status/756126538291093504) too, and the situation sounds broadly comparable there.

**Comment by mfhepp** [comment]
As said, I am fine with any design change that addresses the need for "staff picks". I was not overly enthusiastic since my original design of starRating had been more explicit but was simplified as per explicit requests. So this is kind of a ping-pong game.

**Comment by mfhepp** [comment]
As a hands-on proposal to address the "critics pick" use-case:
We can either expand the domain of http://schema.org/author and http://schema.org/publisher to include http://schema.org/Rating or make a http://schema.org/Rating a subtype of http://schema.org/CreativeWork.

This should address all the needs to indicate the creator of a rating or related judgment.

Note that ratingValue already allows Text, so you can say 

ratingValue = "Critic's Pick"
author = { a schema:Organization ; name = "The New York Times"}

This would also create a nice symmetry to Review.

**Comment by danbri** [comment]
Thanks @mfhepp. We're getting close, and I've made a start on the supporting edits.

I think for now the approach you outline will handle "Critic's Pick", but we might want to consider making a dedicated subtype of Rating (e.g. SimpleEndorsementRating "A rating that expresses a simple endorsement, and whose ratingValue does not come from a scale."). Otherwise the data will look like a non-numeric value but the interpretation defaults to a 1-5 scale, which is a little confusing.

**Comment by mfhepp** [comment]
Dan:

I would suggest to

a) make the edits I proposed (regarding author etc. properties); this will handle the source of ratings in a more formalized way, and
b) consider a type like SimpleEndorsementRating in the context of a future restaurants extension. 

I think that SimpleEndorsementRating is not immediately needed for hotels, so we can decouple the two issues.

Martin

**Comment by danbri** [comment]
(just to clarify, /author was amended appropriately last week)

**Comment by gmackenz** [comment]
Shouldn't Example 2 on [starRating](http://webschemas.org/starRating) be updated to use author instead of name for [DEHOGA](https://github.com/schemaorg/schemaorg/blob/329d354db7f5e9697b4b2b209e4ea92b7ceaa001/data/sdo-hotels-examples.txt#L130)?

**Comment by danbri** [comment]
You're right, thanks. I made a pass through fixing examples but I focussed on changed property/type names.

**Comment by gmackenz** [comment]
Created a pull request for the name/author change on the hotel examples #1273

**Comment by danbri** [comment]
Published via http://schema.org/docs/releases.html#v3.1
http://blog.schema.org/2016/08/schemaorg-update-hotels-datasets-health.html
