### ISSUE TITLE
There should be a way to describe video playlists

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#781]
The type http://schema.org/MusicPlaylist can be used to describe music playlists, but there is no analogous type for videos like YouTube play lists.

(Arose out of issue #526.)

**Comment by danbri** [comment]
Where do we say that http://schema.org/MusicRecording doesn't cover video? I guess it's name is ambiguous - does it refer to the music that was recorded, or the resulting files? The former is more audio-only than the latter, since you could claim various forms of video as being recordings "of music". Looking at the examples we have they seem to be roughly at FRBR Expression level, with precise timings ("PT6M33S"), but not a specific file/format/encoding. The last example under /MusicRecording btw seems more focussed on MusicRelease and doesn't list tracks as recordings.

Do you expect MusicPlaylist for non-video to cover (a) saying which expressions of some musical work ('recordings' in the abstract) are in some playlist (b) saying which collections of bytes (actual digital music files) are in some playlist? I'd like to get clear on the basic audio terminology before we do video.

**Comment by vholland** [comment]
Good point. I guess a MusicPlaylist could have videos, but can it have non-music videos. How do we model channels for cat videos, say?

**Comment by danbri** [comment]
Yeah, this kind of composition keeps biting us in various ways. General playlist sharing would be a great thing to support - lots of educational uses etc. Nearby: https://en.wikipedia.org/wiki/XML_Shareable_Playlist_Format

**Comment by elf-pavlik** [comment]
In social media I find list of entities on which each item one can perform some action:
* ReadAction
* WatchAction
* ListenAction
* PlayAction
* BuyAction / TakeAction (OfferCatalogue?)
* DrinkAction / EatAction

Having a way to associate a ItemList to an Action subtype and possibly clarifying Planned or Done aspect could help here...

**Comment by vholland** [comment]
Closing this until there is a better defined use case.
