### ISSUE TITLE
Add explicit relationship between location, homeLocation and workLocation

### ISSUE THREAD

**Issue by scor** [schemaorg/schemaorg#823]
The 'location' property is used on http://schema.org/Event. homeLocation and workLocation are properties of http://schema.org/Person. I would think all those properties are related, and in particular, homeLocation and workLocation should be sub-properties of location.

As a result, the description of 'location' should be generalized: 
> The location of the event, organization or action.

**Comment by danbri** [comment]
Make sense to me.  You also mentioned being explicit about 'location' often having textual values...? I think we should do that too.

**Comment by danbri** [comment]
Implemented and merged to sdo-phobos, thanks for the suggestion @scor! 

http://sdo-phobos.appspot.com/location

**Comment by scor** [comment]
Great, thanks, looking better. Should we also generalize the description a little bit, right now it says "The location of the event, organization or action."

Something like: The location of the event, organization or action.

**Comment by danbri** [comment]
Thanks @scor - done! /cc #827 as we're in final review now.

**Comment by danbri** [comment]
http://sdo-phobos.appspot.com/location

**Comment by danbri** [comment]
Fixed in http://schema.org/docs/releases.html#v2.2  - thanks all

**Comment by dsimmons** [comment]
@scor @danbri: I realize this is an older issue, but because it's relevant to the context of this dialogue....

In the same way that the gist of this PR was to unify `location`, `workLocation`, and `homeLocation`, is there any way that we could unify the expected types?

Specifically, if nothing else, Text is expected for `location`, whereas it's not for `homeLocation` and `workLocation`.

`location` also supports PostalAddress, whereas `homeLocation` and `workLocation` don't (and instead support ContactPoint).

I guess, in the spirit of these being related fields, is there any reason that they couldn't be even *more* uniform? :smile:
