### ISSUE TITLE
Mechanism for Compound Prices

### ISSUE THREAD

**Issue by mfhepp** [schemaorg/schemaorg#829]
In GoodRelations and schema.org, we miss a mechanism for modeling prices that consist of multiple components, like

car: 100 USD per week + 0.10 USD per mile
apartment: 100 USD per week + 50 $ cleaning fee per stay

The current model leaves open whether multiple UnitPriceSpecifications are alternatives or meant in combination.

Pull-request #830 addresses this issue.

**Comment by danbri** [comment]
Can you give some example sites (ideally using schema.org) where this vocab could improve things?

**Comment by brewerdigital** [comment]
@danbri @mfhepp here are two examples where a mechanism for compound prices could be helpful; rental fees are a standard charge at nearly all vacation rental websites. 
http://www.vrbo.com/324460#rates
http://www.homeaway.com/vacation-rental/p333759#ratesAnchor
Additional information about rental rates > Cleaning Fee $200

**Comment by danbri** [comment]
@mfhepp et al - do you have a sense for how sites have dealt with the absence of this construction so far? Have they been attempting to partially mark it up somehow, or just omitting?

**Comment by thadguidry** [comment]
@danbri @mfhepp so... since this is particular issue has some work merged, does the discussion on this issue then flow further into possibly us adding a concrete creditCardFees property on PriceSpecification #908 ?  Its a common thing and the upcoming W3C Payment Request API work has this at a different level at the Details (line items in an order) which is equivalent to PriceSpecification with Composite pricing.

@RichardWallis does FIBO have an opinion on potential creditCardFees property ?

**Comment by RichardWallis** [comment]
@thadguidry I have not been involved in FIBO discussions recently, but I don't think CreditCards using Schema.org are a current focus for them.

Looking at the current [CreditCard](http://schema.org/CreditCard) spec, the [feesAndCommissionsSpecification](http://schema.org/feesAndCommissionsSpecification) property inherited from FinancialProduct comes close to what is being looked for here.

Not sure how this could be related via a payment type option to a PriceSpecification.

Seems a bit ironic to be discussing this at the time the European Union have made the applying of surcharges for credit card transactions illegal. ;-)
