### ISSUE TITLE
branchCode is repeated for children of Place

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#873]
The branchCode property is repeated on http://schema.org/Store and http://schema.org/LocalBusiness (and perhaps others). Instead, it should just inherit the property from http://schema.org/Place.

**Comment by danbri** [comment]
scripts/rdfa2nt data/schema.rdfa | grep branchCode

    <http://schema.org/branchCode> <http://schema.org/rangeIncludes> <http://schema.org/Text> .
    <http://schema.org/branchCode> <http://www.w3.org/2000/01/rdf-schema#comment> "A short textual code (also called \"store code\") that uniquely identifies a place of business. The code is typically assigned by the parentOrganization and used in structured URLs.\n<br /><br /> For example, in the URL http://www.starbucks.co.uk/store-locator/etc/detail/3047 the code \"3047\" is a branchCode for a particular branch.\n      " .
    <http://schema.org/branchCode> <http://schema.org/domainIncludes> <http://schema.org/Place> .
    <http://schema.org/branchCode> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
    <http://schema.org/branchCode> <http://schema.org/domainIncludes> <http://schema.org/Store> .
    <http://schema.org/branchCode> <http://schema.org/domainIncludes> <http://schema.org/LocalBusiness> .
    <http://schema.org/branchCode> <http://www.w3.org/2000/01/rdf-schema#label> "branchCode" .

**Comment by danbri** [comment]
I believe I did this knowingly. But I guess we will already be mocked for branchCode appearing on Volcano.

We have a few cases such as this where a property is somewhat applicable to a supertype, and more applicable to a sub-type (or range/values too), e.g. foodEstablishment can point to a FoodEstablishment or just a Place where food is available. Are there non-localbusiness places where branchCode is applicable? In my experience schema.org's support for multiple supertypes is not always well supported, which is another reason to tolerate this grudgingly on Place (despite the Volcano issue).

**Comment by mfhepp** [comment]
Dan:

We should not be overly sensitive to complaints that a property that is applicable to a supertype may sound unusual on a particular subtype. First of all, it will always be clear at which level of abstraction a property is being added. We do not say that volcanoes have branchCodes and fax numbers. We say that branchCode and faxNumber are potentially useful properties for places and that a volcanoe is a special form of a place in schema.org.

People with a database background will often expect a Web vocabulary to define integrity constraints in the sense of rules of what must not be expressed about an entity. However, in a schema that is used by many people in many cultural contexts, it is much harder to rule out combinations that seem far-fetched at first sight. How knows whether there is a volcanoe with a fax number?

So let's be proactive and relaxed about that. Otherwise, we need a lot of painful "ontology engineering meets philosophy" types in the hierarchy.

What we could do is add information about

- which properties are popular for which types (similar to our "used on X to Y sites" for types) and
- which properties are particularly relevant for a given type (but this will require a lot of additional meta-data in the vocabulary).

But we also have to keep in mind that such a mechanism can actually put a break on a broader use of schema.org properties, because people will only use properties that are already very popular, even if others are applicable and useful.

Martin

PS: The simplest and most convincing solution would be to install a fax machine and attach a branch code to a volcanoe somewhere on Earth, take a picture of this, and add it to the schema.org Web site ;-)


-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by jvandriel** [comment]
_"PS: The simplest and most convincing solution would be to install a fax machine and attach a branch code to a volcanoe somewhere on Earth, take a picture of this, and add it to the schema.org Web site ;-)"_

hehe, loving the idea, +1

**Comment by chaals** [comment]
On Fri, 06 Nov 2015 15:07:57 +0100, Dan Brickley  
<notifications@github.com> wrote:

> I believe I did this knowingly. But I guess we will already be mocked  
> for branchCode appearing on Volcano.

I'm one of those who "mocks us" a bit for that. But the real point is  
"we're pragmatic. A lot of work to ensure your volcano cannot have a fax  
number is good for theoretical purity, but irrelevant. People who want to  
use their data for strict reasoning about facts should be looking at  
something more than just schema as a source".

> We have a few cases such as this where a property is somewhat applicable  
> to a supertype, and more applicable to a sub-type (or range/values too),  
> e.g. foodEstablishment can point to a FoodEstablishment or just a Place  
> where food is available. Are there non-localbusiness places where  
> branchCode is applicable?

Given that e.g. a library, school, or hospital is a "localBusiness", I  
can't think of something else that needs the code. (Although it might  
actually be useful for tracking points of lava eruption with multiple  
outlets - although I am not an expert in vulcanology, just guessing there  
is a use case there).

> In my experience schema.org's support for multiple supertypes is not  
> always well supported, which is another reason to tolerate this  
> grudgingly on Place (despite the Volcano issue).

I don't think it's that critical whether or not it is on Place. Having it  
on more than one thing seems a little odd, but I don't see the big problem  
in practice.

cheers

-- 
Charles McCathie Nevile - web standards - CTO Office, Yandex
  chaals@yandex-team.ru - - - Find more at http://yandex.com

**Comment by vholland** [comment]
All schemas have their quirks. I thought this was an error. Given it was intentional, I rescind my suggestion to only have it on Place.

**Comment by gebrits** [comment]
> Are there non-localbusiness places where branchCode is applicable? 

It would make sense for (subtypes of) CivicStructure

**Comment by vholland** [comment]
If we want to add branchCode to other types, we should create a new issue. Otherwise, this conversation will become difficult to follow.
