### ISSUE TITLE
Propose disambiguatingDescription on Thing

### ISSUE THREAD

**Issue by vholland** [schemaorg/schemaorg#880]
Systems like Wikipedia/WikiData often have a short description to help disambiguate entities. For example, the [Wikipedia page for "Phobos"](https://en.wikipedia.org/wiki/Phobos) lists the many entities by that name, allowing users to determine the page for the Greek god vs a moon of Mars, or the comic book character.

Wikidata calls this property "description", but I think we want something different so consumers do not need to determine which description is the disambiguator and which is the true description.

I would like to add ```disambiguatingDescription``` or even ```disambiguator``` to Thing.

**Comment by Aaranged** [comment]
+1.  This will be especially useful if the coder does not provide a sameIs for URI-based disambiguation, or if there is, indeed, no identifier she or he can use for the Thing being declared.

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Book",
  "name": "My Unpublished Book",
  "character": [
    {
	  "@type": "Person",
	  "name": "John S.",
	  "disambiguatingDescription": "This the the character that sent the blackmail letter in Chapter 1, not to be confused with the John Smith introduced in Chapter 17."
	},
    {
	  "@type": "Person",
	  "name": "John Smith",
	  "disambiguatingDescription": "This is the character that appeared in Hyde Park in Chapter 17, not to be confused with the John S. who sent the blackmail letter in Chapter 1."
	}
  ]
 }
</script>
```

**Comment by danbri** [comment]
If something text is a 'disambiguatingDescription' of a thing, then it will also meet the criteria of being its 'description'; we should probably declare any new property as a sub-property of 'description'.

I quite like the idea of doing something like this, because in practice 'description' varies wildly from huge slabs of text (sometimes including markup or escaped markup) to super short strings. 

@rvguha - any thoughts?

**Comment by rvguha** [comment]
Yes, I like disambiguating descriptions :)

guha

**Comment by vholland** [comment]
See pull request #891

**Comment by danbri** [comment]
any thoughts @mfhepp @scor @pmika  @chaals @ajax-als @shankarnat @tmarshbing ?

**Comment by Fred-Laurent** [comment]
In the Wikipedia example given by @vholland , there is a need to list (and disambiguate ?) the different entities for a given name. So could it be possible to  add 'Thing' as an expected value for 'disambiguatingDescription' ?

If so, we could have : 

<code>
\<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Thing",
  "name": "Phobos",
  "disambiguatingDescription": [
	{
  		"@type": "Thing",
  		"name" : "Phobos (moon)",
                "description" : "A moon of Mars",
  		"sameAs": "https://en.wikipedia.org/wiki/Phobos_(moon)"
	},
	{
  		"@type": "Thing",
  		"name" : "Phobos (mythology)",
                "description" : "the Greek god of horror",
  		"sameAs": "https://en.wikipedia.org/wiki/Phobos_(mythology)"
	}
  ]
}
\</script>
</code>

**Comment by danbri** [comment]
Merged for review in v2.3, http://sdo-deimos.appspot.com/disambiguatingDescription

I'm convinced by the Wikipedia usecase.

**Comment by darobin** [comment]
Question: would it be viably useful to use this for the subtitle of a `CreativeWork` (where the title is the `schema:name`)?

**Comment by danbri** [comment]
@darobin perhaps sometimes, but it feels a stretch to suggest that all subtitles will always be adequately distinctive to consider them *by definition* disambiguatingDescriptions. What you suggest feels more like it lives on the content creation / curation / metadata management side, where authors of subtitles are encouraged to give good descriptions.  (this is a bit vague since we don't afaik have a subtitle property; are you suggesting we need one? )

**Comment by darobin** [comment]
Yes, I agree it feels like a stretch (hence the question :).

The situation we have is that of articles that always have a `name` and may commonly also have a subtitle. We don't want to smudge them all into a list of `name` because there may already be several, with differing languages. We've also considered `alternateName` but you can't use the subtitle as an alternative to the actual name.

One thing that does seem to match is `additionalName`, but it's only for `Person`. I tend to think that allowing it on `CreativeWork` would make sense — probably more sense than using `disambiguatingDescription` I guess :)

**Comment by danbri** [comment]
On reflection, I think we are currently underspecified here.

Consider:

* a Person with "disambiguatingDescription" of "Former Governor of Texas" - does this feel ok? or too ambiguous? (usecase is #1061 fact-checking schema).
* does it have to be completely disambiguating? or perhaps along with other properties like "name": "Rick Perry"?
* Another example: A Person with name "John Smith" is under-specified; if you add  disambiguatingDescription: Former leader of British Labour Party you get https://en.wikipedia.org/wiki/John_Smith_(Labour_Party_leader)

I suggest amending "A sub property of description. A short description of the item used to disambiguate from other, similar items." to say

"A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation."

**Comment by danbri** [comment]
http://webschemas.org/disambiguatingDescription updated accordingly - please take a look

**Comment by danbri** [comment]
Closing per http://webschemas.org/docs/releases.html#g880
