### ISSUE TITLE
Disambiguate schema:address and schema:location 

### ISSUE THREAD

**Issue by betehess** [schemaorg/schemaorg#913]
- what's the difference between the two?
- is one preferred over the other?
- do I want to use both at the same time?
- can't there be only one?

**Comment by betehess** [comment]
Probably relevant to this discussion: https://productforums.google.com/forum/#!topic/webmasters/-2jgBgIsoiQ

**Comment by danbri** [comment]
Thanks. What happened here was that we decided in the last release to more explicitly anticipate the use of 'address' with textual values. This is something which http://schema.org/docs/datamodel.html says can happen anywhere, but given the complexity of addresses sometimes a hard-to-dismantle simple string is all you have. It looks like by doing so we have made it overlap more with 'location'. The fact that 'location' allows PostalAddress confuses things somewhat too. 

(I'll chase up the google-side of your enquiry elsewhere, with a different hat on :)

**Comment by dsimmons** [comment]
Just curious if there's been any further development on this since. Some guidance or a rule of thumb would be welcome from my perspective!

The heuristic I've been using (and tell me if this is incorrect) to model "locations", particularly as it pertains to Organization, is as follows:
  - If I have a https://schema.org/streetAddress, I use Address.
  - If it's a more general "region" (https://schema.org/addressLocality, https://schema.org/addressRegion) (eg. Cambridge, MA) and I couldn't put something in the "physical and metaphorical" mailbox, I tend to use https://schema.org/location.
