### ISSUE TITLE
educationalRole and Role seem related, but don't mention each other

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#927]
/cc @philbarker @vholland 

Not urgent but just wanted to note this for potential consistency/cleanup attention. If they are unrelated we could just say so...

**Comment by philbarker** [comment]
I've never quite been sure how Role works, but with that in mind...

Currently we can say:
"Alice is a teacher who works for Rydell High"

<div vocab="http://schema.org/" typeof="Person">
    <span property="name">Alice</span> is a
    <span property="worksFor" typeof="EmployeeRole">
        <span property="roleName">teacher</span>
        who works for
        <span property="worksFor" typeof="HighSchool">
            <span property="Name">Rydell High</span>
        </span>
    </span> 
</div>

and "'Designing a treasure map' is a lesson plan for teachers"
<div vocab="http://schema.org/" typeof="CreativeWork">
    <span property="name">Designing a treasure map</span> is a 
    <span property="learningResourceType">lesson plan</span> for
    <span rel="audience" typeof="EducationalAudience">
         <span property="educationalRole">teacher</span>s
    </span>
</div>

Being able to suggest that the treasure map lesson plan is suitable for Alice seems like a reasonable use case.

To make the link: 
First, create a new subtype of role, EducationalRole (obvious examples: 
teacher & learner, less obvious roles are educational admin roles, parents of 
learners--so not a EmployeeRole) 

EducationalRole simply replaces/supplements EmployeeRole in first example.

Second, allow EducationalRole to be a value type for educationalRole, so:
<div vocab="http://schema.org/" typeof="CreativeWork">
    <span property="name">Designing a treasure map</span> is a  
    <span property="learningResourceType">lesson plan</span> for
    <span rel="audience" typeof="EducationalAudience">
         <span property="educationalRole" typeof="EducationalRole">
             <span property="roleName">teacher</span>s
         <span>
    </span>
</div>

If that sounds valid from the schema.org point of view, it would be useful to get input from @jgoodell2 about how roles are modelled in things like CEDS

**Comment by RichardWallis** [comment]
Currently [educationalRole](http://schema.org/educationalRole) 'An educationalRole of an EducationalAudience.' is only a property for the [EducationalAudience](http://schema.org/EducationalAudience) type.    Whereas I believe you are discussing it in much broader (person to organization or course) relationships.

As to the application of the Role type there are a couple of posts worth reading from the [Schema Blog](http://blog.schema.org/2014/06/introducing-role.html), and one I posted on [Data Liberate](http://dataliberate.com/2015/04/the-role-of-role-in-schema-org/).

With the "Alice is a teacher who works for Rydell High" use case, you could EmployeeRole as it is, with a roleName of "Teacher".  A subtype of Role 'EducationalRole' would then be appropriate for other non-employee relationships, not just on EducationalAudience.  It could be for instance used to enhance a creator relationship with a course or educational material CreativeWorkSubtypes.

Because of the special nature of Role and its subtypes, you would not need to add it to the range of properties to use it.

~Richard.

**Comment by philbarker** [comment]
*sigh* github ate the RDFa examples in my post.

Gists at

"Alice is a teacher who works for Rydell High"
https://gist.github.com/philbarker/59830c2866877b41b8cd

"'Designing a treasure map' is a lesson plan for teachers" (current practice)
https://gist.github.com/philbarker/f6ca25ab09a253e90534

"'Designing a treasure map' is a lesson plan for teachers" (with Role)
https://gist.github.com/philbarker/036b96381c6cbffe6651

Thanks @RichardWallis I had forgotten about those blog posts. They help; now that I have concrete use they make sense :)

Yes, for the Alice use case EmployeeRole with roleName 'Teacher' would work, but it's worth remember that not every teacher is an employee (e.g. private tutors, privatdozent). Also I imagine it would be easier for applications focussing on the educational domain to be able to pick out a subclass of Role rather than dive down into parsing text values of roleName.

**Comment by jgoodell2** [comment]
Sorry for the slow reply.

CEDS handles Role in multiple ways, initially as entities that define an organization role, such as Postsecondary Staff or Early Learning Teacher. This is just a way of organizing the properties associated with a person in a particular role. We have subclass properties/vocabulary for classifying within a role, such as type of teacher. 

More relevant to this conversation might be the reference model CEDS calls the Normalized Data Schema (NDS), it has a "Person" entity, an Organization (i.e Organi**s**ation for Phil and others that speak English instead of U.S.ish :), and a Role. The model assumes that a person is only a teacher through relationship within the context of an organization. It is normalized to this level to recognize that one person may have multiple roles at a time, a K12 teacher, a PS Student, and a parent of a Early Learning Child. For P20W data uses we need to be able to recognize that one person and the various roles and relationships over time.

This is a different use case, but CEDS may be able to provide some relevant data vocabulary.

@jgoodell2

**Comment by jgoodell2** [comment]
I forgot to include perhaps the most relevant thing from CEDS for educationalRole for a learning resource...

CEDS currently defines the element "Learning Resource Intended End User Role" with these standard values: 
Administrator
Mentor
Parent
Peer-Tutor
Specialist
Student
Teacher
Team
Other

This could be one source for EducationalAudience additionalType ( e.g. https://ceds.ed.gov/element/000923#Administrator ) and/or text values used for educationalRole

**Comment by HughP** [comment]
Just reading over this for an application we are considering in my organization. I was looking at the reverenced elements over at https://github.com/stuartasutton/LRMI_Vocabs/blob/master/educationalAudienceRole.ttl and I do not see _Team_ or _Other_. Is this by omission, and an oversight or is this by design and symptomatic of different applications of LRMI principles?

**Comment by jgoodell2** [comment]
Hugh;
Re: Team or Other options for educationalRole 

I think as the LRMI group we are proposing the unambiguous terms from existing CEDS educationalRole for educationalAuduenceRole. Team could mean a team of teachers, students, parents, etc. If I recall correctly,  the conclusion from a work group conversation was that it would be better to tag a resource intended for a team of students as "student". (If it becomes standard practice and Schema vocab not to use the "team" option, and the CEDS community agrees, then "team" could be deprecated in a future version of CEDS.)

Also, an LRMI implementation might just tag a non-standard text label for any "other" category that doesn't fit within the standard vocabulary categories, rather than use a generic "other".  (CEDS is often implemented in systems that require an "other" option, but for tagging web content "other" is ambiguous.) Any non-standard text label could be interpreted as "other" than the standard vocabulary. ...If new roles emerge in practice over time they could become part of the standard vocabulary.
-Jim

**Comment by HughP** [comment]
@jgoodell2 One other thing about the CEDS vocabulary. I see "Mentor" as a term. Is there a reciprocal entity to the mentoring relationship?  We have Parent-Child, Teacher-Student, Mentor-???  Is it assumed to be Mentor-Student?

**Comment by jgoodell2** [comment]
@HughP Sorry for the slow reply. Yes, we can assume a reciprocal Mentor-Student relationship.

**Comment by JimSaiya** [comment]
BTW, I've worked at an organization (government agency) that used the 
term "mentee", belive it or not. 

Jim Saiya
Web Developer / Information Architect
✉ jsaiya@formatdata.com
[in] www.linkedin.com/in/jimsaiya

On Wed, 27 Apr 2016 13:16:11 -0700, jgoodell2  wrote:

       @HughP Sorry for the slow reply. Yes, we can assume a reciprocal 
Mentor-Student relationship. 
—
You are receiving this because you are subscribed to this thread. 
Reply to this email directly or view it on GitHub

   *
