### ISSUE TITLE
Type-coerce "colleague" to @id in JSON-LD context

### ISSUE THREAD

**Issue by lanthaler** [schemaorg/schemaorg#929]
... otherwise the example at http://schema.org/Person is not 100% correct as [Geert-Jan notice on StackOverflow](http://stackoverflow.com/questions/34226440/do-type-id-values-have-to-be-explicitly-typed-in-json-ld).

**Comment by danbri** [comment]
Makes sense. I believe, given the way we do things currently, the way we'd express this would be adding URL as another expected type. And indeed the example under discussion is using URLs. Let's do that.

**Comment by danbri** [comment]
Implemented and queued for release, see http://webschemas.org/docs/jsonldcontext.json

**Comment by jaygray0919** [comment]
Do you publish a change log of the differences between the current release and the planned release?

Here's the reason I ask:

We use a subset of the schema.org jsonldcontext.json statements in our @context declaration.

We also include other non-schema.org statements.

So, rather than using @vocab shema.org (and benefiting from updates to the vocab), we try to make the terms used in any document explicit.

Hence the desire to explicitly update existing documents with any vocab changes.

Thanks for guidance here.

 

/jay gray
