### ISSUE TITLE
Extension Proposal: Brand

### ISSUE THREAD

**Issue by kevinSuttle** [schemaorg/schemaorg#948]
``` json
{
  "@context": "http://schemas.acme.com",
  "@type": "Brand",
  "name": "ACME",
  "fullName": "ACME, Inc.",
  "isPartOf": "https://schemas.acme.com/design/brands",
  "version": "0.1.0",
  "colorPalette": "https://schemas.acme.com/design/brands/rocketskates/colors",
  "logos": "https://schemas.acme.com/design/brands/rocketskates/logos"
}
```

**Comment by mfhepp** [comment]
My few cents:

- "brand" needs to be with an uppercase initial character (http://schema.org/Brand) 
- the default protocol of schema.org is, so far, http and not https
- the brand type in schema.org is the abstract notion of the brand; logos, color schemes, and other visual entities are related entities in their own right, at least in my understanding. So let's not conflate the brand with its style guidelines.

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by kevinSuttle** [comment]
@mfhepp How would you correlate the 2?

**Comment by mfhepp** [comment]
We may need additional properties for linking from an Organization, Person and Brand to such visual entities and design-oriented meta-data. However, my immediate feeling is that such data will not be provided by many sites and is thus not a priority for schema.org (just my personal assessment).

A quick fix could be to include schema:Brand in the domain of additionalProperty, which would give you plenty of ways of modeling additional information. You can also define an external vocabulary that references or imports schema.org elements,

**Comment by thadguidry** [comment]
Brands can be registered Trademarks in the United States and 'owned' or 'registeredOwner' by an organization or person.

https://www.uspto.gov/trademarks-application-process/search-trademark-database

@RichardWallis @danbri @mfhepp @vholland 
1. Looks like we are missing a property called 'owner' or 'trademarkHolder' or somesuch on the Brand type.
2. Logo(s) of a Brand is usually held at a URL with the idea of a media kit, etc. for use by the Press without prior authorization or if you are an authorized dealer or reseller.  We need a property on Brand to hold this URL (could be called **mediaKit** or **pressInfo**  Example: iPhone mediaKit URL http://www.apple.com/pr/products/iphone/iPhone.html

**Comment by mfhepp** [comment]
Legal ownership can be modeled in schema.org via http://schema.org/owns, either directly pointing to a schema:Product or http://schema.org/OwnershipInfo for more detailed information.

Now, since schema:Product is just a role of a schema:Thing, i.e. to be relevant in a commercial context, you can simply model ownership of a schema:Brand by using an MTE:

foo:myBrand a schema:Brand, schema:Product.


foo:ACME_Company a schema:Corporation;
	schema:owns foo:myBrand.

And you are all set without changing schema.org.

Another example that there is more to express with GoodRelations in schema.org than many assume ;-)

Martin
-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by thadguidry** [comment]
@mfhepp Ah, just adding OwnershipInfo seems to resolve that particular need of 1 with use of an MTE saying that iPhone is both a Brand and Product.  But for just Brand, can we make it easier for developers to have the new property and expect a type of OwnershipInfo somehow ?

Your thoughts on 2 for the Logo ?

**Comment by mfhepp** [comment]
Since schema:owns is a very fundamental property, I would not blur its intended meaning by expanding the domain to include schema:Brand; instead, I would recommend to use an MTE in this case; also because this is likely not a typical patterns. Most markup about brands will not state the legal ownership, but just the name and logo.

all: Keep in mind that an MTE for "iPhone" as Brand AND Product refers to the "iPhone" brand, NOT a cellphone (neither actual nor ProductModel).

**Comment by mfhepp** [comment]
As for logos: I think it will be better to use the existing schema:logo property with a LIST of URLs or ImageObjects. If you want to link to a page with logos, simply use http://schema.org/url.

We could define a subproperty http://schema.org/logosUrl, but I think that is too specific.

As for "fullName": "ACME, Inc.", - at least in Germany, a brand is a unique text; it may include the legal form of a company (like ACME, Inc.) or not. Most companies register just the characteristic name (like "IBM"). Some register both ("ACME and ACME, Inc. are registered trademarks of ACME, Inc."). In the later case, you have TWO schema:Brand entities. Their relatedness can be modeled using http://schema.org/isSimilarTo or http://schema.org/isRelatedTo (if you use an MTE) or even schema:sameAs. So I see no need for schema:fullName.

schema:colorPalette is IMO very specific and maybe better suited for ImageObject (a consumer can infer it from there equally well; also, the same brand might use multiple color schemes; attaching this to the ImageObject captures the link from a version of a logo or brand to its colors.

Version info is IMO likely not as popular as e.g. in software releases. I might be wrong and would be happy to learn the contrary.

partOf is an ambiguous property and touches the very complicated area of meronomy (see https://en.wikipedia.org/wiki/Meronomy). Shall it mean legal ownership? Then use schema:owns.
Shall it mean a variant or successor? Then maybe we should lift http://schema.org/successorOf and http://schema.org/predecessorOf to schema:Product, which would also make sense bc in some cases individual products might need them.

So I would suggest to close this issue.
