### ISSUE TITLE
provide a status property for CreativeWork

### ISSUE THREAD

**Issue by chharvey** [schemaorg/schemaorg#987]
Similar to the [`eventStatus`](https://schema.org/eventStatus) property for type `Event`, I propose adding a similar property to [`CreativeWork`](https://schema.org/CreativeWork), perhaps named `creativeWorkStatus`, or simply `status`.

This property would have values expected to be of a new type, `CreativeWorkStatusType`, which would be _"an enumeration type whose instances represent several states that a CreativeWork may be in."_ Perhaps the enumeration members of this type might include values such as `Draft`, `Unstable`, `InProgress`, `OnHold`, `Complete`, `Finalized`, `Published`, `Stable`, `Deprecated`, `Obsolete`, and so on.

Although the current properties `dateCreated`, `dateModified`, and `datePublished` describe useful information about the _date on which a creative work's status had changed_, I do not believe they richly describe its status in the manner proposed above.

Related types:
- https://schema.org/EventStatusType
- https://schema.org/OrderStatus
- https://schema.org/PaymentStatusType
- https://schema.org/ReservationStatusType
- https://schema.org/MedicalStudyStatus

**Comment by jeremykelaher-sbs** [comment]
Hello, sbs.com.au are building a content API fully based on strict schema.org conformance with as few propriety extensions as possible (none so far) . This extension would be useful because we have draft content in our graph for preview by journalists and tests with tools like AMP. It strikes me search engines and other semantic query engines could be usefully aware of this status to explicitly avoid crawling "not published" content.

**Comment by ktk** [comment]
The property `creativeWorkStatus` makes a lot of sense, we will use this for describing the status of published open data sets in Switzerland, which often start as drafts and only over time get "stable".

**Comment by fidannajdov33-max** [comment]
😶‍🌫️😶‍🌫️😶‍🌫️😶‍🌫️😶‍🌫️

**Comment by gustavorps** [comment]
Why not just `status` like used on [Medical types](https://schema.org/status)? That already set as stable?
